### ISSUE TITLE
too slow for dynamic data binding

### ISSUE THREAD

**Issue by gimapei** [nhn/tui.grid#1001]
## Version
4.10.1

## Development Environment
window 10, nodejs 10.15.1, Vue 2.6, visual studio code
chrome browser.

## Current Behavior
first. I set the dataSource API type, 
second. the data reset when I click button on page.  ex) this.$refs.tuiGrid.invoke('resetData',data)
third. the second operation was repeated once per second.

result.
Fast increase memory usage for chrome. 
PC performance down. down. and dead.

## Expected Behavior
Quick refresh, Without performance issues

**Comment by js87zz** [comment]
@gimapei 
We need more detail information to solve your issue. 
Please give us source code in codepen or codesandbox

**Comment by gimapei** [comment]
hello 
here is a source for your request.

procedure
#1. download > npm I > npm run serve
#2. open chrome HTTP://localhost:8080
#3. open chrome developer tool on your browser.
     * I found memory increases when I launch the debug window from chrome.
#4. open task manager for window 10
#5. click button on sample page. ( 1fps )
#6. you can see the memory leak

[Uploading sample.zip…]()

**Comment by js87zz** [comment]
@gimapei 
You didn't upload your source code.
If possible, upload the source code in codepen or codesandbox not zip file.
