### ISSUE TITLE
Custom Editor 관련

### ISSUE THREAD

**Issue by globeer** [nhn/tui.grid#1002]
**Describe the bug**
Custom Editor 관련하여 value 값이 numberic 인 경우, 변경후 값이 string 이 되면서 화면에 선택한 항목이 보이지 않는 문제 발생합니다. value 값은 string 형태만 가능한지요?
**To Reproduce**
          formatter: 'listItemText',
          editor: {
            type: 'select',
            options: {
              listItems: [
                { text: 'Deluxe', value: 1 },
                { text: 'EP', value: 2 },
                { text: 'Single', value: 3 }
              ]
            }
          }
**Expected behavior**
Custom Editor 관련하여 value 값이 numberic 인 경우, 변경후 값도 nuberic 형태로 선택된 항목이 보이면 좋겠습니다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: chrome 버전 80.0.3987.163(공식 빌드) (64비트)
 - Version: tui.grid 4.10.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by js87zz** [comment]
@globeer 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
I think that this issue is same as the (#831). We have a plan to improve this, the exact schedule is not fixed.
