### ISSUE TITLE
Why state is initialized?

### ISSUE THREAD

**Issue by mwrote** [nhn/tui.grid#1003]
**Describe the bug**

in below code, when `setTemp` is executed, grid state is initialized.

```
import React, { useState } from "react";
import Grid from "@toast-ui/react-grid";
import "tui-grid/dist/tui-grid.css";

export default function App() {
  const [temp, setTemp] = useState("");
  const data = [
    {
      name: "a",
      id: "2"
    },
    {
      name: "b",
      id: "1"
    }
  ];

  const columns = [
    {
      header: "Name",
      name: "name",
      sortable: true
    },
    {
      header: "ID",
      name: "id",
      sortable: true
    }
  ];
  return (
    <div className="App">
      <Grid data={data} columns={columns} />

      <input type="text" value={temp} onChange={e => setTemp(e.target.value)} />
    </div>
  );
}

```

**To Reproduce**

1. Click Sort button of `ID`
1. input text field
1. then, sort is initialized.

**Expected behavior**
sort state is not initialized. also using checkbox, same issue is occurred.

**Screenshots**

![image](https://user-images.githubusercontent.com/805577/79547694-3f7d8e00-80cf-11ea-957a-2da0e3e78b72.png)

**Desktop (please complete the following information):**
I checked local environment, and Codesandbox.

**Smartphone (please complete the following information):**
cop & paste above code to Codesanbox. this issue will happen.

**Additional context**
none

**Comment by js87zz** [comment]
@mwrote 
I think It's not the bug.
The grid is re-rendered when `data`,`columns` props is changed.
The `data` and `columns` are newly created in your functional component whenever changing the input value. So, It will be solved by preventing to change the reference of `data`, `columns` using React `useMemo` or javascript closure.

**Comment by mwrote** [comment]
OK, Thanks!
