### ISSUE TITLE
represent numbers separated by commas

### ISSUE THREAD

**Issue by kbkim-qw** [nhn/tui.grid#1004]
I want to represent numbers separated by commas.

I used the following function

 {
header : '매입액',
width: 100,
name : 'BUY_PRICE',
editor: 'text',
editOptions: { type: 'text',maxLength: 30, useViewMode: false } ,
formatter: function(value) {
return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
   }

The result looks like this
[object Object ]

If I actually copy it, the value is copied like
 1000000						

Can You Help me?

**Comment by js87zz** [comment]
@kbkim-qw 
The our migration guide is wrong. It will be fixed.
The parameter of `formatter` is object so that you can solve the issue as below. 
Furthermore, there is no `editOptions` option in grid `4.x`.
```js
{
  header : '매입액',
  width: 100,
  name : 'BUY_PRICE',
  editor: 'text',
  formatter: function({ value }) {
    return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }
}


```

**Comment by kbkim-qw** [comment]
Thank you.
It works.
