### ISSUE TITLE
Insert a custom div element / Grid on expand of a row 

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#1008]
**Is there any way to insert a custom div element ( or another grid instance) on 'expand' (event) of a row?**
The current tree model just lets us pass in the data, without scope for customisation.

**Comment by js87zz** [comment]
@SanjaySankar 
We need more detail explanation. You want to add new row when expanding the specific tree row?

**Comment by SanjaySankar** [comment]
Here is the codesandbox link for what I'm looking for : https://codesandbox.io/s/vibrant-napier-h58np
I need to add another <tr> component on row expand. Is that possible?

**Comment by js87zz** [comment]
@SanjaySankar 
Sorry for late replying.
We provide [the example](https://nhn.github.io/tui.grid/latest/tutorial-example14-tree), the row is appended to parent row when the tree row is expanded. 
However, I think the functionality you want is not above example as I checked your sandbox. You want to append the customized row, but we don't provide the method of customizing the row format yet.
