### ISSUE TITLE
셀병합에 문의드립니다

### ISSUE THREAD

**Issue by Jin-hoKim** [nhn/tui.grid#1009]
안녕하세요
몇가지 문의 사항이 있어서요
1. colspan 병합은 지원되지 않나요? rowspan은 예제로 찾아 확인했는데 colspan은 안보여서요;;
2. rowHeaders: ["checkbox"]로 앞에 체크박스를 넣었습니다.
    체크된 항목만 추출하려고 하는데 제공되는 메소드가 있는지요? 제가 잘 못찾아서 문의드립니다;

**Comment by Jin-hoKim** [comment]
> 안녕하세요
> 몇가지 문의 사항이 있어서요
> 
> 1. colspan 병합은 지원되지 않나요? rowspan은 예제로 찾아 확인했는데 colspan은 안보여서요;;
> 2. rowHeaders: ["checkbox"]로 앞에 체크박스를 넣었습니다.
>    체크된 항목만 추출하려고 하는데 제공되는 메소드가 있는지요? 제가 잘 못찾아서 문의드립니다;

2번에 대한 문의는 문서를 다시 찾아보다 getCheckedRowKeys() 이 메소드를 봤습니다

**Comment by js87zz** [comment]
Unfortunately, We don't support `colSpan` yet. We have a plan of developing it, but the schedule is not decided due to other priority. 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
