### ISSUE TITLE
About "Furthermore, there is no editOptions option in grid 4.x."

### ISSUE THREAD

**Issue by kbkim-qw** [nhn/tui.grid#1012]
Hello.

In previous issue #1004,
(represent numbers separated by commas #1004)

About "Furthermore, there is no editOptions option in grid 4.x." that you mentioned.

Can I get a detailed explanation or API guide?

**Comment by kbkim-qw** [comment]
For example, a vertical combo box list ( Currently horizontal )

I want to know detailed setting information such as.

**Comment by js87zz** [comment]
The below issue will be helpful to you. Thank you!
https://github.com/nhn/tui.grid/issues/883
