### ISSUE TITLE
if I need to pass the object to CellValue, how can i do it?

### ISSUE THREAD

**Issue by jochouen** [nhn/tui.grid#1014]
**Summary**
In using '@toast-ui/react-grid' in TypeScript.
I need to pass the array object to CellValue, but CellValue = number | string | boolean | null | undefined;
how can i pass it?

**Screenshots**
<img width="127" alt="スクリーンショット 2020-04-23 17 56 00" src="https://user-images.githubusercontent.com/10725284/80079824-bd3c1080-858b-11ea-9320-70cb7e13a45a.png">

**Version**
"tui-grid": {
      "version": "4.10.1",

**Additional context**

```
class Sample {
  private el: HTMLDivElement;

  constructor(props: SampleProps) {
    const rootDom = document.createElement('div');
    this.el = rootDom;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props: SampleProps) {
    // tui grid's CellValue = number | string | boolean | null | undefined; not object, but i need to pass the object to CellValue
    // I don't know how to pass it. I need to write the code like ↓，Otherwise, there will be a type error.
    const sampleArr = (props.value as unknown) as SampleType[];
    const element = sampleArr.map((item: SampleType, index: number) => (
      .....
    ));
    ReactDOM.render(element, this.el);
  }
}


const columns: OptColumn[] = [
  
  ...,
  {
    header: 'Sample',
    name: 'sample',
    sortable: true,
    renderer: Sample
  },
  ....
];
```

**Comment by js87zz** [comment]
@jochouen 
We need to add the `object` type to `CellValue` type definition for handling the issue as you wrote in react-wrapper. I think that your code(`(props.value as unknown) as SampleType[];`) will be passed without any compile error, but you got an error. Can you give us your error screenshot?

**Comment by jochouen** [comment]
@js87zz 
Thank you for your reply.
I mean, if I write this-> ((props.value as unknown) as SampleType[];), I can avoid ts error.
But I think this is not the best.So if you can add the object type to CellValue type, I think it is the best.
thank you. :)

**Comment by js87zz** [comment]
@jochouen 
The `object` type has been added in `v4.13.0`(#1054).
