### ISSUE TITLE
XSS Issue

### ISSUE THREAD

**Issue by hot900418** [nhn/tui.grid#1016]
I want to know how to respond to Toast Grid XSS. XSS is not responding when entering javascript on Grid. Please tell me how to respond to XSS.

**Comment by js87zz** [comment]
@hot900418 
It's hard to know your issue. You need to give us more detail information like your source code, screenshot.

**Comment by hot900418** [comment]
@js87zz 
Not a bug. Screen shots are difficult to provide.
When you type <script>alert('hi');</script> in the grid, an alert message appears.

**Comment by js87zz** [comment]
@hot900418 
You can prevent XSS through defining the `escapeHTML` column option.
```js
const grid = new Grid({
  // ...
  columns: [
    {
      header: 'Name',
      name: 'name',
      escapeHTML: true
    },
    // ...
  ]
});
```
