### ISSUE TITLE
Is there a function that you are offering after data is shown on the grid?

### ISSUE THREAD

**Issue by wjdgns7989** [nhn/tui.grid#1017]
I want to take data from the database and appear with specific colors according to the conditions.
So I tried to use 

```js
grid.on('successResponse', function(data){
  grid.findRows(function(row) {
    return ~;
  }).forEach(function(element) {
    grid.addCellClassName(element.rowKey, 'name', 'classname');
  }); 
});
```
,but I failed(I modified the css in advance).
I tried debugging, and before the data is shown on the grid, the findRows() function has been executed.
I think we should excute the findRows() function after Grid is made.
Is there a function that you are offering after data is shown on the grid?
I desperately need your help.

**Comment by js87zz** [comment]
@wjdgns7989 
`successResponse` callback is executed before the response data will be applied to grid.
To solve the issue you commented we provide the `onGridUpdate` lifecycle option. This callback will be executed every time the data is update through datasource or `resetData` API.
You can change your option as below. 
```js
const grid = new tui.Grid({
  // ...
  onGridUpdated() {
    grid.findRows(function(row) {
      // write your condition
      return row.rowKey % 2 === 0;
    }).forEach(function(row) {
      grid.addCellClassName(row.rowKey, 'name', 'classname');
    });
  }
});
```

**Comment by wjdgns7989** [comment]
Thanks.
I used tui-grid 4.5.1 Version.
So, I updated tui-grid 4.10.0 Version and solved this problem.
(I added "contentType : 'application/x-www-form-urlencoded'" and your code.)
Thank you for your support.
