### ISSUE TITLE
grid display issue

### ISSUE THREAD

**Issue by jochouen** [nhn/tui.grid#1018]
**Summary**
In using '@toast-ui/react-grid' in TypeScript.
I passed some data in, but only two data are displayed, there should be four data.There was a display problem.
I think this is a calculation error of bodyHeight, What do you think?
I set auto.

**Screenshots**
<img width="1509" alt="スクリーンショット 2020-04-28 12 49 16" src="https://user-images.githubusercontent.com/10725284/80445593-a6ad0500-894f-11ea-82a5-66fcaa8c554c.png">

**Version**
"version": "4.10.1"

**Additional context**
```
<Grid
        columns={columns}
        data={data}
        bodyHeight="auto"
        rowHeight="auto"
      />
```
Because the height will be different according to different data, so I set auto.
But there is a problem with the display.
If this is not a bug, what should I do?

**Comment by js87zz** [comment]
@jochouen 
The grid has been rendered properly when i tested it. Can you give us more detail source code or example in codepen or jsfiddle?

**Comment by jochouen** [comment]
@js87zz 
<img width="1791" alt="スクリーンショット 2020-04-30 16 10 18" src="https://user-images.githubusercontent.com/10725284/80682288-27f5ca80-8afd-11ea-9793-0085bc7d3d36.png">

```
import ....
.......

class SampleContent {
  private el: HTMLDivElement;

  constructor(props: CellRendererProps) {
    const rootDom = document.createElement('div');
    this.el = rootDom;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props: CellRendererProps) {
    const sampleArr = (props.value as unknown) as [];
    const element = sampleArr.map(
     (item: {url: string; id: string}, index: number) => (
        <div key={index} style={marginTop: '10px'}>
          <p>{item.url}</p>
          <p>{item.id}</p>
        </div>
      )
    );
    ReactDOM.render(element, this.el);
  }
}

const GridSample: React.FC = () => {
  const columns = [
    {name: 'id', header: 'ID', renderer: SampleContent},
    {name: 'name', header: 'Name'}
  ];

  const data = [
    {
      id: [
        {
          url: 'url1',
          id: 'id1'
        },
        {
          url: 'url2',
          id: 'id2'
        },
        {
          url: 'url3',
          id: 'id3'
        },
        {
          url: 'url4================ Up to here is data 1',
          id: 'id4'
        }
      ],
      name: 'name1'
    },
    {
      id: [
        {
          url: 'url1',
          id: 'id1'
        },
        {
          url: 'url2',
          id: 'id2'
        }
      ],
      name: 'name2'
    },
    {
      id: [
        {
          url: 'url1',
          id: 'id1'
        },
        {
          url: 'url2',
          id: 'id2'
        }
      ],
      name: 'name3'
    }
  ];

  return <Grid columns={columns} data={data} />;
};

export default GridSample;


```
The above is the sample code.


Maybe I know where the problem is.
```
<div key={index} style={marginTop: '10px'}>
```
I set the margin, So there was a display problem.
I think, When calculating the height, did you not include the value of margin? Or should I use other methods to set the margin?

**Comment by js87zz** [comment]
@jochouen 
Sorry for late replying.
I tested it you commented with `margin-top`, but the our react example is well performed.
The reason that the style `overflow: hidden` is added in my renderer. If that style is not applied, the height is not calculated properly with margin.
Could you add the style `overflow: hidden` in your renderer as below?
```js
class SampleContent {
  private el: HTMLDivElement;

  constructor(props: CellRendererProps) {
    const rootDom = document.createElement('div');
    // add the `overflow` style
    rootDom.style.overflow = 'hidden';
    this.el = rootDom;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props: CellRendererProps) {
    const sampleArr = (props.value as unknown) as [];
    const element = sampleArr.map(
     (item: {url: string; id: string}, index: number) => (
        <div key={index} style={marginTop: '10px'}>
          <p>{item.url}</p>
          <p>{item.id}</p>
        </div>
      )
    );
    ReactDOM.render(element, this.el);
  }
}
```
