### ISSUE TITLE
체크박스 전체 선택 시 속도문제

### ISSUE THREAD

**Issue by daehan0522** [nhn/tui.grid#1019]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
3.9.0

**Additional context**
체크박스 전체 선택 시 다중선택을 했을때 100개이상이 넘어가면 속도가 오래걸립니다.
해당문제에대한 답변부탁드립니다.

![image](https://user-images.githubusercontent.com/42962279/80481194-f65df180-898c-11ea-8c46-77c946adf3ab.png)

**Comment by js87zz** [comment]
@daehan0522 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
`3.x` has the performance problem. So we recommend updating version to `4.x`
