### ISSUE TITLE
tui grid header custom 관련 질문

### ISSUE THREAD

**Issue by seoyoung-heo** [nhn/tui.grid#1021]
안녕하세요.
tui grid 사용하여 개발중인데요.
header를 동적으로 뿌려주고 있는데...
헤더에 select box를 같이 넣을 방법이 있을까요?

헤더 이름 위에 select box를 넣고 싶은거거든요...

table로 그리면 아래 그림과 같은건데...
tui grid로 가능한지 궁금하며, 가능하다면 방법도 좀 알려주세요.!

![image](https://user-images.githubusercontent.com/64517494/80563926-733da980-8a27-11ea-9e71-59fa4e91c6f5.png)

**Comment by js87zz** [comment]
@seoyoung-heo 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
