### ISSUE TITLE
Checkbox Custumizing issue.

### ISSUE THREAD

**Issue by worjs320** [nhn/tui.grid#1023]
Hi, nice to meet you.
I am using the toast grid very well.

i want to custumize checkbox in IE.
but, this link(https://nhn.github.io/tui.grid/latest/tutorial-example11-row-headers) example code is ES6. 
Is there an example written in ES5 grammar?

**Version**
4.10.1

**Additional context**

**Comment by js87zz** [comment]
@worjs320 
Currently, we don't provide the es5 examples.
You can implement it using the [prototype](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype) and `function` as es5 syntax.
