### ISSUE TITLE
Frozing table after first filter and sort

### ISSUE THREAD

**Issue by Alexby8** [nhn/tui.grid#1028]
**Describe the bug**
When we first time apply some filter and then sort the table with big number of rows (bigger then 500) the page freezes for a big time. Next manupulations are going well. Problem in the first step.
Video example:
https://youtu.be/6OMgEVE1fmU
Example page:
http://art-media-pro.ru/

**To Reproduce**
1. Go to example page
2. Set text filter "Contains 1"
3. Try to sort the second column

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 81.0.4044.129

**Comment by js87zz** [comment]
@Alexby8 
We checked the freezing the browser. 
It looks critical, we will fix it next release. Thank you for providing the detail example!

**Comment by js87zz** [comment]
@Alexby8 
The performance of sorting and filtering has been improved in `v4.13.0`(#1037)
