### ISSUE TITLE
When using custom rendering, I think should avoid limit data type and should make render method optional.

### ISSUE THREAD

**Issue by mwrote** [nhn/tui.grid#1031]
**Summary**

Two error is occurred.
1. at `value: name`, can't assign {value: string, id: number} to OptRow
2.  at `renderer: NameCell', require `render` method in NameCell class, but rendering is success.

```
    class NameCell {
      private el: HTMLSpanElement;
      constructor(props: any) {
        this.el = document.createElement('span');
        this.el.innerHTML = props.value.value;
      }
      getElement() {
        return this.el;
      }
    }
    const data: OptRow[] = [
      {
        name: {
          value: 'name',          // <-- 1. this is error
          id: 1111,
        },
        comment: 'comment'
      }
    ];
    const columns: OptColumn[] = [
      {
        name: 'name',
        header: 'Name',
        renderer: NameCell          // <-- 2. this is error
      },
      {
        name: 'comment',
        header: 'Comment'
      }
    ]
```

``` 
<Grid data={data} columns={columns} /> 
```

I think
- If only want to display the data, don't need to use "render", so you should make render optional
- When using custom cells, the data structure is unpredictable, so you should add a free data structure type to OptRow

**Screenshots**

![image](https://user-images.githubusercontent.com/805577/81251513-6855cb00-905e-11ea-8c27-60b13989f041.png)
![image](https://user-images.githubusercontent.com/805577/81251600-9e934a80-905e-11ea-8b3d-aa7e866f528a.png)
![image](https://user-images.githubusercontent.com/805577/81251616-a5ba5880-905e-11ea-8a67-00951d956ef9.png)

**Version**
@toast-ui/react-grid: ^4.10.1

**Comment by js87zz** [comment]
@mwrote 
1. at `value: name`: can't assign {value: string, id: number} to OptRow
  * This is related with [this issue](https://github.com/nhn/tui.grid/issues/1014). We will change it.
2. at `renderer: NameCell`: require render` method in NameCell class, but rendering is success.
  * I think the `render` method should be mandatory. If the grid is never changed, rendering will be successful. But the grid can be changed through various way(editing the cell, calling API) and the more strict type is acceptable for the safety to typescript user.

**Comment by js87zz** [comment]
@mwrote 
The `object` type has been added in `v4.13.0`(#1054).

**Comment by mwrote** [comment]
thanks
