### ISSUE TITLE
컬럼 checkBox

### ISSUE THREAD

**Issue by hongbining** [nhn/tui.grid#1032]
renderer로 한 컬럼에 checkbox 생성까지는 했습니다. 
그리고 그리드가 로드 될때 1이면 checked로 하고 싶은데 어디서 예제가 부족해 어디서 할지 잘 모르겠습니다.  그리고 checkbox 위치가 왼쪽으로 있는데 가운데로 수정하고싶습니다.

```js
class CustomCheckBox{
	constructor(props) {
		const el = document.createElement("input");
		el.type = "checkbox";
		
        this.el = el;
        this.render(props);
    }

    getElement() {
        return this.el;
    }

    render(props) {
        this.el.value = String(props.value);
        const checked = Boolean(props.value);
    }
}
```

칼럼 :  {header: "연결상태", name:"CONN_STATUS", width: 70, align :"center", renderer: { type: CustomCheckBox} }

**Comment by js87zz** [comment]
@hongbining 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
[This link](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) is our tutorial link.
If you refer the MDN document for manipulating the DOM, it will be helpful.

**Comment by mucsiza** [comment]
`el.type = 'checkbox';
el.checked = Boolean(props.value);`

이렇게 하니 잘 됩니다.
