### ISSUE TITLE
another issue of editing cell in tree grid

### ISSUE THREAD

**Issue by izzumi** [nhn/tui.grid#1033]
**Describe the bug**
I've confirmed that the last problem(#995 )  has been solved.
but when I tried with adding new row, it failed.(works well in modifying row)
please check again...

**Comment by js87zz** [comment]
This issue is only caused when the empty row is appended like as below.
```js
grid.appendRow();
// or
grid.appendRow({});
```
We will fix it for executing with empty row.

**Comment by js87zz** [comment]
@izzumi 
The bug has been fixed in `v4.13.0`(#1034).
