### ISSUE TITLE
After editing a grid, I want executing refresh function.

### ISSUE THREAD

**Issue by wjdgns7989** [nhn/tui.grid#1038]
I use **tui-grid-4.10.0** version.

After editing a grid, I want executing refresh function(because of grid refresh with edit result).
So, I executed 'readData()' with parameter in refresh function.
But, 'Uncaught TypeError : Cannot read property 'rowSpanMap' of undefined' error has occured.
How can I modify it?
This is my code.

```
onAfterChange(ev) {
    if(confirm("really"+ev.value+"update?") {
        $("#id1").val(ev.value);
    }
    refresh();
}
```
```
function refresh() {
    let form_param = {};
    let form_param_array = $("#param").serializeArray();
    $(form_param_array).each(function(i, item){
        form_param[item.name] = item.value;
    });
    let param = Object.assign(form_param);
    grid.readData(grid.getPagination().getCurrentPage(), param, true);
}
```

Error Contents
Uncaught TypeError : Cannot read property 'rowSpanMap' of undefined        ---------- tui.grid-4.10.0.js:2294

**Comment by js87zz** [comment]
@wjdgns7989 
When i tested it like you comment in our example, grid has been rendered properly.
Can you give more detail code? 
I think that It is better to update the data at once than request every modify the cell value. How about it?

**Comment by wjdgns7989** [comment]
Thank u for your answer.
Umm.. Your opinion is so good. but, I don't use frequency data update.
Recently, I found problem in my code.

```
onAfterChange(ev) {
    $("#id1").val(ev.value);
    refresh();
}
```

This code work well.
I think 'confirm function' is somthing wrong.
If you check, comment please. Thanks.
