### ISSUE TITLE
toast grid XSS 

### ISSUE THREAD

**Issue by jwsong826** [nhn/tui.grid#1040]
How do I respond to XSS in toast grid v3? If you enter the value '<script>alert('hi');</script>' in the grid, an alert message will appear in that window. I've tried using the 'escapeHTML:true' option in github, but it's still the same.

**Comment by js87zz** [comment]
@jwsong826 
`3.x` has default option(`useHtmlEntity`) for preventing XSS. However, when I checked the option, `useHtmlEntity` has a bug. Currently, we don't have the plan for `v3.x` for some time. How about upgrading the version `v4.x`
