### ISSUE TITLE
rowheader height issue

### ISSUE THREAD

**Issue by worjs320** [nhn/tui.grid#1041]
**Summary**
Hi nice to meet you. im using tui grid well.
The height of the rowheader is not increased by the height of the row.

**Screenshots**
![image](https://user-images.githubusercontent.com/32512236/81647361-dc7ddd80-9467-11ea-8af6-0089b4ff333e.png)

**Version**
4.11.0

**Comment by js87zz** [comment]
@worjs320 
Can you try as below?
```js
const grid = new tui.Grid({
  // ...
  rowHeight: 'auto'  // this option adjust the height.
});
```
