### ISSUE TITLE
How to overwirte css styles of front end framework using tui.grid?

### ISSUE THREAD

**Issue by taurenshaman** [nhn/tui.grid#1048]
**Summary**
I'm using [Metro4](https://github.com/olton/Metro-UI-CSS) as the front end framework of the whole site. When I import tui.grid to my website, Metro's css effects tui.grid even if tui.grid is referenced after metro. I think `[class*=cell-], [class*=col-]` makes the effect, and found `display: table-cell;` has some work after I tried some times.

**Screenshots**
There should be two columns, but: 
![2020-05-15222422](https://user-images.githubusercontent.com/1308706/82061134-e3704e80-96fa-11ea-9ca3-5eda44bb635c.png)

I try to change `display: table-cell;` of  `[class*=cell-], [class*=col-]`:
![image](https://user-images.githubusercontent.com/1308706/82061641-917bf880-96fb-11ea-9532-a77ed6b723ab.png)

But it only affects on header of the table, the content still has some problems: 
![image](https://user-images.githubusercontent.com/1308706/82062040-16ffa880-96fc-11ea-9004-64b9fcef7cbf.png)

Can anyone give me some advice?

**Version**
v4.11.0

**Additional context**
Double click on cell to edit it:
https://codepen.io/taurenshaman/pen/NWGBMqB

Thank you very much!

**Comment by taurenshaman** [comment]
temporary solution: 
```
.tui-grid-cell {
    display: table-cell;
}
.tui-grid-cell-current-row {
    display: table-row;
}
.tui-grid-cell-content {
    display: block;
}
/*.tui-grid-cell-has-input {
    display: table-cell;
}*/
```

**Comment by js87zz** [comment]
@taurenshaman 
Sorry for late replying.
If the css of metro change the css of grid(row, editing cell, etc..), the solution is that overriding the css like above your comment. Because it's hard to provide API or option for controlling the css of grid on various UI-framework. It will be better to override the css directly in your service for preventing side effects.
