### ISSUE TITLE
그리드 select 타입 문의

### ISSUE THREAD

**Issue by pihon1** [nhn/tui.grid#1051]
안녕하세요
그리드 관련해서 문의 하나 드립니다
컬럼의 타입이 select인 경우에 셀을 더블클릭 해야지만 select 타입이라는걸 확인이 가능한데 더블클릭하지 않아도 바로 select 타입이라는걸 알 수 있게 드롭다운 화살표를 바로 표현할 수 있는 방법은 없을까요?

**Comment by js87zz** [comment]
@pihon1 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
[This tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) will be helpful to you.
