### ISSUE TITLE
inquire about checkbox and editor

### ISSUE THREAD

**Issue by kim-seung** [nhn/tui.grid#1056]
![1111](https://user-images.githubusercontent.com/60688938/82532785-037d9300-9b7d-11ea-9905-e312480f371a.JPG)

Hello please send a checkbox in the photo. There are two and many ways I thought.

1. Give the editor property to the last column declaration of the grid and control it through options in the editor.
(I searched through google, but didn't see any properties to control.)
2. I tried implementing the following using the event check, but it doesn't work. (
Even if I try to implement like this, do I need to give the editor property to the column declaration?)

```js
grid.on('check', ev => {
  var condition = ev.rowKey;
    if(condition)
    {
        grid.cancelEditing();
    }
}); 
```

As a result, the above two methods fail to implement, so I ask a question ... Please answer.

**Comment by js87zz** [comment]
@kim-seung 
As far as I can understand, you want to control the state of editing cell of the last column when checking the row-header checkbox. right?
If it's right, you can try as below.
```js
const grid = new Grid({
  // ...
 columns: [{
  name: 'count',
  header: '조정 수량',
  editor: 'text'
 }],
 rowHeaders: ['checkbox']
});

grid.on('check',(ev) => {
  grid.startEditing(ev.rowKey, 'count');
});

grid.on('uncheck', () => {
  grid.cancelEditing();
});
```

**Comment by kim-seung** [comment]
Thank you for answer.
I tried it the way you told me.
In case of check, startEditing function works.
But if it is uncheck, cancelEditing function does not work. ㅠㅠ

**Comment by js87zz** [comment]
@js87zz 
Can you give us grid configuration code?

**Comment by kim-seung** [comment]
Below is the grid code.

var Grid = tui.Grid;
//import Grid from 'tui-grid';
Grid.applyTheme('striped');
const grid = new Grid({
  el: document.getElementById('grid'), // 컨테이너 엘리먼트
  bodyHeight: 'fitToParent',
  rowHeaders: [
    {
      type: 'checkbox',
      width: 60,
      header: `
        <label for="all-checkbox" class="checkbox">
          <input type="checkbox" id="all-checkbox" class="hidden-input" name="_checked" style="display: none;" />
          <span class="custom-input" style="line-height: 2rem;">선택</span>
        </label>
      `
    }
  ],
   columns: [    
    {
      name: 'SL_NM',
      header: '창고',
      align: 'center',
      width: 80,
      resizable: false
      //sortable: true,
      //sortingType: 'desc'
    },
    {
      name: 'LOT_NO',
      header: 'LOT번호',
      align: 'right',
      width: 120,
      resizable: false
      //sortable: true,
      //sortingType: 'asc'
    },
    {
      name: 'ITEM_CD',
      header: '품번',
      align: 'center',
      width: 120,
      resizable: false
    },
    {
      name: 'ITEM_NM',
      header: '품명',
      align: 'center',
      width: 120,
      resizable: false     
    },
    {
      name: 'GOOD_QTY',
      header: '재고수량',
      align: 'center',
      width: 80,
      resizable: false      
    },
    {
      name: 'INV_QTY',
      header: '조정수량',
      align: 'center',
      width: 80,
      resizable: false,
      editor:'text'
      
    }
  ],
  columnOptions: {
        resizable: true
      }  
});

grid.on('check',(ev) => {
  grid.startEditing(ev.rowKey, 'INV_QTY');
});

grid.on('uncheck', () => {
  grid.cancelEditing();
});

**Comment by js87zz** [comment]
@kim-seung 
The canceling the editing is done properly with your option. 
However, I checked the weird operation you commented when i tested in our custom-row-header example. It looks like the browser bug. 
The operation is well done in firefox, safari, but is failed in chrome browser.

**Comment by kim-seung** [comment]
The code I want is below.
Click the checkbox to edit the INV QTY column.
When checkbox is cleared
You cannot modify the INV QTY column.

Do you know a function that can check the value of the checkbox of the row when clicking the INV QTY column of a specific row?

내가 원하는 코드는 다음과 같습니다.
INV QTY 열을 수정하려면 checkbox를 선택해야합니다.
checkbox가 선택 되지 않은 행은 INV_QTY의 수정이 불가능합니다.

특정 행의 INV_QTY열의 값을 클릭했을 경우 현재 row의 checkbox의 값을 알 수 있는 함수를 혹시 아시나요?

**Comment by js87zz** [comment]
As I above commented, the issue is caused by **browser bug**. 
We cannot solve the browser bug.  
The checkbox which used with label causes the bug. How about using plain checkbox without customizing style. In case of it, the operation is executed properly as below.
![2020-05-22 15-36-43 2020-05-22 15_36_54](https://user-images.githubusercontent.com/37766175/82638572-2160fb80-9c42-11ea-9547-17e9c101e441.gif)

**Comment by kim-seung** [comment]
Thank you for answer.
If you click the 2nd row (x) of the unchecked Name column in the capture you sent above, is it not corrected?

**Comment by js87zz** [comment]
@kim-seung 
You try it.

**Comment by kim-seung** [comment]
This is the result of running in firefox browser.
Unchecked checkbox should not be editable. 
However, it can be modified as shown in the photo.
![qqq](https://user-images.githubusercontent.com/60688938/82768194-70887580-9e68-11ea-9af0-9fb355531e14.png)

**Comment by js87zz** [comment]
@kim-seung 
Try as below.
```js
   // force to call cancelEditing when clicking the cell
   grid.on('click', (ev) => {
      if (grid.getRow(ev.rowKey)._attributes.checked) {
        grid.cancelEditing();
      }
    });

    grid.on('check', function(ev) {
      grid.startEditing(ev.rowKey, 'name');
    });

    grid.on('uncheck', function(ev) {
      grid.cancelEditing();
    });
```

**Comment by kim-seung** [comment]
Thank you for answer.
I did it with the code below.

{
      name: 'INV_QTY',
      header: '조정수량',
      align: 'center',
      width: 80,
      resizable: false,
      editor:'text'
}    --> Declaration part of the column to be modified

grid.on('check',(ev) => {
  grid.startEditing(ev.rowKey, 'INV_QTY');
});

grid.on('editingStart',(ev) => {
  var rowKey = ev.rowKey;
  var checkRows = grid.getCheckedRowKeys();
  if(checkRows.indexOf(rowKey)>-1){

  }else{
     grid.cancelEditing();
  }
}); -->After debugging, I enter inside the else statement, but grid.cancelEditing () does not work. grid.cancelEditing () is executed in the Google Developer Tools console.

I tried running on Chrome, Edge and Firefox, but it didn't work correctly.
I think grid.cancelEditing () doesn't fire inside the event.

**Comment by kim-seung** [comment]
grid.on('click', (ev) => {
    if(ev.columnName == "INV_QTY"){
      if(grid.getRow(ev.rowKey)._attributes.checked){
        grid.startEditing(ev.rowKey, 'INV_QTY');
      }else{
        grid.cancelEditing();
      }
    }else if(ev.columnName == "_checked"){
      if(grid.getRow(ev.rowKey)._attributes.checked){
        grid.cancelEditing();
      }else{
        grid.startEditing(ev.rowKey, 'INV_QTY');
      }
    }
  }); 
Sorry for being busy. Let me ask you a few.
1. if(grid.getRow(ev.rowKey)._attributes.checked) execution result of the statement is reversed.
   Why are the results reverse? 
2. Can I check whether it is checked before the click event ends?
3. An event occurs even if you select an area other than the check box of the grid checkbox.
   Can you figure out a solution?
4. Is there a way to enter editor mode with one click?(Currently, editior mode works by double-clicking.)

**Comment by js87zz** [comment]
@kim-seung 
From now on, You try to change the method for customizing checkboxes or use other events.
It is no longer possible to give other guides.

**Comment by kim-seung** [comment]
See the first question photo.
I want to change the background color of the last column to blue.
In the code 
{
name: 'INV_QTY',
header: '조정수량',
align: 'center',
width: 80,
resizable: false,
editor:'text'
}
How do you apply the code?
