### ISSUE TITLE
Is readdata function control possible?

### ISSUE THREAD

**Issue by luckysei** [nhn/tui.grid#1057]
**Summary**
Is there a way to print the total number of items on the page using the data.paginaton.totalcount item among the data received as the readdata function?

I tested it as possible with the onGridUpdated function.
I don't think it'll be easy to use because it keeps paging when I move the page.

Is there any other way?

It was written using a translator due to lack of English composition.

**Screenshots**
![image](https://user-images.githubusercontent.com/62042518/82539183-f914c680-9b87-11ea-9936-029771c21440.png)

**Version**
@toast-ui/vue-grid": "^4.12.1"

**Additional context**

**Comment by js87zz** [comment]
First, you get the data through our dataSource spec right?
So If we provide the API like `getTotalCount`, I think you would print the total count number as below.
```js
onGridUpdated() {
  const totalCount = grid.getTotalCount();
  // write your code
}
```
If the above operation is not what you said, please give us more detail information.
