### ISSUE TITLE
setting readdata.url host

### ISSUE THREAD

**Issue by luckysei** [nhn/tui.grid#1059]
**Summary**
Is there a way to set up the host of readdata.url without specifying it directly?
I am currently using it as shown in the picture below.

This article was written through a translator.
**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/62042518/82619762-c8796f00-9c11-11ea-827b-6e57fb764b6b.png)

**Version**
"@toast-ui/vue-grid": "^4.12.1"

**Additional context**

**Comment by js87zz** [comment]
@luckysei 
After declaring the variable, you can use it.
```js
const base = 'http://localhost:8080'

// ...

api: {
  readData: {
    url: () => `${base}/api/sample/data`
  }
}
```
