### ISSUE TITLE
When I select a lot of data and copy(or paste), get error.

### ISSUE THREAD

**Issue by kkhkykkk** [nhn/tui.grid#1060]
## Version
4.x

## Development Environment
chrome, windows

## Current Behavior
set focus to many cell
press Control + a (select all)
press Control + c (copy)
result console : Cannot read property...(reference to screenshot)

## Expected Behavior
copy to clipboard

![error](https://user-images.githubusercontent.com/17283453/82633684-ae9e5300-9c36-11ea-8951-b4c922194465.png)

**Comment by js87zz** [comment]
@kkhkykkk 
We have the plan to fix it. 
However, if large data should be copied, the performance will be very slowed down.
