### ISSUE TITLE
dataSource is not mapping

### ISSUE THREAD

**Issue by jeong-w-93** [nhn/tui.grid#1061]
<p>
I am using Toast Grid 4.12.1 version in Spring Boot-vue. However, even if you try to load dataSource, it is called but does not mapping</p><p>
But it can be entered manually or imported from vuex 
</p><p>&nbsp;</p><p><br></p><pre class=""><code class="language-markup">  &lt;grid
      :data="gridProps.data"
      :columns="gridProps.columns"
      :options="gridProps.options"
      :theme="gridProps.myTheme"
      @check="onCheck"
      @uncheck="onUnCheck"
      @click="click"
      @editingFinish="editingFinish"
      :rowHeaders="gridProps.rowHeaders"
      :columnOptions="gridProps.columnOptions"
    &gt;&lt;/grid&gt;</code></pre><p><br></p><p><br></p><pre class="line-numbers"><code class="language-javascript">created() {
    this.gridProps = {
     
      rowHeaders: [
          'checkbox', 'rowNum'
      ],
      columnOptions: {
        resizable: true,
        frozenCount: 1,
      },
      columns: [
        {
            header: '아이디',
            name: 'id',
            sortable: true,
            sortingType: 'desc',
            validation: {
                dataType: 'number'
            }
        },
        {
          header: '날짜',
          name: 'date',
          //editor: 'datePicker'
          editor: 'text'
        },
        {
          header: '타입',
          name: 'type',
           editor: 'text',
           filter: {
                type: 'text',
                showApplyBtn: true,
                showClearBtn: true
            },
          
        },
        {
          header: '코멘트',
          name: 'comment',
           editor: 'text',
           validation: {
                dataType: 'string'
            }
        },
        {
          header: '관리자',
          name: 'admin',
           editor: 'text',
           filter: 'select',
        },
      ],
      useClientSort: false,
      data: 
        {
          api: {
           readData: { url: '/api/contacts', method: 'GET' },
          }
        },
     
      myTheme: {
        name: 'myTheme',
        value: {
          cell: {
            normal: {
              background: '#00ff00',
              border: 'black',
              text: '#474747',
            },
            header: {
              background: 'grey',
              border: '#ffff00'
            },
            editable: {
              background: '#ebebce',
              text: 'green',
            }
          }
        }
      },
      options: {
        bodyHeight: 600,
        rowHeaders: ['checkbox'],
        pageOptions: {
          useClient: true,
          perPage: 20,
        
        },
      }
      
    };
    </code></pre><p><img src="//file.okky.kr/images/1590131412530.PNG" data-filename="1590131412530.PNG" style="width: 100%;"></p><p><br></p><pre class="line-numbers"><code class="language-markup">[
    {
        "id": 33037,
        "date": "1590127840313",
        "type": 1,
        "comment": "로그인했습니다.(0:0:0:0:0:0:0:1)",
        "admin": "air"
    },
    {
        "id": 33036,
        "date": "1590127519534",
        "type": 1,
        "comment": "자동 로그아웃했습니다.(0:0:0:0:0:0:0:1)",
        "admin": "air"
    },
</code>

![image](https://user-images.githubusercontent.com/37054073/82643154-06928500-9c4a-11ea-9e5c-2ce2b42e9fec.png)
![image](https://user-images.githubusercontent.com/37054073/82643187-127e4700-9c4a-11ea-97e8-2763326bcdb8.png)

![image](https://user-images.githubusercontent.com/37054073/82643274-317cd900-9c4a-11ea-95e4-01de598dfc6f.png)

**Comment by js87zz** [comment]
The structure of the response data should be as below. Can you check it?
```json
{
  "result": true,
  "data": {
    "contents": [
       {  
        "id": 33036,
         // ...
       },
       // ...
     ], // grid data for mapping
    "pagination": {
       // ...
    }
  }
}
```

**Comment by jeong-w-93** [comment]
> The structure of the response data should be as below. Can you check it?
> 
> ```js
> {
>   "result": true,
>   "data": {
>     "contents": [
>        {  
>         "id": 33036,
>          // ...
>        },
>        // ...
>      ], // grid data for mapping
>     "pagination": {
>        // ...
>     }
>   }
> }
> ```



Sorry How to check response data Structure?

**Comment by js87zz** [comment]
@jeong-w-93 
Look at the network tab of browser devtool. 
If you search in google, you can find the way.

**Comment by jeong-w-93** [comment]
It was solved by changing the response data structure. 
Thanks Locust
