### ISSUE TITLE
How can I use Grid Instance?

### ISSUE THREAD

**Issue by JinSeokE** [nhn/tui.grid#1070]
tui-grid : 4.11.0
@toast-ui/react-grid : 4.11.0
-------------------------------
import Grid from '@toast-ui/react-grid';

class TuiGrid extends Component {
    gridRef = React.createRef() ;
    handleSearch = () => {
        this.gridRef.current.getInstance().readData(1, {'searchLoginId':'test'});
    };

    render() {
        return (
            <div className="App">
                <Grid
                    ref={this.gridRef}
                    data={dataSource}
                    columns={columns}
                    rowHeight={25}
                    bodyHeight={200}
                    heightResizable={true}
                    rowHeaders={['rowNum']}
                    pageOptions={pageOptions}
                />
                <button onClick={this.handleSearch}>조회</button>
            </div>
        );
    }
};

The above code works fine.

but I am working on a project using Nextjs, when I click refresh, the component does not render and the following error is displayed.

window is not defined
ReferenceError: window is not defined

I tried changing it to code like this:

import dynamic from "next/dynamic"
const Grid = dynamic(() => import("@toast-ui/react-grid"), {
    ssr: false
})

but I can't use this code : 
this.gridRef.current.getInstance();

How can I use Grid Instance?

Thank you for answer.

**Comment by js87zz** [comment]
@JinSeokE 
[This issue](https://github.com/nhn/tui.grid/issues/935) is related with your issue.
And refer this [link](https://github.com/vercel/next.js/issues/4957)
