### ISSUE TITLE
filter type select 일때 text 표시

### ISSUE THREAD

**Issue by wjdek924** [nhn/tui.grid#1072]
grid에서 filter를 사용할때 

header : 'test',
name:'test',
formatter:'listItemText',
editor:{type:'select', option:{listItems:gridData5}},
filter:{type: 'select'}

일때 select filter에 value만 표시되어 나타나는데 text값이 표시되게 하려면 어떻게 하여야 될까요?

* gridData5 = [{text:'사과',value:'1'},{text:배,value:'2'}....]
select filter에 표시되는 값은 1,2(value값임)

**Comment by js87zz** [comment]
@wjdek924 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.

What is your version?
When i tested it, the select filter has been displayed with `text` properly.
