### ISSUE TITLE
I'd like to know the order of "rowKey".

### ISSUE THREAD

**Issue by HotRedMat** [nhn/tui.grid#1073]
Hello
I'd like to know the order of the "rowKey" as the title suggests.

While searching, "grid.getRow(rowKey)._attributes.rowNum" .

I wonder if it's okay to use the source code above.

Thank you.

**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@HotRedMat 
We do not recommend to use the code you commented because `_attributes` property is private property. If the data is not sorted, `rowKey`will be same as the index. 
How about using the `getRowAt` API?
