### ISSUE TITLE
about Grid Structure.

### ISSUE THREAD

**Issue by oznwlo** [nhn/tui.grid#1074]
Hello, Thanks for giving 'tui-grid' as an open-source.

I have questions about 'return structure'.

when I search about grid, I have to follow the 'return structure' if I want to use tui-grid like:
`{
    "result": true,
    "data": {
        "contents": [],
        "pagination": {
            "page": 1,
            "totalCount": 100
        }
    }
}`
and Now... my Rest API Return just 'contents area'...
If i want to use tui-grid, Do i make the structure in the Serverside? (using map?) 
 or If I already use another structure serverside, Do I need to develop the structure for tui?

Now, I just return DVO Type like this:
`public List<OutDTO> getDeftRsltAll(
    return service.getDeftRslt(inObj);
)`

Do I need to change the server-side?
Thanks for your answer.

**Comment by js87zz** [comment]
@oznwlo 
If you have a problem to change your REST API to fit our dataSource structure, you don't have to change the your API. You can set the data to grid after communicating with your server through using [resetData](https://nhn.github.io/tui.grid/latest/Grid#resetData) API.
```js
const grid = new Grid({
  columns, 
  data: [] // initial empty data
});

// after loading the DOM
axios.get('./get').then(res => {
  grid.reset(res.data); // set your response data from the server
});
```

**Comment by oznwlo** [comment]
Thanks for your answer.

I can understand what you say. but how about Vue3..?
Is it same..? I tried, but get the  '_toast_ui_vue_grid__WEBPACK_IMPORTED_MODULE_2__.Grid is not a constructor' like  that..
