### ISSUE TITLE
how to editor select li disabled control ?

### ISSUE THREAD

**Issue by wjdek924** [nhn/tui.grid#1075]
editor :{type:'select', options:listItem:data1}

data1 = [{displye:"false",text:"text1",value:1},{displye:"true",text:"text2",value:2}];

I want to do "displye:false" when the value in 'fasle' is displayed in "li".
How can I do this?

**Comment by js87zz** [comment]
We don't provide it in our built-in editor. If you want it, you could make it through [custom editor](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-editor.md)
