### ISSUE TITLE
What I miss in the grid?

### ISSUE THREAD

**Issue by oznwlo** [nhn/tui.grid#1077]
Hello, I'm new one in tui-grid.

I hope to append the row in the grid using 'appendRow' but It is not working well..

template is like:

```html
<div>
            <v-btn class="margin-right-10px" color="primary" v-on:click="addRow" >ADD</v-btn>
            <grid
                ref='mainGrid'
                 :data="gridProps.data"
                 :columns="gridProps.columns"
                 :options="gridProps.options"
                 :columnOptions="gridProps.columnOptions"
                 :rowHeaders="gridProps.rowHeaders"
                 :pageOptions="gridProps.pageOptions"
                 v-on:check="onCheck"/>
</div>
```

and I link the one button with event like:

```js
addRow() {
  console.log("called onClick");
  this.$refs.mainGrid.prependRow();
}
```

but It's not working. appendRow also... 
If i log check, It have some things 'this.$ref.mainGrid' but If I click the button,
It shows
'Cannot read property 'prependRow' of undefined"'

What I am missing..?

**Comment by oznwlo** [comment]
If i log about grid using '$refs' it is not working all..
i try it after rendering with button.

 axios.get('./get').then(res => {
                    this.$refs.grid.reset(res.data); // set your response data from the server
                    });

return is well, but console show 'this.$refs.grid.data.get is not a function" ..

**Comment by js87zz** [comment]
@oznwlo 
If you use the `@toast-ui/vue-grid`, the code should be changed as below.(https://github.com/nhn/tui.grid/tree/master/packages/toast-ui.vue-grid#method)
```js
axios.get('./get').then(res => {
  this.$refs.grid.invoke('resetData', res.data); 
});
```
