### ISSUE TITLE
 How can I use another databases?

### ISSUE THREAD

**Issue by jeong-w-93** [nhn/tui.grid#1078]
Toast Grid is Using well 
But I want to use different database for different grid tables
How can I use another data base?

테이블 마다 다른 db를 불러오려면 어떻게 해야 할까요? body,data,contents 규격 맞추려니 헷갈리네요 Contents에 리스트를 넣자니 인식을 못하구요

My server structure sample is body.java, data.java, contents.java

`public class Body  {
	private boolean result = true;
	private Data data;
}

public class Data  {
	List< Contents > contents;
}

public class Contents {
	private int id;
	private String date;
	private int type;
	private String comment;
	private String admin;
}
`

**Comment by js87zz** [comment]
@jeong-w-93 
If you have a problem to change your API to fit our dataSource structure, you don't have to change the your API or use dataSource. You can set the data to grid after communicating with your server through using [resetData](https://nhn.github.io/tui.grid/latest/Grid#resetData) API.
```js
const grid = new Grid({
  columns, 
  data: [] // initial empty data
});

// after loading the DOM
axios.get('./get').then(res => {
  grid.reset(res.data); // set your response data from the server
});
```
