### ISSUE TITLE
If the child node dynamically add

### ISSUE THREAD

**Issue by ksh1011** [nhn/tui.grid#1079]
If the child node dynamically expands, will it run without problems?
appendRow, appendRows, appendTreeRow all api not working ...

**Comment by ksh1011** [comment]
Also, if invoke('appendRow'), $refs.tuiGrid.data is not updated?

**Comment by ksh1011** [comment]
Also, $refs.tuiGrid does not show children information
![image](https://user-images.githubusercontent.com/22608421/83716413-cc25e080-a66a-11ea-9a4b-34e7fcc98b8a.png)

**Comment by ksh1011** [comment]
![image](https://user-images.githubusercontent.com/22608421/83741105-baf0ca00-a692-11ea-8b5b-146c88bfafea.png)

![image](https://user-images.githubusercontent.com/22608421/83741282-f4c1d080-a692-11ea-8316-e95714f5707c.png)


issue.... 
isn't solving.....

accurate parentRowKey but not matching

**Comment by js87zz** [comment]
@ksh1011 
What is your exact issue? You want to append the row when `expand` the row?
And Please fill out issue **respecting our form** .
