### ISSUE TITLE
Custom Renderer : Select

### ISSUE THREAD

**Issue by chiho1** [nhn/tui.grid#1081]
I'm using it as a translation program.

The custom editor function of the grid is excellent, but I am dissatisfied with double-click or click to display elements.

I'm currently testing the custom renderer function to display the Select Element from the beginning.

I am doing es5 for use in Internet Explorer or Google Chrome browser. But there is an error.

I will attach an image or code, so please refer to it and advise me.

![tuigrid1](https://user-images.githubusercontent.com/66509695/83938573-7c811980-a810-11ea-8fb1-44af78c8314a.png)
![tuigrid2](https://user-images.githubusercontent.com/66509695/83938574-7db24680-a810-11ea-86d6-d777c0ddc34a.png)

**Comment by js87zz** [comment]
@chiho1 
It's better to see this [document] (https://developer.mozilla.org/ko/docs/Learn/JavaScript/Objects/Object_prototypes) to use prototype.
If you have a problem to define your custom renderer, It will be helpful to consider transpiler like [babel](https://babeljs.io/)

**Comment by chiho1** [comment]
I'm using a translation program.

Thank you for your answer. However, I'm not satisfied.

After adding select option using protocol, it was not possible to select it. I checked in ie and chrome.

I will provide the image file below and the code I wrote. How can I choose?

https://uicdn.toast.com/tui-grid/latest/tui-grid.css
https://uicdn.toast.com/tui-grid/latest/tui-grid.js
`
	const gridData = [
		{
			name: '1',
			artist: '1-1',
			release: '1-2',
			genre: '1'
		},
		{
			name: '2',
			artist: '2-1',
			release: '2-2',
			genre: '2'
		},
		{
			name: '3',
			artist: '3-1',
			release: '3-2',
			genre: '3'
		},
		{
			name: '4',
			artist: '4-1',
			release: '4-2',
			genre: '1'
		},
		{
			name: '5',
			artist: '5-1',
			release: '5-2',
			genre: '2'
		}
	];

	var CustomRenderer = function(props) {
		const listItems = props.columnInfo.renderer.options.listItems;
    const el = document.createElement('select');

		for (var i = 0; i < 3; i++) {
			var opt = document.createElement('option');
			opt.value = listItems[i].value;
			opt.innerHTML = listItems[i].text;
			opt.selected = props.value;
			el.appendChild(opt);
		}

    this.el = el;
    this.render(props);
	}

	CustomRenderer.prototype.getElement = function() {
		return this.el;
	}

	CustomRenderer.prototype.render = function(props) {
		this.el.value = props.value;
	}

	const grid1 = new tui.Grid({
		el: document.getElementById('grid1'),
		data: gridData,
		columns: [
			{
				header: 'Name',
				name: 'name'
			},
			{
				header: 'Artist',
				name: 'artist'
			},
			{
				header: 'Release',
				name: 'release'
			},
			{
				header: 'Genre',
				name: 'genre',
				renderer: {
					type: CustomRenderer,
					options: {
						listItems: [
							{ text: 'A', value: '1' },
							{ text: 'B', value: '2' },
							{ text: 'C', value: '3' }
						]
					}
				}
			}
		]
	});
`

![tuigrid1](https://user-images.githubusercontent.com/66509695/84565136-21b46880-ada2-11ea-8c83-fb1388057d84.png)

**Comment by js87zz** [comment]
@chiho1 
Currently, We don't support the case you commented. The custom renderer should be used to display the data because the renderer lifecycle is different from editing lifecycle. However, We have the plan to solve this case more convenient.

**Comment by chiho1** [comment]
I'm using a translation program.

Okay. I'll use custom editor temporarily until a solution is found.
