### ISSUE TITLE
disabled checkbox is checked.

### ISSUE THREAD

**Issue by worjs320** [nhn/tui.grid#1082]
**Summary**
disabled checkbox is checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/32512236/84007710-c7836400-a9ab-11ea-8bae-c7c78b5cbcb4.png)

![image](https://user-images.githubusercontent.com/32512236/84007770-d9650700-a9ab-11ea-9dad-985412eec570.png)

![image](https://user-images.githubusercontent.com/32512236/84007810-e4b83280-a9ab-11ea-8b07-302db0a50b6e.png)

**Version**
4.11.0

**Additional context**

Hi nice to meet you. 
I am using tui gird well.
I want to make the disabled checkbox unchecked.
However, if I scroll down after I press Allcheck, the disabled checkbox is also checked.
Is there a workaround?

**Comment by js87zz** [comment]
@worjs320 
Can you give us more detail code(grid configuration code, calling API)?
When i tested it, the check box has been operated properly.
It will be helpful to upload your source code in code sandbox or jsfiddle for resolving this issue.

**Comment by worjs320** [comment]
@js87zz 
![image](https://user-images.githubusercontent.com/32512236/84467735-f6554f00-acb7-11ea-88fc-677a6655d7dc.png)

its checkbox disable logic code.
My problem is that if I select batch checkbox, and scroll grid,
disable checkbox The disable checkbox is checked.

**Comment by js87zz** [comment]
@worjs320 
Sorry for late replying.
The formatter should be used to only display the cell element. We don't recommend manipulating the row status in `formatter` option like as below. 
```js
tableView.disableRowCheck(row.row.rowKey);
tableView.setValue(row.row.rowKey, 'approval_process, ...);
```
This makes the side effect. I think it's better to get the `disabled` information with your grid data and set it. The example code is below.
```js
const gridData = [
  { id: 1, name: 'name', _attributes: { checkDisabled: true } },
  // ...
]
```

**Comment by worjs320** [comment]
@js87zz 
Thanks to you I solved this issue. Thank you always.
