### ISSUE TITLE
When scrolling is operated in Edit mode

### ISSUE THREAD

**Issue by HotRedMat** [nhn/tui.grid#1083]
**Describe the bug**
When scrolling is operated in Edit mode, the input foam floats in the air.

**To Reproduce**
1. Cell DBClick
2. Text enter.
3. Scroll down or up

**Expected behavior**
Scroll inside the area or exit input mode.

**Screenshots**
![20200609_174310_528](https://user-images.githubusercontent.com/41074464/84127199-e2bca500-aa79-11ea-95ed-3fb700336938.jpg)

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser [all]
 - Version [all]

**Smartphone (please complete the following information):**
 - Device: [all]
 - OS: [all]
 - Browser [all]
 - Version [all]

**Additional context**
If the focus shifts to other areas of the grid, we would like to change it to "blur" processing.

**Comment by js87zz** [comment]
@HotRedMat 
This bug has been fixed in this [PR](https://github.com/nhn/tui.grid/pull/853) and released. The example in our brand site uses the old version of grid, we should update the version in our brand site. Thank you!
