### ISSUE TITLE
listItems에서 한컬럼에서의 여러행의 데이터 바인딩

### ISSUE THREAD

**Issue by kimhyosung** [nhn/tui.grid#1084]
그리드에서 한 컬럼의 여러행들의
listitem의 내용을 각각 다르게 나타내고 싶습니다.
어떤방법이 있는지 알려주시면 감사하겠습니다.

**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@kimhyosung 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
And You should give us more detail information about your exact issue with screenshot or your source code
