### ISSUE TITLE
Custom renderer by @toast-ui/react-grid 4.13.0 and typescript

### ISSUE THREAD

**Issue by drate43** [nhn/tui.grid#1090]
I try to create a custom button column. 

my button code:
```js
class SampleButton {
    private el: HTMLDivElement;
    private click: Function | undefined;

    constructor(props: CellRendererProps) {
      const rootDom = document.createElement('div');     
      rootDom.style.overflow = 'hidden';
      this.el = rootDom;
      if (props.columnInfo.renderer.options) {
        this.click = props.columnInfo.renderer.options.handler;      
      }
      this.render(props);
    }

    getElement() {
      return this.el;
    }

    onClick() {
      if (this.click) {
        this.click('test');
      } 
    }

    render(props: CellRendererProps) {
      const element = (
        <button
          onClick={() => {
            this.onClick();
          }}
          className="btn_ontable_edit"
        >
          edit
        </button>
      );

      ReactDOM.render(element, this.el);
    }
  }
```
this columns code : 
```js
const columns = [
    {
      name: 'edit',
      header: '수정',
      width: 100,     
      renderer: {
        type: SampleButton,
        options: {
          handler: handleOnClickRowModify,        
        },
      },
    },
]
```
this tablecode:
```js
 const [columns, setColumns] = useState(columns);
 const [Rows, setRows] = useState<any[])([]);
 <DataGrid  data={Rows}   columns={columns } />
```
click event code : 
```js
const handleOnClickRowModify = (key: any) => {
  console.log(Rows)
   console.log(key);
}
```
I try to catch button click event...
but  my rows data is null in handler ('handleOnClickRowModify')

I cant find 'custom rendere' example by '@toast-ui/react-grid(ver 4.13.0).'
and use react hook.

How use to custom rendere by '@toast-ui/react-grid(ver 4.13.0).'?

**Comment by js87zz** [comment]
It's hard to give you exact guide because I couldn't see your full source code in jsfiddle or code sandbox. You can use the grid rows in custom renderer as below.
```js
class SampleButton {
  constructor(props) {
    const rootDom = document.createElement('div');
    rootDom.style.overflow = 'hidden';
    this.el = rootDom;
    this.grid = props.grid;
    if (props.columnInfo.renderer.options) {
      this.click = props.columnInfo.renderer.options.handler;
    }
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  onClick() {
    if (this.click) {
     // get current grid rows
     const rows = this.grid.getData();
      this.click('test', rows);
    }
  }

  render() {
    const element = (
      <button
        onClick={() => {
          this.onClick();
        }}
        className="btn_ontable_edit"
      >
        edit
      </button>
    );

    ReactDOM.render(element, this.el);
  }
}
```
 If you give your source code in code sandbox, I can answer your question exactly

**Comment by drate43** [comment]
hi, 
Sorry i am late. 
finally, I resolve this question! 
I use Ref and getInstance(). 
thanks you.

I have more question, 

TuiGrid have many Event, (I could check in type 'EventNameMapping'.)
but i cant see 'onChange Event'
(if grid cell value changed, send to changed value and cell info by 'onChange Event').
 
Do you have plan make 'OnChange Event'?

**Comment by js87zz** [comment]
@drate43 
Do you need the event which is triggered when cell value is changed?
I think [onBeforeChane, onAfterChange](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-event.md#%EC%98%B5%EC%85%98-%EC%84%A4%EC%A0%95%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%ED%95%B8%EB%93%A4%EB%9F%AC-%EB%93%B1%EB%A1%9D) will be helpful to you.
