### ISSUE TITLE
question about paste from clipboard

### ISSUE THREAD

**Issue by anpaul0615** [nhn/tui.grid#1093]
**Summary**

안녕하세요. 클립보드 paste 동작 관련 문의드립니다.

엑셀에서 특정 범위 데이터를 복사한다음, 그리드에 붙여넣으려고합니다.
현재는 그리드의 row 가 1개인 경우, 여러줄의 엑셀데이터를 copy&paste 하더라도 그리드에는 1줄만 복사가 되는것같습니다.

문서를 찾아봐도 위 현상과 관련된 설명을 찾을수가 없어서 여기에 질문드립니다.

어떻게하면 클립보드로부터 붙여넣기를 실행했을때 데이터가 그리드에 온전히 들어갈수있을까요?
의견부탁드리겠습니다.

**Version**

@toast-ui/react-grid v4.13.0

**Comment by js87zz** [comment]
@anpaul0615 
Please make sure you have filled out issue respecting our form in English.
The copied data is pasted the grid based on current length of the row. We will enhance this functionality as you commented. Thank you!
