### ISSUE TITLE
 Can I put an aggregate function in the middle of the grid?

### ISSUE THREAD

**Issue by kwangminini** [nhn/tui.grid#1100]
**Summary**

Can I use the summary as an aggregate function in the middle like the attached picture??

**Screenshots**
![image](https://user-images.githubusercontent.com/48472989/85243169-120ce200-b47c-11ea-8677-10c4af295852.png)

**Version**
https://uicdn.toast.com/grid/latest version

**Additional context**

**Comment by js87zz** [comment]
@kwangminini 
We don't provide the functionality you commented yet. we consider the feature internally. Thank you!
