### ISSUE TITLE
`editor` is not working with `renderer`

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1104]
**Editor is not working with Renderer**

1. Create a new header: 
```  JAVASCRIPT
{
      header: 'Genre',
      name: 'genre',
      renderer: {
        type: LinkRender,
      },
      formatter: 'listItemText',
      editor: {
        type: 'select',
        options: {
          listItems: [
            { text: 'Pop', value: '1' },
            { text: 'Rock', value: '2' },
            { text: 'R&B', value: '3' },
            { text: 'Electronic', value: '4' },
            { text: 'etc.', value: '5' }
          ]
        }
      },
    }
```
2. Try to edit the grid _(Genre)_ and `click` into another cell to save the `edit`
3. Check that the new value is not showing in the grid after editing
4. Than add the event `editingFinish`
```JAVASCRIPT
instance.on('editingFinish', (ev) => {
  instance.clear();
  instance.reloadData();
});
```
5. Edit the _(Genre)_ and check the console, you will get an error.
Full code is [here](https://codesandbox.io/s/tui-grid-example-git-ifrhc)

**Comment by js87zz** [comment]
@denaldhushi 
I checked your issue, the `renderer` and `column option` need to be fixed to work properly.

1. The renderer you create is wrapped by `span` tag, so the value should be set by `textContent`(not `value`)
2. The formatted value should be set in your renderer to displaying the `text` property.
3. The `text` and `value` of formatter option is not matched your column option. The cell value should be same as the `value` property of formatter(not `text` property)

```js
class LinkRender {
  constructor(props) {
    let el;

    el = document.createElement("span");
    el.innerHTML = String(props.value);
    this.el = el;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props) {
    // formattedValue should be set to textContent
    this.el.textContent = String(props.formattedValue);
  }
}

// ...
const columns = [{
  header: 'Genre',
  // genreCode has the value which is same as the `listItems` value property
  name: 'genreCode',
  renderer: LinkRender,
  formatter: 'listItemText',
  editor: {
    type: 'select',
    options: {
       listItems: [
         { text: 'Pop', value: '1' },
         { text: 'Rock', value: '2' },
         { text: 'R&B', value: '3' },
         { text: 'Electronic', value: '4' },
         { text: 'etc.', value: '5' }
       ]
    }
  }
}];


```

**Comment by denaldhushi** [comment]
Thank you!
