### ISSUE TITLE
Key press event feature

### ISSUE THREAD

**Issue by sayaya1090** [nhn/tui.grid#1106]
When press any character key on cell in view mode, I wanna grid start cell edit mode(fire startEditing).
Please consider to add custom event listener into column like 'keypress', 'click', 'dragstart', ...
Otherwise, should I use custom renderer and editor?
If I could get renderer and editor impl., I would inject event listener.

**Comment by js87zz** [comment]
@sayaya1090 
The editing is started when press the `enter` key. 
You need to trigger the editing through pressing another key? And we already provide the [click](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-event.md#available-events) event.
