### ISSUE TITLE
Latest tui-date-picker compatibility

### ISSUE THREAD

**Issue by lorefnon** [nhn/tui.grid#1110]
**Summary**

Latest tui.grid depends on 3.x version of tui-date-picker which has a jquery dependency. I was curious if there was any known incompability wrt. the latest tui-date-picker (which has removed this dependency) because of which this hasn't been updated yet ? 

We primarily wanted to not have the jquery dependency in our build.

**Comment by js87zz** [comment]
@lorefnon 
I agree with you totally. We need to update `tui-date-picker` version to `4.x` for preventing the `jquery` dependency to our user dependency graph. After updating the version, we will comment here. 
Thank you!

**Comment by lorefnon** [comment]
@js87zz Thanks for taking a look. 

Just FYI, we used yarn resolutions to force the 4.x version of tui-date-picker and most of the basic features seem to be working fine.

**Comment by lorefnon** [comment]
🙄

**Comment by js87zz** [comment]
@lorefnon 
The tui-pagination and tui-date-picker have been updated and jquery dependency has been removed in `v4.16.1`.
Thank you for waiting!
