### ISSUE TITLE
Is there an option to adjust the row width to the text length entered in the tui-grid?

### ISSUE THREAD

**Issue by shohye** [nhn/tui.grid#1115]
**Summary**
Is there an option to adjust the row width to the text length entered in the tui-grid?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
TUI-GRID 3 version

**Additional context**

**Comment by js87zz** [comment]
@shohye 
The width is not extended automatically. 
I think you can handle it through the `width` option.
```js
// grid option
columns: [
  {
    title: 'Name',
    name: 'name',
    // fix the width you want
    width: 300
  },
  // ...
],
// ...
```
Also, user can resize the column width as default.
![2020-07-03 12-21-46 2020-07-03 12_22_01](https://user-images.githubusercontent.com/37766175/86428486-d4d00c00-bd27-11ea-80af-9b6304ec3f3b.gif)
