### ISSUE TITLE
DataSource not binding

### ISSUE THREAD

**Issue by GwonMung** [nhn/tui.grid#1118]
**Summary**
No data is entered in the grid.
(dataSource,readData)

**Version**
toast-ui.react-grid
release 2.0.4
npm 4.14.0

**Additional context**
I am trying to enter sampledata into a grid by calling api with 1)"dataSource" but it doesn't work.
Checking the 2)Network in the developer window seems to fetch the data fine.
what's the problem?? There are no errors.

Is the data format wrong?

**Comment by js87zz** [comment]
@GwonMung 
I think that the problem may be response data format.
Refer below link.
* [ko](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md#readdata%EC%9D%98-%ED%94%84%EB%A1%9C%ED%86%A0%EC%BD%9C)
* [en](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/data-source.md#protocol-used-in-readdata)

**Comment by GwonMung** [comment]
![image](https://user-images.githubusercontent.com/50918079/87393325-f8793900-c5e8-11ea-9e08-6144689282b7.png)

Shouldn't the response data format look like this??

**Comment by GwonMung** [comment]
@js87zz 

Should I set the response data format on the server side?
