### ISSUE TITLE
tui-grid support sub table?

### ISSUE THREAD

**Issue by hasuikhs** [nhn/tui.grid#1119]
**Summary**
tui-grid support sub table? not tree.

**Screenshots**
![image](https://user-images.githubusercontent.com/50775570/87485968-08d6f580-c675-11ea-8b75-def305664a61.png)
like this.

**Version**
4.x

**Comment by js87zz** [comment]
@hasuikhs 
Sorry for late replying. 
We don't have the plan to support that functionality.
Thank you!
