### ISSUE TITLE
How to change color  number of pagination and Empty space in list?

### ISSUE THREAD

**Issue by jeong-w-93** [nhn/tui.grid#1120]
## How to change color  number of pagination and Empty space in list?

![질문_토스트_색](https://user-images.githubusercontent.com/37054073/87496907-7001a380-c68f-11ea-9faf-fb8c94cc82ab.PNG)

**Comment by js87zz** [comment]
@jeong-w-93 
Sorry for late replying.
Did you change the `tui-pagination` css for your theme?
