### ISSUE TITLE
The keymap is not operated after calling `focusAt` API

### ISSUE THREAD

**Issue by visualp** [nhn/tui.grid#1121]
grid.focusAt(0,100,true);  그리드를 생성후 포커스를 이동후 키포드로 이동을 하려면 
포커스가 고정되어 이동이 안됩니다.
혹시 포커스 이동우 키보드 이벤트가 다시 동작 되도록 하는 방법이 있을까요?

To move the focus after creating a grid and move to the keyford
Focus is fixed and cannot be moved.
Is there any way to make the keyboard event re-activate when the focus moves?

**Comment by js87zz** [comment]
@visualp 
When i tested it, the focused cell has been moved properly by pressing the arrow key.
Can you give us your code in code sandbox or jsfiddle?
