### ISSUE TITLE
 When the type is text or radio, can it be centered?

### ISSUE THREAD

**Issue by shohye** [nhn/tui.grid#1125]
**Summary**
A clear and concise description of what the question is.

1.When type is text, is it possible to center the text when typing?
2.Is the type radio, and can listItems be centered when selected?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.
TUI-GRID 3 version

**Additional context**

**Comment by js87zz** [comment]
@shohye 
Currently, we don't provide the option for it.
Thank you!
