### ISSUE TITLE
Row Header Number after turn to next page

### ISSUE THREAD

**Issue by Seokhwan-Lee** [nhn/tui.grid#1128]
**Summary**
How to set the page number at readData?
I want to add page number

Now
Page 2 > Page Number 1~5

Need
Page 2 > Page Number 6~10

**Screenshots**
![cap1](https://user-images.githubusercontent.com/56380697/88136042-6d6cf400-cc23-11ea-8ab9-ab5afb316bd5.png)
![cap2](https://user-images.githubusercontent.com/56380697/88136044-6e9e2100-cc23-11ea-960b-6e6be95f4831.png)

**Comment by js87zz** [comment]
@Seokhwan-Lee 
The `rowNum` is set based on the grid data.
In your case, the data is the piece of a specific page with communicating the server so that `rowNum` starts at 1.
I think that you can resolve the issue by defining your own renderer.
```js
class RowNumberRenderer {
  constructor(props) {
    const el = document.createElement('span');
    
    this.el = el;
    this.el.innerHTML = this.getRowNum(props);
  }

  getRowNum(props) {
    const currentPage = props.grid.getPagination()._currentPage;
    // You can change the number `5` as your perPage option.
    return Number(props.formattedValue) + (currentPage - 1) * 5;
  }

  getElement() {
    return this.el;
  }

  render(props) {
    this.el.innerHTML = this.getRowNum(props);
  }
}

const grid = new tui.Grid({
  // ...
  rowHeaders: [
    {
      type: 'rowNum',
      renderer: {
        type: RowNumberRenderer
      }
    },
  ],
  pageOptions: {
    perPage: 5
  },
  // ...
});

```

**Comment by Seokhwan-Lee** [comment]
Thank you for your Solution! :) close it!
