### ISSUE TITLE
 When request('createData') is called, the transmitted data string is different from the guide.

### ISSUE THREAD

**Issue by doolybom1** [nhn/tui.grid#1131]
**Summary**
Json string data of request() is output differently from the guide.

As shown in the screenshot below **createdRows[0]** is attached to each element. Is there any way to solve this?

**Screenshots**
Guide json string
```
updatedRows=[{"c1":"data1-1","c2":"data1-2,"rowKey":1},{"c1":"data2-1","c2":data2-2,"rowKey":2}]
```

Current json string
```
{createdRows[0][rowKey]=10, createdRows[0][USER_NUM]=32154, createdRows[0][USER_WORK_JO]=1, createdRows[0][USER_DP_NM]=test, createdRows[0][USER_JOIN_DT]=, createdRows[0][USER_NM]=cvcfd, createdRows[0][USER_PART1]=1, createdRows[0][USER_PART2]=01}
```

**Version**
4.14.0

**Comment by js87zz** [comment]
@doolybom1 
It's hard to resolve your issue curretly.
Can you give more information(Your configuration code and request payload, response data)?

**Comment by doolybom1** [comment]
@js87zz 
It may be possible to close the issue by resolving this issue.
thanks.
