### ISSUE TITLE
In column, toast grid disabled checkbox is not working.

### ISSUE THREAD

**Issue by parkjunho0708** [nhn/tui.grid#1134]
<img width="400" alt="1111111" src="https://user-images.githubusercontent.com/19677175/88445583-94fbd080-ce5e-11ea-81f5-f5c467ab8d8e.PNG">
<img width="400" alt="캡처123123" src="https://user-images.githubusercontent.com/19677175/88445702-587ca480-ce5f-11ea-951b-bc38e9fd9c90.PNG">

Hello, I just got a problems in toast grid in column's checkbox.

I just made toast grid that checkbox disabled in columns as you could see first image.

But, when I clicked that columns, multiple times it suddenly became not disabled states as you could see second image.

Actually, I didn't use the toast ui grid api instance methods such as disableRow(), disableRowCheck() to make the disabled column's checkbox.

I just used the JQuery to disable the column's checkbox.

Furthermore, I saw the example that disabled checkbox in rowHeaders.
But, I just could not find the example that disable checkbox in columns.

Please, write a comment. If anyone knows to solve this problem.
Thank you.

**Comment by js87zz** [comment]
@parkjunho0708 
Sorry for late replying.
The `disableRowCheck` should be used to change the checkbox of `rowHeaders`.
I think that this problem may be solved in custom renderer but I'm not sure. 
To know the exact the issue and solution, Can you give us your source code in code sandbox or jsfiddle?
