### ISSUE TITLE
Grid FileUpload Question

### ISSUE THREAD

**Issue by jininsik** [nhn/tui.grid#1135]
**Summary**
I'd like to upload a file to the grid as shown in the picture, do you have any samples?

**Screenshots**
![image](https://user-images.githubusercontent.com/68724678/88493692-724bf200-cfed-11ea-8012-b511639b0537.png)

**Version**
4.0

**Comment by js87zz** [comment]
@jininsik 
We don't have any sample for that case. 
You can implement using the [Custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md).
If you have a trouble shooting, Please give more information(your source code in **code sandbox** or **jsfiddle**)
