### ISSUE TITLE
 When using formatter, existing value is not visible.

### ISSUE THREAD

**Issue by doolybom1** [nhn/tui.grid#1136]
**Summary**
If the formatter 'listItemText' is used, the existing value is not visible.
I needed to show the values ​​in listitems as text instead of value, so I used the formatter option.
However, the following phenomenon occurs and asks a question.

Please check the contents below. And Please advise if I am using the formatter incorrectly.

**Screenshots**
**'부서'** contains the current value.
![depart](https://user-images.githubusercontent.com/59081012/88612339-f5407b80-d0c5-11ea-8277-fa0e87f222f9.PNG)

```
header: '부서',
name: 'USER_DP_NM',
align: 'center',
onBeforeChange(ev) {
	console.log('DEPARTMENT BEFORE CHANGE: ' + ev.value);
},
onAfterChange(ev) {
	console.log('DEPARTMENT AFTER CHANGE: ' + ev.value);
},
formatter: 'listItemText',              <- If I add this part, the data is not shown as below.
editor: {
	type: 'select',
	options: {
		listItems: departV
	}
}
```
![depart_dissapear](https://user-images.githubusercontent.com/59081012/88612660-ae06ba80-d0c6-11ea-9328-b64f7898652c.PNG)

**Version**
4.14.0

**Comment by js87zz** [comment]
@doolybom1 
The **value** property of `listItems` option should be equal to grid data as below.  Try to check it.
```js
const gridData = ['1', '2', '1', '3', ...];
// ...
data: gridData,
columns: [
  {
    header: 'Genre',
    name: 'genreCode',
    formatter: 'listItemText',
    editor: {
      type: 'select',
      options: {
        listItems: [
          { text: 'Pop', value: '1' },
          { text: 'Rock', value: '2' },
          { text: 'R&B', value: '3' },
        ],
      },
    },
  },
  // ...
],
// ...
```

**Comment by Nitrodist** [comment]
Hello, I would prefer if the values did not *have* to be strings. See #1342
