### ISSUE TITLE
How to request to deleteData server?

### ISSUE THREAD

**Issue by doolybom1** [nhn/tui.grid#1138]
**Summary**
I want to know how to request to deleteData server.

Currently updateData and readData are fine. By the way, I am not sure how to do deleteData. 
I want to show an example of requesting deleteData to the server.
The scenario I want is to delete the data by requesting only the data in the row where the checkbox is selected.

**Screenshots**
![mygrid](https://user-images.githubusercontent.com/59081012/88757706-9ea86f80-d1a1-11ea-800f-1358536da3b5.PNG)

**Version**
4.14.0

**Comment by js87zz** [comment]
Can you try as below?
```js
grid.removeCheckedRows();
grid.request('deleteData');
```

**Comment by doolybom1** [comment]
@js87zz 
Thanks to you, I solved it. Thank you.
