### ISSUE TITLE
When deleting the last row, removeRow is not applied immediately.

### ISSUE THREAD

**Issue by gwonsuji** [nhn/tui.grid#1142]
**Describe the bug**
When you execute the removeRow() function, the row does not disappear immediately, but only when you hover the mouse over the table.

**To Reproduce**
1. Create a basic grid.
2. Use button tag to delete row and add row button.
3. Create a function.
4. Click the button to add a row.
5. Click the button to delete the row. (Do not put the mouse on the table.)
6. The deleted row remains, and the row disappears only when you hover the mouse over the table.

**Expected behavior**
When you click the delete row button, the row disappears from the grid immediately.

**Screenshots**
grid
![image](https://user-images.githubusercontent.com/60372704/89867991-ffe23100-dbec-11ea-8ac7-d366798c3f94.png)

function code
![image](https://user-images.githubusercontent.com/60372704/89867833-beea1c80-dbec-11ea-8318-4e784b35c4b0.png)

button
![image](https://user-images.githubusercontent.com/60372704/89867876-cf9a9280-dbec-11ea-8280-1b57256c5cce.png)

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser chrome
 - Version 84.0.4147.105

**Additional context**

When deleting the last row using the removeRow() function, the row remains unless the mouse hovers over the table. The next execution of the refreshLayout() function is useless.
Is there any way to make the row appear to be deleted as soon as I delete it with the removeRow() function? Or is there another way?

**Comment by js87zz** [comment]
@gwonsuji 
What is your grid version?
When i tested, the operation has been well performed.

![2020-08-14 11-13-58 2020-08-14 11_14_13](https://user-images.githubusercontent.com/37766175/90206698-51720200-de1f-11ea-93a8-d1379f2fa48d.gif)

**Comment by gwonsuji** [comment]
I use CDN service


<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>



This is my script code
`<script>
	var grid1;
	var grid2;
	$(document).ready(function($){
		grid1 = new tui.Grid({
		      el: document.getElementById('grid1'),
		      //data: gridData,
		      scrollX: false,
		      scrollY: false,
		      columns: [
		          {
		            header: '자격증',
		            name: 'gubun',
		            editor: 'text'
		          },
		          {
		            header: '시험과목',
		            name: 'contents',
		            editor: 'text'
		          },
		          {
		            header: '관련된 학과 교과목',
		            name: '0001',
		            editor: 'text'
		          },
		          {
		            header: '현 담당교수',
		            name: '0002',
		            editor: 'text'
		          }
		        ]
		      });
		  grid2 = new tui.Grid({
		      el: document.getElementById('grid2'),
		      //data: gridData,
		      scrollX: false,
		      scrollY: false,
		        columns: [
		          {
		            header: '자격증',
		            name: 'gubun',
		            editor: 'text'
		          },
		          {
		            header: '시험과목',
		            name: 'contents',
		            editor: 'text'
		          },
		          {
		            header: '관련된 학과 교과목',
		            name: '0001',
		            editor: 'text'
		          },
		          {
		            header: '현 담당교수',
		            name: '0002',
		            editor: 'text'
		          }
		        ]
		      });
	});
	
	//행추가
	function append1(){
		grid1.appendRow();
	}
	//행삭제
	function minus1(){
		grid1.removeRow(grid1.getRowCount()-1);
		grid1.refreshLayout();
	}
	//행추가
	function append2(){
		grid2.appendRow();
	}
	//행삭제
	function minus2(){
		grid2.removeRow(grid2.getRowCount()-1);
		grid2.refreshLayout();
	}
	</script>`


And this is my HTML code
`<div class="mt-3">
	        	<h4>2-1. 교육과정 이수를 통해 취득할 수 있는 국가자격 현황(특강 등 비정규 프로그램 지원 제외)</h4>
	        	<div style="float: right;">
	          		<button class="btn btn-primary" onclick="append1();">행추가</button>
	          		<button class="btn btn-primary" onclick="minus1();">행삭제</button>
	        	</div>
	        	<div id="grid1"></div>
	      	</div>
	      	<br>
	      	<div class="mt-3">
	        	<h4>2-2. 교육과정 이수를 통해 취득할 수 있는 공인민간자격 현황(특강 등 비정규 프로그램 지원 제외)</h4>
	        	<div style="float: right;">
	          		<button class="btn btn-primary" onclick="append2();">행추가</button>
	          		<button class="btn btn-primary" onclick="minus2();">행삭제</button>
	        	</div>
	        	<div id="grid2"></div>
	      	</div>`

**Comment by gwonsuji** [comment]
I use CDN service


<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>


1. this is my script code
`<script>
	var grid1;
	var grid2;
	$(document).ready(function($){
		grid1 = new tui.Grid({
		      el: document.getElementById('grid1'),
		      //data: gridData,
		      scrollX: false,
		      scrollY: false,
		      columns: [
		          {
		            header: '자격증',
		            name: 'gubun',
		            editor: 'text'
		          },
		          {
		            header: '시험과목',
		            name: 'contents',
		            editor: 'text'
		          },
		          {
		            header: '관련된 학과 교과목',
		            name: '0001',
		            editor: 'text'
		          },
		          {
		            header: '현 담당교수',
		            name: '0002',
		            editor: 'text'
		          }
		        ]
		      });
		  grid2 = new tui.Grid({
		      el: document.getElementById('grid2'),
		      //data: gridData,
		      scrollX: false,
		      scrollY: false,
		        columns: [
		          {
		            header: '자격증',
		            name: 'gubun',
		            editor: 'text'
		          },
		          {
		            header: '시험과목',
		            name: 'contents',
		            editor: 'text'
		          },
		          {
		            header: '관련된 학과 교과목',
		            name: '0001',
		            editor: 'text'
		          },
		          {
		            header: '현 담당교수',
		            name: '0002',
		            editor: 'text'
		          }
		        ]
		      });
	});
	
	//행추가
	function append1(){
		grid1.appendRow();
	}
	//행삭제
	function minus1(){
		grid1.removeRow(grid1.getRowCount()-1);
		grid1.refreshLayout();
	}
	//행추가
	function append2(){
		grid2.appendRow();
	}
	//행삭제
	function minus2(){
		grid2.removeRow(grid2.getRowCount()-1);
		grid2.refreshLayout();
	}
	</script>
`



2.This is my HTML code
`<div class="mt-3">
	        	<h4>2-1. 교육과정 이수를 통해 취득할 수 있는 국가자격 현황(특강 등 비정규 프로그램 지원 제외)</h4>
	        	<div style="float: right;">
	          		<button class="btn btn-primary" onclick="append1();">행추가</button>
	          		<button class="btn btn-primary" onclick="minus1();">행삭제</button>
	        	</div>
	        	<div id="grid1"></div>
	      	</div>
	      	<br>
	      	<div class="mt-3">
	        	<h4>2-2. 교육과정 이수를 통해 취득할 수 있는 공인민간자격 현황(특강 등 비정규 프로그램 지원 제외)</h4>
	        	<div style="float: right;">
	          		<button class="btn btn-primary" onclick="append2();">행추가</button>
	          		<button class="btn btn-primary" onclick="minus2();">행삭제</button>
	        	</div>
	        	<div id="grid2"></div>
	      	</div>`

**Comment by gwonsuji** [comment]
I'll add the details in detail.
I am using the CDN service.

And when you delete the first row, it is applied immediately, but when you delete the second row, it is not applied immediately.
Attach the gif file below.

![removeBug](https://user-images.githubusercontent.com/60372704/90222755-afb2db00-de47-11ea-9d1b-30c11a2b1cb0.gif)

**Comment by js87zz** [comment]
@gwonsuji 
This issue is resolved in `v4.15.0`(#1148).
Thank you!
