### ISSUE TITLE
Bug report grid in selectbox

### ISSUE THREAD

**Issue by karismaup** [nhn/tui.grid#1146]
![bug](https://user-images.githubusercontent.com/69657454/90200172-d3f3c500-de11-11ea-85d1-54bdcacf4897.png)

1. selectbox doubleclick (modify mode)

2. grid in scroll-y  click  down 

bug occurred  ( selectbox - Float in the air )

and.....

================================ 
I would like to add features like this one. ( i wish )
1. excel export.............

**Comment by js87zz** [comment]
@karismaup 
The demo version of our brand site is old version..
It should be updated...😐
This bug is resolved in latest version.

Excel export is in our plan but the exact schedule is not decided.
Thank you for your contributing!

**Comment by js87zz** [comment]
@karismaup 
This issue has been resolved. Thanks! :)
https://ui.toast.com/tui-grid
