### ISSUE TITLE
grid 동적 컬럼 생성 질문

### ISSUE THREAD

**Issue by JiYeon888** [nhn/tui.grid#1147]
그리드 생성시 그리드의 컬럼들을 리스트로 받아서 뿌려줄수 있나요?
가로로 항목이 늘어날수 있는 상황입니다.
그리드를 뿌릴때 항목으로 뿌릴 컬럼을 디비 조회해서 세팅후에 
그리드 항목으로 세팅할수 있는지 궁금합니다.
예를들어 
columns: [{
					header: '순서',
					name: 'regDate',
				},
				{
					header: '성명',
					name: 'lCodeNm',
				},
                                 .
                                 .
                                 .
이런식으로 구성되는 컬럼항목을 리스트로 받아서 출력하고 싶습니다.
만약에 구현되는 부분이라면 혹시 부분 리스트? 도 가능할까요?

순서 |  성명    |  취미1  |  취미2   |  취미3   |  취미4  | 
1      |  홍길동 |   요리   |   독서    |   요리    |   독서   | 

이런식으로 취미부분만 리스트로 뿌리는것도 되는지 궁금합니다.
(취미1~취미4는 디비에서 가져오는 값) 
취미 갯수가 유동적입니다... 그래서 취미갯수를 디비에서 리스트로 조회해와서 컬럼으로 뿌리고 싶은데....
제가 설명을 잘 못해서 전달이 잘 되었는지 걱정이네요...

**Comment by js87zz** [comment]
@JiYeon888 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@JiYeon888 
The [setColumns](https://nhn.github.io/tui.grid/latest/Grid#setColumns) API will be helpful to you.
