### ISSUE TITLE
How to customize the render of tree resource ?

### ISSUE THREAD

**Issue by smallt93** [nhn/tui.grid#1151]
**Summary**
I want to display avatar in tree, how can I do it? 

**Screenshots**
![image](https://user-images.githubusercontent.com/32450456/90740373-1b3df200-e2f9-11ea-9d12-67ec8e369dae.png)

**Version**
4x

**Comment by js87zz** [comment]
@smallt93 
Can you try it through [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-renderer.md)?
