### ISSUE TITLE
Change the color representation of the selection layer

### ISSUE THREAD

**Issue by SDuck4** [nhn/tui.grid#1152]
## Version
4.14.0

## Development Environment
Chrome, Windows 10

## Current Behavior

Selected cells are represented by **selection layer**. And **selection layer** has `opacity: 0.1` style.
So when you want set style of selected cells, you must consider `opacity: 0.1`.

For example, If you want set background to `#E5F1F8`, you must set `#0073B9`.

Because of `opacity: 0.1`, you have to calculate the color to be applied in reverse.
It is not intuitive and limits the range of colors.

## Expected Behavior

Use **selection layer** to represent `border`.
And Make `background` style for each selected cells.

**Comment by js87zz** [comment]
@SDuck4 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by SDuck4** [comment]
@js87zz 이슈 템플릿에 한글로 적어도 된다고 나와있는데, 영문으로 바꿔야하나요?
```
<!--
Thank you for your contribution.

When it comes to write an issue, please, use the template below.
To use the template is mandatory for submit new issue and we won't reply the issue that without the template.

And you can write template's contents in Korean also.
-->
```

**Comment by js87zz** [comment]
@SDuck4 
타 사용자들을 위해 영문으로 이슈 작성하는 것을 내부 정책으로 운영하고 있습니다. 
번거러우시더라도 변경해주시면 감사하겠습니다!

The issue is wrote in English as an internal policy for other users.
Thank you for if you could change it!

**Comment by SDuck4** [comment]
@js87zz
I change it to English. :)

**Comment by js87zz** [comment]
@SDuck4 
To use the background color of each cell for the selection layer, current structure should be totally changed.
It may be painful, but it seems necessary to consider the problem you said.
We will discuss about it later internally. But it probably won't be solved in a short time.
Thank you!
