### ISSUE TITLE
Word break option

### ISSUE THREAD

**Issue by pvictor** [nhn/tui.grid#1153]
Thanks for this great library, very cool to use!

## Version
4.15.0

## Development Environment
Windows 10, Chrome 84.0.4147.125

## Current Behavior
When the content of a cell is too long, the words can be cut in half despite the option `whiteSpace` because there's a `word-break: break-all;` in CSS.

This behaviour can be seen in the example : https://nhn.github.io/tui.grid/latest/tutorial-example12-whitespace for whiteSpace = normal, pre-wrap, pre-line (depending on grid's width)

## Expected Behavior
Would it be possible to define word-break option the same way as whiteSpace?

Thanks

**Comment by js87zz** [comment]
@pvictor 
Sorry for late replying.
You can  implement with our [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-editor.md) without any option.
But I think defining custom renderer for just styling is inconvenient. We consider the option to apply the style you want to our built-in editor. Thank you for your contributing!

**Comment by js87zz** [comment]
@pvictor 
We added the `styles`, `classNames`, `attributes` options for default renderer in `v4.16.1`. You can apply the style more convenient than custom renderer.
```js
const columns = [
  {
    name: 'name',
    renderer: {
      styles: {
        wordBreak: 'break-all',
      },
      attributes: {
        myCustom: 'my-custom',
        title: (props: CellRendererProps) => `my ${props.value}`,
      },
      classNames: ['my-class'],
    },
  },
];
const grid = new Grid({
  columns, 
  // ...
})
```

**Comment by pvictor** [comment]
Wow this is great, can't wait to try it.
Thank you very much!
