### ISSUE TITLE
disableCell and selectbox z-index

### ISSUE THREAD

**Issue by eungee0907** [nhn/tui.grid#1156]
## Version
4.13.0

## Development Environment
win10, chrome 84.0.4147.135

hello. i have two questions.

1. Can't I disable only certain cells like disableColumn function or disableRow function? 

2. The select box does not come to the top as shown.  z-index of the div on the select box is set, but it is not solved. Is there anything else to consider? When I set the position of the tui-select-box to fixed, it comes to the top, but scrolling down is a mess, so I don't think it's the right solution... The same thing happens to date pickers.

![image](https://user-images.githubusercontent.com/33338284/92111816-da30fc00-ee27-11ea-858d-436da0addd2b.png)

**Comment by js87zz** [comment]
@eungee0907 
1. Can't I disable only certain cells like disableColumn function or disableRow function?
=> We don't provide API to change `disabled` state of certain cell yet. Currently, only row or column can be disabled using `disableRow`, `disableColumn` API.
2. Can you upload the your code in code sandbox or jsfiddle?
