### ISSUE TITLE
그리드의 숫자와 시간기능

### ISSUE THREAD

**Issue by jeongSula** [nhn/tui.grid#1158]
안녕하세요. 

저는 토스트 그리드를 쓰고있는 유저입니다.
너무나도 좋은 툴을 발견한거 같아 기쁘게 사용하고 있습니다.
사용중에 숫자 또는 시간 타입만 입력해야하는 셀에 대한 설정을 찾지 못하여 문의 드립니다.
숫자와 시간을 입력하는 설정이 있는지 궁금합니다.

혹시 없다면 editorMap 에서 숫자와 시간타입이 추가가능한지 궁금합니다. 

 exports.editorMap = {
                    text: [text_1.TextEditor, { type: 'text' }],
                    **number: [text_1.TextEditor, { type: 'number' }],
                    time: [text_1.TextEditor, { type: 'time' }],**
                    password: [text_1.TextEditor, { type: 'password' }],
                    checkbox: [checkbox_1.CheckboxEditor, { type: 'checkbox' }],
                    radio: [checkbox_1.CheckboxEditor, { type: 'radio' }],
                    select: [select_1.SelectEditor],
                    datePicker: [datePicker_1.DatePickerEditor]
                };

수고하십시오! 
감사합니다.

**Comment by js87zz** [comment]
@jeongSula 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

We don't support the `number`, `time` built-in editor. So you implements it through the custom editor.
This [tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-editor.md) and [API](https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor) will be helpful to you.
