### ISSUE TITLE
rowspan 기능에 대해 물어볼게있습니다!

### ISSUE THREAD

**Issue by yui2070** [nhn/tui.grid#1160]
안녕하세요.

제가 ajax를 통해서 데이터를 가져온 다음에 그리드에 데이터를 넣어주는 방식으로 현재 사용중입니다.
grid.resetData(데이터);

가져온 값은
![image](https://user-images.githubusercontent.com/33174711/92353397-2f685880-f11b-11ea-8d8f-3eab9e047312.png)
이런식으로 보여집니다.

그리고 제가 물어보고싶은건 저 상태에서
![image](https://user-images.githubusercontent.com/33174711/92353435-48710980-f11b-11ea-830c-2792b18beee2.png)
이 상태로 변경할 수 있는지!
그리고 가능하다면 샘플코드도 부탁드립니다..

감사합니다~

**Comment by js87zz** [comment]
@yui2070 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

Look at this [tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/row-span.md) and [example](https://nhn.github.io/tui.grid/latest/tutorial-example06-attributes).
