### ISSUE TITLE
컬럼 width 최소사이즈 관련 문의드립니다.

### ISSUE THREAD

**Issue by newera65** [nhn/tui.grid#1161]
안녕하세요 저는 toast그리드를 너무잘사용하고있는 개발자입니다.

다음과같이 컬럼설정을 했는데요~
	    columns: [
					      {header: '팀', name: 'team_nm', align:'center', width:70},
					      {header: '1', name: 'inning1', align:'center', width:30},
					      {header: '2', name: 'inning2', align:'center', width:10},
					      {header: '3', name: 'inning3', align:'center', width:10},
					      {header: '4', name: 'inning4', align:'center', width:10},
					      {header: '5', name: 'inning5', align:'center', width:10},
					      {header: '6', name: 'inning6', align:'center', width:10},
					      {header: '7', name: 'inning7', align:'center', width:10},
					      {header: '8', name: 'inning8', align:'center', width:10},
					      {header: '9', name: 'inning9', align:'center', width:10},
],
아래처럼 width를 주었는데 width가 30인거나 10인거나 동일하더라구요 이게 뭔가 40밑으로는 다 동일한 사이즈를 갖는거같은데.. 혹시 뭔가 제가 잘못한것인지 아니면 원래 설정이 width가 40밑으로는 불가한건지
도움을 받을수있을까요?!

**Comment by js87zz** [comment]
@newera65 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

If you want to set the width under the `40px`, you can solve the issue using `minWidth` option.
```js
const columns = [
  {
    header: 'name',
    name: 'name',
    width: 10,
    minWidth: 10
  },
  // ...
]
```
