### ISSUE TITLE
tui vue Grid 질문입니다.. resetData를 했는데 그리드 표현이 이상합니다...

### ISSUE THREAD

**Issue by ehgml164** [nhn/tui.grid#1162]
![111](https://user-images.githubusercontent.com/71052116/92674321-fff25f80-f357-11ea-9143-32f15f852b85.PNG)

위와 같이 tuiGrid.vue 컴포넌트를 만들었습니다.
그리고 이 컴포넌트를 import해서 각 화면에서 사용하는데

![image](https://user-images.githubusercontent.com/71052116/92674454-4b0c7280-f358-11ea-830e-aa6d66acb8bc.png)

위와같이 사용합니다.
그런데 data를 변경시켜서 컴포넌트의 watch  부분에서 resetdata를 했는대도

![image](https://user-images.githubusercontent.com/71052116/92674509-742d0300-f358-11ea-8724-6d176b689846.png)

위위와 같이 한쪽으로 컬럼이 쏠리고 데이터 표시가 안됩니다ㅠㅠ
왜이럴까요....아무리 찾아보고 수정해봐도 답을 모르겠습니다.....답부탁드려요!!

**Comment by js87zz** [comment]
@ehgml164 
Thank you for raising an issue.
We will try and get back to you as soon as possible.

Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@ehgml164 
Please give your detail source code like your option property and the data for resetData API.
I think the column width config may be problem, but it's not exact thing, so give more information to solve the issue.
And change the title and contents **in English**
