### ISSUE TITLE
An error that occurs when drawing a spline chart with null include data.

### ISSUE THREAD

**Issue by feents** [nhn/tui.grid#1165]
**Describe the bug**
An error that occurs when drawing a spline chart with null include data.

**To Reproduce**
1. Draw line chart with series data has null value.
ex) data: [3.28, 3.32, null, 2.90, 3.56, null]
2. Chart options set "spline: true"
3. Error: "Uncaught TypeError: Cannot read property 'left' of undefined"

**Expected behavior**
I expected chart with empty middle.

**Screenshots**
1. Remove "spline: true" => correct.
![test usage](https://user-images.githubusercontent.com/67404954/92694470-101f3480-f382-11ea-8f8c-f2d9445459b2.png)

2. Contain "spline: true" => Error.
![tui_test2](https://user-images.githubusercontent.com/67404954/92694705-65f3dc80-f382-11ea-967b-d5636e91d903.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser: Microsoft Edge, Google Chrome
 - Version: Chromium 85.0.4183.83

**Smartphone (please complete the following information):**
I don't test.

**Additional context**
none

**Comment by js87zz** [comment]
@feents 
This repository is grid repo.
chart repository is [here](https://github.com/nhn/tui.chart/issues)
