### ISSUE TITLE
I don't see any data in tui-grid.

### ISSUE THREAD

**Issue by ehgml164** [nhn/tui.grid#1167]
![image](https://user-images.githubusercontent.com/71052116/92844429-ccc7d300-f420-11ea-932c-14562ed3c99f.png)
Express the grid as above.

![image](https://user-images.githubusercontent.com/71052116/92844525-ea953800-f420-11ea-9ab3-705da6cadbf0.png)
I put the data fixed like this.

But I can't see the data. 
It is the same when applying the resetdata and refreshlayout properties.

If you fix other parts of the source, you can see the data while refreshing.
![image](https://user-images.githubusercontent.com/71052116/92846455-11ed0480-f423-11ea-8a3c-dab6b81517be.png)

Is that because two tui-grids have to be displayed simultaneously in one view (screen)...
Please respond.

**Comment by js87zz** [comment]
@ehgml164 
Give more detail information like your full source code or example on jsfiddle or code sandbox.

**Comment by ehgml164** [comment]
When doing resetData, when the height of the grid dom is 0, resetdata is not available. What should I do....

**Comment by js87zz** [comment]
Try to set `minBodyHeight` or `bodyHeight` option.
