### ISSUE TITLE
 IE browser renderer support?

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#1168]
**Summary**

I want to create a button through a custom renderer

But in IE browser (class CustomSliderRenderer {}) An error occurs in the class part

Chrome and Edge browsers work normally

Doesn't custom renderer support IE browser?

If IE browser is supported, how do you solve the error phenomenon in the class part?

**Version**
tui-grid-4.15.0

**Comment by js87zz** [comment]
@gurgus0189 
IE Browser doesn't support the `class` syntax.
You can implement custom render using [javascript prototype](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Inheritance_and_the_prototype_chain).
```js
// es6
class Renderer {
  constructor() {
    // ...
  }
  
  getElement() {
    // ...
  }
}

// es5
function Renderer() {
  // ...
}
Renderer.prototype.getElement = function() {
  // ...
}
```

**Comment by gurgus0189** [comment]
I applied it in the way I told you

And I could see the concept of es5 and es6. Thanks for the answer.
