### ISSUE TITLE
How to make certain cells uneditable

### ISSUE THREAD

**Issue by handslm** [nhn/tui.grid#1169]
I want to make certain cells uneditable
If a cell has data, I want to make it uneditable.
How I make it?

**Comment by js87zz** [comment]
We don't support `disable` functionality for cell unit.
However, I think you can implement it using `editingStart` custom event.
```js
grid.on('editingStart', (ev) => {
  // check the value 
  if (ev.value) {
    ev.stop();
  }
});
```

**Comment by handslm** [comment]
It works normally and well. very very thank you!
