### ISSUE TITLE
why grid paging type two case client and datasource

### ISSUE THREAD

**Issue by an-sangkil** [nhn/tui.grid#1172]
**Summary**
hi ~
i' am question 

one, why paging type is two case?
client type, datasource type ,
when then use type?

two, datasource type is custom response data

use datasource method , 
I want to receive response data according to the standard being used in the server and change it to the response standard provided by toast. Is it possible that way?

thanks!

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
"@toast-ui/vue-grid": "^4.15.0",

**Additional context**

**Comment by js87zz** [comment]
@an-sangkil 
Sorry for late replying.
1. client pagination
The client pagination is to apply pagination without communicating with the server.
If you don't have a lot of data, you can use this feature to show it in pages.
2. data source
Data source can help to set the data is responded by the server. However, the response data structure should be match with the specific structure. Otherwise, the grid cannot handle all the case of data.

You don't have to use data source to communicate with the server. 
If you want to use the data format provided the server, it's better to use [resetData](https://nhn.github.io/tui.grid/latest/Grid#resetData) API.

```js
// ajax
axios.get(...).then(data => {
  const gridData = ...
  const pageState = { page: 2, totalCount: 20, perPage: 5 };
  grid.resetData(gridData, pageState)
});
```

**Comment by an-sangkil** [comment]
@js87zz   thank you for answer
but i am using vue.js  
reset method is does not work

`
this.$http.get(`${this.$store.state.HOST}/observation.diary/list`)
        .then(({data}) => {
          let contents = data.detail.contents.contents
          let observeData = []
          for (let x of contents) {
            observeData.push({'name': x.entityManagementNumber})
          }

          let option ={pageState:{
              page: 1
              , totalCount: 10
              , perPage: 1
            }}

          this.$refs.tuiGrid.invoke('resetData', observeData, option);
        })

`

why not   do not working method

**Comment by an-sangkil** [comment]
`
this.$http.get('${this.$store.state.HOST}/observation.diary/list')
        .then(({data}) => {
          let contents = data.detail.contents.contents
          let observeData = []
          for (let x of contents) {
            observeData.push({'name': x.entityManagementNumber})
          }
          let option ={pageState:{
              page: 1
              , totalCount: 10
              , perPage: 1
            }}
          this.$refs.tuiGrid.invoke('resetData', observeData, option);
        })
`

**Comment by an-sangkil** [comment]
` this.$http.get(`${this.$store.state.HOST}/observation.diary/list`)
        .then(({data}) => {
          let contents = data.detail.contents.contents
          let observeData = []
          for (let x of contents) {
            observeData.push({'name': x.entityManagementNumber})
          }

          let option ={pageState:{
              page: 1
              , totalCount: 10
              , perPage: 1
            }}

          this.$refs.tuiGrid.invoke('resetData', observeData, option);
        })`

**Comment by js87zz** [comment]
@an-sangkil 
Can you upload your code in code sandbox or jsfiddle?
