### ISSUE TITLE
How do I recall the contents of the clipboard in the custom cell renderer?

### ISSUE THREAD

**Issue by Kang-Programming** [nhn/tui.grid#1176]
**Summary**
I want to apply the contents from the clipboard to custom cells.
Normal cells are applied, but not custom cells.
Is there anything I need to add to a separate listener event or grid option?
The source code is as follows:

        var TextInputRenderer = function (props) {
            var el = document.createElement('input');
            el.type = 'text';

            el.style.width = 'calc(100% - 10px)';
            el.style.padding = '6px 7px';
            el.style.border = 'solid 1px #ddd';
            el.style.margin = 'auto 5px';
            
            this.el = el;
            this.render(props);
        }

        TextInputRenderer.prototype.getElement = function () {
            return this.el;
        }

        TextInputRenderer.prototype.render = function (props) {
            this.el.value = props.value;
        }
        var CustomCheckBox = function (props) {
            var el = document.createElement('input');
            const { grid, rowKey, columnInfo } = props;
            el.type = 'checkbox';
            el.checked = grid.getValue(rowKey, columnInfo.name);
            el.addEventListener('click', () => {
                grid.setValue(rowKey, columnInfo.name, el.checked);
            });
            el.style.width = 'calc(100% - 10px)';
            this.el = el;
            this.render(props);
        }

        CustomCheckBox.prototype.getElement = function () {
            return this.el;
        }
        CustomCheckBox.prototype.getValue = function () {
            return this.el.value;
        }
        CustomCheckBox.prototype.render = function (props) {
            this.el.value = props.value;
        }
        ruleGrid2 = new tui.Grid({
            el: document.getElementById('ruleGrid2'),
            rowHeaders: ['checkbox'],
            columns: [
                { header: 'ID', name: 'ID', dataType: 'number', hidden: true }
                , { header: "ParseRuleID", name: "ParseRuleID", dataType: "number", hidden: true }
                , { header: "Name", name: "Name", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer }, width: '100' }
                , { header: "Code", name: "Code", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer }, width: '90' }
                , {
                    header: "Methods", name: "ParseMethods", formatter: 'listItemText', editor: {
                        type: 'select', options: {
                            listItems: [ { text: 'Token_Delimiter_Order', value: '0' }, { text: 'Token_Line_Position', value: '1' }, { text: 'Line_Token_Position', value: '2' }]
                        }
                    }, width: '130', copyOptions: { useListItemText: false }
                }
                , {
                    header: "Data Type", name: "DataType", formatter: 'listItemText', editor: {
                        type: 'select', options: {
                            listItems: [{ text: 'Text', value: '0' }, { text: 'Number', value: '1' }, { text: 'Date Time', value: '2' }]
                        }
                    }, width: '60', copyOptions: { useListItemText: false }
                }
                , { header: "Format", name: "Format", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer }, width: '50' }
                , { header: "Length", name: "Length", dataType: "number", editor: 'text', renderer: { type: TextInputRenderer }, width: '50' }
                , { header: "Order Line", name: "Order_Line", dataType: "number", editor: 'text', renderer: { type: TextInputRenderer },width: '60' }
                , { header: "Position", name: "Position", dataType: "number", editor: 'text', renderer: { type: TextInputRenderer },width: '50' }
                , { header: "Token", name: "Token", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer },width: '70' }
                , { header: "Delimiter", name: "Delimiter", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer },width: '70' }
                , { header: "EndToken", name: "EndToken", dataType: "string", editor: 'text', renderer: { type: TextInputRenderer },width: '70' }
                , { header: "Repeat Value", name: "RepeatValueBool", renderer: { type: CustomCheckBox }, width: '65'/*, copyOptions: { useListItemText: false }*/ }
                , { header: "NonParse Area", name: "NonParseAreaBool", renderer: { type: CustomCheckBox }, width: '65'/*, copyOptions: { useListItemText: false }*/ }
            ],
            data: [],
            editingEvent: 'click'
        });

The renderer that is currently in question is 'CustomCheckBox'.

**Version**
4.15.0

**Comment by js87zz** [comment]
@Kang-Programming 
I think the `checked` property needs to be changed in `render` method.
```js
//...

CustomCheckBox.prototype.render = function (props) {
  this.el.value = props.value;
  this.el.checked = String(props.value) === 'true' ? true : false;
}
```

**Comment by Kang-Programming** [comment]
> @Kang-Programming
> I think the `checked` property needs to be changed in `render` method.
> 
> ```js
> //...
> 
> CustomCheckBox.prototype.render = function (props) {
>   this.el.value = props.value;
>   this.el.checked = String(props.value) === 'true' ? true : false;
> }
> ```

Thank you for your answer. I applied it to the source code as you told me, but I still can't apply the contents of the clipboard.
I tested it as follows.:

1. I've copied all the row values of the cell by dragging them all.
2. When I pasted the copy from No. 1 into the notepad, I checked that I copied the value properly.
3. After that, I revised the contents of all cells little by little in the contents of notepad.
4. Then, when I pasted it into the grid, it still didn't paste properly on the CustomCheckBox render. (The contents of pasting all columns except CustomCheckBox have been applied correctly.)
5. And then I copied the grid that was pasted again.
6. When pasting, CustomCheckBox column only failed to display the corrected contents in No. 3. (In other words, the contents of the clipboard could not be delivered internally to the CustomCheckBox render)

I also reviewed the addition of events in the eventListener of typescript, but the clipboard event was not called properly.

**Comment by Kang-Programming** [comment]
> @js87zz 
> I think the `checked` property needs to be changed in `render` method.

Thank you for your answer. I applied it to the source code as you told me, but I still can't apply the contents of the clipboard.
I tested it as follows.:

1. I've copied all the row values of the cell by dragging them all.
2. When I pasted the copy from No. 1 into the notepad, I checked that I copied the value properly.
3. After that, I revised the contents of all cells little by little in the contents of notepad.
4. Then, when I pasted it into the grid, it still didn't paste properly on the CustomCheckBox render. (The contents of pasting all columns except CustomCheckBox have been applied correctly.)
5. And then I copied the grid that was pasted again.
6. When pasting, CustomCheckBox column only failed to display the corrected contents in No. 3. (In other words, the contents of the clipboard could not be delivered internally to the CustomCheckBox render)

I also reviewed the addition of events in the eventListener of typescript, but the clipboard event was not called properly.

**Comment by js87zz** [comment]
@Kang-Programming 
Can you upload your source code in code sandbox or jsfiddle?

**Comment by Kang-Programming** [comment]
> @js87zz 
> Can you upload your source code in code sandbox or jsfiddle?

https://jsfiddle.net/r8qkjymb/

my project is applying mvc model at asp.net in c#.
Interworking between the database and the server, and the server and WEB are communicating through WCF. :)

**Comment by js87zz** [comment]
@Kang-Programming 
If the code in jsfiddle is not worked, I cannot resolve the issue.
Is it hard to provide the simple example with your mock data?
