### ISSUE TITLE
Global search text filter

### ISSUE THREAD

**Issue by b1tc0re** [nhn/tui.grid#1177]
**Summary**
1. How to make a global table search filter. I tried to use api but it doesn't work for me. `Grid.filter('name', [{code: 'contains', value: 'key2' }]);` 

Now I check the match on the server and form a response with the result, but it's not convenient.
```
{
  _attributes: { className: ['active-filtered'] }
}
```
2. If I update the table using the reloadData method, all rows are redrawn, is it possible to check the received data and compare it with the table and redraw only the changed rows? Or maybe there is such a method that works this way?

**Screenshots**
1. Global search

![G2](https://user-images.githubusercontent.com/8367655/93946306-94d65f00-fd41-11ea-92fc-96c6cf961507.gif)

**Version**
4.15.0

**Comment by js87zz** [comment]
@b1tc0re 
1. Can you try to change `contains` to `contain`? When i tested it, the data is filtered properly.
2. We don't provide the way to diff the data. It may be more inefficient to compare all data fields on each row.
