### ISSUE TITLE
Memory leak or endless cycle Tree UI

### ISSUE THREAD

**Issue by b1tc0re** [nhn/tui.grid#1178]
**Describe the bug**
If call `grid.resetOriginData();` and `grid.restore()` browser freezes.

**To Reproduce**
1. Go to https://cdpn.io/b1tc0re/debug/WZzdWr/XBAGRqLDpnRr
2. Click on button resetOriginData
3. Click on button restore

**Screenshots**
![2](https://user-images.githubusercontent.com/8367655/93948974-758f0000-fd48-11ea-9f63-a37ef50561c6.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome , safari
 - Version Chrome 85.0.4183.102

**Comment by js87zz** [comment]
@b1tc0re 
Thank you for reporting. 
We will check it.

**Comment by js87zz** [comment]
@b1tc0re 
The bug has been fixed in `v4.15.3`.
