### ISSUE TITLE
Error in deleting(removeCheckedRows()) new row in empty grid. 

### ISSUE THREAD

**Issue by caleb-donghun** [nhn/tui.grid#1179]
**Describe the bug**
Error in deleting(removeCheckedRows()) new row in empty grid. 
However, if you add a new row with an existing row, the removeCheckedRows() will proceed normally.

**To Reproduce**
2. Click on 'prependRow()'
3.  Click on 'removeCheckedRows()'

**Screenshots**
**#Error in deleting(removeCheckedRows()) new row in empty grid.**
![image](https://user-images.githubusercontent.com/67719512/93952507-f61f2200-fd83-11ea-9290-84f867838001.png)

**# if you add a new row with an existing row, the removeCheckedRows() will proceed normally.**
![image](https://user-images.githubusercontent.com/67719512/93952568-223aa300-fd84-11ea-9538-3f56c7d780ca.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser chrome
Version Chrome 85.0.4183.102

**Comment by js87zz** [comment]
@caleb-donghun 
Thank your for reporting.
We will fix it!

**Comment by js87zz** [comment]
@caleb-donghun 
Is this issue still be problem in the latest version of Grid? 
It that, can you upload your source code in jsfiddle or code sandbox?

**Comment by caleb-donghun** [comment]
@js87zz 
Currently, the source is implemented as follows. There is still the same issue.

<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.pagination/latest/tui-pagination.js"></script>
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>

    	// GRID생성
	var grid = new tui.Grid( {
		el: document.getElementById('grid'),
		rowHeaders: ['checkbox',  'rowNum'],    
		editingEvent : 'click',
	    scrollX: false,
		pageOptions: {
	        useClient: true,
	        perPage: 10
	    },
	    rowHeight: 28,
	    minRowHeight: 20,
		columns: [
			{ header: '그룹코드', name: 'tpCd', editor: 'text', validation: { required : true, unique : true },  sortingType: 'desc',  sortable: true },
			{ header: '코드명',	name: 'tpNm', editor: 'text', sortingType: 'desc',  sortable: true	},
			{ header: '설명', name: 'descCntn', 	editor: 'text' , sortingType: 'desc',  sortable: true },
			{ header: '사용여부', name: 'useYn', width: 100, align : 'center', sortingType: 'desc',  sortable: true,
			    formatter: 'listItemText',
			    editor: { type: 'select', options: { listItems: [ { text: 'Y', value: 'Y'},{ text: 'N', value: 'N'}	]}}
			},
		],
		data: clsData 
	} );

	//삭제버튼
	function delRow() {
		var chkArray = grid.getCheckedRowKeys();
		if(chkArray.length > 0){
			grid.removeCheckedRows();
			grid.request('deleteData', {
			    checkedOnly: true,
			    //showConfirm : false
			});
		}
		else{
			alert('항목이 선택되지 않았습니다.');
		}		
	}

**Comment by js87zz** [comment]
@caleb-donghun 
There is no problem on testing the grid with your code.
To resolve the issue, give the example demo source in **jsfiddle** or **code sandbox**. If the detail information is not provided to us, we cannot resolve and implement it.

**Comment by caleb-donghun** [comment]
@js87zz 
Thank you for your quick reply.
I'll share the link.
**https://jsfiddle.net/donghunhyun/juo84agt/4/#&togetherjs=Nk6yHNiToy**

Please check.

**Comment by js87zz** [comment]
@caleb-donghun 
I checked your code and it was a problem of CDN link. Our CDN link has been changed as below. If you change the link, grid will be worked well.
```html
<!-- before -->
<link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>

<!-- after -->
<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
```

**Comment by caleb-donghun** [comment]
@js87zz 
Oh! it works well!!!
Thank you for your quick help. 
I look forward to seeing more good TUI GRID features in the future! 
Have a great day!
