### ISSUE TITLE
Date Filter does not working on IE11

### ISSUE THREAD

**Issue by eggplantiny** [nhn/tui.grid#1183]
**Describe the bug**
I wanna filter data using TUI Grid and DateRangePicker with Vue.js

It does work good on Chrome browser but i catched it does not work on the IE11

![tui-grid-bug-report-1](https://user-images.githubusercontent.com/57978095/94222767-4683b480-ff29-11ea-9fd6-652509cb94e2.png)

I changed the date range with another vue component and invoked method of tui.grid

and i use formatter function of tui grid to display date

i made a [repository of exmaple app](https://github.com/eggplantiny/vue-tui-grid-filter-eg) for you can check this bug

thx for your help and maintain this great application.

 - OS: Window 10
 - Browser: Chrome 85, Internet Exploler 11

- @toast-ui/vue-grid: ^4.15.1
-  vue: ^2.6.11

**Comment by js87zz** [comment]
@eggplantiny 
Sorry for late replying.
I checked your issue. It's not the grid issue.
The problem is `Date` constructor function issue. 
If the date format delimiter is `.`, the date is not parsed properly in `IE11`(maybe safari too)

```js
new Date('2020.10.09') // cannot be parsed in IE11
```
So, you need to change the format and formatter option.

```js
columns: [
    {
        name: 'createdAt',
        header: '생성일',
        filter: {
            type: 'date',
            operator: 'AND',
            // change dot to dash
            format: 'yyyy-MM-dd'
        },
        formatter ({ value }) {
            // change dot to dash
            return moment(value).format('YYYY-MM-DD')
        }
    },
    {
        name: 'userName',
        header: '사용자명'
    }
],

```
