### ISSUE TITLE
Case insensitive select filter

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#1184]
When the value in the column is in all `CAPS`, is there a way to search for that value even if we type the value in` lower case`. For example : If the value in the column is `Birdy`, no results come up when we search for `birdy` in the search tab.

![Screenshot from 2020-09-25 10-53-43](https://user-images.githubusercontent.com/52497530/94229608-9fe5e680-ff1d-11ea-85cb-de5cebebee09.png)

**Comment by js87zz** [comment]
@SanjaySankar 
Sorry for late replying.
I think we need more options for the filter functionality. We will consider it.
Thanks!

**Comment by selvasleroy** [comment]
+1

**Comment by selvasleroy** [comment]
> When the value in the column is in all `CAPS`, is there a way to search for that value even if we type the value in` lower case`. For example : If the value in the column is `Birdy`, no results come up when we search for `birdy` in the search tab.
> 
> ![Screenshot from 2020-09-25 10-53-43](https://user-images.githubusercontent.com/52497530/94229608-9fe5e680-ff1d-11ea-85cb-de5cebebee09.png)

+1

**Comment by Raemerrr** [comment]
> When the value in the column is in all `CAPS`, is there a way to search for that value even if we type the value in` lower case`. For example : If the value in the column is `Birdy`, no results come up when we search for `birdy` in the search tab.
> 
> ![Screenshot from 2020-09-25 10-53-43](https://user-images.githubusercontent.com/52497530/94229608-9fe5e680-ff1d-11ea-85cb-de5cebebee09.png)

+1

**Comment by SanjaySankar** [comment]
@js87zz can we expect this enhancement with the next release since others are also interested?

**Comment by js87zz** [comment]
@js87zz 
We are planning to fix the bugs In next release(maybe this week). We will work for this enhancement after that.

**Comment by js87zz** [comment]
@SanjaySankar 
This issue has been fixed in `v4.17.0`. Thanks!

**Comment by geomna** [comment]
Does case-insensitive filtering really work now? I am using the "latest" version, but the filtering is still case sensitive.

**Comment by davidlam-at-home** [comment]
interested in case-insensitive filtering as well.

**Comment by bondjw07** [comment]
Also need case insensitive search, is there any way around this?

**Comment by paulfelce** [comment]
Bumping this. As I'd also like to see this work regardless of case.
