### ISSUE TITLE
Can i remove current selection range?

### ISSUE THREAD

**Issue by seonk94** [nhn/tui.grid#1185]
**Summary**
When there is a current selection range , can we remove the selection range due to event ( ex: focusout event) ?

**Version**
"version": "4.15.0"

**Comment by js87zz** [comment]
@seonk94 
What is your point? You want to delete the data or just release selection?
Give more detail information.

**Comment by gopal-abbineni** [comment]
@seonk94  There was no API exposed on grid. but the work around i got for removing current selection range is to get grid instance and run below code
`gridInstance.dispatch('initSelection');`
also we can remove the focused cell on the table by running below snippet
`gridInstance.dispatch('setFocusInfo', null, null, false);`

Is there any better approach @js87zz
