### ISSUE TITLE
How can I deserialize it?

### ISSUE THREAD

**Issue by Munhun** [nhn/tui.grid#1186]
안녕하세요?

Toast Grid를 사용하고 싶어서...
테스트를 하고 있는 중입니다.
updateData 를 할 때 서버에 데이터가 직렬화되어 넘어오는데
다음과 같이 넘어 옵니다.

updatedRows[0][name]=aaa&updatedRows[0][value]=21&updatedRows[0][rowKey]=0&updatedRows[1][name]=bbb&updatedRows[1][value]=23&updatedRows[1][rowKey]=1

이것은 어떻게 사용할 수 있는 객체로 변환할 수 있는지요?
(How can I deserialize it?)

**Comment by js87zz** [comment]
@Munhun 
Find it for your server configuration.
We cannot answer because we don't know the your server environment.

**Comment by Munhun** [comment]
updatedRows[0][name]=aaa&updatedRows[0][value]=21&updatedRows[0][rowKey]=0&updatedRows[1][name]=bbb&updatedRows[1][value]=23&updatedRows[1][rowKey]=1
이 데이터를 JSON 형식으로 변환 할 수 있는 방법이 있을까요?
딕셔너리나 배열로 변환 할 수 있을까요?
