### ISSUE TITLE
Is there a way to get the current data after filters have been applied?

### ISSUE THREAD

**Issue by ip999** [nhn/tui.grid#1187]
I may not be using this in the way in which it is intended, but for my use case I would like to use the grid control as an "excel -like" filter for some simple datamining in the browser and then take the filtered data into a map (leafletjs). 

Ideally I'd like to be able to return an array of JSON objects representing the current state of the visible data once filters have been applied. Can this be done?

**Comment by js87zz** [comment]
You need to get the filtered data through grid API? is it right?
If so, we need to add new API for it.

**Comment by ip999** [comment]
Yes, that's right. It looks like I can get an array of the remaining rows' indices after filter from "instance.store.data.filteredIndex" so I think that could work for now, but yes native API support would be much better than my spaghetti "hack".

**Comment by ip999** [comment]
@js87zz I just noticed that there is also filteredRawData so watching the "grid.on("filter") event I can get the desired data there. This seems to work for now, thanks

**Comment by SanjaySankar** [comment]
@js87zz Is this a planned feature? I also want this for my project.
