### ISSUE TITLE
Use with bootstrap modal problem

### ISSUE THREAD

**Issue by kim-seung** [nhn/tui.grid#1189]
I am using bootstrap version 4.5.2 and tui.grid version 4.10.0.
When drawing a grid using tui.grid in the bootstrap modal Grid is not displayed on the initial screen. 
Grid is displayed normally when you run the developer tool.
Please ask for a solution.
(Grid is displayed normally on screens other than bootstrap modal.)

● Initial execution screen (There is no grid header.)
![modal1](https://user-images.githubusercontent.com/60688938/95166608-28e80200-07e9-11eb-9840-7385c5792f3d.JPG)

● Screen after running developer tool (There is a header of the grid.)
![modal2](https://user-images.githubusercontent.com/60688938/95166627-343b2d80-07e9-11eb-927a-a639ccf35b20.JPG)

**Comment by js87zz** [comment]
@kim-seung 
Upload your example code in jsfiddle or code sandbox.
We cannot implement each example for resolving the issue.
