### ISSUE TITLE
 I have a question about grid focus.

### ISSUE THREAD

**Issue by kim-seung** [nhn/tui.grid#1190]
When you click the content in the grid, the focus moves normally.
However, after clicking content in the grid, when clicking outside the grid, focus in the grid remains.
Please ask for a solution.

● Even if you click outside, the focus in the grid remains.
![1111111](https://user-images.githubusercontent.com/60688938/95274923-11a92300-0882-11eb-9fec-40ee005c4efe.JPG)

**Comment by js87zz** [comment]
@kim-seung 
It's our specification for layer editor.
If you want to remove focus, use the [blur](https://nhn.github.io/tui.grid/latest/Grid#blur) API
