### ISSUE TITLE
그리드 bodyHeight관련 질문입니다.

### ISSUE THREAD

**Issue by jabel123** [nhn/tui.grid#1193]
gridBodyHeight설정을 하지않고 값을 설정하였는데,,
minHeight의 값이 적용되네요,, 어쩌다 한번씩 auto가 적용되긴 하는것 같은데

외부함수에서 bodyHeight 값을 조정하는 방법이 있을까요?

**Comment by js87zz** [comment]
@jabel123 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
