### ISSUE TITLE
"Cannot read property 'rowSpanMap' of undefined" occurs when deleting rows

### ISSUE THREAD

**Issue by seo-rio** [nhn/tui.grid#1194]
**Describe the bug**
Error occurs when the raw data is recalled and the row is deleted by recalling the data back to ajax.

**To Reproduce**
1. Create Grid (Initialize Data)
2. Recall data using ajax (approximately 700 results)
3. Select 400th from first row (click + shift used, Scroll down during this process)
4. tui-grid.js:2388 Uncaused TypeError: Unable to read property 'rowSpanMap' for undefined (Occurs when the scroll position is more than half of the total position.)
5. Recall data using ajax (approximately 700 results)
6. tui-grid.js:2777 Uncaught TypeError: Cannot read property 'forEach' of undefined

**Desktop (please complete the following information):**
 - OS: Window10
 - Browser: Chrome 
 - Version 85.0.4183.121

**Comment by js87zz** [comment]
@scs9310 
Can you give us more detail information?
We need your data or grid configuration code. It's the best to upload your code in code sandbox or jsfiddle.

**Comment by scs9310** [comment]
@js87zz 
JSFiddle link : https://jsfiddle.net/fnjxy1e0/

This is the sequence of actions.
![issue](https://user-images.githubusercontent.com/44385760/97397988-c5f01380-192d-11eb-9292-f4f9d1f04e56.gif)

**Comment by js87zz** [comment]
@seo-rio 
I checked your issue. We will fix it and then comment here.
Thanks!

**Comment by seo-rio** [comment]
@js87zz 
Thank you for check it.
I'll be waiting for the reply.

**Comment by js87zz** [comment]
@seo-rio 
The bug has been fixed in `v4.15.3`.

**Comment by seo-rio** [comment]
Thank you
