### ISSUE TITLE
How can I apply tui grid to table that already completed?

### ISSUE THREAD

**Issue by jiseonmoon** [nhn/tui.grid#1195]
**Summary**
How can I apply tui grid to table that already completed?

**Screenshots**

**Version**
4.15.1

**Additional context**
How can I apply tui grid to table that already completed?

\<table id="countryList">
    \<thead>
        \<tr>
            \<th th:text="#{country.label.name}"> Country </th>
            \<th th:text="#{country.label.capital}"> Capital </th>
            \<th th:text="#{country.label.square}"> Square </th>
        \</tr>
    \</thead>
    \<tbody>
        \<tr th:each="country : ${countryList}">
            \<td th:text="${country.name}"></td>
            \<td th:text="${country.capital}"></td>
            \<td th:text="${country.square}"></td>
        \</tr>
    \</tbody>
\</table>
\<script>
$(document).ready(function(){
    $('#countryList').function();
});
\</script>

I want to use tui pagination at this table. And I also want this table to have tui grid's design. How can I do it?

**Comment by js87zz** [comment]
@jiseonmoon 
Try it. It is not the issue we can solve.

**Comment by jiseonmoon** [comment]
In [DataTables](https://datatables.net),

<table id="countryList">
<thead>
<tr>
<th th:text="#{country.label.name}"> Country
<th th:text="#{country.label.capital}"> Capital
<th th:text="#{country.label.square}"> Square
</tr>
</thead>
<tbody>
<tr th:each="country : ${countryList}">
<td th:text="${country.name}">
<td th:text="${country.capital}">
<td th:text="${country.square}">
</tr>
</tbody>
</table>
<script>
$(document).ready(function(){
$('#countryList').DataTable();
});
</script>

Do you mean there is no function like DataTables that can be used for html table?

**Comment by js87zz** [comment]
@jiseonmoon 
Yes. We don't support that functionality.

**Comment by jiseonmoon** [comment]
Thank you for your answer.
