### ISSUE TITLE
How to merge row after grid create

### ISSUE THREAD

**Issue by eungee0907** [nhn/tui.grid#1196]
**Summary**
I would like to receive data in the same format as number 1 from DB and display it in the same format as number 2 on the grid. 
In the example, when you create a grid, you set up a row span. But I wonder how to rowspan after making a grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/33338284/97137375-010d0e00-1799-11eb-9960-d81ec9f536bd.png)

**Version**
4.15.0

**Comment by js87zz** [comment]
@eungee0907 
Sorry for late replying.
Look [this document](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/row-span.md)
Thanks!
