### ISSUE TITLE
Set the value and focus out the cell without click another cell on the same grid

### ISSUE THREAD

**Issue by yj1008** [nhn/tui.grid#1201]
**Summary**
Set the value and focus out the cell without click another cell on the same grid

**Version**
4.15.1

**Additional context**
Is there any way to lose focus from the cell editing and set the value without click another cell on the same grid?
It is quite tricky to user to click after every single editing the grid.
Please kindly let me know.
Thank you.

**Comment by js87zz** [comment]
@yj1008 
Do you want to modify the value without any click event or key(enter) event?
How do you want to control editing?
