### ISSUE TITLE
When using the tree function, how do you use it when importing data into the API through a datasource?

### ISSUE THREAD

**Issue by caleb-donghun** [nhn/tui.grid#1202]
Hello!
I'd like to use the tree function in the grid.
When using the tree function, how do you use it when importing data into the API through a datasource?
"_children"  I don't know how to implement API through data source.
Could you guide me?
Thanks!

**Comment by js87zz** [comment]
@caleb-donghun 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
You need to give more detail information.
