### ISSUE TITLE
ios 에서 스크롤이 보여지지 않는 문제

### ISSUE THREAD

**Issue by serile** [nhn/tui.grid#1204]
##  Version
TOAST UI Grid 4.14.0

## Development Environment
OS: iOS 14
Browser: Saferi

## Current Behavior
현재 진행중인 프로젝트의 모바일 웹페이지 개발에 사용되는 그리드를 TOAST UI Grid 로 선택하여 개발 중입니다.
다른 브라우저에는 문제가 없는데 iOS 의 Safari 나 Chrome 같은 브라우저에서 그리드의 스크롤이 보이지 않는 현상이 발생합니다.
해결방법이 있을까요?

**Comment by rladudtjr871** [comment]
해결 하셨나요?

**Comment by serile** [comment]
iOS 화면 스타일을 다크 모드로 설정 했을 때만 스크롤이 안보이는 현상인데
답변도 없고 해서 그냥 내버려뒀습니다.

**Comment by serile** [comment]
> 해결 하셨나요?

iOS 화면 스타일을 다크 모드로 설정 했을 때만 스크롤이 안보이는 현상인데
답변도 없고 해서 그냥 내버려뒀습니다.

**Comment by rladudtjr871** [comment]
그렇군요.. 감사합니다!
