### ISSUE TITLE
수동으로 validation 업데이트 하는 방법이 있을까요?

### ISSUE THREAD

**Issue by uastory** [nhn/tui.grid#1211]
각 셀의 Validation이 서로 상관관계가 있습니다. `Size 2` 컬럼은 `Size 1` 컬럼값이 있을 경우만 값을 입력할 수 있고,  `Size 1` 컬럼보다 작아야 합니다.  
`Size 1` 컬럼 값을 입력한 후 `Size 2` 값을 입력하면 Validation이 정상 동작하지만, 이후 `Size 1`값을 수정할 때에는 `Size 2`의 Validation이 업데이트 되지 않습니다.

`grid.validate()` 메소드를 호출하면 전체 셀의 validation 체크를 다시 하여 업데이트 할 줄 알았는데... 그렇게 동작하지 않더군요.

수동으로 전체 grid의 validation을 다시 체크하도록 하는 방법이 있을까요?
 
![image](https://user-images.githubusercontent.com/5935819/97299198-ef5e6000-1897-11eb-9917-4925d5893479.png)

**버전**
4.15.2

**Comment by js87zz** [comment]
@uastory 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@uastory 
We have not considered the validation for the cell which has the relation with other cells. As you said, I will consider adding a new API or other way.
