### ISSUE TITLE
[Client Pagination] Copy-related issues

### ISSUE THREAD

**Issue by gbajs2018** [nhn/tui.grid#1213]
When I set "useClient: true" among the grid options and copied the "Name" column in the first row of page 2, I found an issue where the "Name" column of page 1 was copied (photo attached). Is there an option to resolve this issue?
![Screenshots](https://user-images.githubusercontent.com/45655846/97384166-82d47700-1912-11eb-9128-32f4f9fb12c7.PNG)

**Comment by gbajs2018** [comment]
example site
https://nhn.github.io/tui.grid/latest/tutorial-example23-client-pagination

**Comment by js87zz** [comment]
The bug has been fixed in `v4.15.3`.
