### ISSUE TITLE
After adding a line, click the Save button to get a null value.

### ISSUE THREAD

**Issue by baekgor7** [nhn/tui.grid#1214]
**Summary**
I'd like to ask you again.
After adding a line, click the Save button with the focus on the artist to get a null value.
I want to get 222 out of the artist.
Please give me an answer.

**Screenshots**
![캡처1](https://user-images.githubusercontent.com/24218046/97544110-7df3ee00-1a0c-11eb-9b7c-f26b1d2d29cf.GIF)
![캡처2](https://user-images.githubusercontent.com/24218046/97544124-81877500-1a0c-11eb-95f1-128cf01f7d68.GIF)
![캡처3](https://user-images.githubusercontent.com/24218046/97544135-83e9cf00-1a0c-11eb-9f15-f885d1b71b96.GIF)

**Version**
4.15.2

**Comment by js87zz** [comment]
@baekgor7 
Call the [finishEditing](https://nhn.github.io/tui.grid/latest/Grid#finishEditing) API in your save function.
```js
function fnSave() {
  grid.finishEditing();
  // ...
}
```

**Comment by baekgor7** [comment]
Thank you very much. ^^
