### ISSUE TITLE
Question about value change after applying filter

### ISSUE THREAD

**Issue by Raemerrr** [nhn/tui.grid#1216]
grid.filter('ABC', [{code: 'eq', value: 'General'}]);

After using the filter to search for a list of rows (select type) by the'normal' value in the'ABC' column
I would like to change from'General' to'Advanced'.

But if I change the value of SelectBox, the filter doesn't work.
I think it's a natural result in some ways.

But what I want is to take a specific list of values ​​and change the values ​​in batch.

I would like to receive guidance on implementing the feature.

✅When using a filter, is there any way to fix the values ​​hanging on the filter to make it work without problems?

**Comment by Raemerrr** [comment]
엇.. 자문 자답인지 모르겠으나.. 확인 차 답글 달아 문의드립니다..
grid.resetData(grid.findRows({
            ABC: '일반'
        }));
그리드를 필터로 찾는 것이 아닌 해당 조건에 맞게 resetData를 한 후 작업하니 정상 동작 하였습니다..
이런 식으로 기능 구현을 하면 될까요~?

**Comment by js87zz** [comment]
@Raemerrr 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by jongil8030** [comment]
I'm really curious, why do I have to write it in English?

**Comment by js87zz** [comment]
@jongil8030 
It's for Foreign user.

**Comment by js87zz** [comment]
@Raemerrr 
Can you upload your example code or screenshot in detail?
I think you want to  change the specific value(`일반`) of the column. right?

**Comment by Raemerrr** [comment]
> @Raemerrr
> Can you upload your example code or screenshot in detail?
> I think you want to change the value(`일반` => `고급`) of the specific column. right?
![image](https://user-images.githubusercontent.com/29060626/99013775-9fb8ad80-2594-11eb-836f-1fa6b85e4748.png)
After filtering to'normal' and changing to another value, the grid stops.

**Comment by js87zz** [comment]
@Raemerrr 
I have found the another bug when changing the data through select editor on filtered data. However, Unlike what you said grid have not stopped.
To resolve your issue, give more detail information like your source code or gif screenshot.
