### ISSUE TITLE
Consider supporting REST APIs which do implement paging or your expected JSON format

### ISSUE THREAD

**Issue by ejstembler** [nhn/tui.grid#1218]
## Version

latest

## Development Environment

- macOS 10.15.7 (19H15)
- Safari Version 14.0 (15610.1.28.1.9, 15610)

## Current Behavior

If you set the grid data it accepts `[{}]` an array of objects. However, if you use a REST API the grid expects that queryStings are used to pagination and the resulting JSON must be in the verbose format it requires.

Most REST data APIs do not conform to this.  I would recommend accepting data in the format similar to what `.data` can use, the array of objects `[{}]`. This would also help with adoptation.

**Disclaimer**: Perhaps I'm missing something and this is already supported?

```js
// Write example code
```

**Comment by js87zz** [comment]
@ejstembler 
Can you explain your proposal in detail? It's about response data format?
