### ISSUE TITLE
React에서 appendData, appendTreeData method 사용시 버그 발생

### ISSUE THREAD

**Issue by usang0810** [nhn/tui.grid#1220]
**Describe the bug**
React에서 tui grid에 tree data 사용중 api 통신 요청 후 appendData or appendTreeData method 사용시 멈춤 현상이 나타납니다.

**To Reproduce**
1. tree grid를 생성합니다.
2. 서버에 api 요청 후 appendData or appendTreeData를 요청합니다.
3. 작동이 멈춥니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/38275730/98509850-566f1200-22a5-11eb-84ab-0c99118235a2.png)
api 호출 전 이미지

![image](https://user-images.githubusercontent.com/38275730/98510006-acdc5080-22a5-11eb-9e5e-a45ff8f25e4b.png)
api 호출 후 이미지

![image](https://user-images.githubusercontent.com/38275730/98510112-e01edf80-22a5-11eb-9b3b-fa981b25662d.png)
![image](https://user-images.githubusercontent.com/38275730/98510068-caa9b580-22a5-11eb-9ea0-4e499fc00259.png)
expand 이벤트 핸들러입니다.

await GetFileList(prjObj); 이 코드를 실행하기 전에는 append method가 잘 동작하지만 호출 이후에는 동작하지 않습니다.

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome
 - Version 4.15.2
 - React 17.0.1

**Comment by js87zz** [comment]
@usang0810 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@usang0810 
The result data of `GetFileList` will be added to grid? If it possible, give more information about your code. It's the best to upload your code in codepen or jsfiddle.

**Comment by usang0810** [comment]
Rewritten in English writing #1225
