### ISSUE TITLE
 An error occurs when adding a row after calling server api in the 'react' environment

### ISSUE THREAD

**Issue by usang0810** [nhn/tui.grid#1225]
Hello I am working on a project using react. I have to use the grid in the project, so I am using toast ui grid. However, a bug occurs when using a tree type grid. The bug that occurs occurs when the 'appendRow' or 'appendTreeRow' method is used. If you simply use it, there is no problem, but if you call the api to the server through 'axios' and use it, it will stop from that moment. What is the problem?

A similar situation was created and posted in'codesendbox'. Please confirm
https://codesandbox.io/s/vigorous-spence-fi46s?file=/src/App.js

Desktop
 - OS: windows10
 - Browser: chrome
 - dependencies
"react": "^17.0.1"
"@toast-ui/react-grid": "^4.15.2"
"axios": "^0.20.0"

**Comment by js87zz** [comment]
@usang0810 
We don't support the `async function` as the our event callback properly. Support for this functionality will probably take quite a while and will not be an easy task. To resolve the issue, I think that  it seems the best way to set the data by bypass as below.

```js

const handleExpand = async (ev) => {
  const { rowKey, instance } = ev;
  const descendantRows = instance.getDescendantRows(rowKey);

  if (descendantRows && descendantRows.length <= 0) {
    // stop the event
    ev.stop();
    const data = await getSomeDataWithAsync();
    data.type = "dir";
    data._children = [];

    instance.appendTreeRow(data, {
      parentRowKey: rowKey
    });
    // expand the row after setting the data through API
    grid.expand(rowKey);
  }
};
```

**Comment by usang0810** [comment]
Thanks to you, the problem was solved.
