### ISSUE TITLE
Question about radioButton style

### ISSUE THREAD

**Issue by Raemerrr** [nhn/tui.grid#1228]
I want to display it as shown in the picture.
![image](https://user-images.githubusercontent.com/29060626/99199873-80fd2580-27e5-11eb-95c3-53ec3c5d25f1.png)
- https://www.youtube.com/watch?v=pyPlOFhexQk

I don't want to display it as shown in the picture.
![image](https://user-images.githubusercontent.com/29060626/99199918-bb66c280-27e5-11eb-9cbf-c73430817090.png)
- https://nhn.github.io/tui.grid/3.9.0/tutorial-example04-input-types

**Comment by js87zz** [comment]
@Raemerrr 
What is your grid version correctly?

**Comment by Raemerrr** [comment]
> @Raemerrr
> What is your grid version correctly?

/*!
 * TOAST UI Grid
 * @version 4.15.2 | Mon Oct 26 2020
 * @author NHN. FE Development Lab
 * @license MIT
 */

**Comment by js87zz** [comment]
@Raemerrr 
Currently, our radio editor is rendered as below. It's different from your screenshot.
![스크린샷 2020-11-16 오후 3 20 31](https://user-images.githubusercontent.com/37766175/99219110-5039e200-281f-11eb-8992-12e3255df0e9.png)
