### ISSUE TITLE
Question about roadmap

### ISSUE THREAD

**Issue by jechaviz** [nhn/tui.grid#1229]
I have visited www.syncfusion.com/vue-ui-components/vue-grid

They have all next components for their grids. Have u planning to add some of them? I have seen you have already implemented some. 

Mobile optimized and touch friendly
Touch support in Vue DataGrid/Datatable.
Responsive pager UI in Vue DataGrid/Datatable.
Vue DataGrid CRUD, CUSTOM Editor.
Theming 
Export to PDF, CSV, and Excel 
Keyboard navigation
Context menu
Stacked headers
Grouping. Data can be grouped in the ascending or descending order. Rows can be grouped by dragging and dropping the desired columns in the interactive drop area.

Thank you for your attention. 

ALL COMPONENTS
GRIDS
Data Grid
Tree Grid
Pivot Table
Spreadsheet
EDITORS
Rich Text Editor
Word Processor
DROPDOWNS
AutoComplete
ListBox
ComboBox
Dropdown List
MultiSelect Dropdown
Dropdown Tree
INPUTS
TextBox
Input Mask
Numeric Textbox
Radio Button
Checkbox
Color Picker
File Upload
Slider
Toggle Switch Button
DATA VISUALIZATION
Charts
Stock Chart
Circular Gauge
Linear Gauge
Diagram
HeatMap Chart
Maps
Range Selector
Smith Chart
Sparkline Charts
Barcode Generator
TreeMap
Bullet Chart
Kanban
CALENDARS
Scheduler
Gantt Chart
Calendar
DatePicker
Date Range Picker
DateTimePicker
TimePicker
NAVIGATION
Accordion
Context Menu
Menu Bar
Sidebar
Tabs
Toolbar
Tree View
File Manager
LAYOUT
Avatar
Card
Dialog
ListView
Tooltip
Splitter
Dashboard Layout
BUTTONS
Button
Button Group
Dropdown Menu
Progress Button
Split Button
Chips
NOTIFICATIONS
Badge
Toaster
Progress Bar
FORMS
In-place Editor
Query Builder UI
VIEWER
PDF Viewer
Frequently Asked Questions

**Comment by js87zz** [comment]
@jechaviz 
The plan has not yet been reviewed regarding the all new functionality. However, we have the top priority we are thinking as below.
* DOM structure improvement(related issue: #1155)
* support the custom filter and external filter
* enhance the tree grid to use other functionality(sort, filter)
* improve the performance with large column data
* export CSV format data
* context menu
* enhance the custom header for using
