### ISSUE TITLE
Datepicker doesn't look properly on grid

### ISSUE THREAD

**Issue by hoon-jo** [nhn/tui.grid#1232]
I added this in my columns array

```
editor: {
    type: 'datePicker',
},
```

and It looks like down below.

![image](https://user-images.githubusercontent.com/65211698/100412686-b264d380-30b8-11eb-9bcf-cd429a8b547b.png)

I don't know why it looks like that
Even I imported css file of datepicker

How can I fix it??

**Comment by hoon-jo** [comment]
And I'm curious how can I change language to Korean.
can u let me know?

**Comment by js87zz** [comment]
@hoon-jo 
You need to give more information to us about your code(grid, datepicker configuration)
The i18n could be changed through static API.
```js
import Grid from 'tui-grid';

Grid.setLanguage('ko')
```

**Comment by James-dalsoft** [comment]
I have the same problem (layout broken because November is too long?)

Setting a language of Grid to 'ko' doesn't work for datepicker.

**Comment by hoon-jo** [comment]
I'm still on this problem now too. I can't figure out how should I do. So I
temporarily had to change the css of date picker forcefully because I have
much of thing to work now :(
Sorry for cant help you.  If you find out how to fix it, can you mail me
again and let me know how you fixed it?

2020년 12월 16일 (수) 오후 2:35, James-dalsoft <notifications@github.com>님이 작성:

**Comment by js87zz** [comment]
@hoon-jo @James-dalsoft 
If you want to resolve your issue, give us your source code or configuration in code sandbox or jsfiddle.
The datepicker layout is rendered properly in our example. And i18n of date picker can be changed through this [API](https://nhn.github.io/tui.date-picker/4.0.0/DatePicker#localeTexts)
