### ISSUE TITLE
그리드에서 editor로   신규, 수정 된 상태를 보여주는 컬럼을 추가할수있는 방법이 있을까요?

### ISSUE THREAD

**Issue by jijoungsoo** [nhn/tui.grid#1235]
그리드에서 editor로   신규, 수정 된 상태를 보여주는 컬럼을 추가할수있는 방법이 있을까요?

**Comment by js87zz** [comment]
@jijoungsoo 
Please make sure you have filled out issue **respecting our form** in English and given us as much context as possible. If not, the issue will be closed or not replied.
