### ISSUE TITLE
rowHeader autoHeigt not apply.

### ISSUE THREAD

**Issue by worjs320** [nhn/tui.grid#1236]
**Describe the bug**
When I click the sort button, 
The height is not adjusted automatically.
Can you tell me what needs to be fixed directly in the tui library code?
my tui grid version is '4.10.0'
Below is my code.

```js
tableApplicationView = new tui.Grid({
    el: document.getElementById('table_host_area'),
    bodyHeight: 250,
    scrollX: true,
    scrollY: true,
    rowHeaders: [{type:'checkbox'}, {type:'rowNum'}],
    columns: [
        {header: '<%=MessageConfig.getViewProps("applicationgroup_list.defineApplicationTable.headerText.1")%>', name: 'APPNAME', whiteSpace: 'normal', sortable: true, filter: 'select',},
        {header: '<%=MessageConfig.getViewProps("applicationgroup_list.defineApplicationTable.headerText.2")%>', name: 'FILENAME', whiteSpace: 'normal', sortable: true, minWidth:150, filter: 'select',},
        {header: '<%=MessageConfig.getViewProps("applicationgroup_list.defineApplicationTable.headerText.3")%>', name: 'VERSION', whiteSpace: 'normal', sortable: true, "align":"center"}
    ],
    rowHeight:'auto',
 });
```

**To Reproduce**
1. create Table
2. Click sort button

**Screenshots**
![image](https://user-images.githubusercontent.com/32512236/101732624-d97fc400-3b00-11eb-87f3-3218d9013f38.png)

**Desktop (please complete the following information):**
   Window
  Chrome

**Comment by js87zz** [comment]
@worjs320 
When i checked your issue, there is no problem regardless of the sortable option.
Can you implement it in code sand box or jsfiddle to resolve it?

**Comment by worjs320** [comment]
@js87zz 
https://5qxi5.csb.app/
its code sand box url

**Comment by js87zz** [comment]
@worjs320 
Thank you for your reproduction. 
I checked your issue and the CDN url is old url.(**tui-grid -> grid**) I recommend the version update or changing CDN url
```js
// old-url(deprecated)
<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css"/>
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>

// new-url
<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css"/>
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
```

Currently, our latest version is `v4.15.3`. when i tested your issue in `v4.15.3`, there is no problem.
![2020-12-17 11-08-37 2020-12-17 11_08_52](https://user-images.githubusercontent.com/37766175/102434551-50184680-4058-11eb-9bbe-34770eca292b.gif)

**Comment by worjs320** [comment]
@js87zz Thank you very munch
