### ISSUE TITLE
i want to show row status which is update(U) or create(C) in the grid

### ISSUE THREAD

**Issue by jijoungsoo** [nhn/tui.grid#1237]
i want to make row status which is update(U) or create(C) in the grid

![image](https://user-images.githubusercontent.com/9294333/101776302-11542f00-3b34-11eb-9c49-5090b1a73385.png)

**Comment by js87zz** [comment]
@jijoungsoo 
Try to add the `row status` data as you call the appendRow API. In case of editing, update it in `beforeChange` event.

```js
// append row
document.querySelector('#btn').addEventListener('click', () => {
  grid.appendRow({ ...,  rowStatus: 'C'});
});

// edit cell
grid.on('afterChange', ev => {
  const { changes } = ev;
    if (ev.origin === 'cell' && changes[0].columnName !== 'rowStatus') {
      grid.setValue(changes[0].rowKey, 'rowStatus', 'U')
    }
});
```
