### ISSUE TITLE
Enable to use input in grid area

### ISSUE THREAD

**Issue by gisellekim** [nhn/tui.grid#1244]
Hello,
I wanted to use input and select tag in tui-grid.
And it is clearly visible but not usable. 
Evene though I've added preventDefault method to tui-grid area but it still isn't working.

Could you please let me know how to enable the input, select tag in grid?
(you are able to find a piece of my codes below.)

![image](https://user-images.githubusercontent.com/69022097/102837987-7404cf00-4440-11eb-9db0-36f50430ae0d.png)

![image](https://user-images.githubusercontent.com/69022097/102863947-ab8e6e00-4476-11eb-956c-f56d0e94b8d8.png)

![image](https://user-images.githubusercontent.com/69022097/102837961-618a9580-4440-11eb-9f04-85d8de863d7c.png)

![image](https://user-images.githubusercontent.com/69022097/102837874-28eabc00-4440-11eb-891d-4c6ba5b63ad7.png)

**Comment by js87zz** [comment]
@gisellekim 
Changing the cells directly or binding events are not recommended. Try to use [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) to control. And it will be resolved for selection problem defining the `mousedown` event.
```js
selectBox.addEventListener('mousedown', (ev) => {
  ev.stopPropagation();
});
```
