### ISSUE TITLE
Select filter has empty options

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#1245]
**Description**:
When there are empty values in a column in the grid, the select filter has empty options in the filter dropdown. I couldn't find any way to override this behaviour. Both null and empty string are shown as empty in the dropdown. Is there a solution for this? Attaching screenshots below:

 - OS: Linux 18.04.5
 - Browser: Chrome Version 87.0.4280.88 
 - TUI grid: v4.16.1

**Screenshots**:
![Screenshot from 2020-12-22 14-52-19](https://user-images.githubusercontent.com/52497530/102872190-69106580-4465-11eb-9dcb-cec7b218ef9b.png)

**Comment by js87zz** [comment]
@SanjaySankar 
Sorry for late replying. I was on vacation.
I checked your issue. I will fix it.

**Comment by SanjaySankar** [comment]
@js87zz is it possible to fix [this issue](https://github.com/nhn/tui.grid/issues/1184) as well since it is also a filter functionality and related to this?

**Comment by js87zz** [comment]
@SanjaySankar 
OK, I will include that functionality in next release. However, the work will be delayed because I am currently working on another project.😓

**Comment by SanjaySankar** [comment]
@js87zz any updates on this fix? Will it get merged soon?

**Comment by js87zz** [comment]
@SanjaySankar 
Sorry for late replying.
The most of the work has been done except for the test, so I think it will be far away soon. I'll let you know as soon as it's resolved.
