### ISSUE TITLE
Custom header not working

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#1246]
I wanted a custom header for my project. I want to render my own filter component inside the header. But it's throwing this error.
![Screenshot from 2020-12-22 18-40-07](https://user-images.githubusercontent.com/52497530/102892211-89e8b300-4485-11eb-991c-d6325af8d5bf.png)

HeaderRenderer is a simple renderer I wrote. I couldn't find any other documentation about header renderer. I don't know if I did something wrong. I referred #759 for this.

Here is the [codesandbox](https://codesandbox.io/s/muddy-platform-0viwi?file=/src/App.js) where I have reprodced this. Please help me find a solution

**Comment by js87zz** [comment]
@SanjaySankar 
The `CustomFormatter` should be exported directly as below
```js
export class CustomFormatter {
  constructor(props) {
    const el = document.createElement("div");
    this.el = el;
    this.render(props);
  }

  getElement() {
    this.el.style.textAlign = "center";
    return this.el;
  }

  render(props) {
    ReactDOM.render(
      <div>
        <button>btn</button>
      </div>,
      this.el
    );
  }
}

// do not wrap like this!
// export const CustomRenderer = {
//   type: CustomFormatter
// };
```
