### ISSUE TITLE
전체 체크 시 setValue이용 문의드립니다.

### ISSUE THREAD

**Issue by khcho0** [nhn/tui.grid#1250]
안녕하세요. 현재 체크박스 기능을 추가하고 체크 시 특정 컬럼에 값을 넣는 작업을 진행중입니다.

단건(특정로우)의 경우
grid.on("check", function(e){
     grid.setValue(e.rowKey, "NAME" "value");
});
를 사용하여 값을 넣었는데,

전체 체크를 한 후 전체 로우에 값을 넣을때
grid.on("checkAll", function(e){
     grid.setValue(e.rowKey, "NAME" "value");
});
에 e.rowKey 값 대신에 어떤 값이 들어가야하는지? 아니면
다른 function을 사용해야하는지 잘 모르겠습니다.
 
조언 부탁드리겠습니다.

**Comment by js87zz** [comment]
@khcho0 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

And try as below.
```js
grid.on("checkAll", function(e){
  grid.getCheckedRowKeys().forEach((rowKey) => {
    grid.setValue(rowKey, "NAME", "value");
  });
});
```

**Comment by khcho0** [comment]
@js87zz 

Thanks for the answer. I also solved the problem through a loop. I asked you if there is any way to solve it without a loop. Thank you for your kind answer to Korean questions.
