### ISSUE TITLE
I want to know how to retrieve the selected row number value.

### ISSUE THREAD

**Issue by apollonius9** [nhn/tui.grid#1255]
Version
"@toast-ui/react-grid": {
"version": "4.16.1",
"resolved": "https://registry.npmjs.org/@toast-ui/react-grid/-/react-grid-4.16.1.tgz",
"integrity": "sha512-qrg5D7VjET4rDVp1gurY9TT4v5cAU6POGyeRYDxzFcm5cpeShQEZOioHxVM1p65Y7HxOkp5WdGM1DRTNq12rWw==",
"requires": {
"tui-grid": "^4.16.1"
}
},

It's being developed in a react environment!

I want to import the selected grid row number by getting value.

alert(this.gridRef.current.instance.getFocusedCell());
Type error: Unable to read the 'getFcousedcell' property of undefined .
An error will occur.

Thank you.

**Comment by apollonius9** [comment]
gridClick = (object) => {  
   for (var key in object) {
       console.log("key: " + key + " / " + object[key])
    }
}

Resolved using grid events.

When you receive object return, you can check the key value and do it.

thanks!

**Comment by js87zz** [comment]
@apollonius9 
Can you upload your source code and environment in code sandbox or jsfiddle?
