### ISSUE TITLE
use to ‘ctrl + f’

### ISSUE THREAD

**Issue by ysyang93** [nhn/tui.grid#1259]
If you use the ‘crtl + f’ search function after the grid is drawn in Chrome, the data after scrolling is not searched.
I want to search across the grid.
without using the toast grid filter function

I am in use toast ui grid 4.10.0

Is there a solution?
please help
Thank you

**Comment by js87zz** [comment]
@ysyang93 
Because of Virtual scrolling, only visible data of the scroll area will be able to be searched.
If you want to search the entire data at once, use our filter functionality or set `scrollY: false, bodyHeight: 'auto'` to option.
