### ISSUE TITLE
How to use both renderer for custom header and renderer for custom cell at the same column?

### ISSUE THREAD

**Issue by jgs082** [nhn/tui.grid#1262]
The column renderer for creating buttons and the header renderer for multi-lines in headers have been used in the same column.

How should I set up the "renderer:" ?

// column renderer:
class TgrButton {...}

// header renderer:
class ColumnHeaderBr {...}

// colSpecs
[{
  header:'Material Order',
  name: '_btn',
  width: 40,
  renderer: ???
},
...]

**Comment by js87zz** [comment]
@jgs082 
The cell renderer should be configured as the column option and the header renderer should be configured as the header option. There is no way to apply them to the same cell at the same time and that is not our intention for renderer.
```js
const gridOptions = {
  // ...
  columns: [
        // ...
        {
          header: 'Material Orde',
          name: '_btn',
          renderer: TgrButton
        }
  ],
  header: {
    // ...
    columns: [
      {
        name: '_btn',
        renderer: ColumnHeaderBr
      }
    ]
  }
}
```

**Comment by jgs082** [comment]
Thank you for your reply.
I got it.
