### ISSUE TITLE
Grid Cell 편집시 '<' 값을 입력하면 그대로 '<' 값이 보여졌으면 합니다.

### ISSUE THREAD

**Issue by xman2310** [nhn/tui.grid#1266]
안녕하세요.

Grid Cell 편집 시 '<' 값을 입력하면, 편집이 끝난 후에는 '<' 문자 이후의 입력한 문자열은 화면에 나타나지 않습니다.
다시 편집하려 들어가면 안보이던 값들이 나타나고요.

'<' 대신 '&amp;lt;' 를 입력하면 나타나기는 하는데.. 일반 사용자들이 사용할 수 있는 대안은 아닌 것 같습니다.

Cell 편집 시 '<'를 입력하면, 그 값 그대로 보여질 수 있는 방법은 없나요?

**Comment by js87zz** [comment]
@xman2310 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@xman2310 
Try to `escapeHTML` option as below.
```js
columns: [
  {
    name: 'col1',
    escapeHTML: true
  }
],
// ...
```
