### ISSUE TITLE
Prevent renderer when scrolling

### ISSUE THREAD

**Issue by khcho0** [nhn/tui.grid#1270]
Whenever it is scrolled, the grid is newly rendered. Is there any way to prevent this? I am using it by changing the input type value in the grid arbitrarily, but it is newly rendered and the changed type is initialized whenever scrolling occurs.

Thank you

**Comment by js87zz** [comment]
@khcho0 
Because of Virtual scrolling, only visible data of the scroll area will be newly rendered. However, this behavior does not change existing data. If you change the cell data by force, you should not do that.
Can you give me the detail code in the code sandbox or jsfiddle?
