### ISSUE TITLE
resetData issue

### ISSUE THREAD

**Issue by dantory** [nhn/tui.grid#1271]
**Describe the bug**
changing data multiple times and calling a resetData method prevents certain cells from being clicked

**To Reproduce**

[ source code ]
https://codesandbox.io/s/blazing-architecture-xvxnh?file=/index.html

1. create empty grid ( without data )
2. resetData call ( reset button click ) 
3. resetData call ( reset button click one more time )
4. some items cannot be selected

The data passed to the resetData method in steps 2 and 3 are different. ( with filter )

![Feb-17-2021 12-00-44](https://user-images.githubusercontent.com/26054516/108150319-d82dd180-7117-11eb-8cd5-2272b74b2c3b.gif)

**Comment by js87zz** [comment]
@dantory 
The problem is reusing the data for `resetData` API. Reusing of data is not recommended because the data references to reactive data continuously. It will be fixed by createing new data as below. Thank you for your detail description~!
```js
function createData() {
  return [
    {
      code: "1",
      search_name: "매운김치"
    },
    {
      code: "2",
      search_name: "김치볶음밥"
    },
    {
      code: "3",
      search_name: "김치전"
    },
    {
      code: "4",
      search_name: "김치밥"
    },
    {
      code: "5",
      search_name: "새우볶음밥"
    }
  ];
}
```

**Comment by heodak-lbs** [comment]
@js87zz i got it! thank you for your answer  👍

**Comment by dantory** [comment]
@js87zz i got it! thank you for your answer 👍
