### ISSUE TITLE
appendRow로 Tree구성시 두개의 로우가 보입니다.

### ISSUE THREAD

**Issue by youngwonseo** [nhn/tui.grid#1273]
# Version
4.16.1

# Development Environment
버전 88.0.4324.192(공식 빌드) (x86_64)

# Descriptions
Tree 사용시 부모로우가 열여(expand)있는 상태에서   자식로우 추가(appendRow, appendTreeRow) 시  자식로우가 두개표시됩니다.

**Comment by js87zz** [comment]
@youngwonseo 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
