### ISSUE TITLE
appendRow({},{parentRowKey}로  생성한 트리의 parent의 경우 부모로우가 접히지않음

### ISSUE THREAD

**Issue by youngwonseo** [nhn/tui.grid#1274]
# Version
v4.12.0

# Development Environment
버전 88.0.4324.192(공식 빌드) (x86_64)

# Description
원래 자식로우가 없는 로우에 자식노드를 동적으로 추가(appedRow사용) 한경우  expand, collapse 가  정확하게 작동하지 않음
여기서 정확하게란 클릭으로 접히고 열리는 동작을 의미합니다.
<img width="373" alt="스크린샷 2021-02-27 오후 6 53 49" src="https://user-images.githubusercontent.com/6938268/109383956-2bc8c800-792d-11eb-99b3-22ffbd1d1478.png">

위 그림을 보면  spine block과 prolo therapy모두 expand되어있지만 prolo therapy의 경우 화살표가  collapse상태로 유지되어 있고 클릭해도 반응이 없음

**Comment by js87zz** [comment]
@youngwonseo 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
