### ISSUE TITLE
Is there way to append multi rows at the same rowkey?

### ISSUE THREAD

**Issue by odh0kopens** [nhn/tui.grid#1275]
**Summary**
There is a case like this.
I wanted to put multiple rows in a specific rowkey in a tree-structured grid, so I executed appendTreeRow or appendRow through a for statement, but it was confirmed that only one row was added differently than expected.

`
for(var i = 0; i < rowCnt; i++){
   grid.appendTreeRow(obj, {parentRowKey : rowKey});
}
`

I have noticed that to insert multiple rows I have to use the appendRows function, but in that function  there's no parameters that could be put in a specific rowkey. How do I insert multiple rows in a specific rowkey?

**Version**
4.16.1

**Comment by js87zz** [comment]
@odh0kopens 
Sorry for late replyng.
When i tested as you commented as below, there was no problem. 
```js
for(var i = 0; i < 5; i++) { 
  const obj = {
    name: 'dynamic loading data',
    _children: [
      {
        name: 'leaf row'
      },
      {
        name: 'internal row',
        _children: []
      }
    ]
  };
  grid.appendTreeRow(obj, { parentRowKey : 8 }); 
}
```

Can you give us detail code in code sandbox or jsfiddle?
