### ISSUE TITLE
라라벨(Laravel8) modifyData post 형식으로 보내는데 Route가 못읽는 것 같습니다. 어떤 방식으로해야될까요?? 

### ISSUE THREAD

**Issue by GoMuggi** [nhn/tui.grid#1276]
blade.php
source : 
button type="button" onclick="grid.request('modifyData')"><img src="{{asset('assets/imgs/save.png')}}"></button>
                            {{-- <button type="submit" onclick="rowSave()"><img src="{{asset('assets/imgs/save.png')}}"></button> --}}
                            
                        </div>
                        <div id="grid"></div>
                    </form>
                        <script>
                            
                            const grid = new tui.Grid({
                                el: document.getElementById('grid'),
                                data: {
                                    api: {
                                    readData: { url: "{{ route('mains.list') }}", method: 'GET' },
                                    modifyData : { url: "{{ route('mains.save') }}", method: 'POST' }

web.php source : 

Route::post('mains/save', [MainController::class, 'saveData'])->name('mains.save');

controller source : 

/**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function saveData(Request $request)
    {
        $a = $request;
        echo $a;
        return  $request;
    }

이렇게 해놨는데 데이터 전송을 안하는 것 같네요

**Comment by js87zz** [comment]
@GoMuggi 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied. 
We do not support below syntax. Try to write your API path as plain string.
```js
{{ route('mains.list') }}
```
