### ISSUE TITLE
I am sending it in the form of Laravel8 modifyData post, but it seems that the Route cannot be read. Which way should it be??

### ISSUE THREAD

**Issue by GoMuggi** [nhn/tui.grid#1278]
blade.php
source :
button type="button" onclick="grid.request('modifyData')">
                    </div>
                    <div id="grid"></div>
                </form>
                    <script>
                        
                        const grid = new tui.Grid({
                            el: document.getElementById('grid'),
                            data: {
                                api: {
                                readData: { url: "{{ route('mains.list') }}", method: 'GET' },
                                modifyData : { url: "{{ route('mains.save') }}", method: 'POST' }

web.php source :
Route::get('mains/list', [MainController::class, 'getindext'])->name('mains.list');
Route::post('mains/save', [MainController::class, 'saveData'])->name('mains.save');

controller source :

/**
* Store a newly created resource in storage.
*
* @param \Illuminate\Http\Request $request
* @return \Illuminate\Http\Response
*/
public function saveData(Request $request)
{
$a = $request;
echo $a;
return $request;
}

I wonder why... please help 
I have no idea how to approach it.

**Comment by js87zz** [comment]
@GoMuggi 
Grid cannot know the exact url if you write the url as below.
```js
readData: { url: "{{ route('mains.list') }}", method: 'GET' },
```
Try to pass the url as plain url text
```js
// just example
readData: { url: 'http://localhost:8080/main/data', method: 'GET' },
```
