### ISSUE TITLE
I set the editor type to select, but I don't want to modify it.

### ISSUE THREAD

**Issue by hhs9102** [nhn/tui.grid#1279]
**Summary**
Editor type='select' has been set.
Can I assign editable=false for this cell?

I set the editor type='select' to show the text value, but I want to make it impossible to modify it.

Should I use the disabled column and modify the css?

**Version**
4.16.1

**Comment by js87zz** [comment]
@hhs9102 
If you want to disable specific column, it would be resolved through `disabled` option as below.
```js
const grid = new tui.Grid({
  el: document.getElementById('grid'),
  // ...
  columns: [
    {
      header: 'Name',
      name: 'name',
      editor: 'text',
      // column is disabled
      disabled: true
    },
    // ...
  ]
});

// API
grid.disableColumn(columnName)
```
Also, you can disable the row using `_attributes` option.

```js
const grid = new tui.Grid({
  el: document.getElementById('grid'),
  // ...
  data: [
    {
        name: 'X',
        artist: 'Ed Sheeran',
         // row is disabled
        _attributes: {
          disabled: true
        }
      },
    // ...
  ]
});

// API
grid.disableRow(rowKey);
```
However, we don't support the `disabled` option or API for cell.

**Comment by js87zz** [comment]
@hhs9102 
Sorry for late replying.
I think you want to display the cell as `text - value` like native select box right?
If so, the [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) would be helpful to you. You can display the value you want through it.
