### ISSUE TITLE
select 

### ISSUE THREAD

**Issue by sejin-v** [nhn/tui.grid#1280]
select기능 
`  formatter: 'listItemText',
          defaultValue: 'defaultValue',
          editor: {
            type: 'select',
            options: {
              listItems: this.user.groupOccupation
            }
          },`
사용시 listItems에 매칭되는 경우가 없을때 placehorder 처럼 값을 띄우고 싶은데 defaultValue는 사용 불가능 한가요?

**Comment by js87zz** [comment]
@sejin-v 
Please make sure you have filled out issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied.
