### ISSUE TITLE
혹시 숫자형을 금액표시 콤마(,) 찍을 방법은 없나요?

### ISSUE THREAD

**Issue by gana21** [nhn/tui.grid#1282]
숫자형 데이터를 grid 에 표시할때 세자리수 마다 금액 콤마 찍는 formatter 같은건 없을까요?
예제)
250000000 >>> 250,000,000

**Comment by sejin-v** [comment]
formatter 없던데요ㅜㅜ
저는 그래서 @afterChange에서 바뀔때 그값을 
 this.$refs.grid.invoke(
            'setValue',
            rowNo,
            columnsName,
            Number(changeValue ).toLocaleString()
          );
이런식으로 직접 바꿔서 셋팅했어요

**Comment by gana21** [comment]
> columnsName

아.. 역시 없군요 ㅠ 
감사합니다. 그런데 제가 javascript 초보라 그런데 혹시 위에 말씀하신 invoke 함수를 어느 지점에 넣어야 할까요? ㅠ

제꺼 script 내용이 
`	// GRID 를 보여준다.
	var grid = new tui.Grid({
		el: document.getElementById('grid'),
		scrollX: true,
		scrollY: true,
		rowHeight: 20,
		bodyHeight: 550,
		data: dataSource,
		rowHeaders: [
			'rowNum',
			{
			type: 'checkbox',
			header: '<label for="all-checkbox" class="checkbox"><input type="checkbox" id="all-checkbox" class="hidden-input" name="_checked" /><span class="custom-input"></span></label>'
			}
		],
		header: {
			height: 35
		},
		columns: [
			{
				header: '구분',
				name: 'ty',
				width: 130,
				editor: 'text',
				sortingType: 'desc',
				sortable: true
			},
			{
				header: '코드',
				name: 'code',
				width:160,
				sortingType: 'desc',
				sortable: true
			},
			{
				header: '명칭',
				name: 'sj',
				editor: 'text',
				width:180,
				sortingType: 'desc',
				sortable: true
			},
			{
				header: '규격',
				name: 'standard',
				editor: 'text',
				width:200 ,
				sortingType: 'desc',
				sortable: true
			},
			{ header: '단위', name: 'unit', editor: 'text', width:100 },
			{ header: '입고단가', name: 'input_cost', editor: 'text', width:120, validation:{dataType: 'number', required:false, min:0} },
			{ header: '출고단가', name: 'output_cost', editor: 'text', width:120, validation:{dataType: 'number', required:false, min:0} },
			{ header: '적정재고', name: 'stock', editor: 'text', width:120, validation:{dataType: 'number', required:false, min:0} },
			{ header: '비고', name: 'comment', editor: 'text' }
		],
      summary: {
        height: 40,
        position: 'bottom', // or 'top'
        columnContent: {
          input_cost: {
            template: function(valueMap) {
              return `${valueMap.sum}`;
            }
          },
          output_cost: {
            template: function(valueMap) {
              return `${valueMap.sum}`;
            }
          },
          stock: {
            template: function(valueMap) {
              return `${valueMap.sum}`;
            }
          }

        }
      },
		columnOptions: {
			resizable: true
		}
		
	});`

이렇게 작성되어있습니다. 감사합니다 ㅠ

**Comment by sejin-v** [comment]
저는 좀 다른 형태로 써서  도움이 될지 모르겠는데 
저렇게 사용하실거면 template에서 <grid ref="grid"  @afterChange="changeMethod" >에

method:{
changeMethod(changeData){
       const changeValue = changeData.changes[0].value;
      const changeRowKey = changeData.changes[0].rowKey;
      const changeColumns = changeData.changes[0].columnName;
        this.$refs.grid.invoke('setValue', changeRowKey, changeColumns,Number(changeValue ).toLocaleString() );
}
}

이런식으로 사용했어요 

근데 저렇게하면 문자열로 인식되니까 summary가안되기 때문에 다시 뽑아서 합계구하는 method를 만들어야하더라구요,...

**Comment by js87zz** [comment]
@gana21 @sejin-v 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
The [custom render](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) should be helpful to you.
