### ISSUE TITLE
Is it possible "Search Row"? 

### ISSUE THREAD

**Issue by diana8282** [nhn/tui.grid#1284]
**Summary**
Does this grid support the "Search row" function?

**Screenshots**
Grid currently in use.
![image](https://user-images.githubusercontent.com/80510505/110908537-4dc14200-8352-11eb-8050-9f4734a3336b.png)

I want to this function.
The filter is applied based on the input box text. It is possible even if the page is changed, such as page 1, page 2, etc.
타사 그리드입니다.  input box에 입력한 내용을 기반으로 filter가 적용됩니다.
1페이지, 2페이지 등 페이지 변경이 되어도 가능합니다.
![image](https://user-images.githubusercontent.com/80510505/110909256-3cc50080-8353-11eb-9531-c699dd1579f4.png)

**Version**
4.16.1

**Additional context**
I want that function.
Can I implement such a function?

--
Like the second image, is there a text input box that can be searched in the grid, and is there a function that can apply in the input text to the filter?
If possible, please give me a guide on how to use that.
두번째 이미지처럼 그리드 내에 검색이 가능한 text input box가 있고, 입력한 정보를 바로 필터에 적용시킬 수 있는 기능이 있나요?? 가능하다면 어떻게 사용하면 되는지 가이드 부탁드립니다.

**Comment by js87zz** [comment]
@diana8282 
Currently, we do not support it.
