### ISSUE TITLE
Is there any feature that can set ui Grid column width by header and content?

### ISSUE THREAD

**Issue by 13461819** [nhn/tui.grid#1286]
columns[].width = "auto"
이렇게 설정해놓으면 컬럼 넓이가 content에 맞게 조절되면서 header가 짤려서 나와요.
sortingType이랑 filter가 모두 다 설정되어있어 header 크기가 제법 되는데, content가 공백이거나 길이가 짧으면 header가 짤리네요.

혹시 header랑 content랑 둘 중 더 긴 넓이에 맞게 column width를 조절하는 방법이 있을까요?
header에는 다국어 처리가 되어있어 setWidth()나 minWidth 등의 고정 넓이는 사용할 수 없습니다.

**Comment by js87zz** [comment]
@13461819 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
And Can you give us detail code in code sandbox or jsfiddle?

**Comment by 13461819** [comment]
https://jsfiddle.net/vjnwd3r2/1/
Here is my fiddle sample.
But for some reason, it doesn't working; column[].width: "auto"

In my case(it works), column "CCCCC"'s width becomes fits the content "c" and too short to show "sort, filter icon"
I want to set width → MAX(Header Text, Content) not MAX(Content)

**Comment by js87zz** [comment]
@13461819 
If the grid width is fixed, the width of each column is distributed to fit the grid width unless specified as pixels.
Can't the width of each column be adjusted to fit the header size?
