### ISSUE TITLE
Copy시 CopyOptions-customValue에 설정한 함수가 적용되지 않음.

### ISSUE THREAD

**Issue by tmdtn1608** [nhn/tui.grid#1287]
**Describe the bug**

**To Reproduce**
최소 3 column 이상의 grid를 생성.
CopyOptions - customValue로 데이터를 변경하는 함수를 설정.
그리드에 데이터 2 column 이상의 데이터를 copy하여 엑셀에 붙여넣기한 후 확인.

**Expected behavior**
선택한 셀의 모든 데이터가 customValue에 설정된 함수에 따라 변경된 값이 출력

**Screenshots**
* grid
![bug_grid](https://user-images.githubusercontent.com/23470138/111960680-617b5e00-8b33-11eb-8c99-705fc6096e1f.png)
* excel. customValue로 html 태그를 제거하는 함수를 입력하였으나 카피영역이 시작하는 셀은 적용되지 않았음. 이전 셀을 선택했을경우에 적용됨.
![bug_excel](https://user-images.githubusercontent.com/23470138/111960962-c33bc800-8b33-11eb-8ed4-4683aea4c068.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 89.0.4389.90

**Comment by tmdtn1608** [comment]
grid 작성시 
`rowHeaders: ['rowNum']`
를 추가했을경우 발생되는것 확인.
rowHeaders 추가시 getTextWithCopyOptionsApplied에서 첫번째 선택한 셀의 값을 가지고 오지 못하는것을 확인.

**Comment by js87zz** [comment]
@tmdtn1608 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.
And Can you give us detail code in code sandbox or jsfiddle?
