### ISSUE TITLE
Unselecting all filters creates misaligned columns

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#1288]
**Description**
When we implement filters on tables that have _scrollX = true_ and has a color theme, when we unfilter all values of any filter column we get broken columns on scrolling to the extreme right side!

**Expected behavior**
Columns to not break when no data is present

**Codesandbox link**
I have reproduced the bug here: https://codesandbox.io/s/eloquent-snow-5iuzk.
I have enabled horizontal scroll and have implemented filter on the first column. On unselecting "Select All" option, and scrolling to the right, you can observe the behaviour

**Screenshots!**
![Screenshot from 2021-03-23 21-59-01](https://user-images.githubusercontent.com/52497530/112182161-0d4fa700-8c23-11eb-8e88-0b262faaf671.png)
![Screenshot from 2021-03-23 21-58-59](https://user-images.githubusercontent.com/52497530/112182174-104a9780-8c23-11eb-8cf3-7c266211223c.png)

**Desktop:**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Chrome
 - Version: Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by js87zz** [comment]
@SanjaySankar 
I checked the issue.
I'm currently working on another project, so I have not spent enough time in the bugs of the grid. In the middle of April, some bugs will be fixed, including the bugs you posted. Thanks for the report.

**Comment by js87zz** [comment]
@SanjaySankar 
This bug has been fixed in `v4.17.0`. Thanks!
