### ISSUE TITLE
change column and header color react grid 

### ISSUE THREAD

**Issue by eomsungryul** [nhn/tui.grid#1290]
hi 
According to the doc,

The wrapper component does not provide a way to call static methods of TOAST UI Grid. If you want to use static methods such as applyTheme or setLanguage you should use it via importing tui-grid directly.

in conclusion  react grid is not change colunm color and header color. 

can you show me tui-grid directly example? use react grid and tui-grid

**Comment by js87zz** [comment]
You can call static method like as below with react wrapper.
```js
import TuiGrid from 'tui-grid';
// ...

TuiGrid.applyTheme('striped');
// ...
```

link: https://github.com/nhn/tui.grid/tree/master/packages/toast-ui.react-grid#static-methods

**Comment by eomsungryul** [comment]
thx. In my case npm issue... reinstall it works fine.
