### ISSUE TITLE
열 고정 후 스크롤시 왼쪽 , 오른쪽 렌더링 매칭이 느린 문제

### ISSUE THREAD

**Issue by joonhyeokc** [nhn/tui.grid#1291]
그리드의 열 고정 옵션을 사용 했을 경우 스크롤 할 때 왼쪽(고정된) 데이터들과 오른쪽 데이터가 느리게 맞춰지는 현상 때문에 질문 드립니다.
왼쪽은 렌더링이 빠릿한데 오른쪽은 렌더링이 좀 느려서 그런듯..
스크롤 때마다 mouse hover 이벤트가 발생해서 그런거 같은데, 혹시 호버기능 자체를 없앨 수는 없을까요?

**Comment by js87zz** [comment]
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied. 

The browser engine cannot sync the scroll perfectly.
We know the this problem and have the plan for syncing the scroll between left and right area.
But current DOM structure should be totally changed and it probably won't be solved in a short time.
The next major version schedule is not decided yet.
