### ISSUE TITLE
 I want to block inquiry.(Grid)

### ISSUE THREAD

**Issue by GoMuggi** [nhn/tui.grid#1292]
Whenever I open the screen, it can be viewed immediately. I want to know how to prevent it. What should I do?

**Comment by js87zz** [comment]
@GoMuggi 
You need to give more detail information to us.

**Comment by GoMuggi** [comment]
I am using Tui-grid.
When you open the page with the grid applied, it seems to automatically become ReadData. Is there a way to prevent ReadData at first start up??

**Comment by GoMuggi** [comment]
> @GoMuggi
> You need to give more detail information to us.

I am using Tui-grid.
When you open the page with the grid applied, it seems to automatically become ReadData. Is there a way to prevent ReadData at first start up??
