### ISSUE TITLE
function error when applying filter(select)

### ISSUE THREAD

**Issue by MammothCo2** [nhn/tui.grid#1294]
### **Summary**
I contacted you because there was a problem with the filter part.
Individual selection is possible as shown in the screenshot, but multiple selections are not possible.

### **Screenshots**
-- possible
![image](https://user-images.githubusercontent.com/81662608/113096283-dafc0600-922f-11eb-8dd5-a3182d019e26.png)
![image](https://user-images.githubusercontent.com/81662608/113096473-30d0ae00-9230-11eb-9c6d-079bfb705962.png)  ![image](https://user-images.githubusercontent.com/81662608/113096602-72f9ef80-9230-11eb-9173-95061f3cd0f6.png)

-- impossible
![image](https://user-images.githubusercontent.com/81662608/113097218-7f327c80-9231-11eb-98c1-e5a3e68d49f7.png)
![image](https://user-images.githubusercontent.com/81662608/113097273-91141f80-9231-11eb-83cc-974c2a004ad9.png)

### **Version**
operating system : windows 10
browser : Chrome 버전 89.0.4389.90(64bit)
TUI Grid : v4.10.0

### **context**
It receives data into a 'dataset' and spread it across the grid.
![image](https://user-images.githubusercontent.com/81662608/113101794-1dc1dc00-9238-11eb-8822-dbe66d80d70f.png)

If you look below, the data is received in json format.
![image](https://user-images.githubusercontent.com/81662608/113095570-9e7bda80-922e-11eb-9dae-b9cc33e3eb1a.png)

Is it possible to grasp the situation with the current information?
Please answer. Thank you.

**Comment by js87zz** [comment]
@MammothCo2 
Multi-selection of the `select` filter works well as shown below.
![2021-04-02 11-06-46 2021-04-02 11_06_59](https://user-images.githubusercontent.com/37766175/113372433-ac9f3780-93a3-11eb-8828-e7049514b3d5.gif)

It is better to give the detailed code in code sandbox or jsfiddle.

**Comment by MammothCo2** [comment]
Thank you for answer.
First off, every time I filter data from the grid, I don't get the data from the server.
Data is fetched from the server on lookup.
After that, when filtering, you filter by the retrieved data.
After checking a little more, I will ask you again.
Thank you. Have a nice day.
