### ISSUE TITLE
When clicking on a filter, filter windows all do not appear.

### ISSUE THREAD

**Issue by MammothCo2** [nhn/tui.grid#1295]
### **Summary**
When you click on a filter as shown below, part of the filter window does not appear.
Is there a solution? If you have a solution, please answer.
Thank you.

### **Screenshots**
![image](https://user-images.githubusercontent.com/81662608/113112515-3637f380-9244-11eb-85e3-61c682a3de74.png)

### **Version**
운영체제 : Linux 18.04.5
브라우저 : Chrome 버전 87.0.4280.88
TUI 그리드 : v4.16.1

**Comment by js87zz** [comment]
@MammothCo2 
If the screen is small, it seems to be cut off. 
This is the bug and should be fixed. Thanks for your contributing!

**Comment by MammothCo2** [comment]
Thank you for the answer.
Do you have any plans to modify it?
If you have a plan, when do you plan to modify it?
Please answer. Thank you.

**Comment by js87zz** [comment]
@MammothCo2 
This bug has been fixed in `v4.17.0`. Thanks
