### ISSUE TITLE
Question in ASP.NET

### ISSUE THREAD

**Issue by crazydrum** [nhn/tui.grid#1296]
안녕하세요.

ASP.NET에 TOAST GRID를 올려 테스트 하던 중, 문의사항이 발생하여 남겨봅니다.

ASPX 파일 생성 후, 프론트에 Grid Tree 관련 예제를 실행하였을 때,

트리가 펼쳐지도록 버튼을 누르면 PostBack이 발생하여 이를 방지하고자 하는데,

옵션 여부나, 혹은 해당 이벤트 부분을 설명 부탁드려 봅니다.

직접 수정하여 사용해야 한다면 그리 하겠습니다.

감사합니다.

--------------------------------------------------------------------------------------------

Hello.

During testing by uploading TOAST GRID in ASP.NET, an inquiry arises and I leave it.

After creating the ASPX file, when executing the Grid Tree related example in the front,

I want to prevent this by causing PostBack when the button is pressed to expand the tree.

Please explain the option or the event part.

If you need to modify and use it yourself, I will.

Thank you.

**Comment by js87zz** [comment]
@crazydrum 
It's hard to give a definite answer because I'm not familiar with ASP.NET.. Can you show me exactly what the problem is by image or video?

**Comment by crazydrum** [comment]
I have prepared 2 screenshots for explanation.
When you click the button, you can see that the page-reload occurs as shown in the attachment and is caught at the break point. In this case, screen initialization will continue to occur and normal operation will not be possible.
![click it](https://user-images.githubusercontent.com/25650350/113526973-eb78fb80-95f6-11eb-94ab-ee7671a33e3f.jpg)
![break point to page_load](https://user-images.githubusercontent.com/25650350/113526975-ef0c8280-95f6-11eb-893c-f4eb8310215c.jpg)
