### ISSUE TITLE
how about grid readData block 

### ISSUE THREAD

**Issue by GoMuggi** [nhn/tui.grid#1299]
I am using Tui-grid.
When you open the page with the grid applied, it seems to automatically become ReadData. Is there a way to prevent ReadData at first start up??

**Comment by js87zz** [comment]
@GoMuggi 
Try to add 
```js
const grid = new Grid({
  data: {
    api: {
        // ...
    },
    // add this option
    initialRequest: false,
  },
  columns,
  // ...
})
```
