### ISSUE TITLE
How can I specify a Custom Renderer for Column value in Json format?

### ISSUE THREAD

**Issue by yongje1204** [nhn/tui.grid#1300]
어떻게 하면 Json형식으로 Column값의 커스텀 렌더러를 지정할 수 있습니까??

저는 Json형식으로 Toast grid의 컬럼을 지정했는데, 커스텀 렌더러를 지정한 부분은 동작하지 않습니다.
I specified the column of the Toast grid in Json format, but only the part where the custom renderer was specified does not work.

setColumn 메소드로 지정해보아도 지정되지 않는데 Json형식으로는 어떻게 커스텀 렌더러를 지정할 수 있나요?
It is not specified even if it is specified with the setColumn method. How can I specify a custom renderer in Json format?

참고로 커스텀 렌더러는 function과 prototype로 구현했습니다
For reference, the custom renderer is implemented as a function and prototype.

**Comment by js87zz** [comment]
@yongje1204 
It's hard to know the exact problem.
Please give us the detailed code.

**Comment by yongje1204** [comment]
When specifying a column in JSON format, the type value of the renderer is surrounded by ", so the function of the custom renderer cannot be recognized.

It would be convenient if you could format each column with the grid's method!

I'm sorry for not having the sauce right now
