### ISSUE TITLE
Highlight 질문 입니다.

### ISSUE THREAD

**Issue by 9yh** [nhn/tui.grid#1301]
JqGrid를 Toast Grid로 전환 중 입니다.

셀을 선택하면 선택된 셀의 행을 하이라이트로 표현하려고 합니다.
하이라이트가 적용된 셀을 다시 선택하면 행의 하이라이트를 해제 하는 것입니다.

아래와 같이 focusChange 이벤트핸들러를 작성하여 하이라이트를 적용해봤습니다.

특정 행의 셀을 선택하면 하이라이트가 적용되는것은 확인되었으나 동일한 셀을 다시 선택하면 focusChange 이벤트가 발생하지 않아 적용된 하이라이트가 해제되지 않습니다.

click 이벤트핸들러에 구현을 해보았지만 이 경우 RowHeader 체크박스의 check 이벤트핸들러가 호출되지 않는 현상이 있었습니다.

어떤 이벤트핸들러에 구현을 해야 원하는 작업이 될지 궁금해서 질문 합니다.

var selectedRowKeys = new Set();
grid.on('focusChange', (ev) => {
    var rowKey = ev.rowKey;
    if (selectedRowKeys.has(rowKey)) {
        grid.removeRowClassName(rowKey, 'highlight');
        selectedRowKeys.delete(rowKey);
    } else {
        grid.addRowClassName(rowKey, 'highlight');
        selectedRowKeys.add(rowKey);
    }
});

**Comment by js87zz** [comment]
@9yh 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@9yh 
Try as below.
```js
grid.on('click', (ev) => {
  var rowKey = ev.rowKey;
      
  if (ev.columnName !== '_checked') {
    if (selectedRowKeys.has(rowKey)) {
      grid.removeRowClassName(rowKey, 'highlight');
      selectedRowKeys.delete(rowKey);
    } else {
      grid.addRowClassName(rowKey, 'highlight');
      selectedRowKeys.add(rowKey);
    }
  }
});
```
