### ISSUE TITLE
rowHeight : 'auto' is not  applicable when I attach image file in the rows

### ISSUE THREAD

**Issue by enyoung4141** [nhn/tui.grid#1307]
The option rowHeight: 'auto' is applied well in my project . 
![general](https://user-images.githubusercontent.com/82195944/114639725-7fd71280-9d09-11eb-98e8-f31b386c9887.png)

However, the thing I want to do is put the image files in the column to show it like small thumbnail.
But when I add images, the rowNum header's height does not follow the row height of the other columns like this.
![image](https://user-images.githubusercontent.com/82195944/114639794-a85f0c80-9d09-11eb-9a04-c9c7daa92679.png)

My source code is here.
![image](https://user-images.githubusercontent.com/82195944/114639860-d17f9d00-9d09-11eb-9511-637aaa5d424b.png)

And i am using this CDN now.
<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css"/>
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>

**Comment by js87zz** [comment]
@enyoung4141 
When i test as you commented, the height has been adjusted properly.

![스크린샷 2021-04-14 오전 10 52 32](https://user-images.githubusercontent.com/37766175/114642898-a13afd00-9d0f-11eb-84e2-b59b369ea4a6.png)

Can you implement your code in [code sand box](https://codesandbox.io/) or [jsfiddle](https://jsfiddle.net/)?

**Comment by enyoung4141** [comment]
I uploaded it in jsfiddle. Please check here https://jsfiddle.net/Ljn34dzv/35/

Thanks!

**Comment by js87zz** [comment]
@enyoung4141 
The example is well worked in chrome.

![스크린샷 2021-04-14 오전 11 48 06](https://user-images.githubusercontent.com/37766175/114647014-4b6a5300-9d17-11eb-92e0-e308bee5dbe8.png)
