### ISSUE TITLE
editor datePicker의 timepicker만 사용하도록 설정할 수 있나요?

### ISSUE THREAD

**Issue by silvercoin99999** [nhn/tui.grid#1308]
![timepicker](https://user-images.githubusercontent.com/53526963/114649944-5d9ac000-9d1c-11eb-8571-f93a474cac29.PNG)

timepicker를 datePicker의 옵션이 아닌
timepicker만 따로 사용할 수 있는 방법이 있을까요?

**Comment by js87zz** [comment]
@silvercoin99999 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied

**Comment by js87zz** [comment]
@silvercoin99999 
Currently we don't support it. Thanks!
