### ISSUE TITLE
Can I put a check box in the column header?

### ISSUE THREAD

**Issue by yongje1204** [nhn/tui.grid#1315]
I don't want to use the row header feature because it fixes the position of the cell.

I want this.
![image](https://user-images.githubusercontent.com/63336689/114995066-6637f580-9ed8-11eb-8efa-b57c840da0e4.png)

But TUI Grid is..
![image](https://user-images.githubusercontent.com/63336689/114995132-78199880-9ed8-11eb-8ff7-974eafd64296.png)

How can I add a checkbox and add functionality to the header without using the row header feature?

**Comment by Apoerin** [comment]
I have the same question

**Comment by Apoerin** [comment]
@yongje1204 I found a solution. You can use rowHeader, just give your column header `name: '_checked'`

**Comment by yongje1204** [comment]
@Apoerin Thanks for answering.
But it's fixed in the first column. I want to use it in a different column.

**Comment by Apoerin** [comment]
@yongje1204 like this?
![aa](https://user-images.githubusercontent.com/44097858/115362034-70e8d800-a1c1-11eb-80ba-de22d31fd399.png)

**Comment by yongje1204** [comment]
@Apoerin Oh! Yes! I Want It!!

**Comment by Apoerin** [comment]
@yongje1204 so take `rowHeader` code and do this in a column you need
`{
      type: 'checkbox',
      name: '_checked',
      header:  `
      <label for="all-checkbox" class="checkbox">
        <input type="checkbox" id="all-checkbox" class="hidden-input" name="_checked" />
        <span class="custom-input"></span>
      </label>
    `,
      renderer: {
        type: CheckboxRenderer,
      }`
Not sure how to put text near checkbox

**Comment by yongje1204** [comment]
@Apoerin Thank you so much!
I'll try it!

**Comment by bso-oo** [comment]
> @yongje1204 like this? ![aa](https://user-images.githubusercontent.com/44097858/115362034-70e8d800-a1c1-11eb-80ba-de22d31fd399.png)

f you don't mind, can I see the code for this picture? I can't apply the check box to the cell.

**Comment by Apoerin** [comment]
@bso-oo sorry, this project is abandoned and I don't have a code anymore
