### ISSUE TITLE
페이지 메소드와 기타 여러 문제

### ISSUE THREAD

**Issue by nomidev** [nhn/tui.grid#1317]
**Summary**

새로 프로젝트 하면서 tui-grid를 도입했는데 몇가지 문제가 있어 질문 드립니다.

1. 문서의 콜백 사용하기 부분의 이벤트를 삽입하면 아래와 같은 에러가 납니다. 
'successResponse'이벤트를 제거하면 에러는 없어지네요

```javascript
bootstrap:253 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at assign (bootstrap:253)
    at bootstrap:259
    at Array.forEach (<anonymous>)
    at assign (bootstrap:253)
    at bootstrap:259
    at Array.forEach (<anonymous>)
    at assign (bootstrap:253)
    at bootstrap:259
    at Array.forEach (<anonymous>)
```

2. ajax로 데이터 로드 후 totalCount를 보여주기 위해 grid.getPaginationTotalCount() 호출하면
첫번째 콜에서는 제대로 보여지지 않고 한번 더 콜을 해야 보여집니다.
getPagination() totalItems는 정확히 보이지만 값은 undefined로 나옵니다.

1. 프로젝트 전체를 vue.js로 하지 않고 DOM 이벤트와 Data 정도만 사용하려고 역시 CDN으로 넣어서 사용 중 입니다.
Vue.js mounted 훅 안에서 Vue.js data에 그리드 인스턴스를 만들면 전체 행을 체크하거나 첫번째 행에 컬럼을 편집하면 브라우저가 죽어버립니다.
결국 Vue.js에서 걷어냈는데요 혹시 무엇때문인지 아실까 해서...

**Comment by js87zz** [comment]
@nomidev 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by js87zz** [comment]
@nomidev 
Please give us a detailed screenshot and code for each issue. This information alone is difficult to reproduce.
