### ISSUE TITLE
tui-grid-layer-focus incorrect height

### ISSUE THREAD

**Issue by attyskater** [nhn/tui.grid#1318]
**Describe the bug**
tui-grid-layer-focus incorrect height

**To Reproduce**
If you insert multi-line text , the row height scales correctly, while if you click on the cell the tui-grid-layer-focus div is wrong in height. See example here: [https://jsfiddle.net/1fencg0w/](https://jsfiddle.net/1fencg0w/)

**Expected behavior**
When clicking on the cell, the height of the focus div must be the same as the original row.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - v4.16.1

**Comment by attyskater** [comment]
Ok I found the problem, setting rowHeight: 'auto' works, otherwise it doesn't.

**Comment by js87zz** [comment]
@attyskater 
You're right!
The height is resized automatically with `rowHeight: 'auto' ` option.
Because there are disadvantages in performance, without this option, height is not adjusted.

**Comment by attyskater** [comment]
@js87zz 
I don't understand how it works though... If you in the example put rowHeight: 60 and there are carriage returns in the text, it resizes the height of the focus but the line stays higher. This causes a graphical problem for selecting/editing rows. If one fixes the row height wouldn't one have to cut the content?
Another strange thing on the documentation is that the default value is 'auto' but as you can see on the jsfiddle example is not so.
Thanks for your help
