### ISSUE TITLE
Select with options  in Column Header 

### ISSUE THREAD

**Issue by Apoerin** [nhn/tui.grid#1319]
I want to have a select menu with options in Column header with custom checkbox like here. Is it possible?

![ss](https://user-images.githubusercontent.com/44097858/115370576-7a763e00-a1c9-11eb-81f2-1e220b9526c8.png)

<img width="119" alt="114699883-24188380-9d21-11eb-814f-e418095ebb5a" src="https://user-images.githubusercontent.com/44097858/115371068-f40e2c00-a1c9-11eb-9e18-391e82207e35.png">

TOAST UI Grid
 @version 4.16.1

**Comment by js87zz** [comment]
@Apoerin 
You can implement it through [custom column header](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-column-header.md).
However, this can be complicated and difficult to communicate with other cell data.
