### ISSUE TITLE
The pickers are obscured by the splitter.

### ISSUE THREAD

**Issue by xman2310** [nhn/tui.grid#1320]
The pickers are obscured by the splitter.
How do you solve it?

![image](https://user-images.githubusercontent.com/78667784/115400935-c99d8c80-a224-11eb-84f2-ab8a9819c173.png)

**Comment by js87zz** [comment]
@xman2310 
Can you give us your example in jsfiddle or code sandbox?

**Comment by xman2310** [comment]
https://stackblitz.com/edit/angular-simulation-z94kxb?file=app%2Fwidgets%2Fgrid%2Fgrid.component.ts

**Comment by js87zz** [comment]
@xman2310 
This is not our issue. 
Try to adjust the `overflow` or `z-index` of the splitter.

**Comment by xman2310** [comment]
The 'datePicker' and 'select' types were resolved as follows.


.tui-datepicker {
  position: fixed !important;
  z-index: 2000;
}

.tui-select-box-dropdown {
  position: fixed !important;
  border: 1px rgb(170, 170, 170) solid !important;
  width: auto !important;
  z-index: 2000;
}

.tui-grid-editor-select-box-layer li {
  padding: 0 50px 0 8px !important;
}



However, the'checkbox' and'radio' types could not be resolved.
