### ISSUE TITLE
Method "getFormattedValue(rowKey, Name)" Doesn't work in 4.16.1

### ISSUE THREAD

**Issue by yongje1204** [nhn/tui.grid#1321]
It has been confirmed to work in version 4.14, but not in 4.16.1.
Has the method been deleted or changed?

[in 4.14]
![image](https://user-images.githubusercontent.com/63336689/115480805-3d23b600-a286-11eb-92ed-6b97b09867cf.png)
it does work

[in 4.16.1]
![image](https://user-images.githubusercontent.com/63336689/115480743-1b2a3380-a286-11eb-896b-e441f9e1f17b.png)
It doesn't work

These two are exactly the same source.

**Comment by js87zz** [comment]
@yongje1204 
There seems to be no problem with the grid. 
Can you try to check `this.grid` context?

**Comment by yongje1204** [comment]
When I run getValue in the same way it works, but when I run getFormattedValue it doesn't work.

![image](https://user-images.githubusercontent.com/63336689/115498033-bf70a200-a2a7-11eb-8b59-f7fd5ecda247.png)

![image](https://user-images.githubusercontent.com/63336689/115498101-e333e800-a2a7-11eb-9a42-d723dccb1e97.png)

Do those two methods behave differently?
I don't know how to provide the source because it is created separately as a js file to create and operate the grid.

**Comment by js87zz** [comment]
@js87zz 
The example code that your grid configuration code and calling `getFormattedValue` API code in [jsfiddle](https://jsfiddle.net/) or [code sandbox](https://codesandbox.io/).

**Comment by yongje1204** [comment]
https://jsfiddle.net/jewazmv6/

It doesn't seem to work on fiddle either

**Comment by js87zz** [comment]
@yongje1204 
You use wrong cdn url. Try to change the url as below.
`https://uicdn.toast.com/grid/latest/tui-grid.css`
`https://uicdn.toast.com/grid/latest/tui-grid.js`

**Comment by yongje1204** [comment]
@js87zz 
Wow... it's resolved... Thank you! And sorry.. ㅠㅜ
