### ISSUE TITLE
Select box editor with a large amount of values does not permit viewing/selecting

### ISSUE THREAD

**Issue by joebordes** [nhn/tui.grid#1331]
**Describe the bug**

If the list of select options is very large the editor shows a partial set and does not permit scrolling

https://jsfiddle.net/cd2kmvjL/1/

**To Reproduce**
1. Go to https://jsfiddle.net/cd2kmvjL/1/
2. DoubleClick on the only cell that is there
3. See the error

**Expected behavior**

Not quite sure what I would expect here as the list is very big it may be a good idea to have some other type of editor for this situation, but at least we should have a smaller/contained select box and be able to scroll through the options and select one.

**Comment by js87zz** [comment]
@joebordes 
This issue has been fixed in `v4.17.0` yesterday. Thanks!

**Comment by joebordes** [comment]
Yes!  It works now. Thanks!
