### ISSUE TITLE
The area you can select is outside the actual area.

### ISSUE THREAD

**Issue by hhs9102** [nhn/tui.grid#1332]
**Describe the bug**
Change the hidden column to showColumn.
The area you can select is outside the actual area.

**To Reproduce**
https://jsfiddle.net/phb5vkto/2/

Steps to reproduce the behavior
1. Press the control column button.
2. Click the test2 column box area.
-> The contents of the bug are shown.

**Expected behavior**
Only the real area should be clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/12446405/116043927-40b2a500-a6ab-11eb-8d6d-bfbaa1559e4f.png)

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : chrome

**Additional context**
grid.refreshLayout(); is not working.
(Defined under toggleClick function.)

**Comment by js87zz** [comment]
@hhs9102 
I checked the issue. 
I will fix it. Thanks!

**Comment by hhs9102** [comment]
@js87zz 
Can you tell me roughly how long it will take to release after modifying it?

**Comment by js87zz** [comment]
@hhs9102 
The bug has been fixed in `v4.18.0`. Sorry for the late fix.
