### ISSUE TITLE
Tables disappear when I move rows

### ISSUE THREAD

**Issue by Apoerin** [nhn/tui.grid#1338]
I have a function which moves checked rows from one table to another. 
```
function moveToSecondGroup() {
  secondMainGrid.appendRows(getCheckedRows());
  firstMainGrid.removeCheckedRows();
  firstMainGrid.uncheckAll();
  secondMainGrid.uncheckAll();
}
```
However, when I want to move all checked rows from table it makes my other tables disappear like on screenshot.
I have 3 tables positioned one under another and yellow/grey ones have hidden headers.
![prob2](https://user-images.githubusercontent.com/44097858/116682972-44963e00-a9af-11eb-84c2-57aba2570af7.png)

I tried this solution and it works.
```
function moveToSecondGroup() {
  secondMainGrid.appendRows(getCheckedRows());
  firstMainGrid.removeCheckedRows();
  if (firstMainGrid.getRowCount() == 0) {
    firstMainGrid.appendRow('');
  }
  firstMainGrid.uncheckAll();
  secondMainGrid.uncheckAll();
}
```

but maybe there's another one I can use to keep yellow/grey tables under that main table without adding an empty/dummy row to white table?

 TOAST UI Grid
 @version 4.16.1

**Comment by js87zz** [comment]
@Apoerin 
It's complicated case🧐. 
It's hard to understand to add a dummy for keeping the data.
Could you give me the application code in code sandbox or jsfiddle? 

Are you using this structure because you want to group data?
