### ISSUE TITLE
Selecting a date after filtering results in an error

### ISSUE THREAD

**Issue by handslm** [nhn/tui.grid#1340]
when i filtering grid, selecting date is in error.
And grid also in error.
I have attached a video.

https://user-images.githubusercontent.com/71375862/116833795-2a01d600-abf6-11eb-89d7-51c8941eb749.mp4

**Comment by js87zz** [comment]
@handslm 
Could you give me the your code in code sandbox or jsfiddle?
It is difficult for us to reproduce the all situation.
