### ISSUE TITLE
When pagination is applied, the focus option of appendRow does not work.

### ISSUE THREAD

**Issue by yongje1204** [nhn/tui.grid#1341]
https://jsfiddle.net/yfvnzs3e/9/
1. click the Add button ( The Add button has the option of adding and focusing a row.)
2. If the page turn during append, the focus option does not work.

Is this normal behavior?
If this is normal, is there any way to focus when the page is turned?

**Comment by js87zz** [comment]
@yongje1204 
Currently, the grid cannot focus the new cell unless the appended row is on the same page.
I think there will be more users who don't want this operation. We'll discuss the issue internally.
