### ISSUE TITLE
How Can I insert Fileupload And FileLink controll in cell?

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1344]
hello, 

i want to input **Fileupload And FileLink function in cell.** 

How can i do that?

below is example.

![image](https://user-images.githubusercontent.com/81946046/116948127-87129000-acb9-11eb-8adb-66b2c8669174.png)

**Comment by js87zz** [comment]
@jsw-coder 
[This tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-renderer.md) will be helpful to you
