### ISSUE TITLE
Select Filter does not working on IE11

### ISSUE THREAD

**Issue by winnever** [nhn/tui.grid#1345]
Filter example page에서 Artist 컬럼의 Filter를 클릭시 그림과 같은 오류가 발생합니다.
Chrome 에서는 정상 작동하며, IE11에서 오류가 발생하는 것으로 보입니다.

IE11에서 사용 가능하도록 조치할 수 있는 방법이 있을까요?

감사합니다.

![image](https://user-images.githubusercontent.com/83747682/117248509-0ef3c800-ae7b-11eb-8155-b6777b96225a.png)

![image](https://user-images.githubusercontent.com/83747682/117248386-d81db200-ae7a-11eb-8b20-e29dceed22b9.png)

OS: Window 7

Browser: Internet Exploler 11

@toast-ui-grid: 4.17.0

**Comment by js87zz** [comment]
@winnever 
Please make sure you have filled out issue respecting our form **in English**. If not, the issue will be closed or not replied.
The issue has been checked and it will be fixed.

**Comment by js87zz** [comment]
@winnever 
The issue has been fixed in `v4.17.1`. Thanks!
