### ISSUE TITLE
I want sample by using django. 

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1349]
hello, i am making board by using django. 

but i don't know, how can i display DB data to grid. 

is there any sample what i refer?

**Comment by js87zz** [comment]
@jsw-coder 
Try to use [resetData](https://nhn.github.io/tui.grid/latest/Grid#resetData) API or [dataSource](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md)
