### ISSUE TITLE
그리드 rowkey 가 null로 세팅되는 문제 해결방법 문의

### ISSUE THREAD

**Issue by dvlmal** [nhn/tui.grid#1353]
그리드 생성 후 getValue를 위해 rowkey를 확인하니 rowke가 null로 세팅되어 작업할 수가 없는데
코딩을 잘못한건지 해결방법이 있는지 알고 싶습니다.

- render 소스
`class chkboxRender {
	constructor(props) {
		const el = document.createElement("input");
		const { grid, rowKey, columnInfo } = props;
		el.type = "checkbox";
		el.checked = Boolean(props.value);

		el.addEventListener('click', (ev) => {
			if(el.checked) {
				el.value = false;
				grid.setValue(rowKey, columnInfo.name, el.value);
			}
			else {
				el.value = true;
				grid.setValue(rowKey, columnInfo.name, el.value);
			}
		});

		this.el = el;
		this.render(props);
	}

	getElement() {
		return this.el;
	}

	getValue() {
		return this.el.value;
	}

	render(props) {
		this.el.value = String(props.value);
		const checked = Boolean(props.value);
	}
}`

- props 소스
`this.gridPrgmProps = {
			data: dataSourcePrgm,
			columns: [ // for columnData prop
				{
				header: '프로그램No',
				name: 'prgmNo',
				hidden: true
				},
				{
				header: '삭제',
				name: 'delChk',
				width: '50',
				align: 'center',
				renderer: {
					type: chkboxRender
				}
				},
				{
				header: '프로그램명',
				name: 'prgmNm',
				sortable: true,
				editor: 'text'
				},
				{
				header: '메뉴연결',
				name: 'haveMenuYn',
				width: '80',
				align: 'center',
				sortable: true
				},
				{
				header: '프로그램경로',
				name: 'prgmPath',
				sortable: true,
				editor: 'text'
				},
				{
				header: '비고',
				name: 'rmk',
				sortable: true,
				editor: 'text'
				},
				{
				header: '수정일시',
				name: 'recUpdDatm',
				width: '150',
				align: 'center',
				sortable: true
				}
			],
			useClientSort: false
		};`

- grid
`<grid-prgm
              ref="prgmGrid"
              :data="gridPrgmProps.data"
              :columns="gridPrgmProps.columns"
              :language="'ko'"
              :theme="'striped'"
              @successResponse="successRespon"
              @failResponse="failRespon"
              @errorResponse="errorResponHandled"
              @click="clickPrgmGrid"
            />`

- 생성된 grid의 console capture 화면
![console_capture](https://user-images.githubusercontent.com/84057480/117914228-de4ddb80-b31d-11eb-827c-cf49d5813e38.JPG)

**Comment by js87zz** [comment]
@dvlmal 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied. And write the **Clean code**.
