### ISSUE TITLE
Move in and out rows in the tree structure, break the expand and collapse

### ISSUE THREAD

**Issue by attyskater** [nhn/tui.grid#1358]
**Describe the bug**
Move in and out rows in the tree structure, break the expand and collapse

**To Reproduce**
1. Go to https://jsfiddle.net/rd9hx5k6/
2. Move the magic whip line as in the [video](https://www.dropbox.com/s/rtno8ofhadspk6p/bugTree.mkv?dl=0) and you will see that the Chaos and the calm folder breaks down

**Desktop :**
 - OS: Windows 10
 - Browser: Brave

**Comment by js87zz** [comment]
@attyskater 
I checked the issue. It will be fixed.

**Comment by attyskater** [comment]
@js87zz 

Thank you very much

**Comment by js87zz** [comment]
@attyskater 
The bug has been fixed in `v4.17.2`.
