### ISSUE TITLE
className > row is not work

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1359]
hello, 

I am want to apply color to row, so **i coding below.**
(by reference https://nhn.github.io/tui.grid/latest/tutorial-example06-attributes)
![image](https://user-images.githubusercontent.com/81946046/118435599-391a7500-b71a-11eb-9cfc-4a7b5f619834.png)

but this is **not working.**
css is loaded
![image](https://user-images.githubusercontent.com/81946046/118435614-42a3dd00-b71a-11eb-8135-029b1d86b449.png)

**result**
![image](https://user-images.githubusercontent.com/81946046/118435632-4d5e7200-b71a-11eb-8c5e-314be8090883.png)

**Comment by js87zz** [comment]
@jsw-coder 
You should add your style for `red` class. Try to check your css.
