### ISSUE TITLE
When using chrome, an error occurs when copying from excel to Tui grid.

### ISSUE THREAD

**Issue by winnever** [nhn/tui.grid#1363]
**Describe the bug**

When using chrome, an error occurs when copying from excel to Tui grid.

Works fine in IE11.

When pasting into the Name column in the Validation example page, an error as shown in the picture occurs.

**Screenshots**

![image](https://user-images.githubusercontent.com/83747682/118438247-00c96580-b71f-11eb-84e9-90a771e040a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - Browser [e.g. chrome, safari] : chrome
 - Version [e.g. 22] : 90.0.4430.212

**Comment by js87zz** [comment]
@winnever 
We will fix it. Thanks!

**Comment by js87zz** [comment]
@winnever 
The bug has been fixed in `v4.17.2`.
