### ISSUE TITLE
how can i column align/vlign by using columnOptions?

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1366]
hello, 

i want to column align to middle.

how can i do that by using columnOptions?
(https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/setting-width-height.md)

**Comment by js87zz** [comment]
@jsw-coder 
You can cofigure align as below.
```js
const grid = new tui.Grid({
  // header align
  header: {
    align: 'left',
    valign: 'top',
  },
  columns: [
    {
      header: 'Name',
      name: 'name',
      // column align
      align: 'right',
      valign: 'top'
    },
  ],
  // ...
});
```
