### ISSUE TITLE
tui grid date filter datepicker option setting. TUI GRID 날짜 필터 datepicker 옵션 변경 방법 문의

### ISSUE THREAD

**Issue by EleninJayTech** [nhn/tui.grid#1367]
안녕하세요 TUI GRID 사용중 datepicker 옵션 변경 방법 문의 드립니다.

현재 column > filter 옵션에 date 를 적용하여 datepicker 가 출력 되어 사용중입니다.
궁금한점은 grid 에서 의존되어 사용되고있는 datepicker 옵션을 변경하여 한글로 변경하고 싶은데
옵션에 접근하는 방법을 찾지 못해 문의 드립니다.

`columns: [{'name':'reg_date', 'header':'생성일시', filter:{type:'date'}},]`

캡쳐 사진 첨부합니다.
https://i.imgur.com/FbP4wQu.png

답변 부탁드립니다.
감사합니다.

---
[참고용 전체 코드 이미지]
https://i.imgur.com/K4NDEY5.png

**Comment by js87zz** [comment]
@EleninJayTech 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

There is no way to set `i18n` on **datepicker** through grid configuration.. :(
If you want to change the language of the `tui-data-picker`, refer the date-picker [API](https://nhn.github.io/tui.date-picker/3.3.3/DatePicker#localeTexts) and [tutorial](https://github.com/nhn/tui.date-picker/blob/master/docs/getting-started.md#datepicker).

```js
import TuiDatePicker from 'tui-date-picker';

TuiDatePicker.localeTexts['your lang'] = {
  titles: {
    // days
    DD: // ...
    // daysShort
    D: // ...
  },
  // ...
};

// grid option
const grid = new tui.Grid({
  columns: [
    {
      header: 'DatePicker (Using options)',
      name: 'c2',
      editor: {
        type: 'datePicker',
        options: {
          // set your language
          language: 'customKey',
          format: 'dd/MM/yyyy'
        }
      }
    },
  ]
});
