### ISSUE TITLE
트리에서 resetData를 이용했을 때 멈추는 현상이 있습니다.

### ISSUE THREAD

**Issue by doosanpark** [nhn/tui.grid#1368]
**Describe the bug**
새로운 데이터를 추가하는 코드를 구현하고 있었습니다.
간단하게 input창 두개를 생성하고 기존 데이터 리스트에 새로운 데이터 객체를 추가해서 resetData를 이용해 데이터를 갱신하려고 했습니다. 그런데 자꾸 멈추는 현상이 생기더라구요. 코드를 살짝 변경해서 데이터 리스트에 데이터 객체 추가하는 것 없이 resetData를 이용하는 것은 잘 작동되는 것을 확인했습니다. 
아무런 에러도 발생하지 않고 마치 무한루프에 빠진 것 같은 증상을 보이는군요.

확인 부탁드리고 해결해주시면 감사하겠습니다.
그리고 이 외에 다른 방식으로 데이터를 추가할 수 있다면 그 방식도 알려주시면 감사하겠습니다.

다음과 같이 코드를 추가합니다.
`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width='device-width', initial-scale=1.0">
    <title>Document</title>
    <script src="./pagination/pagination.min.js"></script>
    <link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
    <script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
    <link rel="stylesheet" href="./pagination/pagination.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
    <div id="grid"></div>
    <div>

        항목명: <input id="itemName">
        점수: <input id="score">
        <button onclick = addData()>추가</button>

    </div>
    <script>

        var treeData = [
            {
                item: "전체",
                score: "",
                _children: [{
                    item: "인사",
                    score: "",
                    _children: [{
                        item: "첫 응대",
                        score: 5
                    }, {
                        item: "끝 응대",
                        score: 5
                    }]
                }]
            },
        ]

        
        var Grid = tui.Grid;
        Grid.applyTheme('clean');
        var grid = new Grid({
            el: document.getElementById("grid"),
            data: treeData,
            rowHeaders: ["rowNum", "checkbox"],
            treeColumnOptions: {
                name: "item"
            },
            pageOptions: { perPage: 10 },
            columns: [
                {
                    header: "문항명",
                    name: "item",
                    width: "auto",
                    sortable: true,
                    sortingType: 'desc'
                }, {
                    header: "배점",
                    name: "score",
                    align: "center",
                    width: 100
                }
            ],
            summary: {
                height: 40,
                position: "bottom",
                columnContent: {
                    score: {
                        template: function(valueMap){
                            return `합계: ${valueMap.sum}`
                        }
                    }
                }
            }
        })

        grid.on('expand', ev => {
            const { rowKey } = ev;
            const descendantRows = grid.getDescendantRows(rowKey);

            console.log('rowKey: ' + rowKey);
            console.log('descendantRows: ' + descendantRows);

            if (!descendantRows.length) {
                grid.appendRow(
                    {
                        name: 'dynamic loading data',
                        _children: [
                            {
                                name: 'leaf row'
                            },
                            {
                                name: 'internal row',
                                _children: []
                            }
                        ]
                    },
                    { parentRowKey: rowKey }
                );
            }
        });

        grid.on('collapse', ev => {
            const { rowKey } = ev;
            const descendantRows = grid.getDescendantRows(rowKey);

            console.log('rowKey: ' + rowKey);
            console.log('descendantRows: ' + descendantRows);
        });

        var ddata = [
            {
                item: "전체",
                score: "",
                _children: [{
                    item: "인사",
                    score: "",
                    _children: [{
                        item: "첫 응대",
                        score: 5
                    }, {
                        item: "끝 응대",
                        score: 5
                    }]
                }]
            },{
                item: "안전체",
                score: "22"
            }
        ]

        function addData(){
            var itemName = $("#itemName").val();
            var scoreVal = $("#score").val();

            console.log("itemName", itemName);
            console.log("scoreVal", scoreVal);

            var newObj = {
                item: itemName,
                score: scoreVal
            }

            treeData.push(newObj);
            console.log("treeData", treeData);
            var data = treeData;
            grid.resetData(data)
            
        }

      
        

    </script>

</body>

</html>
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by js87zz** [comment]
@doosanpark 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

Can you try to change your CDN link as below? 
`<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js">`

It is not yet supported to operate the tree in conjunction with pagination or summary.

**Comment by doosanpark** [comment]
It is exactly same CDN link.
I will try another way.

**Comment by js87zz** [comment]
@doosanpark 
Sorry, I wrote the wong link. Can you try as below?
`<script src="https://uicdn.toast.com/grid/latest/tui-grid.js">`

**Comment by goandstop42** [comment]
@doosanpark 
 I'm wondering about its current status. Whether the issue has been resolved? If resolved, how it was addressed?
