### ISSUE TITLE
@toast-ui/react-grid 에서 TypeScript 적용방안에 문의드립니다.

### ISSUE THREAD

**Issue by darionkim** [nhn/tui.grid#1369]
**Summary**
타입스크립트를 적용중인데
멤버의 코드를 보던 중에 onClick의 event가 any로 되어있고
에러규칙이 미적용 되어 있어
// eslint-disable-next-line @typescript-eslint/no-explicit-any 
이벤트의 타입을 찾아 보려는데 나오지 않네요.

디버그모드에서는 GridEvent로 나오고 MouseEvent를 랩핑했는데
@toast-ui에서 GridEvent를 찾을 수가 없어서요.

그냥  any로 사용해야되는 건지
아니면 다른 방안이 있는지 궁금해지네요.

**Screenshots**
![image](https://user-images.githubusercontent.com/8843368/119116867-a2282280-ba63-11eb-8bd6-7568d1a1d528.png)

**Version**
"@toast-ui/react-grid": "^4.17.0"

**Additional context**
다른 멤버들이 좋아합니다.

**Comment by js87zz** [comment]
@darionkim 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.

We need to export the event type for solving your issue in react-grid. 
I think you can define the type yourself and use it, but it would be a hassle for the user. 
Try to use `any` type. And I will let you know if the `GridEvent` type is added later. 
Thank you!

**Comment by darionkim** [comment]
Sorry.

I will write in English next time.

Thank you for your answer.
