### ISSUE TITLE
Rest api I would like to inquire about the standard.

### ISSUE THREAD

**Issue by bison225** [nhn/tui.grid#1374]
Pathvariable URL is ${PATHVARIABLE} and cannot be used with an EL tag when the extension is JSP.
You can use it by changing the extension to HTML.
We want to use rest path in JSP extension.
Is there a way to replace it with a string other than ${}?

i used <script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script> this version.

Please reply.

**Summary**
El tag of JSP and grammar overlap.${}

**Comment by js87zz** [comment]
@bison225 
I don't understand exactly what it is about. 
Please give us a more detailed example. 
If it is a technical issue specific to the jsp, it may not be something we will answer here.

And the cdn link was changed to url below.
`<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>`

**Comment by bison225** [comment]
KOR---------------------------------------------------------------
예시 부분 입니다.
sequence 파라미터를 바인딩 시켜 rest api 를 호출 하는 방식인데요.
updateData: {
	url: () => `/v1/etc/snapslife/${seq}`,
	method: 'POST',
	headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' },
}
위와 같이 ${seq} 가 JSP 에서는 EL태그(컴파일 언어)로 인식이 되어 값이 null이 되어
url: () => `/v1/etc/snapslife/`, 로 생성이 됩니다.
확장자를 HTML로 변경하여 진행하여보니 
url: () => `/v1/etc/snapslife/${seq}`, 로 url이 정상적으로 인식이 됩니다.
tui-grid.js에서 rest api를 사용시 seq 파라미터를 바인딩 할때 
${seq} 가 아닌 다른 대체문자로 커스텀이 가능한지를 여쭤보는 겁니다.
ex : 
1) url: () => `/v1/etc/snapslife/#{seq}`,
2) url: () => `/v1/etc/snapslife/@{seq}`,

ENG---------------------------------------------------------------

Here's an example.
It's a method that binds sequence parameters and calls rest api.
updateData: {
url: () => `/v1/etc/snapslife/${seq}`,
method: 'POST',
headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' },
}
As shown above, ${seq} is recognized as an EL tag (compiled language) in JSP, resulting in a null value.
url: () => Created with '/v1/etc/snapslife/'
I changed the extension to HTML to proceed.
url:() => '/v1/etc/snapslife/${seq}', Laurl will be recognized normally.
When using restapi in tui-grid.js, when binding seq parameters,
I'm asking if it's possible to customize it with a replacement character other than ${seq}.
ex :
1) url: () => `/v1/etc/snapslife/#{seq}`,
2) url: () => `/v1/etc/snapslife/@{seq}`,

@js87zz  please

**Comment by js87zz** [comment]
@bison225 
Use as a normal string merge as shown below. I think it would be better to look for JavaScript specifications, not grids.
```js
url: () => '/v1/etc/life/' + seq,
// ...
```

**Comment by bison225** [comment]
$는 일반적인 스트링인가요? $를 다른 문자로 대체할수있냐고 질문을 드린건데 왜 이해를 못하시는지 모르겠네요.
Is $ a normal string? I asked you if you could replace $ with another letter, but I don't know why you don't understand.

가이드문서에 rest api url : ${action} 명시되어있잖아요 $ -> 다른 문자 안되냐고 물어본겁니다.
The guide document states ${action}, so I asked if there was another text.

**Comment by js87zz** [comment]
@bison225 
이번 답변은 한글로 작성하겠습니다.
`${}`은 템플릿 리터럴이라는 자바스크립트에 지정된 [명세](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals)입니다. 그리드에 한정된 문법이 아니구요. 정해진 문법이니 당연히 다른 문자로도 치환이 불가능하겠죠? 그래서 위에 jsp EL 표현식과 겹칠 수 있으니 다른 형태로 가공하여 일반 문자열 병합 형태로 시도해보라고 작성한 거구요. 
여기는 오픈소스 공간이지만 일반적으로 통용되는 규칙과 예의라는 것이 있습니다.  공격적인 질문과 답변으로 싸우고 논쟁하는 공간이 아닙니다. 원하는 기능이나 궁금한 점이 있다면 좀 더 예의를 갖춰주세요. 여기는 질문자님의 공간이 아닙니다.

**Comment by bison225** [comment]
다소 공격적인 말투로 보였으면 죄송합니다. 번역기를 돌려야해서 화법을 딱딱하게 하다보니 그렇게 보였을 수 있네요. 
번역기로만 해석하다보니 제가 이해를 잘 못했습니다. 친절한 답변 정말 감사합니다.
많은 사용자분들께 도움이 될것 같습니다 
@js87zz
