### ISSUE TITLE
Grid Design

### ISSUE THREAD

**Issue by chiho1** [nhn/tui.grid#1378]
I am using a translation program.

I am using the latest version of tui-grid.

It looks like the design of the grid is wrong.

tui-grid-rside-area and tui-grid-rside-area > tui-grid-body-container > tui-grid-table-container seem to be the cause.

I'd like to know what the problem is.

I attach the code.

/*****************************************************************************************************************************/

번역 프로그램을 사용하고 있습니다.

tui-grid의 latest 버전을 쓰고 있습니다.

그리드의 디자인이 틀어져서 보입니다.

tui-grid-rside-area와 tui-grid-rside-area > tui-grid-body-container > tui-grid-table-container 가 원인으로 보입니다.

어떤 게 문제인지 알려주었으면 합니다.

코드 첨부합니다.

`<!DOCTYPE html>
<html lang="ko">
<head>
  <link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="js/jquery-ui.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
  <script>
    const Grid = tui.Grid;

    Grid.setLanguage('ko');
    tui.Grid.applyTheme('clean', {
      cell: {
        focused: {
          border: 'none'
        }
      }
    });

    var grid1 = "";
    $(function(){

      const dataSource1 = [
        { 'test1':'test1-1', 'test2':'test2-1', 'test3':'test3-1', 'test4':'test4-1', 'test5':'test5-1', 'test6':'test6-1', 'test7':'test7-1' }
      ];

      grid1 = new tui.Grid({
        usageStatistics: false, // 오픈소스 사용 통계 비활성화
        el: document.getElementById('grid1'),
        data: dataSource1,
        scrollX: false,
        scrollY: false,
        rowHeight: 'auto',
        bodyHeight: 520,
        columns: [
          {
            header: 'test1',
            name: 'test1',
            align: 'left',
            width: 150
          },
          {
            header: 'test2',
            name: 'test2',
            align: 'left',
            width: 150
          },
          {
            header: 'test3',
            name: 'test3',
            align: 'left',
            width: 150
          },
          {
            header: 'test4',
            name: 'test4',
            align: 'left',
            width: 150
          },
          {
            header: 'test5',
            name: 'test5',
            align: 'left',
            width: 150
          },
          {
            header: 'test6',
            name: 'test6',
            align: 'left',
            width: 150
          },
          {
            header: 'test7',
            name: 'test7',
            align: 'left',
            width: 150
          }
        ]
      });

      grid1.on('failResponse', function(ev) {
        grid1.clear();
      });

      setTimeout(function(){
        grid1.refreshLayout();
      }, 100);
    })
  </script>
<style>
  *{font-family: 'Noto Sans KR'; text-decoration: none; list-style: none;margin:0; padding:0}

  /** table **/
  .table_area {height: auto; overflow: auto;}
  table, table td, table th{text-align:center;}
  .table_area table{border:1px solid #e5e5e5; width:100%}
</style>
</head>
<body>
  <div class="content-wrapper">
		<div class="cont">
    	<section class="content">

				<div class="box">
          <div class="box-body" style="width: 1265px;">
            <div class="table_area">
              <div id="grid1" style="width: 100%;"></div>

            </div>

          </div>

				</div>
    	</section>
    </div>
  </div>
  </body>
</html>
`

![20210602_2](https://user-images.githubusercontent.com/66509695/120466857-82d1b380-c3da-11eb-98a3-d355cc1d26a1.png)
![20210602_1](https://user-images.githubusercontent.com/66509695/120466862-8402e080-c3da-11eb-9977-269cc371c7f5.png)

**Comment by js87zz** [comment]
@chiho1 
Can you try to as below?
```js
const dataSource1 = [
    { 'test1':'test1-1', 'test2':'test2-1', 'test3':'test3-1', 'test4':'test4-1', 'test5':'test5-1', 'test6':'test6-1', 'test7':'test7-1' }
  ];
  const grid = new tui.Grid({
  // set total width
  width: 1050,
  columns: [
    {
      header: 'test1',
      name: 'test1',
      align: 'left',
    },
    {
      header: 'test2',
      name: 'test2',
      align: 'left',
    },
    {
      header: 'test3',
      name: 'test3',
      align: 'left',
    },
    {
      header: 'test4',
      name: 'test4',
      align: 'left',
    },
    {
      header: 'test5',
      name: 'test5',
      align: 'left',
    },
    {
      header: 'test6',
      name: 'test6',
      align: 'left',
    },
    {
      header: 'test7',
      name: 'test7',
      align: 'left',
    }
  ]
});
```

**Comment by chiho1** [comment]
I am writing a translator.

good!

Why don't these examples appear at https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/setting-width-height.md?
![20210610_1](https://user-images.githubusercontent.com/66509695/121448957-ad6fcd80-c9d3-11eb-86e8-89a7b919e950.png)

**Comment by chiho1** [comment]
It's resolved, so close.
