### ISSUE TITLE
How can i add row by using javascript?

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1381]
hello, 
how can i do that?

1. i want to add row by using add_button
2. i want to delete row by using del_button 
3. i want to know row number that is modified or add row

(한글
     1. add_btn 버튼을 클릭시, grid에 row를 추가하고자 합니다. 
     2. del_btn 버튼을 클릭시, grid에 row를 제거하고자 합니다. 
     3. 내용이 수정된 row나 row가 추가된 곳을 어떻게 확인가능할까요?)

![image](https://user-images.githubusercontent.com/81946046/120960410-bcb60780-c796-11eb-9dd5-a6c74b0ef7a7.png)

**Comment by js87zz** [comment]
@jsw-coder 
Try to use [appendRow](https://nhn.github.io/tui.grid/latest/Grid#appendRow),  [removeRow](https://nhn.github.io/tui.grid/latest/Grid#removeRow) API. 
And you can get the information for modified rows through [getModifiedRows](https://nhn.github.io/tui.grid/latest/Grid#getModifiedRows) API
