### ISSUE TITLE
Upload  appendRow, removeRow, getModifiedRows API Example source.

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1383]
hello, 

i did write question about adding row.

and someone tell me about referening appendRow, removeRow, getModifiedRows. 

But There is no example source. 

please upload example source.

(한글)
얼마전에 아래와 같이, row를 추가하는 문의글을 올렸습니다. 
appendRow, removeRow, getModifiedRows 함수를 이야기하셨는데, 매뉴얼에 가니 예제 샘플이나 소스가 없습니다. 

예제 샘플이나 소스 업로드 부탁드립니다. 

![image](https://user-images.githubusercontent.com/81946046/121298120-4cda8500-c92e-11eb-885e-ccd6bbb755f3.png)

**Comment by js87zz** [comment]
The example code snippet is as below.
```js
const appendBtn = document.getElementById('appendBtn');

const appendedData = {
  name: 'Music',
  artist: 'Lee',
  type: 'Deluxe',
  release: '2019.09.09',
  genre: 'Pop'
};

appendBtn.addEventListener('click', () => {
  grid.appendRow(appendedData);
});
// ...
grid.removeRow(rowKey); // pass the rowKey you want to remove
```
