### ISSUE TITLE
Is it possible to use keyboard to change value of checkbox in grid?

### ISSUE THREAD

**Issue by hastrobee** [nhn/tui.grid#1386]
**Summary**
Is it possible to use keyboard to change value of checkbox in grid?

**Screenshots**
![image](https://user-images.githubusercontent.com/85718707/121621814-deb9cd80-caa7-11eb-999b-86cf68af51f4.png)

**Version**
"version": "4.17.0"
TOAST UI Grid for Vue

**Additional context**

**Comment by js87zz** [comment]
@hastrobee 
Are you using the custom renderer?
If so, you can control the operation of the checkbox through your own key event.
If not, can you add the detailed code?

**Comment by hastrobee** [comment]
Adding  @keydown.native in grid tag, it works!

        <grid ref="myGrid" :scrollY="true" :bodyHeight="450"
              :data="myGrid.data"
              :columns="myGrid.columns"
              :language="'ko'"
              :theme="'striped'"
              @beforeRequest="beforeReq"
              @successResponse="successRespon"
              @failResponse="failRespon"
              @errorResponse="errorResponHandled"
              @keydown.native="myKeyDown"
        />
...

		myKeyDown(ev) {
			if(ev.keyCode == 13 || ev.keyCode == 32){
				const cell = this.$refs.myGrid.invoke('getFocusedCell');
				const el = this.$refs.myGrid.invoke('getElement', cell.rowKey, cell.columnName);
				el.children[0].click();
			}
		}
