### ISSUE TITLE
grid 중복 사용

### ISSUE THREAD

**Issue by unique-jj** [nhn/tui.grid#1387]
한 페이지에 탭 형식으로 두개의 그리드를 사용하려고합니다.

두개 그리드의 id와 데이터는 각각 달리해서 서로 매칭되게 마크업 했습니다.

결과는

첫 탭 한개의 그리드는 정상 노출되고

두번쨰 탭 그리드는 header와 제목 tr 만 노출되고 

content td 즉, 데이터에서 불러오는 정보들이 빈값입니다. 해당 td를 아예 렌더링 하지 못해요.

제가 뭔가 추가적으로 작업해야하거나 잘못된 방법으로 한건지

원래 한페이지에서 두개의 그리드를 렌더링 할 수 없는건지 문의드립니다.

(부트스트랩4와 함께 사용중입니다.)

**Comment by js87zz** [comment]
@unique-jj 
Please make sure you have filled out issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied.

And we need more information to know your issue exactly. 
It's helpful to give use detail code in code sandbox or jsfiddle
