### ISSUE TITLE
옆에 있는 column의 값을 똑같이 가지려면

### ISSUE THREAD

**Issue by newwwwna** [nhn/tui.grid#1388]
처음 grid를 보여줄 때, 옆에 있는 column의 값을 똑같이 가진 칼럼을 만들고자 합니다.
grid.setValue와 grid.getValue를 활용해서 쿼리의 수정 없이 javascript 단에서 같은 값을 가진 칼럼을 추가로 만들 수 있을까요?

**Comment by js87zz** [comment]
@newwwwna 
Please make sure you have filled out issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied.
