### ISSUE TITLE
How to give pagination attribute to grid?

### ISSUE THREAD

**Issue by Ankitabathia** [nhn/tui.grid#1390]
I am setting pagination attribute but not able to see my data in grid paginated. All the data comes on first page. how should i link pagination and grid. PageOptions attribute is not working. I get my data through webmethod and assign to grid on jquery success method.

**Comment by js87zz** [comment]
@Ankitabathia 
Can you give me the your grid configuration code?

**Comment by Ankitabathia** [comment]
> @Ankitabathia
> Can you give me the your grid configuration code?
My aspx code is here:

<link rel="stylesheet" href="https://uicdn.toast.com/tui.pagination/latest/tui-pagination.css" />
<script src="https://uicdn.toast.com/tui.pagination/latest/tui-pagination.js"></script>

<link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<link rel="icon" href="data:;base64,=">

<form id="form1" runat="server">
    <div id="grid" class="tui-pagination"></div>
</form>
<script language="javascript" type="text/javascript">
    const dataSource = {
        api: {
            readData: { url: '/api.aspx', method: 'GET' },
        }
    };
    const grid = new tui.Grid({
        el: document.getElementById('grid'),
        d1ata: dataSource,
        scrollX: false,
        scrollY: false,
        minBodyHeight: 30,
        //rowHeaders: ['rowNum'],
        pageOptions: {
            perPage: 5
        },
        columns: [
            {
                header: 'CustomerPartNo',
                name: 'CustomerPartNo',
                filter: 'text'
            },
            {
                header: 'CustomerNo',
                name: 'CustomerNo',
                filter: {
                    type: 'text',
                    showApplyBtn: true,
                    showClearBtn: true
                }
            },
            {
                header: 'PartNumber',
                name: 'PartNumber',
                filter: {
                    type: 'text',
                    showApplyBtn: true,
                    showClearBtn: true
                }
            }
        ]
    });
    
    grid.on('failResponse', ev => {
      console.log('check!', ev);
    });
</script>

**Comment by Ankitabathia** [comment]
api.aspx.cs code

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace CustomerPartRelate
{
    public partial class api : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            //var dataObj = new { CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" };
            //var dataStr = JsonConvert.SerializeObject(dataObj);
            var data = new List<cpr>();
            data.Add(new cpr{ CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" });
            data.Add(new cpr { CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" });
            data.Add(new cpr { CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" });
            data.Add(new cpr { CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" });
            data.Add(new cpr { CustomerPartNo = "cprno1", CustomerNo = "cn1", PartNumber = "pn1" });
            var dataObj = new {
                result = true,
                data = new {
                    contents = data,
                    pagination = new { page = 1, totalCount = 1 }
                }
            };
            var dataStr = JsonConvert.SerializeObject(data);
            Response.Clear();
            Response.ContentType = "application/json; charset=utf-8";
            Response.Write(dataStr);
            Response.End();
        }
    }
    public class cpr
    {
        public string CustomerPartNo;
        public string CustomerNo;
        public string PartNumber;
    }
}

**Comment by js87zz** [comment]
@Ankitabathia 
The code seems almost similar with [this example](https://nhn.github.io/tui.grid/latest/tutorial-example10-data-source) and doesn't seem to be a problem.
The cdn link is wrong, so can you like to change it? 
```html
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
```
If this does not work, there could be some external factors.. But this situation is difficult for me to know at the moment.

**Comment by Ankitabathia** [comment]
> @Ankitabathia
> The code seems almost similar with [this example](https://nhn.github.io/tui.grid/latest/tutorial-example10-data-source) and doesn't seem to be a problem.
> The cdn link is wrong, so can you change it as below?
> 
> ```
> <script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
> ```
> 
> If this does not work, there could be some external factors.. But this situation is difficult for me to know at the moment.

Not working yet!

**Comment by Ankitabathia** [comment]
> @Ankitabathia
> The code seems almost similar with [this example](https://nhn.github.io/tui.grid/latest/tutorial-example10-data-source) and doesn't seem to be a problem.
> The cdn link is wrong, so can you change it as below?
> 
> ```
> <script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
> ```
> 
> If this does not work, there could be some external factors.. But this situation is difficult for me to know at the moment.

Not able to resolve my issue. Can you please help more. Need it very urgently.
