### ISSUE TITLE
connecting link to on the column header

### ISSUE THREAD

**Issue by spicyyou** [nhn/tui.grid#1394]
hello, 
I would like to connect link to the grid column header.
Is there any solution?
thank you.

[한글]
안녕하세요.
그리드 컬럼 헤더에 링크를 연결하고 싶습니다.
방법이 있을까요?

**Comment by js87zz** [comment]
@spicyyou 
[This feature](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-column-header.md) will be helpful.
