### ISSUE TITLE
Summary question.

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1397]
hello,
Writing summary. 
As shown in the table below, we are going to apply the summary to the part with a green background.

Ask questions that are not in the example.
- How do I center the summary field?

- How do I change the background color of the summary column?

- As shown in the table below, we want to apply two summaries.
How can I do that?
(The first summary, each sum, is the sum of each column, and the second summary, Total Sum, is the sum of all columns.)

[한글]
안녕하세요
summary를 작성 중입니다. 아래 표와 같이 초랙색 배경인 부분에 summary를 적용하려고 합니다. 

예제에 없는 내용 질문합니다. 
**- summary란을 중앙 정렬은 어떻게 하면 될까요?
- summary란의 배경색을 어떻게하면 될까요?
- 아래 표와 같이 summary를 2개로 적용하고자 합니다. 어떻게하면 될까요?**
(첫번째 summary인 each sum은 각 컬럼의 합계이며, 두번째 summary인 Total Sum은 모든 컬럼의 sum입니다.)

![image](https://user-images.githubusercontent.com/81946046/122874287-cc744500-d36d-11eb-962c-3d53dd9fcd43.png)

**Comment by js87zz** [comment]
@jsw-coder 
* align, background color
Since there is no theme option right now, styling is recommended by overriding CSS as the next best option.
```css
.tui-grid-cell.tui-grid-cell-summary {
  // write your style code
}
```
* multiple summaries
Writing multiple summaries is not currently supported. It looks good but it will take a lot of time to improve.
