### ISSUE TITLE
Merge(rowspan) Question.

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.grid#1398]
I want to merge the cells with the green background in Table 1.

You can proceed by using the Attributes attribute, but in this case, it seems that the code is too laborious.
Currently, data is read from the DB, converted to JSON, and then the data is sent to the Toast Grid.
If you do it like the example site below, you need to do a separate task when loading data from DB.
(Reference site: http://nhn.github.io/tui.grid/latest/tutorial-example06-attributes)

Is there any possible way to put attributes in a column so that they are automatically merged if they have the same content? (e.g. automerge=true)

[한글]
표1의 초록색 배경의 셀을 합치려고 합니다. 

Attributes 속성을 이용하여 진행하면 되는데, 이런 경우 너무 코드에 손이 많이가는것 같습니다. 
현재는 DB에서 Data을 읽어와서 JSON으로 변환 후 Toast Grid에 Data를 전송하고 있습니다. 
아래 Example 사이트 처럼한다면, Data를 DB에서 로드할때 별도의 작업을 해야합니다. 
(참조 사이트:  http://nhn.github.io/tui.grid/latest/tutorial-example06-attributes)

컬럼에 속성을 넣어 같은 내용이 있는 경우 자동으로 합병되도록 가능한 방법은 없을까요? (예: automerge=true)

![image](https://user-images.githubusercontent.com/81946046/122876887-fb3fea80-d370-11eb-8edb-8d22c22ea4ec.png)

**Comment by js87zz** [comment]
@jsw-coder 
I will consider it, but I have no immediate plans to support this feature.
Thanks!
