### ISSUE TITLE
I have a question about how to use the React Tui.Grid custom event. ㅠㅠ

### ISSUE THREAD

**Issue by byunghyun** [nhn/tui.grid#1402]
안녕하세요. 
리액트 토스트 그리드에서 uncheck 이벤트를 사용이 가능한지 궁금합니다.
(Hello I'd like to use the uncheck event on the react grid, can I use it?)
https://nhn.github.io/tui.grid/latest/Grid#event-uncheck

useRef()를 이용해서 custom Event를 사용 할 수 있는 것인지.. 가능 하다면 예시를 하나 보여주실 수 있나요?
(Can we useRef() to use custom event? If possible, could you show me an example?)

**Comment by js87zz** [comment]
@byunghyun 
You can use the custom event as below.
```js
<Grid onUncheck={...}>
```
