### ISSUE TITLE
데이터 바인딩 에러

### ISSUE THREAD

**Issue by ljh965** [nhn/tui.grid#1406]
<template>
  <div>
    <div @click="perPage">클릭클릭</div>
    <grid ref="tuiGrid"
      :data="gridProps.data"
      :columns="gridProps.columns"
      :options="gridProps.options"
      @successResponse="successResponse"
    />
  </div>
</template>

<script>
import 'tui-grid/dist/tui-grid.css'
import 'tui-pagination/dist/tui-pagination.css';
import { Grid } from '@toast-ui/vue-grid'

export default {
  components: {
    'grid': Grid
  },
  data() {
    return {
      instance: null,
      gridProps: null
    }
  },
  created() {
    this.gridProps = {
      data: {
        api: {
          readData: { url: '/sampleList', method: 'GET' },
        }
      },
      options: {
        pageOptions: {
          perPage: 1
        }
      },
      columns: [
        { name: "LOT", header: "LOT", align: "center" },
        { name: "PHONE", header: "PHONE", align: "center" },
        { name: "ID", header: "ID", align: "center" },
      ]
    }
  },
  methods: {
    perPage: function() {
      this.$refs.tuiGrid.invoke("setPerPage", 5);
    },
    successResponse: function(event) {
      if (this.instance == null) {
        this.instance = event.instance;
      }
    }
  }
}
</script>

![image](https://user-images.githubusercontent.com/52273613/123602372-a1896580-d833-11eb-85f9-7401f7213449.png)

Network를 확인해보면 api요청은 정상적으로 작동하지만 grid에 데이터가 바인딩 되진 않는데 왜 이런건가요?

**Comment by KimGenius** [comment]
![image](https://user-images.githubusercontent.com/29722636/123607429-d9df7280-d838-11eb-9e9e-7f11679a6f8e.png)
https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/data-source.md
문서에 보시면 response 형식이 나와있습니다. 해당 문서 참고해서 해보시면 될거같아요!

**Comment by js87zz** [comment]
@ljh965 
Please make sure you have filled out issue **respecting our form in English and given us as much context** as possible. If not, the issue will be closed or not replied.
