### ISSUE TITLE
How to make filter clientside without calling the data source again?

### ISSUE THREAD

**Issue by Ankitabathia** [nhn/tui.grid#1409]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@Ankitabathia 
Please make sure you have filled out issue respecting our form in English and **given us as much context** as possible. If not, the issue will be closed or not replied.
