### ISSUE TITLE
'data-row-key' values

### ISSUE THREAD

**Issue by vnfjri123** [nhn/tui.grid#1410]
I would like to know more about where the value of 'data-row-key' comes from in the tag 'td'.

**Comment by js87zz** [comment]
@vnfjri123 
It is a unique value as a key value to distinguish between each row.

**Comment by vnfjri123** [comment]
> @js87zz
> It is a unique value as a key value to distinguish between each row.

Can I modify a unique value?

**Comment by js87zz** [comment]
@js87zz 
If you want to change it, you can configure the data with the `rowKey`.
```js
const data = [
  {
    rowKey: 1 // write the unique key that you want
  },
  // ...
];
It is not recommended to change the `rowKey` by force other than this method.
```

**Comment by vnfjri123** [comment]
> @js87zz
> If you want to change it, you can configure the data with the `rowKey`.
> 
> ```js
> const data = [
>   {
>     rowKey: 1 // write the unique key that you want
>   },
>   // ...
> ];
> ```
> 
> It is not recommended to change the `rowKey` by force other than this method.

As you said, the DB data was solved after the secondary processing process. Thank you.
