### ISSUE TITLE
custom column header is not working

### ISSUE THREAD

**Issue by spicyyou** [nhn/tui.grid#1411]
I'm currently using the 4-point version.
 However, when I use custom column header, 
it is rendered on the entire row as shown in the picture below. 
Is it because I didn't use version 4.7? 
Then can I know how to update from 4.0 to 4.7?

- Code:
```javascript
var CustomColumnHeader = function(props) {
        const columnInfo = props.columnInfo;
        const el = document.createElement('div');
        var msg = columnInfo.header;
        el.textContent = msg;
        const sel = document.createElement('select');
        sel.title = msg;
        $(sel).addClass("w150");
        sel.id = columnInfo.name;
        sel.name = columnInfo.name;
        var opt = document.createElement("option");
        opt.text = "전체수신";
        opt.value = "all";
        sel.appendChild(opt);
        var opt = document.createElement("option");
        opt.text = "optionnm";
        opt.value = "optval";
        sel.appendChild(opt);
        el.appendChild(sel);
        this.el = el;
        this.render(props);
    }

    CustomColumnHeader.prototype.getElement = function() {
        return this.el;
    }

    CustomColumnHeader.prototype.render = function(props) {
        //this.el.value = props.value;
        this.el.value = 'optval';
    }
```

- Result
<img width="153" alt="스크린샷 2021-06-30 오전 11 15 27" src="https://user-images.githubusercontent.com/43233184/123891850-7f5b2900-d994-11eb-8a49-7a1b3606ce34.png">

[한글]
안녕하세요.
저는 현재 4점대 버전의 tui를 사용하고 있습니다. (정확한 버전은 모르겠습니다.)
그런데 custom column header를 사용하면 헤더에 렌더링 되는 것이 아닌 전체 row에 렌더링 되고 있습니다.
4.7버전으로 업그레이드하지 않아 생긴 문제일까요?
그렇다면 4.7버전으로 업그레이드 하는 방법이 궁금합니다.
감사합니다.

**Comment by js87zz** [comment]
@spicyyou 
Can you give your grid configuration code?

**Comment by spicyyou** [comment]
@js87zz 
```javascript
{
                header: 'day0',
                name: 'day0',
                sortingType: 'desc',
                sortable: 'true',
                renderer: CustomColumnHeader
            },
```

here, Thank you

**Comment by spicyyou** [comment]
> @spicyyou
> Can you give your grid configuration code?

@js87zz 
```javascript
columns : [
...
            {
                header: 'day0',
                name: 'day0',
                sortingType: 'desc',
                sortable: 'true',
                renderer: CustomColumnHeader
            },
...
```

this is my grid configuration code. Thank you

**Comment by js87zz** [comment]
@spicyyou 
The custom column header option should be configured with `header` option as below.
```js
const grid = new Grid({
  header: {
    columns: [
      {
        name: 'name',
        renderer: CustomColumnHeader
      }
    ]
  },
  columns: [
    // ...
  ] 
});

```

**Comment by spicyyou** [comment]
> @spicyyou
> The custom column header option should be configured with `header` option as below.
> 
> ```js
> const grid = new Grid({
>   header: {
>     columns: [
>       {
>         name: 'name',
>         renderer: CustomColumnHeader
>       }
>     ]
>   },
>   columns: [
>     // ...
>   ] 
> });
> ```
> 
> * tutorial link: https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-column-header.md

Thank you. Now, It works well.

But I have a more question.
The tutorial said `Options sortable and filter are ignored in custom column header.`
There is no way to implement sortable??

**Comment by js87zz** [comment]
@spicyyou 
Yes, currently it needs to be implemented in the custom column header yourself.
We're gonna have to consider it.
