### ISSUE TITLE
tui.Grid.applyTheme row hover

### ISSUE THREAD

**Issue by vnfjri123** [nhn/tui.grid#1417]
-CODE
tui.Grid.applyTheme('default',{
row: {
hover: {
background: '#e4edf4'
}
})
IMG
1.
![1](https://user-images.githubusercontent.com/83931273/124219012-625e5b80-db36-11eb-9f2c-ea5fd28d0590.png)
2.
![2](https://user-images.githubusercontent.com/83931273/124219024-67230f80-db36-11eb-88fb-890d52a11803.png)
3.
![3](https://user-images.githubusercontent.com/83931273/124219031-6db18700-db36-11eb-803b-e0f63f1fe9f9.png)

"1." doesn't seem to be a problem. But "2." and "3." seem to have problems. This problem occurs with combined cells.

I don't want to apply 'row hover' css for combined cells.

Or, I want to apply 'row hover' css to another row included in the combined cell if it becomes hover.

How do I solve this?

**Comment by js87zz** [comment]
@vnfjri123 
This requirement is not currently supported.

**Comment by vnfjri123** [comment]
> @vnfjri123
> This requirement is not currently supported.

When can We get support for this function?

**Comment by js87zz** [comment]
@vnfjri123 
There are no plans at the moment yet because there are many other priorities.

**Comment by vnfjri123** [comment]
> @vnfjri123
> There are no plans at the moment yet because there are many other priorities.

Resolved. Thank you.
