### ISSUE TITLE
그리드의 로우를 새로 추가할때  셋팅된 값이 변경될때마다 이벤트를 발생시키고 싶습니다

### ISSUE THREAD

**Issue by kangsue9** [nhn/tui.grid#1418]
로우를 새로 추가할때 
여기 그리드의 헤더에 select 부분입니다. 여기에 셋팅된 값이 변경될때마다 이벤트를 발생시키고 싶습니다

{
          header: 'Type',
          name: 'typeCode',
          formatter: 'listItemText',
          editor: {
            type: 'select',
            options: {
              listItems: [
                { text: 'Deluxe', value: '1' },
                { text: 'EP', value: '2' },
                { text: 'Single', value: '3' }
              ]
            }
          }
        },

**Comment by vnfjri123** [comment]
#1149 여기 Description 참고해보시면 좋을 것 같습니다.

**Comment by kangsue9** [comment]
변경하고 포커스가 이동한후가 아닌 변경 하자마자 이벤트를 발생시킬 수는 없는건가요? 셀렉스박스에 선택시 아래 또 로우가 나와야 합니다. blur 형식이 아닌 바로 이벤트가 발생할 방법은 없을까요?

**Comment by vnfjri123** [comment]
> 변경하고 포커스가 이동한후가 아닌 변경 하자마자 이벤트를 발생시킬 수는 없는건가요? 셀렉스박스에 선택시 아래 또 로우가 나와야 합니다. blur 형식이 아닌 바로 이벤트가 발생할 방법은 없을까요?

`
        $('.tui-select-box-placeholder').on('change', function(e) {
            grid.appendRow(data, option)
        });`

될지는 모르겠지만 셀렉트 박스 값이 변경될 때 기준으로 class 이나 id 값 가져오셔서 appendRow를 활용하여 data 값과 로우 생성 지점에대한 option 을 주시면 어떨까요.
