### ISSUE TITLE
Not able to change font and background color of the grid row/cell.

### ISSUE THREAD

**Issue by Ankitabathia** [nhn/tui.grid#1419]
I am trying to assign class dynamically from JS to row on change of a grid cell. I am somehow able to see the change in font family and size but the colour of font and the background is not changing according to the css class assigned.

**Comment by js87zz** [comment]
@Ankitabathia 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

We need more information to know what you want exactly. Please give us the your code and some screenshots
