### ISSUE TITLE
그리드 상에서 select 이벤트

### ISSUE THREAD

**Issue by kangsue9** [nhn/tui.grid#1420]
그리드 상에서 로우를 하나 생성해서 아래의 코드와 같은 select타입의 콤보박스 의 값을 선택시 바로 아래에 새로운 로우가 생성되게 하려고 합니다. 선택하고 다른곳으로 가야 발생하는 이벤트 말고 선택하자마자 발생되는 이벤트는 없을까요? beforeChange,afterChange 이벤트는 다른곳의 포커스가 이동해야 이벤트가 발생하더군요 포커스는 그대로이며 그자리에서 변경했을시 이벤트는 없을까요? 

{
header: 'Type',
name: 'typeCode',
formatter: 'listItemText',
editor: {
type: 'select',
options: {
listItems: [
{ text: 'Deluxe', value: '1' },
{ text: 'EP', value: '2' },
{ text: 'Single', value: '3' }
]
}
}
},

**Comment by js87zz** [comment]
@kangsue9 
Please make sure you have filled out issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied.

The event occurs only after a complete modification of the value. 
Events for Select Boxes are not currently supported.
