### ISSUE TITLE
Datasource - How to get it to refresh data

### ISSUE THREAD

**Issue by kheldaroz-droid** [nhn/tui.grid#1421]
I'm using a MySQL Database and the data in this particular table could update every 250 ms.

I can't find any examples of datasource with the data updating.

It displays the data fine, it just doens't update.

` <script>
        // var Grid = tui.Grid;
        // import Grid from 'tui-grid';
        const dataSource = {
            api: {
                readData: { url: '/WebAI/GetPointViewerData.php', method: 'GET', initParams: { param: 'param' } },
                createData: { url: '/WebAI/GetPointViewerData.php', method: 'POST' }, // need to create these files
                updateData: { url: '/WebAI/GetPointViewerData.php', method: 'PUT' }, // need to create these files
                modifyData: { url: '/WebAI/GetPointViewerData.php', method: 'PUT' }, // need to create these files
                deleteData: { url: '/WebAI/GetPointViewerData.php', method: 'DELETE' } // need to create these files
            }
        };

        const instance = new tui.Grid({
            el: document.getElementById('grid'), // Container element
            // rowHeaders: ['rowNum'],
            // data: treeData,
            //rowHeaders: ['checkbox'],
            //bodyHeight: 500,
            // treeColumnOptions: {
            //     name: 'IOM_Name',
            //     // useCascadingCheckbox: true,
            //     useIcon: true,
            // },
            columns: [
                {
                    header: 'IOM',
                    name: 'IOM_Name'
                },
                {
                    header: 'BACnet ID',
                    name: 'Object_Identifier'
                },
                {
                    header: 'Com Port',
                    name: 'Com_Port'
                },

                {
                    header: 'Channel',
                    name: 'IOM_channel'
                },
                {
                    header: 'BACnet Name',
                    name: 'Object_Name'
                },
                {
                    header: 'Name',
                    name: 'Description',
                    editor: {
                        type: CustomTextEditor,
                        options: {
                            maxLength: 10
                        }
                    }
                },
                {
                    header: 'Value',
                    name: 'value'
                },
                {
                    header: 'Units',
                    name: 'Units_No_Mark_Up',
                    editor: {
                        type: 'select',
                        options: {
                            listItems: [
                                <?php
                                $sql = "SELECT * FROM BACnetUnits";
                                $result = $conProgramDB->query($sql);

                                if ($result->num_rows > 0) {
                                    // output data of each row
                                    while($row = $result->fetch_assoc()) {
                                        echo "{ text: '".$row['Units_No_Mark_Up']."', value: '".$row['idUnits']."' },".PHP_EOL;
                                        //echo "{ text: '".$row['Units']."', value: '".$row['idUnits']."' },".PHP_EOL;
                                    }
                                }

                                ?>

                            ]
                        }
                    },
                },
                {
                    header: 'State',
                    name: 'Label',
                    editor: {
                        type: 'select',
                        options: {
                            listItems: [
                                <?php
                                $sql = "SELECT * FROM OnOffLabels where Source = 'Local'";
                                $result = $conProgramDB->query($sql);

                                if ($result->num_rows > 0) {
                                    // output data of each row
                                    while($row = $result->fetch_assoc()) {
                                        echo "{ text: '".$row['Label']."', value: '".$row['idOnOffLabels']."' },".PHP_EOL;
                                        //echo "{ text: '".$row['Units']."', value: '".$row['idUnits']."' },".PHP_EOL;
                                    }
                                }

                                ?>

                            ]
                        }
                    },
                }
            ],
            data: dataSource
        });
        instance.on('expand', ev => {
            const { rowKey } = ev;
            const descendantRows = grid.getDescendantRows(rowKey);

            console.log('rowKey: ' + rowKey);
            console.log('descendantRows: ' + descendantRows);

            if (!descendantRows.length) {
                grid.appendRow(
                    {
                        name: 'dynamic loading data',
                        _children: [
                            {
                                name: 'leaf row'
                            },
                            {
                                name: 'internal row',
                                _children: []
                            }
                        ]
                    },
                    { parentRowKey: rowKey }
                );
            }
        });

        instance.on('collapse', ev => {
            const { rowKey } = ev;
            const descendantRows = grid.getDescendantRows(rowKey);

            console.log('rowKey: ' + rowKey);
            console.log('descendantRows: ' + descendantRows);
        });

        // instance.resetData(api: { readData: { url: '/WebAI/GetPointViewerData.php', method: 'GET' } }); // Call API of instance's public method

        //instance.applyTheme('striped'); // Call API of static method
        //setInterval(instance.readData(dataSource), 250);
        setInterval(function() {
            instance.readData();
        }, 250)
        //setInterval(instance.request('readData'), 250);
    </script>`

**Comment by kheldaroz-droid** [comment]
this works but its not really what I want it to do, as it causes the grid to reload

` setInterval(function() {
           instance.readData('data'); 
        
        }, 250)`


I only need the "value column to update
![image](https://user-images.githubusercontent.com/74744371/124678750-88a14400-df06-11eb-83e3-17769a4bd9ff.png)

I suspect that it should be something like this

` setInterval(function() {
                 instance.setColumnValues('value','data');
        }, 250)`

It just updates column with the word 'data'
![image](https://user-images.githubusercontent.com/74744371/124678690-68718500-df06-11eb-9983-5781caf4a2ee.png)


Do I need to create a new datasource for SetColumnValues ?

**Comment by kheldaroz-droid** [comment]
Ok I got it working :) - probably a better way to do it but it works 
 so first I had to declare keyColumnName

`const instance = new tui.Grid({
            el: document.getElementById('grid'), // Container element
            keyColumnName:'Object_Identifier',
            // rowHeaders: ['rowNum'],`


then I had to add an ajax call

`  setInterval(function() {
        
            jsonObject = {
                'Object_Identifier' : 'Test',
                'Present_Value' : 'Test '
            }
           // function testAjax(handleData) {
            $.ajax({
                type:'post',
                url:'WebAI/GetPointViewerDataUpdateV1.php',
                data: {pointValues:jsonObject},
                dataType: "script",
                success: function(response) {
                    //console.log('SUCCESS BLOCK');
                   // console.log(response);
                   // handleData(response);

                },
                error: function(response) {
                    console.log('ERROR BLOCK');
                    console.log(response);
                }
            });
         

        }, 250)`

and then I used php to generate the script file

`<?php

require_once "config.php";

//header('Content-Type: application/json');

// Create connection
$conProgramDB = new mysqli($dbhost, $dbuser, $dbpass, $database);
// Check connection
if ($conProgramDB->connect_error) {
    die("Connection failed: " . $conProgramDB->connect_error);

}

$sql = "SELECT * FROM Objects_IOM_Units";

            $result = $conProgramDB->query($sql);
//echo '<script>';
            if ($result->num_rows > 0) {
                while ($WebAI_Object_Names_Data = $result->fetch_assoc()) {
                    if ($WebAI_Object_Names_Data['Object_Type'] == 6 || $WebAI_Object_Names_Data['Object_Type'] == 7 || $WebAI_Object_Names_Data['Object_Type'] == 8) /** binary object */
                    {
                        if ($WebAI_Object_Names_Data['Present_Value'] == 1)
                        {
                            //$array[$WebAI_Object_Names_Data['idObject']] = $WebAI_Object_Names_Data['On'];
                            echo "instance.setValue('".$WebAI_Object_Names_Data['Object_Identifier']."','value','".$WebAI_Object_Names_Data['On']."' );".PHP_EOL;
                        } else {
                         //   $array[$WebAI_Object_Names_Data['idObject']] = $WebAI_Object_Names_Data['Off'];
                            echo "instance.setValue('".$WebAI_Object_Names_Data['Object_Identifier']."','value','". $WebAI_Object_Names_Data['Off']."' );".PHP_EOL;
                        }

                    } else {
                        echo "instance.setValue('".$WebAI_Object_Names_Data['Object_Identifier']."','value','".$WebAI_Object_Names_Data['Present_Value']."' );".PHP_EOL;
                       // $array[$WebAI_Object_Names_Data['idObject']] = round($WebAI_Object_Names_Data['Present_Value'],2);
                    }


                }
            }



mysqli_close($conProgramDB);


?>`

**Comment by js87zz** [comment]
@kheldaroz-droid 
Currently, modifications on the grid are not updated every time, but are executed only when `request` API are explicitly called. Updating data and reloading the entire grid whenever the value is modified can be a performance issue, which is how it works now.
We also believe that improvements are needed on this feature, but it seems difficult to work on it right away.

Thanks!
