### ISSUE TITLE
그리드상에서 여러로우 사이에 새로운로우를 생성할수 있나요?

### ISSUE THREAD

**Issue by kangsue9** [nhn/tui.grid#1422]
이 그리드 로우 사이사이에 다른포맷형식의 새로운 로우를 생성해서 작업을 하려 하는데 

1. 새로운 형식의 포맷형( 새로운 columns[{새로운 컬럼형식 }] )으로 넣을 수 있는지 
2. 서로틀린 포맷형식의 로우로 들어갈 수 있는지
3. 된다면 어떻게 해야하는지 

부탁드립니다. 너무 어렵네요 ㅠㅠ

**Comment by js87zz** [comment]
@kangsue9 
Please make sure you have filled out issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied.

What exactly is the feature you want? Can you show me if you have screenshots or links?
It does not support changing columns dynamically when inserting the row.
