### ISSUE TITLE
How to get the row status of grid?

### ISSUE THREAD

**Issue by dvlmal** [nhn/tui.grid#1424]
I want to get the row status value for editable control of a specific cell.

How can I get the status value of a row?

and How can I control the editable of a cell?

**Comment by js87zz** [comment]
@dvlmal 
Currently, there are no APIs that provide this information. 
Can I know what kind of usability you want? It can help to find an alternative.

**Comment by dvlmal** [comment]
I want to control the grid so that it can be entered in the create row but not in the update row.

I thought it would be possible because it was possible to classify the state when storing data, but there was no way, so I asked.
