### ISSUE TITLE
I cannot update the modified data using dataSource update request

### ISSUE THREAD

**Issue by sunsaladin** [nhn/tui.grid#1429]
I cannot update row data using dataSource. readData works well, but when i want update the row to the server, the api_update.html file is not changed at all at the server side. 

html code ---------------------------------------------------------------------------------------------------------------
!DOCTYPE html>
html>
head lang="en">
	meta charset="UTF-8">
	link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
	script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
/head>
body>
	div id="grid"></div>
	button onclick="grid.request('updateData')">저장</button>

	<script>
        // 웹서버에서 GRID 데이터를 가져오고 수정된 GRID 데이터를 전송하도록 설정한다.
		var clsData = {
			contentType: 'application/json;charset=UTF-8',
			api: {
				readData: { url: 'api_read.html', method: 'GET' },
				updateData: { url: 'api_update.html', method: 'POST' }
			}
		};

        // GRID 를 보여준다.
		var grid = new tui.Grid( {
			el: document.getElementById('grid'),
			columns: [
				{
					header: '이름',
					name: 'name'
				},
				{
					header: '나이',
					name: 'value',
					editor: 'text'
				}
			],
			data: clsData
		} );
	</script>
/body>
/html>
html code end -------------------------------------------------------------------------------------------------------------------------

original api_update.html file
{
	"result": true,
	"data": {    
		"contents": [],
    	        "pagination": {
      		      "page": 1,
      		      "totalCount": 100
		}
         }	
}

original page view
![image](https://user-images.githubusercontent.com/86605661/125183008-d216c980-e24d-11eb-8c1f-4e2607acea16.png)

changing row
![image](https://user-images.githubusercontent.com/86605661/125183028-ee1a6b00-e24d-11eb-9a99-bb65feaf77ae.png)

after click update button,
the original api_update.html is not changed at all.
The api_update.html file has no content

----------------------------------------------------------------------------------------------------------------------------------------
Additionaly, in above code, when i change method of update to "PUT",  the error occurs like below img. Why? 

![image](https://user-images.githubusercontent.com/86605661/125183068-5406f280-e24e-11eb-8dea-e5828c2cb2d5.png)

**Comment by js87zz** [comment]
@sunsaladin 
Is api's endpoint `html`? 
Anyway, in order to update the data, the request API must be called.
```js
grid.request('updateData');
```
