### ISSUE TITLE
contextMenu cannot disable

### ISSUE THREAD

**Issue by zoo-hyeon** [nhn/tui.grid#1432]
## Version
v4.18.0

## Development Environment
Browser: Chrome
OS: Windows 10

## Current Behavior
```js
new Grid({
    ...
    contextMenu: () => { return [] }
})
```
i thought that when contextMenu return empty list, then disable. but it wasn't

## Expected Behavior
When context Menu return empty list or set False then default context Menu disabled.

i'm using [tui-context-menu](https://ui.toast.com/tui-context-menu) for contextMenu previous version. and we've already developed several features using tui-context-menu.

Personally, if contextMenu is added in tui.Grid, I thought that tui-context-menu would be improved and used. Is there a reason you developed it separately?

**Comment by js87zz** [comment]
@zoo-hyeon 
I didn't want to add the dependency.
And it didn't fit internal `preact` structure. 
I'll think about that option. Thank you!

**Comment by pvictor** [comment]
`contextMenu` is a great feature, but it would be nice to be able to deactivate it sometimes.
Thx
