### ISSUE TITLE
How to set variable row height?

### ISSUE THREAD

**Issue by jeiea** [nhn/tui.grid#1433]
**Summary**
I have a field having long character limit. I want show all content of the field by adjusting row's height but it seems tui grid fixes each row's height.
Because it's hard to find ideal height for all rows, I want items to be listed like normal block content.
I don't think there is one, but I'm going to ask first.

**Version**
4.16.1

**Comment by js87zz** [comment]
@jeiea 
Sorry for late replying.
Can you want to adjust the row height with contents as below?
https://nhn.github.io/tui.grid/latest/tutorial-example12-whitespace

**Comment by jeiea** [comment]
I want each row to have different heights.

**Comment by js87zz** [comment]
@jeiea 
As shown in the example above, the height is set according to the content.
```js
const grid = new Grid({
  // set `auto` option
  rowHeight: 'auto',
  columns: [
    {
      header: "whiteSpace: 'nowrap'",
      name: 'nowrap',
      editor: 'text',.
      // set white space you want
      whiteSpace: 'pre'
    },
  ]
});
        
```

**Comment by jeiea** [comment]
You are right. I set row height unawarely. Close this.
