### ISSUE TITLE
edit mode input element keydown event?

### ISSUE THREAD

**Issue by minwooj123** [nhn/tui.grid#1436]
grid version 4.18.1 
javascript + jquery

Columns: [  {
    title: '이름',
    name: 'name',
    editOptions: {
      type: 'text',
      useViewMode: true,
      onKeyDown: function(ev) {
        console.log(ev);                   <=== No Event ?????
      }
    }
  }
]

I'm going to create an AutoComplete function.

**Comment by js87zz** [comment]
@minwooj123 
Please refer [this tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-editor.md). it will be helpful to you.
