### ISSUE TITLE
Height of <tr> is different from the height of <td> when height > 40px

### ISSUE THREAD

**Issue by dndgus482** [nhn/tui.grid#1439]
**Describe the bug**
when the height of rows is more than 40px, I cannot see the last row completely. (Sometimes)

**To Reproduce**
[https://jsfiddle.net/dndgus482/8nwpr4zk/4/](https://jsfiddle.net/dndgus482/8nwpr4zk/4/)
I don't know why it's not working in jsfiddle, but if you try it on Chrome, you can see the bug

**Expected behavior**
The last cell should be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/27889578/126922237-2102e9e4-4d2c-4e3e-a759-93ba71b583f5.png)
As you can see, the border of the cell and the actual cell are in different places.

![image](https://user-images.githubusercontent.com/27889578/126922153-51a81638-b903-4df1-b9d7-0df04252a628.png)
The height of the real cell is 52.62, but the height of tr is 52.

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser Chrome
 - Version 4.18.1

**Additional context**

**Comment by js87zz** [comment]
@dndgus482 
I cannot reproduce it in chrome.
The grid has been rendered properly as below.

![스크린샷 2021-07-28 오전 10 21 18](https://user-images.githubusercontent.com/37766175/127248500-2381db89-0728-4f3b-9a7c-feaebe0b595d.png)

That's weird. What's the chrome version?

**Comment by dndgus482** [comment]
I found it depends not only on browsers but also on servers that render HTML...
I tried on spring + JSP and vscode live server.
and when I tried on safari, it was fine.
Anyways Thank you!
