### ISSUE TITLE
Difference between appendRow and appendRows

### ISSUE THREAD

**Issue by engca** [nhn/tui.grid#1441]
**Summary**
appendRows 를 사용시 ctrl + a 로 전체 선택이 되지 않습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/26476194/128103780-fdba7248-b0b1-4d04-b8e6-28c513c0f6dd.png)
appendRows 사용시 위처럼 선택이 됩니다.
![image](https://user-images.githubusercontent.com/26476194/128103804-e12c31a7-170c-4e09-8ff7-0cc11fad0758.png)
appendRow 사용시 위처럼 제대로 전체선택이 됩니다.

**Version**
"@toast-ui/vue-grid": "=4.17.2"

**Additional context**
안녕하세요.
일단 제가 제대로 사용하지 못하는것일수도 있어서 버그리포트말고 질문으로 남깁니다.
appendRow 를 사용하여 여러 데이터 추가시 ctrl + a 로 전체 선택이 되지만
appendRows 를 사용하여 여러 데이터를 한번에 추가시 ctrl + a 로 전체 선택이 되지 않습니다.
혹시나하여 getSelectionRange 를 사용하여 확인해보았는대
appendRow 사용시 end: [2, 5], start: [0, 0] 이렇게 선택된 범위가 제대로 나오는대
appendRows 사용시 end: [3, 5], start: [0, 0] 이렇게 선택된 범위가 이상합니다.

**Comment by js87zz** [comment]
@engca 
Can you try it in `v4.18.1`?
But if it still doesn't work, thanks for giving me your configuration code in code sandbox?
And Please make sure you have filled out issue respecting our form **in English**.

**Comment by engca** [comment]
Hello.
Sorry for the late reply.
When I tested it in the code sandbox, it worked fine.
The same symptom occurred only in the project I made.
I'm late to reply.
I haven't been able to find the cause of why these symptoms only appear in my projects yet.
If I have any problems or questions in the future, I will write again.
thank you.

**Comment by engca** [comment]
Hello.
It seems you have found the cause.
This phenomenon is found when adding in mounted using vue.
I use a translator to interpret the answers, and I also upload the replies back to the translator, so you may not understand well or you may not understand what I mean.
This is the code sandbox address I tested.
https://codesandbox.io/s/boring-morning-6g3w8?file=/src/App.vue
This is my first time asking github, so I don't know if it's the wrong way.
thank you.
