### ISSUE TITLE
Selected cell border is wrong when row has variable height

### ISSUE THREAD

**Issue by jeiea** [nhn/tui.grid#1449]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4188984/130170208-e0e62a39-cff6-4d5c-926f-9fa48038191b.png)

**To Reproduce**
[codesandbox](https://codesandbox.io/s/tui-grid-report-bn9p8)

**Expected behavior**
The blue border should exactly wrap 'Birdy' cell.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google chrome
 - Version: latest

**Comment by js87zz** [comment]
@jeiea 
Can you add `rowHeight: auto` option as below?
```js
ew TuiGrid({
  el: document.getElementById('app')!,
  data: gridData,
  rowHeight: 'auto'
  // ...
});
```

**Comment by jeiea** [comment]
It worked. Why `'auto'` is not applied? Documentation says [it is default](https://github.com/nhn/tui.grid/blob/43a41b1fcdb1d9f3f3603638ab966077c9a04c9b/packages/toast-ui.grid/docs/ko/setting-width-height.md#%EB%86%92%EC%9D%B4-%EC%84%A4%EC%A0%95).

**Comment by js87zz** [comment]
@jeiea 
The document is wrong.. 
I will fix it. Thanks!
