### ISSUE TITLE
Date filter: equals not working with another format

### ISSUE THREAD

**Issue by pvictor** [nhn/tui.grid#1452]
**Describe the bug**
I have trouble using another format than the default one `yyyy/MM/dd`, if I set `filter.format = 'yyyy-MM-dd'` then : 
* format is not applied in date picker box
* equal filter don't work

**To Reproduce**
Here's a jsfiddle: https://jsfiddle.net/sh2x8tda/1/

Here's my configuration:

```js
const grid = new Grid({
  el: document.getElementById('grid'),
  data,
  columns: [
    {
      header: 'ID',
      name: 'id'
    },
    {
      header: 'DATE',
      name: 'date',
      filter: {
      	type: 'date',
        format: 'yyyy-MM-dd'
      }
    },
    {
      header: 'DATE2',
      name: 'date2',
      filter: {
      	type: 'date'
      }
    },
    {
      header: 'CITY',
      name: 'city',
      editor: 'text'
    },
    {
      header: 'COUNTRY',
      name: 'country'
    }
  ]
});
```

**Expected behavior**
When selecting a date present in the grid with equal filter, it should return one row.

**Screenshots**

With custom format: format not applied and no row
![image](https://user-images.githubusercontent.com/4415580/130570709-d4b5b306-2cbf-424b-8221-63683680a4fa.png)

With default format: all good
![image](https://user-images.githubusercontent.com/4415580/130570782-fe1ce5bb-59e9-4e87-bcbb-3ea29bf94c79.png)

**Desktop (please complete the following information):**
Browser: 
* Firefox version 85.0.2
* Brave Version 1.28.106 Chromium: 92.0.4515.159 (Build officiel) (64 bits)

Thanks for your help!

**Comment by js87zz** [comment]
@pvictor 
Thanks for reporting. I will fix it!

**Comment by jajugoguma** [comment]
@pvictor 
The cause of this problem is that you passed the option in the wrong form.
To set the format to the date picker, you need to pass the options in the form below.
```js
const grid = new Grid({
  // ...
    {
      header: 'DATE',
      name: 'date',
      filter: {
      	type: 'date',
        options: {
          format: 'yyyy-MM-dd'
        }
      }
    },
// ...
});
```

I've noticed that the example is wrong, and I'll fix it in the right way. Thanks!

**Comment by pvictor** [comment]
Indeed, it works fine like that. 
Thank you !
