### ISSUE TITLE
Transfer data from grid to server.

### ISSUE THREAD

**Issue by minwooj123** [nhn/tui.grid#1459]
Transfer data from grid to server
Can we do it'sir?
1. Total data shown after filter
2. Complete data in the grid

Implementing download of grid data to Excel.

tui.grid vesion : 4.18.1 + jquery

**Comment by js87zz** [comment]
@minwooj123 
The Excel export feature is not yet supported, but it is currently under development. 
We need a detailed explanation of server transfer of data. Do you want to save the filtered data through communicating with the server?

**Comment by minwooj123** [comment]
I'm making it.
If you filter on the grid, there is data, but I want to send the data in that state to the server.
The documentation only sends the selected values.

**Comment by js87zz** [comment]
@minwooj123 
You want an API that only provides filtered data, right? 
I should add this API later.

**Comment by minwooj123** [comment]
That's right.
Current full data is grid.getData()
I know, but I don't know the filtered data.
Thank you for your response.
