### ISSUE TITLE
Flexible width

### ISSUE THREAD

**Issue by gisellekim** [nhn/tui.grid#1464]
**Summary**
Is it possible to make the width flexible by dragging the line like the previous version?

**Screenshots**
Original
![image](https://user-images.githubusercontent.com/69022097/132150135-68cd8c1f-058b-4c6e-ab5f-265f4ce87bab.png)

After dragging
![image](https://user-images.githubusercontent.com/69022097/132150151-66bb16c6-4a18-4311-88a6-feb3f41304fc.png)

**Version**
4.16.1

**Comment by js87zz** [comment]
@gisellekim 
You can control the width as below
```js
const grid = new Grid({
  // ...
  columnOptions: {
    resizable: true
  },
})
```

**Comment by gisellekim** [comment]
Thank you
