### ISSUE TITLE
Is there any way to specify the grid pagination holder?

### ISSUE THREAD

**Issue by parkx** [nhn/tui.grid#1470]
**Summary**
Is there any way to specify the grid pagination holder?

**Screenshots**
N/A

**Version**
4.8

**Additional context**
Currently, the holder element is automatically created inside the grid holder, 
can't it be changed to an element in a different position?

**Comment by js87zz** [comment]
@parkx 
Sorry for late replying.
I think you can implement the desired pagination component using the [`resetData`](https://nhn.github.io/tui.grid/latest/Grid#resetData) API.
