### ISSUE TITLE
Custom tree grid expand/collapse icons

### ISSUE THREAD

**Issue by atmgrifter00** [nhn/tui.grid#1473]
Is there a suggestion/pattern you have for supplying cells (specifically the first cell in a row) in a tree grid setup a custom icon if that row has any children or not? Essentially I want to replace the folder icon being used for groups with an arrow icon (which changes between expanded and collapsed states), and no icon for leaf level rows.

The result would ideally look something like the following:
![image](https://user-images.githubusercontent.com/26874831/135327223-7b591fbd-a8b1-4860-98ec-3f3930b6a886.png)

Thanks!

**Comment by atmgrifter00** [comment]
I believe I have figured out the approach I need. I'll close this out.

**Comment by vlcAitac** [comment]
@atmgrifter00 Hi, I'm trying to add custom icons and haven't managed to accomplish it. Do you maybe remember how you solved the issue?

**Comment by atmgrifter00** [comment]
Oh geez, no. Our team ultimately went with a separate package for accomplishing what we need. I have no idea what this would have been. Sorry.

**Comment by vlcAitac** [comment]
Thank you for your time anyway :)
