### ISSUE TITLE
한 화면내에 스타일이 다른 그리드를 여러개 사용하려고 합니다

### ISSUE THREAD

**Issue by walnut02** [nhn/tui.grid#1482]
Version
toast ui grid 4.19.1
Angular CLI: 12.2.7
Node: 14.15.4
Package Manager: npm 7.21.0
OS: win32 x64

Development Environment
Chrome

Current Behavior
한 화면내에 스타일이 다른 그리드를 여러개 사용하려고 하는데
applytheme를 그리드별로 각각 다르게 적용할 수 있는지 궁금합니다.

**Comment by js87zz** [comment]
@walnut02 
Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. If not, the issue will be closed or not replied.
