### ISSUE TITLE
Pagination issue in IE 11

### ISSUE THREAD

**Issue by soo-ni** [nhn/tui.grid#1484]
**Summary**

[KO]
안녕하세요, pagination 관련해서 질문 드립니다.
chrome에서는 datasource와 setPerPage를 이용해 pagination이 잘 되고 있습니다.
IE 11의 경우 아래 오류 예시와 같이 문제가 발생하고 있습니다. (스크린샷 첨부)

오류 예시)
* 데이터 총 1586건 조회
  - 100건씩 보이게 하는 경우: 페이지 1개 생성
  - 1000건씩 보이게 하는 경우: 페이지 10+n개 생성

해당 오류가 IE 에서만 발생하는 이유를 알 수 있을까요?

[EN]
Hello, I have question about pagination.
In chrome, pagination is working fine by using datasource and setPerPage method.
But in IE 11, a problem is occurring as shown in the error example below. (Screenshot attached)

Error ex)
* A total datas: 1586
  - In case of 100 row limits: Create 1 page
  - In case of 1000 row limits: Create 10+n pages

Could you please check what the problem is in IE?

**Screenshots**
![image](https://user-images.githubusercontent.com/19357410/136447973-d4e84e74-4947-42c6-b1d4-5c3e139f0886.png)
![image](https://user-images.githubusercontent.com/19357410/136447927-f7406c04-8865-4bd4-8ca1-f622990b5ee3.png)
![image](https://user-images.githubusercontent.com/19357410/136446602-40ec1e87-828b-451a-8e70-d3ee9677bf68.png)

**Version**
- Vue.js
- tui-grid: 4.18.1
- Internet Explorer: 11

**Comment by jajugoguma** [comment]
@soo-ni 
Sorry for late replying.
Can you give me sample data for reproduction?
I will additional reply after checking this problem.
