### ISSUE TITLE
each APPLYTHEME 

### ISSUE THREAD

**Issue by walnut02** [nhn/tui.grid#1486]
Version
toast ui grid 4.19.1
Angular CLI: 12.2.7
Node: 14.15.4
Package Manager: npm 7.21.0
OS: win32 x64

Development Environment
Chrome

I want to use several TUI-GRID TABLE with different styles in one screen.
I wonder if the APPLYTHEME can be used differently for each TUI-GRID TABLE.

**Comment by jajugoguma** [comment]
@walnut02 
Sorry for late replying.
The themes can only be set globally, so you cannot set different themes for different grid instances.
