### ISSUE TITLE
_attributes Bug?

### ISSUE THREAD

**Issue by minwooj123** [nhn/tui.grid#1497]
i'm using php

my data set
$list['data']['contents'][0]['_attributes']['className']['column']['m_name']="Myclass";

grid set class name Myclass

![image](https://user-images.githubusercontent.com/87161007/139999922-e2bae15d-e986-4514-bfd5-50f2fb7da651.png)

The space between the class names...
It happens.

Myclass -> M y c l a s s 

Is this a bug?

I'm using the last version of tui grid. V.4.19.2

**Comment by jajugoguma** [comment]
@minwooj123 
Can you give your sample code using such as code sandbox? I want to know more detail.
