### ISSUE TITLE
Questions about encryption.

### ISSUE THREAD

**Issue by tackiyo** [nhn/tui.grid#1498]
안녕하세요.
저는 자바스크립트와 스프링 프레임워크 환경에서 개발 중입니다.
AES알고리즘으로(CryptoJs) 그리드 데이터를 암호화하여 서버로 전달하려고 합니다.
이를 위해 제공되는 API 또는 Ajax 옵션이 있습니까?

-----------------------------------
Hello
I am developing in JavaScript and Spring Framework environment.
I want to encrypt grid data with the AES algorithm (CryptoJs) and forward it to the server.
Are there API or Ajax options provided for this?

**Comment by jajugoguma** [comment]
@tackiyo 
There is no API provided for it.
If you want to do it, you need to get and post-process the data using APIs such as 'getData'.
