### ISSUE TITLE
on(eventName, fn) - Question

### ISSUE THREAD

**Issue by js7309** [nhn/tui.grid#1504]
안녕하세요.
이벤트 api 등록 할 때

<div id="on" class="definition-list" style="margin: -40px 0px 0px; padding: 0px 0px 40px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-bottom-color: rgb(238, 238, 238); border-left-color: initial; border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: inherit; font-family: Arial, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><dl style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><dt class="subsection-term" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><h4 class="title" style="margin: 0px 0px 16px; padding: 0px 200px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: 0px; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(34, 34, 34); position: relative;"><span class="name" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: 20px; line-height: inherit; font-family: inherit; vertical-align: middle; color: rgb(51, 51, 51);">on(<span class="param" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">eventName</span>,<span class="param" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span> </span>fn</span>)</span></h4></dt><dd class="subsection-description" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><p class="description" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: 1.4em; font-family: inherit; vertical-align: baseline; color: rgb(119, 119, 119);">Add custom event to grid.</p><div class="params-wrapper" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; overflow-x: auto;"><h5 class="title" style="margin: 0px; padding: 24px 0px 6px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: inherit; vertical-align: baseline; color: rgb(85, 85, 85);">PARAMETERS</h5>

Name | Type | Description
-- | -- | --
eventName | string | custom event name
fn | function | event handler

</div></dd></dl></div><div id="prependRow" class="definition-list" style="margin: -40px 0px 0px; padding: 0px 0px 40px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-bottom-color: rgb(238, 238, 238); border-left-color: initial; border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: inherit; font-family: Arial, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><dl style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><dt class="subsection-term" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><br class="Apple-interchange-newline">

이렇게 되어 있는데, 펑션 안에 사용자 정보를 전달 하는 인수를 넣어 주실 수 있을까요?

on(eventName, object, fn)

이런식으로 말이죠.
                     var myArray = new Array();
		    

                 grid1.on('click',   { test1 : "111" , test2 :  myArray } ,  function(ev) {  
			console.log("  test1 ====> " + ev.data.test1);
			console.log(" test2  ====> " + ev.data.test2.length);
		    });

**Comment by jajugoguma** [comment]
@js7309 
You just declare the data what you want externally and use it. So we have no plans to add this.
And please fill out the form next time
