### ISSUE TITLE
그리드 셀 선택할 때 값을 가져오고 싶습니다.

### ISSUE THREAD

**Issue by cheolhwajeong** [nhn/tui.grid#1514]
grid.on('click', (ev) => {
        const { columnName, rowKey} = ev;
        alert(rowKey);
이렇게 하면 클릭한 rowKey나 컬럼명은 잘 가지고 오는데 클릭한 셀의 value는 어떻게 가져올까요?
const { columnName, rowKey} = ev;에 getColumnValues, getValue등등 을 추가해서 확인하면 undefined만 나옵니다.
참고할만한 예제가 있다면 부탁드립니다.

**Comment by jajugoguma** [comment]
@cheolhwajeong 
To get the value when a grid cell is clicked, you can use the `getValue` API.
```ts
grid.on('click', (ev) => {
  const {rowKey, columnName} = ev;
  grid.getValue(rowKey, columnName);
});
```

And next time, please fill in the form. Thanks!
