### ISSUE TITLE
API command .filter does not work 

### ISSUE THREAD

**Issue by attyskater** [nhn/tui.grid#1516]
Using the .filter command of the API gives an error in the console

1. Go to https://jsfiddle.net/fuL2wzom/
2. Run
3. Watching errors in console

 - OS: Windows 10
 - Browser Brave

**Comment by jajugoguma** [comment]
@attyskater 
Wrong way to use filter API.
To make it work properly, you should use it as follows.
```ts
const state = {
  code: 'eq',
  value: 'Pop'
};
    
grid.filter('genre', [state]);
```

Please check [the document](https://nhn.github.io/tui.grid/latest/Grid#filter) for the exact usage of the filter API.

**Comment by attyskater** [comment]
Thanks for the reply now I will try your suggestion. I read the documentation but then followed the examples found here (there seems to be an error from what you reported): https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/filter.md

**Comment by jajugoguma** [comment]
@attyskater 
Thank you for report it.  I'll correct the document.

**Comment by attyskater** [comment]
Thank you!
