### ISSUE TITLE
Make New Header

### ISSUE THREAD

**Issue by Yadon079** [nhn/tui.grid#1518]
**Summary**

I want to make a new header when i clicked button.

for example, when i make grid like this

|----------|
|      A      |         B        |         C      |      <--- header
|----------|
|      a      |          b        |         c      |       <--- data
|----------|

and i want to add columns.

so i checked F from list [D, E, F]. then grid append F columns like this

|-------------|
|      A      |         B        |         C       |         F     |  <--- header
|-------------|
|      a      |          b        |         c       |         f      |  <--- data
|-------------|

is it possible when i use custom column header?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
latest version 4.19.4

**Additional context**

**Comment by jajugoguma** [comment]
@Yadon079 
There is no way to set a custom renderer for columns set later.
Another way is to hide columns that you do not need to show immediately after creating them for all columns.

```ts
const grid = new tui.Grid({
  // ...
  columns: [
    // ...
    {
      name: 'F',
      hidden: true,
    }
  // ...
});

// When want to show column F
grid.showColumn('F');
```

**Comment by Yadon079** [comment]
@jajugoguma 
I am solved this problem another method

Using DataSource and Object Arrays

Thanks!
