### ISSUE TITLE
토스트Grid의 context menu에 관련된 질문입니다. 

### ISSUE THREAD

**Issue by leeheejoong** [nhn/tui.grid#1519]
만들다 보니 toast grid 기본 샘플 페이지에서는 context menu가 기본적으로 표시되는데

샘플페이지와 똑같이 구현해보니 구현되지 않습니다. 그래서 toast ui에 포함된 context menu를 사용하여

만들어 보았지만 우측 클릭시 엉뚱한곳에 메뉴가 만들어지는 현상을 겪고 있습니다. 

context menu를  toast grid에서 사용하려면 어떻게 해야할까요

**Comment by jajugoguma** [comment]
@leeheejoong 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.
And Can you give us detail code in code sandbox or jsfiddle?

**Comment by leeheejoong** [comment]
@jajugoguma  
when i checked your page in sample i can see the context menu. but  i just made same page  i can't see context menu.
how can i use context menu in my page.  
i attached my code. it is works. but it has bug. 


https://jsfiddle.net/tsjckh58/

**Comment by jajugoguma** [comment]
@leeheejoong 
The example code does not work and the grid does not use tui.context-menu. 
Can you give another example that works properly and use contextMenu of grid?

**Comment by leeheejoong** [comment]
@jajugoguma  so could you tell me how to use context-menu in grid..
my example does not working.

**Comment by jajugoguma** [comment]
@leeheejoong 
If you follow the context menu example in the grid, you can use the context menu.
You said that you followed the example, but it doesn't work properly, so I'd like to see the code for how you wrote it.
If you give me the example code, I'll check it out and tell you how to fix it.

**Comment by leeheejoong** [comment]
i just follow basic grid sample.  i couldn't found any context menu example in the gird. if u have context menu example in the grid. 
could u give me sample url or sample source or  jsfiddle.. thx

**Comment by jajugoguma** [comment]
@leeheejoong 
How about [export example](https://nhn.github.io/tui.grid/latest/tutorial-example27-export)?
Implementing using the contextMenu options in this example doesn't work?

**Comment by leeheejoong** [comment]
@jajugoguma i just sent u  my sample page

**Comment by jajugoguma** [comment]
@leeheejoong 
The bundle path is invalid.
`https://uicdn.toast.com/grid/latest/tui-grid.js` is the correct path as shown in [REAMDME.md](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/README.md).

**Comment by leeheejoong** [comment]
omg it's work thx so much
