### ISSUE TITLE
그리드의 로우 및 셀 높이 변경 시 포커스 및 에디터창 위치 버그

### ISSUE THREAD

**Issue by js7309** [nhn/tui.grid#1521]
**Describe the bug**

그리드의 로우 및 셀 높이를 기본 40px이 아니고 작게 사용 하기 위해서 조정 하면
포커스 및 에디터 창이 이상한 위치에서 생김

**To Reproduce**
1.  http://jsfiddle.net/js7309/f12rp53w/
2. 실행 후 실행 된 로우를 선택 하거나 더블클릭 했을 경우 포커스 및 에디터 창이 이상하게 움직임

**Expected behavior**

**Screenshots**

<img width="457" alt="스크린샷 2021-11-19 오후 6 56 51" src="https://user-images.githubusercontent.com/5871324/142603551-04edfd3f-29f6-424c-aea9-6346e187f45d.png">

<img width="457" alt="스크린샷 2021-11-19 오후 6 57 30" src="https://user-images.githubusercontent.com/5871324/142603582-852c4075-921b-4575-badc-0ca620d9e260.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version:  95.0.4638.54(공식 빌드) (x86_64)

**Additional context**

**Comment by jajugoguma** [comment]
@js7309 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

**Comment by YoungHoonZo** [comment]
> @js7309 Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

I have a similar experience.
When I tested, when the rowHeight value is 20, the same symptoms are coming out.
https://jsfiddle.net/gizmo80/c4rjkt67/19/

**Comment by jajugoguma** [comment]
@YoungHoonZo @js7309 
I'll fix it. Thanks!
