### ISSUE TITLE
Is there a way to handle unmount in custom renderer?

### ISSUE THREAD

**Issue by jeiea** [nhn/tui.grid#1522]
**Summary**
I have some unclear issue with my project, in the meantime I have curiosity about how to handle tui.grid destruction in custom renderer.
I couldn't find any guide in [custom renderer documentation](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-renderer.md).

**Screenshots**
N/A

**Version**
4.19.3

**Comment by jajugoguma** [comment]
@jeiea 
May I know what exactly you are curious about grid destruction in the custom renderer?

**Comment by jeiea** [comment]
I have a difficulty when using material ui button component in tui.grid. I'm using it by `ReactDOM.render` and it may not be intended usage, but it works on some degree. Current problem is when I destroy tui.grid before MUI button's ripple effect is finished, it throws error because MUI try to access the element which is deleted by tui.grid. I can't find the way to prevent this except to disable ripple effect.

**Comment by jajugoguma** [comment]
@jeiea 
It seems like that you should add a beforeDestroy method to your custom renderer class and let that method performs to remove the MUI element.

```ts
class CustomRenderer {
  // ...
  beforeDestroy () {
    // Do what you want
  }
  // ...
}
```

**Comment by jeiea** [comment]
I couldn't solve my original problem but it's what I'm searching. Close this issue.
