### ISSUE TITLE
버튼을 클릭하면 특정 컬럼을 숨기고 보이고 하고싶은 데 어떻게 해야할까요?

### ISSUE THREAD

**Issue by TechLogi** [nhn/tui.grid#1524]
버튼을 하나 만들고
해당 버튼을 클릭하면 특정 컬럼을 toogle 하는 기능을 구현하고 싶은데 어떻게 접근해야할까요?

**Comment by Yadon079** [comment]
if you make column, Using show and hide
check this api docs -> https://nhn.github.io/tui.grid/latest/Grid#showColumn

**Comment by jajugoguma** [comment]
@TechLogi 
You can do that by calling [`hideColumn`](https://nhn.github.io/tui.grid/latest/Grid#hideColumn), [`showColumn`](https://nhn.github.io/tui.grid/latest/Grid#showColumn) on the button.
