### ISSUE TITLE
unique validation about editable cell

### ISSUE THREAD

**Issue by spicyyou** [nhn/tui.grid#1525]
Hello.
I would like to use unique validation in editable cell.
but if the cell is blank it shows red.
And also I want the red box to be invisible when I use disabled option.
``` javascript
validation: {
        unique: true
      }
```
Thank you.

### 한글 번역
안녕하세요.
현재 validation의 unique 옵션을 사용하고 싶습니다. 그런데
셀이 editable할 때 값이 빈값이어도 unique처리가 됩니다. 빈값이 아닐때만 unique처리하는 방법이 없을까요?
또한 셀이 disabled할 때도 unique해집니다. disabled가 우선적으로 처리될 방법이 있을까요? 감사합니다.

**Comment by jajugoguma** [comment]
@spicyyou 
If there is only one cell with an empty value, this is the intended behavior because that cell is unique.
Is it a question of style to say that cells become unique even when disabled?
