### ISSUE TITLE
Block dblclick editing

### ISSUE THREAD

**Issue by Yadon079** [nhn/tui.grid#1526]
**Summary**
I have created multiple grids. Among them, Some grids that work by double-clicking and Other grids that do not work. 
So I want to block the double click event all grid, I tried the method `grid.off('dblclick')` but it doesn't apply.

**Screenshots**

**Version**
latest Version

**Additional context**

**Comment by jajugoguma** [comment]
@Yadon079 
You can prevent double-click editing by using the following:
```ts
grid.on('dblclick', ev => {
  ev.stop()
});
```

**Comment by Yadon079** [comment]
Thanks! I try it and done!
