### ISSUE TITLE
useClient pagination bug?

### ISSUE THREAD

**Issue by Yadon079** [nhn/tui.grid#1527]
**Summary**
Can I use multiple client pagination at the same time?
I generated two grids on one page and used client pagination. Only the grid is not loaded and the page freezes.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Latest Version

**Additional context**

**Comment by jajugoguma** [comment]
@Yadon079 
Can you give example code in code sandbox or jsfiddle to solve your issue?
