### ISSUE TITLE
using cdn service questions

### ISSUE THREAD

**Issue by YoungHoonZo** [nhn/tui.grid#1532]
using vue cdn service. and toast grid too cdn service.
vue.js : 2.6.14
toastui-vue-grid.js : 4.19.4

<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@2.21.2/dist/bootstrap-vue.min.css" />
    <link rel="stylesheet" href="https://uicdn.toast.com/grid/v4.19.4/tui-grid.css" />

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@toast-ui/vue-grid@4.19.4/dist/toastui-vue-grid.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.24.0/axios.min.js" integrity="sha512-u9akINsQsAkG9xjc1cnGF4zw5TFDwkxuc9vUp5dltDWYCSmyd0meygbvgXrlc/z7/o4a19Fb5V0OUE58J7dcyw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/bootstrap-vue@2.21.2/dist/bootstrap-vue.min.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue-icons.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            new Vue({
                el:'#app',
                data() {
                    return {
                        columns: [
                            // for columnData prop
                            {
                                header: 'Name',
                                name: 'name'
                            },
                            {
                                header: 'Artist',
                                name: 'artist'
                            }
                        ]
                    }
                },
                // components:{
                //     'toast-grid':toastGridComp,
                // },
                methods: {
                }
            });
        })
    </script>
</head>
<body>

    <div id="app" class="container">
        <grid ref="tuiGrid"
              :columns="columns"
              :scrollX="scrollX"
              :scrollY="scrollY" ></grid>
    </div>

</body>
</html>

When I run the above source, an error occurs. Below is the error message.
Please advise if there is a solution.

toastui-vue-grid.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Grid')
    at toastui-vue-grid.js:1
    at toastui-vue-grid.js:1
(익명) @ toastui-vue-grid.js:1
(익명) @ toastui-vue-grid.js:1

# Added
I tried adding a dependency.
There is no error, but nothing.
https://jsfiddle.net/gizmo80/qLcrkw03/3/

**Comment by jajugoguma** [comment]
@YoungHoonZo 
The wrapper does not support CDN services. Please use npm install.
