### ISSUE TITLE
Can I use "tui-time-picker" like "tui-date-picker"?

### ISSUE THREAD

**Issue by vnfjri123** [nhn/tui.grid#1534]
How can I use it if I can?

**Comment by vnfjri123** [comment]
Like "https://nhn.github.io/tui.grid/latest/tutorial-example08-date-picker'".

**Comment by jajugoguma** [comment]
@vnfjri123 
No. Currently, only the date picker is supported, so it is not possible to add a time picker as above.
You should use a [custom editor](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-editor.md).

**Comment by vnfjri123** [comment]
thanks :)
