### ISSUE TITLE
그리드에서 특정 값이면, 그 해당 컬럼의 배경색을 변경하는 방법

### ISSUE THREAD

**Issue by Limky** [nhn/tui.grid#1541]
제목 그대로 그리드에서 서버로 부터 불러온 값이 특정 값이면, 그 해당 컬럼의 배경색을 변경하는 방법이 있을까요?
일단 서버로 부터 불러온 값을 특정값인지 체크하는 로직이 있어야할 것 같고 특정값이면 해당 컬럼에 배경색을 변경해주어야 하는데...
따로 tui-grid 예제에는 없는 것 같아서 문의드립니다. ^^..

**Comment by jajugoguma** [comment]
@Limky 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

The Validation feature allows you to check if a cell is a specific value.
If you want to designate a separate color for multiple values, you must implement it yourself by using `addCellClassName`.

**Comment by singsinghe** [comment]
일단 업데이트가 되었는지 체크하는 함수가 들어가야 하구요. 

    grid.on('onGridUpdated',ev=>{
      chkRowColor(); 
    }); 

     // loc라는 컬럼의 값을 체크한다고 가정할때
       function chkRowColor(){

var cnt = grid.getRowCount();   
for(i=0; i<=cnt; i++){

  a = grid.getValue(i,"loc");                       
  
   if(a=='입고완료'){     
        grid.addRowClassName(i,"bg-green");  
   } 
} 
}

값이 입고완료일 경우 bg-green이라는 클래스를 적용하는 기능입니다.

**Comment by Limky** [comment]
> 일단 업데이트가 되었는지 체크하는 함수가 들어가야 하구요.
> 
> grid.on('onGridUpdated',ev=>{ var cnt = grid.getRowCount(); for(i=0; i<=cnt; i++){ a = grid.getValue(i,"loc"); if(a=='입고완료'){ grid.addRowClassName(i,"bg-green"); } } });
> 
> 값이 입고완료일 경우 bg-green이라는 클래스를 적용하는 기능입니다.

답변 주셔서 감사합니다~ 혹시, bg-green 클래스 선언은 어떻게 하셨는지 알 수 있을까요 ? (선언위치, 선언부내용 등)

**Comment by Limky** [comment]
해결했습니다. 감사합니다.
