### ISSUE TITLE
Header CheckBox

### ISSUE THREAD

**Issue by Yadon079** [nhn/tui.grid#1546]
**Summary**
I want to make checkbox in header like Screenshots.
Can i make this use custom renders?

**Screenshots**
![image](https://user-images.githubusercontent.com/39683512/148528864-bfa7e556-e70a-4bfa-9774-1c18921332f9.png)

**Version**
latest Version

**Additional context**

**Comment by jajugoguma** [comment]
@Yadon079 
Currently, there is no way to create a checkbox in the header area.
Also, custom renderers cannot be applied in the header area.

**Comment by Yadon079** [comment]
oh...okay! thank you for answer :)
