### ISSUE TITLE
How to get rowKey for delete?

### ISSUE THREAD

**Issue by cheolhwajeong** [nhn/tui.grid#1548]
**Summary**
 I need to get the rowKey of the selected row as a variable. How can I get it?

**Version**
TUI Latest Version
Windows10
Chrome 96.0.4664.110

**Additional context**

I would like to delete the row I selected without using the checkbox.
```js
function delRow(){
    grid.removeRow(rowKey);
)
```
To use the above code, I need to get the rowKey of the selected row as a variable. How can I get it?
Could you provide sample code, please?

**Comment by jajugoguma** [comment]
@cheolhwajeong 
It seems that you can perform the desired action by using the following.

```js
function deleteFocusedRow() {
  const rowKey = grid.getFocusedCell().rowKey
  if(rowKey) {
    grid.removeRow(rowKey);
  }
}
```

**Comment by cheolhwajeong** [comment]
@jajugoguma 
Thanks for providing great sample code.
But there seems to be a bug when using that code. Failed to delete row 0.
So I solved it by applying the following:
```js
function deleteFocusedRow() {
    const rowKey = grid.getFocusedCell().rowKey
    if(rowKey==0) {
        grid.removeRow(rowKey);
    }
    else if(rowKey) {
        grid.removeRow(rowKey);
    }
}
```
