### ISSUE TITLE
multiple label select box

### ISSUE THREAD

**Issue by bso-oo** [nhn/tui.grid#1549]
안녕하세요

![image](https://user-images.githubusercontent.com/74163829/149048757-d520bffe-15f5-44ce-bab8-52e6075d5757.png)

그리드에도 위와 같이 label 적용이 가능할까요?

**Comment by jajugoguma** [comment]
@bso-oo 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

The built-in select box editor cannot apply labels.
You should create a custom editor if you want to apply it.

**Comment by bso-oo** [comment]
> 

Hi, 대연~~~~ Is it available on Vue, too?
