### ISSUE TITLE
How to use v-model in tui-grid?

### ISSUE THREAD

**Issue by sewoongKim-ray** [nhn/tui.grid#1551]
Hello team, 
I am making a tui-grid for vue,
and I wonder whether it is possible to use v-model for tui-grid or not.
I tried to find some examples, but there was only using v-model for tui-vue-editor.
if it is possible, how can I use it? please give some examples.

thank you and happy new year

**Comment by bso-oo** [comment]
데이터 바인딩 하시는건가요?
```javascript
<grid
          ref="grid"
 />
 ```
 this.$refs.grid.invoke('resetData', res.data);

**Comment by sewoongKim-ray** [comment]
gridProps.data 객체에 변경사항이 계속 반영 --> 이 부분이 안되는것 같아요, 처음 써봐서 제가 방법을 못 찾는것 같기도 하고..

**Comment by sewoongKim-ray** [comment]
this.$refs.tuiGrid2.invoke('getModifiedRows').updatedRows 이런식으로 받아와서 해결 했습니다
