### ISSUE TITLE
can i disable checkbox(all checkbox) in the rowheader???

### ISSUE THREAD

**Issue by zerothree3782** [nhn/tui.grid#1556]
Hello 

is there any way to disable checkbox(all checkbox) in the rowheader??

thank you.

**Comment by chohyunjik2** [comment]
안녕하세요.

전체선택 버튼의 헤더를 disabled 시키는 방법은 아래와 같습니다.

1) disabled
var rowHeaders = ['rowNum', {
                type: 'checkbox',
                header: `<input type="checkbox" id="all-checkbox" class="hidden-input" name="_checked" />`
}];

수동 disabled
$('.hidden-input').prop('disabled', true);

2) hidden 
var rowHeaders = ['rowNum', {
                type: 'checkbox',
                header: `<input type="checkbox" id="all-checkbox" class="hidden-input" name="_checked" hidden />`
}];

hidden은 숨기는 기능인데 비슷한 구조로 생각되어 올립니다.
disabled은 hidden 처럼 attr를 넣어주어도 적용이 안되며 disabled 의 경우 그리드 로드이후 script 처리 해주시면 됩니다. 
저의 경우 jquery으로 작성하였습니다.

**Comment by jajugoguma** [comment]
@chohyunjik2 
Currently there is only `disableRowCheck` API which disables only one row's checkbox.
So if you want to disable the checkbox for all rows, you should do this action for them.
I'll consider adding the feature to disable checkboxes for all rows.
Thanks!
