### ISSUE TITLE
Is it possible to apply a vertical layout?

### ISSUE THREAD

**Issue by sewoongKim-ray** [nhn/tui.grid#1560]
Hello team, 
I am making a new tui-vue grid, My question is, is it possible when a user click a button, then the grid appears as  transposed form.
for example

before transpose ---- 

firstname  lastname  address
 john         david        UK
alex          stewart      copenhagen           
------------------------------------------------------
transposed form ----

firstname  john   alex
  lastname  david stewart
  address    UK     Copenhagen**

like this. if it is possible, please give me some sample code.
thank you

**Comment by sewoongKim-ray** [comment]
I have no Idea why the font size can not be handled ;;

before transpose ----
firstname lastname address
     john         david       UK
    alex         stewart    Copenhagen

transposed form ----

firstname  john   alex
  lastname  david stewart
  address    UK     Copenhagen

**Comment by jajugoguma** [comment]
@sewoongKim-ray 
Unfortunately, that feature is not supported.
