### ISSUE TITLE
row merge of large data..help

### ISSUE THREAD

**Issue by xhlrmsgkrhtlvek** [nhn/tui.grid#1562]
**Summary**
A clear and concise description of what the question is.
- row merge of large data is wrong,,
- 대용량 데이터를 병합하면 이상하게 나와요

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.
- It's being tested for a new grid. So I'm using cdn.
- 아직 테스트 중이라 cdn을 사용중입니다.
- <script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>
- < link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />

**Additional context**

HI,,
This code is a slight variation of https://nhn.github.io/tui.grid/latest/tutorial-example25-large-data-performance

안녕하세요,,
이 코드는 https://nhn.github.io/tui.grid/latest/tutorial-example25-large-data-performance 를 조금 변형한 코드에요

===============================================
    const ROW_COUNT = 1000;
    const COL_COUNT = 2;

    const data = [];
    const columns = [];

    for (let i = 0; i < ROW_COUNT; i += 1) {
      const row = { id: i };
      row['c0'] = 'sales '+ i.toFixed().substring(0,1);
      row['c1'] = i;
      data.push(row);
    }
    for (let i = 0; i < COL_COUNT; i += 1) {
      const name = `c${i}`;
      columns.push({ name, header: name, rosSpan:true});
    }

    const grid = new tui.Grid({
      el: document.getElementById('grid'),
      data: data,
      bodyHeight: 500,
      columns: columns
    });
===============================================

I expected this result.
저는 이렇게 나올거라 예상했는데
![image](https://user-images.githubusercontent.com/98307430/150741334-a9c62004-52fa-475c-a29f-d88d1cea4206.png)

But, the results returned like this...
이렇게 나와요,,
![image](https://user-images.githubusercontent.com/98307430/150741371-5a1cdd95-43f1-462b-a4f0-6b7388d679a0.png)

Also, I tried it without using 'for', and it was the same result.
data = [{c0:1, c1:1}, {c0:2, c1:2}, ....... ]
for문 사용 없이 데이터를 직접 입력해서 테스트도 해봤는데 데이터가 많아지면 똑같아져요ㅠㅠ

How can we get the result of the first picture?

It's my first time to ask this question, I'm sorry it's sloppy..

이거 물어보려고 git에 오늘 첨 가입했어요ㅜ
어떻게 하면 데이터가 제대로 나올까요??

**Comment by jajugoguma** [comment]
@xhlrmsgkrhtlvek 
I test using the example code, the row span is applied normally.
```js
const ROW_COUNT = 1000;
const COL_COUNT = 2;

const data = [];
const columns = [];

for (let i = 0; i < ROW_COUNT; i += 1) {
  const row = { id: i };
  row['c0'] = 'sales '+ i.toFixed().substring(0,1);
  row['c1'] = i;
  data.push(row);
}

for (let i = 0; i < COL_COUNT; i += 1) {
  const name = `c${i}`;
  columns.push({ name, header: name, rowSpan:true});
}

const grid = new tui.Grid({
  el: document.getElementById('grid'),
  data,
  scrollX: false,
  scrollY: false,
  columns,
});
```

**Result**
<img width="377" alt="스크린샷 2022-01-26 오전 11 16 28" src="https://user-images.githubusercontent.com/41339744/151092711-dba70b01-a850-45ff-932a-72f457dceca9.png">

Can you give an example that the problem you mentioned actually occurs using a code sandbox, etc.?

**Comment by xhlrmsgkrhtlvek** [comment]
@jajugoguma 
Comparing your code and my code, 
it seems that a problem occurs when **bodyHeight** is present,,,

I removed the  **bodyHeight** option from my code 
and it works properly...!!!

very very thank you for your help!!!!!!!
😀😁😃😄😆😍😘🥰❤👍

**Comment by xhlrmsgkrhtlvek** [comment]
@jajugoguma

sorry for reopen,,,,

Is there any way to use **bodyHeight**  and **rowSpan** together??,,,
I need to adjust the grid height 😢

**Comment by jajugoguma** [comment]
@xhlrmsgkrhtlvek 
Oh, I found that the row span has a bug with scroll...
I'll fix it. Thank you!

**Comment by xhlrmsgkrhtlvek** [comment]
@jajugoguma

oh, it was bug..
Thank you!!
