### ISSUE TITLE
Is there a way to create(insert) transformed(calculated) data not in Grid using DataSource?

### ISSUE THREAD

**Issue by flow2kudo** [nhn/tui.grid#1567]
### Summary
For example, `myGrid` has 2 columns named `A` and `B`.
When user create new row and edits(writes) the value of `A` and `B` columns to `1` and `2`
and try to save that row, the thing that I want is to save `A` , `B` **and `C`** data into database table. `C` has relationship with `A` and `B` such as `C = A + B`.

So, is there way a to pass additional key & value to server using DataSource or other ways?

### Screenshots
(codepen)
https://codepen.io/flow2kudo/pen/abVvoKO

(Web UI)
![image](https://user-images.githubusercontent.com/51441915/151634593-7155b703-bcff-4627-8841-157ee492136c.png)

(Database)
![image](https://user-images.githubusercontent.com/51441915/151634678-6748dcf2-e681-4cb0-9fc4-34bb8d6a26c2.png)

### Version
latest (using CDN)

### Additional context
Thanks a lot.

**Comment by jajugoguma** [comment]
@flow2kudo 
the grid does not support sending data by using dataSource but only loading data.
So, If you want to send data to server( or DB, etc.), you should make the function to do what you want in your service.

**Comment by flow2kudo** [comment]
I totally understand what you said.
Thank you for your kind explaination!
