### ISSUE TITLE
How to send specific variable in modifyData

### ISSUE THREAD

**Issue by cheolhwajeong** [nhn/tui.grid#1570]
When I send modifyData, I would like to send certain variables as well. (Example: Writer ID, IP address, etc.)
Is there a way to use it like initParams used in readData?
If you have a solution, please provide the sample code.
Thank you.

**Comment by jajugoguma** [comment]
@cheolhwajeong 
You can do what you want in the `beforeRequest` event.

```js
const grid = new tui.Grid({
  // ...
  data: {
    api: {
      modifyData: { url: '/api/modify', method: 'POST' },
    },
    contentType: 'application/json',
  },
  // ...
});

grid.on('beforeRequest', (ev) => {
  const { instance, xhr } = ev;
  ev.stop();

  const requestData = instance.getModifiedRows();
  requestData.variable = 'data what you want to send';

  xhr.send(JSON.stringify(requestData));
});

```

**Comment by cheolhwajeong** [comment]
@jajugoguma 
Your example code is perfect. Thank you.
