### ISSUE TITLE
fix row in Sorting

### ISSUE THREAD

**Issue by beckyi** [nhn/tui.grid#1574]
**Summary**
안녕하세요. tui grid 기능 중 `정렬` 관련해서 질문이 있습니다.
`sortable`를 사용 중에 특정 data row를 필터에 영향을 주지 않고 아래로 고정하고 싶습니다.

찾아보는 중 `comparator`를 사용해보았지만 데이터 정렬 조건이 고정된다는 문제가 있습니다.

( 사용자가 누른 정렬이 오름/내림차순 인지 알 수 없어  <img width="23" alt="image" src="https://user-images.githubusercontent.com/18224086/153337706-c6f12c9b-83c6-4bd5-91c5-9dfbf068a68c.png"> 여러 번 눌러도 같은 데이터가 고정되는 문제가 있습니다. )

혹시 다른 방법이 있을까요?

```js
// 파라미터 정보로는 사용자가 누른 정렬이 오름/내림 기준을 알 수 없습니다.
const comparator = (valueA, valueB, rowA, rowB) => {
    // code 값이 'KR' 일 경우에만 고정
    if(rowA.code === 'KR' || rowB.code === 'KR'){
      return -1
    }
  };
```

---

Hello. I have a question about sorting function.
While using `sortable`, I want to fix certain data rows in bottom, without affecting the filter.

I've tried using `comparator`, but the problem is that the sort condition is fixed.
(In `comparator` function, I can't know ascending/descending sorting condition that user wants)

How can I fix data rows without affecting the filter??

```js
// comparator function provides data information only
const comparator = (valueA, valueB, rowA, rowB) => {
    // Fixed only when code value is 'KR'
    if(rowA.code === 'KR' || rowB.code === 'KR'){
      return -1
    }
  };
```

**Version**
- tui-grid: "^4.18.1"

**Reference**
- 참조: https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/sort.md

**Comment by jajugoguma** [comment]
@beckyi 
You can get sort state by calling `getSortState` API. It contains an array of columns that are applied sort with columnName and flag for sort type(ascending or descending). If you use the flag in your comparator, you can know about the current sorting type of column.
