### ISSUE TITLE
scrollEnd event is not triggered on specific zoom level

### ISSUE THREAD

**Issue by ShinSH0** [nhn/tui.grid#1578]
**Describe the bug**
In my case if zoom level is not 100% after change the zoom level with `ctrl-wheel` hotkey, `onScrollEnd` event is not triggering

Am I wrong way to use grid scroll event? or it's just bug?

**To Reproduce**
1. Go to https://jsfiddle.net/wamo6bep/
2. Change the zoom level with `ctrl-wheel` hotkey
3. Scroll down to grid1 or grid2
4. Check the console

**Desktop (please complete the following information):**
 - OS: Window 10 build 19043.1526
 - Browser: Chrome 98.0.4758.82

**Comment by jajugoguma** [comment]
@ShinSH0 
TOAST UI Grid does not support zoom levels other than 100%. If you use it, the grid may occur other problems that are not mentioned by you.

**Comment by ShinSH0** [comment]
ok, thank you for checking this issue.
