### ISSUE TITLE
I want to use the click and double click events separately.

### ISSUE THREAD

**Issue by SimJH** [nhn/tui.grid#1581]
I want to use the click event and the double click event separately.

If I use click event and dblclick event, click event occurs every time I use double click.

I want there will be no click event when double-click.

Is there any good ideas?

**Comment by jajugoguma** [comment]
@SimJH 
If you think about the relationship between clicks and double clicks, you'll see that this isn't that easy. Whether you click or double-click, applications won't know until you actually do it (unless the application doesn't have Eye of Agamotto). So, first, an event for a click occurs, and then an event for a double click.

If you want to use this separately, you should wrap the actions inside the click event handler with `setTimeout` and implement a double click event handler in a way that releases the timer. Of course, this will produce a delay in performing the action of the click event handler.

**Comment by SimJH** [comment]
I think it would be better to support the option in the toast ui grid. 
I would appreciate it if you could improve the next version.
Thank you for your answer. Have a nice day~!
