### ISSUE TITLE
URGENT!! Get checked rows values for tree view

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1582]
**Summary**
I am trying to get the "id" of current row selected in tuigrid tree mode, but I get `null` value.
This works correct in normal view, but when I convert in tree view, it doesn't work.
```js
let recordId = lvdataGridInstance[ListView.Instance].getValue(rowKey, 'recordid'); //null
```

**Screenshots**
![1](https://user-images.githubusercontent.com/20266205/154109359-6884eb75-b0ac-43f0-9407-2c581ce85054.png)

**Version**
 4.17.0

**Comment by jajugoguma** [comment]
@denaldhushi 
I can't reproduce it. Can you give a sample code that reproduces the issue through codesandbox, etc.?

**Comment by denaldhushi** [comment]
@jajugoguma I fixed this issue. Thanks!
I ran into another issue with scrollbar. 
https://codesandbox.io/s/tui-grid-example-git-ifrhc?file=/src/index.js:1791-1827
I have the code similar like this in sandbox, where the scrollbar works correct, but in my local env it doesn't work. 
Do you have any suggeston for that?

**Comment by jajugoguma** [comment]
@denaldhushi 
Have you tried setting the height of the grid by passing a value to the [`bodyHeight`](https://nhn.github.io/tui.grid/latest/Grid#:~:text=the%20row%27s%20height.-,bodyHeight,-%5B%20stringnumber%20%5D) option?

**Comment by denaldhushi** [comment]
@jajugoguma yes, but isn't working
```js
	rowHeight: 'auto',
	bodyHeight: '100',
	scrollX: false,
	scrollY: true,
```

**Comment by denaldhushi** [comment]
btw the `getCheckedRowKeys()` method return me the checked rows when I uncheck the checkboxes. when I check them, this method return `[]`

**Comment by jajugoguma** [comment]
@denaldhushi 
How about setting the `bodyHeight` option as a number?

**Comment by denaldhushi** [comment]
> @denaldhushi How about setting the `bodyHeight` option as a number?

yes @jajugoguma , I have tried it as a number, but the same issue. can be a bug here ?
