### ISSUE TITLE
grid link column cursor option?

### ISSUE THREAD

**Issue by jhj0088** [nhn/tui.grid#1588]
If there's a link on the column, I'd like to change the cursor.

**Comment by jajugoguma** [comment]
@jhj0088 
Can you explain in more detail what you want?

**Comment by jhj0088** [comment]
> @jhj0088 Can you explain in more detail what you want?

I want to change a specific linked column to a hand cursor rather than a regular arrow cursor.

**Comment by jhj0088** [comment]
> @jajugoguma 
I want to change a specific linked column to a hand cursor rather than a regular arrow cursor.
