### ISSUE TITLE
Is there a way to bring the api of datasoure?

### ISSUE THREAD

**Issue by HyunJ1k** [nhn/tui.grid#1589]
**Screenshots**
![image](https://user-images.githubusercontent.com/49899570/155248530-20b40df6-9a90-4c97-8622-98d4e66f542e.png)

**Version**
4.20.3

**Additional context**
Hello

I'm inquiring about using the tui grid.

Data is being displayed using data's api and readData.
Is there a way to bring back the url and initParams of api readData?

In the case of initParams, it is possible using setRequestParams, but there seems to be no getRequestParams.

We checked the api read data using the developer tool as below, but is there a way to bring BoundArgs.

I'll be waiting for the reply.

**Comment by jajugoguma** [comment]
@chohyunjik2 
There is no API or anything that returns `initParams`. If you want to use it, you can declare the object separately and use it.

**Comment by chohyunjik2** [comment]
I wish the returns `initParams` function was added.

Thank you for answer.
