### ISSUE TITLE
How do I apply background color to specific columns using react wrapper?

### ISSUE THREAD

**Issue by klicious** [nhn/tui.grid#1597]
**Summary**
I was able to apply _partial_ background color through the wrapper's `render` component; the implementation example is provided below. However, this method cannot seem to apply the `padding` and `margin` options to the column, thus applying the `background-color` only marginally(compare the yellow-colored columns to sky-blue colored columns in the screenshot below). What is the proper way to apply colors to desired columns? I've already tried adding the `_attribute` field to `data`, assigning class names to specific columns, but that does not seem to work.

```javascript
import Grid from "@toast-ui/react-grid";
import React from "react";

const exposureColumns = [
    {name: 'analyst', header: 'ANALYST', rowSpan: true, sortable: true},
    {name: 'market', header: 'MARKET', rowSpan: true, sortable: true},
    {
        name: 'grossDelta', header: 'GROSS DELTA', renderer: {
            styles: {
                color: (props: any) => fontColor(props.value),
                "background-color": "yellow",
                "padding": "0",
                "margin": "0",
            },
        },
        formatter(props: any) {
            let value = accounting.format(props.value);
            return `${value}`
        }
    },
];

return (
    <div>
        <h2>EXPOSURE</h2>
        <Grid
            data={exposures}
            // @ts-ignore
            columns={exposureColumns}
            draggable={true}
            rowHeight={25}
            rowHeaders={['rowNum']}
        />
    </div>

);

```

**Screenshots**
If applicable, add screenshots to help explain your question.

<img width="125" alt="image" src="https://user-images.githubusercontent.com/14937878/155944633-f2f45f50-b10c-46db-bd09-15e5dfe43ddb.png">

**Version**
"name": "@toast-ui/react-grid",
"version": "4.20.2",

**Additional context**

**Comment by jajugoguma** [comment]
@klicious 
There is a way to add a class name to a column and apply the style with CSS.

```css
.tui-grid-cell.gross-delta {
    background-color: yellow;
}
```
```js
const exposureColumns = [
    // ...
    {
        name: 'grossDelta',
        header: 'GROSS DELTA', 
        className: 'gross-delta',
        // ...
    },
];

/// ...
```
