### ISSUE TITLE
Input two data to horizontal divided one cell.

### ISSUE THREAD

**Issue by yunhyungshin** [nhn/tui.grid#1599]
**Summary**
Input two data to horizontal divided one cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/98299963/156281630-7bebf517-4ac2-492b-9fc5-1ba2f4f488cf.png)

**Version**
  "version": "4.20.0"

**Additional context**
1. I want to divide cell to horizontally.
2. I want to input the data to divided horizontally cell.

**Comment by jajugoguma** [comment]
@yunhyungshin 
We do not officially support that feature.
However, it seems possible to implement it using a [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md).

**Comment by yunhyungshin** [comment]
> @yunhyungshin We do not officially support that feature. However, it seems possible to implement it using a [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md).

I was implements the feature with custom renderer like below code.

But when I drag the line of column then the value change to the 'Null' or 'undefined'.

So I was ask the how to imple the feature.

Please check below code and kindly answer to me TT 


	    class twoCellRenderer {debugger;
	    	  constructor(props) {
	    	    const el = document.createElement('span');
	    	    const { bottom } = props.columnInfo.renderer.options;

	    	    this.el = el;
	    	    this.render(props, bottom);
	    	  }

	    	  getElement() {
	    	    return this.el;
	    	  }

	    	  render(props, bottom) {
	    		  if ( props.value != null && props.value != '' ){
		    		  var tableHtml = '<div style="border-bottom: 1px solid #cfd3d7;text-align: center; height: 25px;line-height:25px;">'+props.value+'</div>' + '<div style="text-align: center; height: 25px;line-height:25px;">'+grid2.getValue(props.rowKey, bottom)+'</div>'
		    		  // var tableHtml = '<table class="">'+
			    		//  '<tr class="grid_body_row"><td style="text-align: center; height: 25px;" class="gridBodyDefault gridBodyDefault_data grdMain2_columnstyle_11_">'+props.value+'</td></tr><tr><td style=\"text-align: center; height: 25px;\" class="gridBodyDefault gridBodyDefault_data grdMain2_columnstyle_11_">'+grid2.getValue(props.rowKey, bottom)+'</td></tr></table>';
  	    			  this.el.innerHTML = tableHtml;
	    		  }
	    	  }
		}

**Comment by yunhyungshin** [comment]
> > @yunhyungshin We do not officially support that feature. However, it seems possible to implement it using a [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md).
> 
> I was implements the feature with custom renderer like below code.
> 
> But when I drag the line of column then the value change to the 'Null' or 'undefined'.
> 
> So I was ask the how to imple the feature.
> 
> Please check below code and kindly answer to me TT
> 
> ```
>     class twoCellRenderer {debugger;
>     	  constructor(props) {
>     	    const el = document.createElement('span');
>     	    const { bottom } = props.columnInfo.renderer.options;
> 
>     	    this.el = el;
>     	    this.render(props, bottom);
>     	  }
> 
>     	  getElement() {
>     	    return this.el;
>     	  }
> 
>     	  render(props, bottom) {
>     		  if ( props.value != null && props.value != '' ){
> 	    		  var tableHtml = '<div style="border-bottom: 1px solid #cfd3d7;text-align: center; height: 25px;line-height:25px;">'+props.value+'</div>' + '<div style="text-align: center; height: 25px;line-height:25px;">'+grid2.getValue(props.rowKey, bottom)+'</div>'
> 	    		  // var tableHtml = '<table class="">'+
> 		    		//  '<tr class="grid_body_row"><td style="text-align: center; height: 25px;" class="gridBodyDefault gridBodyDefault_data grdMain2_columnstyle_11_">'+props.value+'</td></tr><tr><td style=\"text-align: center; height: 25px;\" class="gridBodyDefault gridBodyDefault_data grdMain2_columnstyle_11_">'+grid2.getValue(props.rowKey, bottom)+'</td></tr></table>';
>     			  this.el.innerHTML = tableHtml;
>     		  }
>     	  }
> 	}
> ```

I'm Solved the issue with bad solution.
I'm just use specific custom renderer for each column(twoCellRenderer , two2CellRenderer ). Can't use common custom renderer.
When drag the line of column occured the drag event and the custom renderer couldn't use option(ex:bottom) . the bottom value of option didn't know the value.

 class twoCellRenderer {debugger;
	    	  constructor(props) {
	    	    const el = document.createElement('span');
	    	    //const { bottom } = props.columnInfo.renderer.options;

	    	    this.el = el;
	    	    //this.render(props, bottom);
	    	    this.render(props);
	    	  }

	    	  getElement() {
	    	    return this.el;
	    	  }

	      	  //render(props, bottom) {
	  		render(props) {
	    		  if ( props.value != null && props.value != '' ){
		    		  var tableHtml = '<div style="border-bottom: 1px solid #cfd3d7;text-align: center; height: 25px;line-height:25px;">'+props.value+'</div>'
		    		  + '<div style="text-align: center; height: 25px;line-height:25px;">'+grid2.getValue(props.rowKey, 'QTYDT')+'</div>';
  	    			  this.el.innerHTML = tableHtml;
	    		  }
	    	  }
		}

	class two2CellRenderer {debugger;
  	  constructor(props) {
  	    const el = document.createElement('span');
  	    //const { bottom } = props.columnInfo.renderer.options;

  	    this.el = el;
  	    //this.render(props, bottom);
  	  this.render(props);
  	  }

  	  getElement() {
  	    return this.el;
  	  }

  	  //render(props, bottom) {
		render(props) {
  		  if ( props.value != null && props.value != '' ){
	    		  var tableHtml = '<div style="border-bottom: 1px solid #cfd3d7;text-align: center; height: 25px;line-height:25px;">'+props.value+'</div>'
	    		  + '<div style="text-align: center; height: 25px;line-height:25px;">'+grid2.getValue(props.rowKey, 'AMTDT')+'</div>';
    			  this.el.innerHTML = tableHtml;
  		  }
  	  }
	}
