### ISSUE TITLE
Questions for ServerSide Pagination (서버에서의 페이징 관련 문의사항)

### ISSUE THREAD

**Issue by shhong94** [nhn/tui.grid#1602]
I have some questions about ServerSide Pagination.

Here is a image which i am developing, 
and let me explain SELECT processing.

![tui_pagination](https://user-images.githubusercontent.com/63003560/156316963-a27349f7-2faf-44bb-a9b8-0e60ee13f01e.png)

1. Setting SELECT conditions (including page, perPage...).
2. Push SEARCH button.
3. with SELECT conditions(parameters), WAS connect DB Server. So SELECT Query will be executed.
4. Response will be shown at grid area.

At this time,
I am using "Rownum" paging with the query above.
It appears that the tui gird's API, Datasource, cannot link rownum pagination.

Here is my Questions.

1. I want to start SELECT process AFTER pushing search button. Where should i add readData() event? 
I want to see sample code.

2. Is there way to linking tui gird's pagination with rownum pagination?

**Comment by shhong94** [comment]
* The contents below are the same as the one above.
The difference is only English and Korean.



질문 내용이 잘 전달되지 않음을 방지하고자 원어로도 문의드립니다.


서버사이드 페이징 관련 문의사항이 몇 개 있습니다.
아래 이미지는 제가 개발 중인 화면을 대략적으로 표현한 것이며.
조회 과정을 설명드리겠습니다.


(이미지)


1. 조회 조건을 설정합니다. (페이지, 한 페이지당 보여줄 행 포함...)
2. search 버튼을 클릭합니다.
3. 위에서 설정한 조건으로(또는 파라미터), 어플리케이션 서버가 DB서버와 연동되어 SELECT 쿼리를 수행합니다.
4. 응답결과를 그리드에 보여줍니다.

이 때,
저는 위 SELECT 쿼리에서 오라클의 rownum을 이용하여 페이징을 하려고 합니다.
데이터 소스와 같은 토스트 그리드 API에서는 rownum 페이징과 연동이 되지 않는 듯 합니다.


제가 드릴 질문은 2개입니다.

1. search 버튼 클릭 후에 SELECT 쿼리를 수행하려고 하는데, readData 또는 resetData와 같은 함수를 어디에 위치해야 하나요?
커스텀 이벤트 등의 가이드 문서를 봤지만, 특정 동작 (etc: 버튼 클릭) 이후에 데이터소스와 연동하여 데이터를 불러오는 예시는 없는 듯 합니다.
관련 샘플 코드를 보고싶네요.

2. 토스트 그리드의 페이징과 rownum 페이징 연동이 가능한가요?
위 질문과 마찬가지로, 가이드 문서를 보아도 setPerpage, pagingOption 사용법 등에서도 관련 내용은 찾아볼 수 없네요.

**Comment by HyunJ1k** [comment]
1. 조회 버튼 클릭 스크립트에서 사용하시면됩니다.
`grid.readData` or `grid.request`

2. pageOptions 추가 시 파라미터로 자동으로 넘어옵니다.
http://~~/get?page=1&PerPage=50
page : 현재 페이지
perPage : 페이지 표시 건수
