### ISSUE TITLE
Question for request function. (Cannot read properties of undefined (reading 'map'))

### ISSUE THREAD

**Issue by shhong94** [nhn/tui.grid#1603]
**Summary**
Here is question.

"request" function does not works.
An error occurred with "Cannot read properties of undefined (reading 'map')".

**My Code**
`<body>
	<button onclick="getGridData();">test button</button>
	<div id="grid" style="width: 500px;"></div>
</body>
<script type="text/javascript" src="https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.pagination/v3.4.0/tui-pagination.js"></script>
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
<script>

function getGridData() {
	console.log('시작');
	grid.request('readData');
	console.log('끝');
}

var data_main = {
		api: {
			readData: {
				url: 'https://jsonplaceholder.typicode.com/users',
				method: "GET",
			}
		}
}

var grid = new tui.Grid({
	el: document.getElementById('grid'),
	rowHeaders: ['rowNum'],						// row 번호
	data: data_main,
	pagination: true,							// 페이징
	pageOptions: {
        //useClient: true,
        perPage: 5
    },
	columns: [									// column 
		{
			header: 'ID',
			name: 'id',
		},
		{
			header: 'USERNAME',
			name: 'username',
		},
		{
			header: 'EMAIL',
			name: 'email',
		},
	], 
});
</script>`

**Version**
Latest version

**Additional context**

Let me explain process of reading data.

1. push "test button"
2. getGridData() would be executed.
3. grid.request('readData') should be executed.    <-- but error is occurred here.

I am using Datasource API.
The datasource's url is working properly.

**Comment by HyunJ1k** [comment]
return format of the data source url is incorrect.

Invalid return format currently in use
`[ { id : "abc"}, { id : "aaa"} ]`

return format of the toast grid is as follows.
`{
            result: true,
            data: {
                contents: [ {id : "abc"}, {id : "aaa"}],
                pagination: {
                    page: 1,
                    totalCount: 20
                }
            }
}`

**Comment by jajugoguma** [comment]
@HyunJ1k 
I'm sorry for the late reply.

Are you sure you are using grid version 4.10.0?
The url of the latest version of the grid source is https://uicdn.toast.com/grid/latest/tui-grid.js.
If the version you are trying to use is the latest version, try using the above url and if that doesn't work, please tell me again!
