### ISSUE TITLE
Hey, is there a way to style a single row dynamically? 

### ISSUE THREAD

**Issue by nrep** [nhn/tui.grid#1609]
**Summary**
Like changing the background color of the whole row. I've been tasked with changing row background depending on user input and I'm not finding a way to do this. Any help will be appreciated. Thanks.

**Comment by jajugoguma** [comment]
@nrep 
You can do it by using `[beforeChange](https://nhn.github.io/tui.grid/latest/Grid#event-beforeChange)` event and `[addRowClassName](https://nhn.github.io/tui.grid/latest/Grid#addRowClassName)`.

```css
.tui-grid-cell.some-name {
  background-color: red;
}
```

```js

grid.on('beforeChange', (ev) => {
  const {rowKey, nextValue} = ev.changes[0]

  if (/* condition */) {
    grid.addRowClassName(rowKey, 'some-name')
  }
});
```
