### ISSUE TITLE
Question for "Custom Renderer"

### ISSUE THREAD

**Issue by shhong94** [nhn/tui.grid#1618]
**Summary**
I want show "input" style without doubleclick or click, 
but it doesn't works.

**Screenshots**
[As - is]
![custom renderer1](https://user-images.githubusercontent.com/63003560/159628275-8132f1bf-268f-48e8-b710-446fc05d51b5.PNG)
![custom renderer2](https://user-images.githubusercontent.com/63003560/159628423-66ab005b-1c4a-48e3-972f-1976eb18d2f2.PNG)

In screenShot 1, 
There is no input style.
In screenShot 2,
After doubleclick or click specific cell, we can see a cell with input style. 

[To - be]
![custom renderer3](https://user-images.githubusercontent.com/63003560/159628709-8a541391-f8d6-4b9e-b0b3-dd0edbbf67ec.png)

Like screenShot 3,
I want to show input style at beggning.(without doubleclick or click)

**Version**
latest (4.20.3)

**Additional context**
There are many issues and API guides, but it doesn't work.
Because it seeams that all issue and API guide explain how to use custom renderer with "Vue or React or Other JS libraries".
(https://github.com/nhn/tui.grid/issues/638  <- like this issue)
But i am working with JSP.

So i want to see how to use custom renderer in JSP.

**Comment by shhong94** [comment]
● The contents below are the same as the one above.
The difference is only English and Korean.

**요약**
input 스타일을 더블클릭이나 클릭 없이 처음부터 보여주고 싶은데, 적용이 안됩니다.

**스크린샷 설명**
[As - is]
스크린샷 1에서 보듯이, 셀 클릭 없이는 에딧 모드가 활성화되지 않습니다.
스크린샷 2처럼 클릭을 해야 input 스타일이 활성화 됩니다.

[To - be]
스크린샷 3처럼 
데이터를 불러온 후, 더블클릭이나 클릭 없이 에딧 모드(input 스타일)을 활성화 시키고 싶습니다.

**버전**
최신 버전 (4.20.3)

**추가 내용**
커스텀 렌더러와 관련된 많은 이슈와 가이드 문서가 있지만, 제 상황에는 맞지 않습니다.
관련 문서들이 Vue나 React, 기타 자바스크립트 라이브러리 용으로 작성되서인 듯 합니다. 
(https://github.com/nhn/tui.grid/issues/638 <- 이런 이슈처럼요)
근데 전 JSP로 개발하고 있습니다.

그래서 JSP에서도 커스텀 렌더러를 사용하는 법을 알고 싶습니다.
(해당 가이드문서나 이슈에 나오는 props나 render 등등... jsp에서는 해당되지 않는 사항들이 많습니다)

**Comment by MrILac** [comment]
해당부분에 대한 피드백을 저도 요하는 상황이라 답변을 기다려 봅니다 ㅎㅎ

**Comment by jajugoguma** [comment]
@shhong94 @MrILac 

Currently, It is not supported.
Thanks for the good comments. We will consider adding that feature.
