### ISSUE TITLE
특정 Row 에서만 cell 의 edit 가안되도록 할수있는방법이있는지요?

### ISSUE THREAD

**Issue by jephyros** [nhn/tui.grid#1621]
조건에 따라 cell 의 edit 여부를 정하고싶습니다.
예를들어 이미 조회된 Row의 특정컬럼은 Edit가안되고
 appendRow 통해 추가한 Row(라인) 에 대해서만 Edit 가 가능하고싶습니다.

**Comment by jajugoguma** [comment]
@jephyros 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

You can implement it by using `editingStart` event and `grid.getModifiedRows().createdRows`.

**Comment by jephyros** [comment]
I solved it using editingStart() and editingFinish().
Thank you. I'll close it.
