### ISSUE TITLE
셀렉트박스 placeholder 기능

### ISSUE THREAD

**Issue by lee1nna** [nhn/tui.grid#1625]
**Summary**
기본적으로 제공하는 내장 editor select에서 placeholder를 구현할 수 있는 방법은 없나요?

**Screenshots**
이렇게 셀렉트박스에 placeholder를 추가하고 싶습니다.
![image](https://user-images.githubusercontent.com/71548623/160360380-8412cca9-af7e-474a-b25e-54c994103b91.png)

**Version**
v4.20.3

**Additional context**
커스텀 렌더러로 셀렉트박스를 구현해보려고도 했는데 셀 안에서 제대로 작동이 안돼서 내장 에디터를 사용하려니 placeholder 기능을 못찾겠어서 문의드립니다.

**Comment by jajugoguma** [comment]
@lee1nna 
You cannot set a placeholder in the built-in select editor. 
If you want it, you should create a custom editor referring to [built-in select editor](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/src/editor/select.ts) and [TOAST UI selectbox](https://nhn.github.io/toast-ui.select-box/latest/SelectBox)

**Comment by lee1nna** [comment]
@jajugoguma 하나 더 여쭤보고 싶은 게 있는데, 혹시 셀을 클릭하기 전에도 셀렉트 박스를 표시할 수 있는 방법은 없나요 ? 현재 이렇게 클릭 전에는 빈 셀로 떠서 셀렉트 박스가 있는지 셀을 누르기 전에는 확인하기가 어렵습니다.
- 셀 클릭 전
![image](https://user-images.githubusercontent.com/71548623/160788414-8ab88efb-4fc1-441d-8ce9-f44be87a9267.png)
 - 셀 클릭 후
![image](https://user-images.githubusercontent.com/71548623/160788893-19c959f1-b969-4e00-a88f-4b6bd6585b3c.png)
