### ISSUE TITLE
Question for rowSpan

### ISSUE THREAD

**Issue by shhong94** [nhn/tui.grid#1626]
**Summary**
1. < rowSpan: true > is not working. (in "columns" option)
2. < _attributes.rowSpan[columnName] = N > is not working. (in "data" option)

**Screenshots**
● Below screenshots are about Question 2.

![_attributes1](https://user-images.githubusercontent.com/63003560/160547518-bb903c3e-c3aa-4328-ab4b-5cec36658147.PNG)
Here is original state.

![_attributes2](https://user-images.githubusercontent.com/63003560/160547654-a640f7e1-246e-4d95-a07a-75c1c192cd5f.PNG)
When i change _attributes.rowSpan of 1st row,
2nd and 3rd row move to next column.

**Version**
4.20.3

**Additional context**
i've already see document and tutorial.
I want to know why these features are not working.

Here is my code.

`var grid_test = new tui.Grid({
	el: document.getElementById('grid_test'),						
	rowHeaders: ['rowNum'],												
	data: [
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
		{
			name1: 'hong',			age1: 10,			address1: 'korea',
		},
	],
	columns: [																					
		{
			header: 'name',			name: 'name1',		rowSpan: true,															
		},
		{
			header: 'age',			name: 'age1',		rowSpan: true,
		},
		{
			header: 'address',		name: 'address1',	rowSpan: true,
		},
	],
});
var tempRow = grid_test.getRow(0);
tempRow._attributes.rowSpan = {};
tempRow._attributes.rowSpan['name1'] = 3;

grid_test.setRow(0, tempRow);`

**Comment by shhong94** [comment]
● The contents below are the same as the one above.
The difference is only English and Korean.

**Summary**
1. < rowSpan: true > 옵션이 적용되지 않습니다. (columns 옵션 내에서)
2. < _attributes.rowSpan[columnName] = N > 옵션이 적용되지 않습니다. (data 옵션 내에서)


**ScreenShots**
● 아래 스크린샷들은 2번 질문 관련입니다.

![_attributes1](https://user-images.githubusercontent.com/63003560/160549256-1ce44d13-5d42-45e1-a983-1ad91ba41378.PNG)
위 스크린샷은 원래 상태입니다.

![_attributes2](https://user-images.githubusercontent.com/63003560/160549325-617eacf6-8a45-4155-af7c-4512e845729c.PNG)
첫번째 row의 _attributes.rowSpan을 변경하면,
2번째와 3번째 row 데이터가 옆 컬럼으로 이동합니다.


**Version**
4.20.3


**Additional Context**
이미 여러 문서와 튜토리얼, 이슈들을 봤습니다.
해당 기능들이 왜 동작하지 않는지 알고싶네요.

아래에 코드를 첨부하겠습니다
(rowSpan: true와 _attributes.rowSpan 옵션이 코드상에는 함께 있으나, 따로따로 해보기도 했습니다.)

``var grid_test = new tui.Grid({
el: document.getElementById('grid_test'),
rowHeaders: ['rowNum'],
data: [
{
name1: 'hong', age1: 10, address1: 'korea',
},
{
name1: 'hong', age1: 10, address1: 'korea',
},
{
name1: 'hong', age1: 10, address1: 'korea',
},
{
name1: 'hong', age1: 10, address1: 'korea',
},
{
name1: 'hong', age1: 10, address1: 'korea',
},
{
name1: 'hong', age1: 10, address1: 'korea',
},
],
columns: [
{
header: 'name', name: 'name1', rowSpan: true,
},
{
header: 'age', name: 'age1', rowSpan: true,
},
{
header: 'address', name: 'address1', rowSpan: true,
},
],
});
var tempRow = grid_test.getRow(0);
tempRow._attributes.rowSpan = {};
tempRow._attributes.rowSpan['name1'] = 3;

grid_test.setRow(0, tempRow);`

**Comment by jajugoguma** [comment]
@shhong94 
I cannot reproduce it. It works well.
Can you give some example code for reproducing it through codesandbox, etc.?

In addition, `_attributes.rowSpan` will be deprecated and it doesn't work with `rowSpan` option.

**Comment by shhong94** [comment]
@jajugoguma 

Thank you for your reply.

https://codesandbox.io/s/relaxed-booth-zigdvl?file=/index.html

Here is example code with codesandbox.
It doesn't work too.
Likewise, _attributes.rowSpan doesn't work.

Of course, i used rowSpan and _attributes.rowSpan individually.

**Comment by jajugoguma** [comment]
@shhong94 
You use the wrong CDN URL. The correct URL is `https://uicdn.toast.com/grid/latest/tui-grid.js`.
Please check [Readme](https://github.com/nhn/tui.grid/tree/master/packages/toast-ui.grid#:~:text=%3Cscript%20src%3D%22https%3A//uicdn.toast.com/grid/latest/tui%2Dgrid.js%22%3E%3C/script%3E).

**Comment by shhong94** [comment]
@jajugoguma 

Thank you. I love you.

I think your team should check "getting-started" document.
There is wrong CDN URL. 

https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/getting-started.md

Thank you for your help.
