### ISSUE TITLE
Is it possible to combining data from different APIs?

### ISSUE THREAD

**Issue by penguin418-dbase** [nhn/tui.grid#1628]
**Summary**
A clear and concise description of what the question is.
여러 api를 호출해서 그 결과 테이블을 한번에 병합해서 출력하고 싶습니다. 가능한 방법이 있을까요?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.
version 3

**Additional context**
각 테이블 데이터를 호출하는 api가 존재하는 데, 조인 결과를 리턴하는 api는 없는 상황입니다. 이런 경우, 각 api를 사용해서 데이터를 가져온 다음, 프런트엔드에서 조인 후 토스트 그리드에 출력하고 싶은데, 혹시 좋은 방법이 있을까요?

**Comment by jajugoguma** [comment]
@penguin418-dbase 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

Would you like to check out the [rowSpan](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/row-span.md)?

**Comment by penguin418-dbase** [comment]
Thank you for your answer. but that's not what i was looking for.

**Summary
A clear and concise description of what the question is.**
 I want to print out some complex data requiring join of three tables data from different api.

**Screenshots
If applicable, add screenshots to help explain your question.**

**Version
Write the version of the grid you are currently using.**
version 3

**Additional context
Add any other context about the problem here.**
Our system consists of 3 microservices. Each service has its own API with limited boundary.
I want to use each api to fetch data, then join it on the frontend and print it to the toast grid. Is there any good way?

**Comment by jajugoguma** [comment]
@penguin418-dbase 
Unfortunately, the grid does not support that feature. The data you receive using the API should be joined data.

**Comment by penguin418-dbase** [comment]
thanks for the comments.
