### ISSUE TITLE
Question for DatePicker

### ISSUE THREAD

**Issue by shhong94** [nhn/tui.grid#1630]
**Summary**
I want use DatePicker, but an error occurs like below.
_Uncaught TypeError: tui_date_picker_1.default is not a constructor_

**Screenshots**
![datePicker1](https://user-images.githubusercontent.com/63003560/161003964-7b2ae541-be86-4437-8c8a-0f7b155dc695.PNG)

**Version**
4.20.3

**Additional context**
I think there is no error cause, but it doesn't work.
I've already check CDN URL and etc...

I'm sorry that i can't give you specific code becuase of company's security rule.
Instead, i'll give you example code with codesandbox.
Can't see error in codesandbox, but this code is same as what i'm developing basically.
And it doesn't work here, too.

https://codesandbox.io/s/relaxed-booth-zigdvl?file=/index.html

**Comment by shhong94** [comment]
● The contents below are the same as the one above.
The difference is only English and Korean.

**Summary
**
DatePicker를 이용하려고 하는데, 아래와 같은 에러가 발생합니다.
_Uncaught TypeError: tui_date_picker_1.default is not a constructor_

Screenshots
![](https://user-images.githubusercontent.com/63003560/161003964-7b2ae541-be86-4437-8c8a-0f7b155dc695.PNG)


Version
4.20.3

Additional context

에러가 될만한게 없는거같은데도 작동하지 않습니다.
CDN 주소나 기타 등등 확인했습니다.

보안규정때문에 구체적인 코드를 첨부하지 못한 점 양해 부탁드립니다.
대신에 codesandbox로 예시 첨부합니다.
codesandbox에서는 에러가 발생하지 않는데, 이 코드랑 제가 개발하고 있는거랑 기본적으로 같은겁니다.
마찬가지로 codesandbox에서도 작동하지 않구요.

https://codesandbox.io/s/relaxed-booth-zigdvl?file=/index.html

**Comment by Coen90** [comment]
해결하셨는지 모르겠네요
codesandbox에서는 cdn script 서순 문제로 보입니다.
codesandbox에서는 timepicker를 grid 위로 순서 변경하니 문제없이 작동하네요

**Comment by jajugoguma** [comment]
@shhong94 

Could you try importing datePicker before grid?

**Comment by shhong94** [comment]
@Coen90 
감사합니다 cdn 순서가 문제일 줄은 몰랐네요
덕분에 잘 해결했습니다!

@jajugoguma 
Thank you for your help.
The problem has been solved :)
