### ISSUE TITLE
토스트 그리드 엑셀 업로드, 다운로드 기능을 찾아 봐도 안보이는데 관련 정보가 있나요?

### ISSUE THREAD

**Issue by JAEIN-HWANG** [nhn/tui.grid#1634]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by jajugoguma** [comment]
@JAEIN-HWANG 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

The grid only supports download. please check a [document](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/export.md).
