### ISSUE TITLE
URGENT! Paste from excel to grid issue

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1635]
As far as I know When copy/paste the rows from excel sheet to grid that has less rows, grid should be append (issue https://github.com/nhn/tui.grid/issues/1 
said that fixed at 1.0.4.). But It seemed does not append rows

https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor
If you paste 30 rows to that grid, rows remain just 20 rows and the others are lost.
Is that right action?

In addition. Please tell me the option or process about that.
Version: 4.18.0
Thanks.

**Comment by denaldhushi** [comment]
Is anyone here?

**Comment by jajugoguma** [comment]
@denaldhushi 
Sorry for late reply.
I'll fix it ASAP. Thanks!

**Comment by denaldhushi** [comment]
Great! Please let me know once you have fixed it.

**Comment by denaldhushi** [comment]
@jajugoguma is any update on this issue? Thanks!

**Comment by jajugoguma** [comment]
@denaldhushi 
Sorry for the delay in fixing the bug. We will fix it as soon as possible.

**Comment by denaldhushi** [comment]
@jajugoguma do you have any update for this issue?
