### ISSUE TITLE
csv 파일은 저장이 되는데 엑셀은 안되요

### ISSUE THREAD

**Issue by woonyounggo** [nhn/tui.grid#1643]
그리드 안에서 오른쪽 마우스 클릭하고 export 에서 csv 는 저장이 됩니다.

엑셀로 할때만 에러가 납니다...어찌된일일까요???

[tui/grid] - Not found the dependency "xlsx". You should install the "xlsx" to export the data as Excel format

execExport | @ | utils.js:69
-- | -- | --
  | dispatch | @ | utils.js:69
  | Grid.export | @ | utils.js:69
  | action | @ | light.initItMap?itma…113&searchValue=:88
  | ContextMenuItemComp._this.execAction | @ | utils.js:69
  | eventProxy | @ | customEvents.js:61

**Comment by jajugoguma** [comment]
@woonyounggo 
You should install SheetJS for using export xlsx. [document](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/export.md#%EC%97%91%EC%85%80-%EB%82%B4%EB%B3%B4%EB%82%B4%EA%B8%B0)
