### ISSUE TITLE
I found 'diabled' not 'disabled'

### ISSUE THREAD

**Issue by fixalot84** [nhn/tui.grid#1671]
**Describe the bug**

I found 'diabled' not 'disabled'.

- tui-grid.js 
- v4.21.1
- 16430 line

```js
this.opened = false;
/**
 * @type {boolean}
 * @private
 */

this.diabled = false; // <--
/**
 * @type {boolean}
 */

this.autoclose = autoclose;
```

Maybe has a bug potential I think😏

Bye!

**Comment by jajugoguma** [comment]
@fixalot84 
Thanks for finding the typo. But, It is in TOAST UI SelectBox, not Grid.
I'll correct it.
