### ISSUE TITLE
그리드 body를 초기화 후 다시 리스트 생성에 대해서.

### ISSUE THREAD

**Issue by choi-serena** [nhn/tui.grid#1698]
![그리드](https://user-images.githubusercontent.com/107349444/173229821-ff6a0718-e6a0-4e4b-ac21-e1a8890c0720.jpg)

road 시 grid 출력 후 파일 열기하여 그리드 리스트 추가할 수 있나요?

그리고 grid  리스트 초기화가 가능한가요?

**Comment by jajugoguma** [comment]
@choi-serena 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

You can append rows by using [appendRows](https://nhn.github.io/tui.grid/latest/Grid#appendRows) API and reset data by using [resetData](https://nhn.github.io/tui.grid/latest/Grid#resetData) API.
