### ISSUE TITLE
Tuigrid  selectbox 사용시  같은행의 값바탕으로 listItems 동적 렌더링 관련

### ISSUE THREAD

**Issue by dkdkdltkddn** [nhn/tui.grid#1699]
안녕하세요 그리드 내에 열이  회사 ,사업부 요렇게 있습니다.
회사 칼럼 select box 에서  **a회사 선택**시   **사업부 칼럼**이  listItems가 **a-1 사업부, a-2 사업부, a-3 사업부** 이렇게 뜨고 
**b회사 선택**시  **사업부 컬럼**이  **b-1 사업부  b-2 사업부 b-3사업부** 이렇게  같은행에 있는 값을 바탕으로 동적으로 바꾸고싶습니다.
사업부 칼럼에서 서로 다른 editor.options.listItems 가 보여야합니다. 
조언쫌 부탁드릴수있을까요?

**Comment by jajugoguma** [comment]
@dkdkdltkddn 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

Not sure if that's exactly what you want, but it's not possible to dynamically change the options of the built-in select editor. If you want to do this, you will need to create a custom editor by referring to the implementation of the built-in editor.
