### ISSUE TITLE
Using dataSource: Data doesn't show on the view 

### ISSUE THREAD

**Issue by sbyun1** [nhn/tui.grid#1701]
I'm using Python, Flask to create grid.
when I connect with the server to bring data from my db, 
it seems like there's no problem communicating but  it only shows the column head on the view.
I've checked the Network tab on the Chrome: payload, response seems find?

JS
![image](https://user-images.githubusercontent.com/86010657/173753147-ff2e62ab-e6d6-465a-bac8-0df0c4458a47.png)

Flask
![image](https://user-images.githubusercontent.com/86010657/173753200-d0d7851f-8f5c-4b1a-b42d-9b825059d3b7.png)

View
![image](https://user-images.githubusercontent.com/86010657/173753385-8e3df6ca-7728-45dc-ab7f-5608038ca6fc.png)

Network - Preview
![image](https://user-images.githubusercontent.com/86010657/173753456-ab102620-042a-43fa-a2b0-c24d6cde18c2.png)

Network - Response
![image](https://user-images.githubusercontent.com/86010657/173753497-e1983a25-f131-4d6a-9057-eb7d912915d3.png)

Network - Payload
![image](https://user-images.githubusercontent.com/86010657/173765103-ea291772-e9ae-48ae-9b3e-4820a2b0259d.png)

**Comment by davidlam-at-home** [comment]
@sbyun1 did you solved the problem in the end?
