### ISSUE TITLE
Is there any way I can change language?

### ISSUE THREAD

**Issue by sbyun1** [nhn/tui.grid#1702]
When I right click these menu pops up.
Is there any way I can get them in Korean Language?
I'm using Toast UI with CDN 

![image](https://user-images.githubusercontent.com/86010657/173781581-d5bbeca6-a99b-4658-965a-10868746696d.png)

**Comment by fixalot84** [comment]
You can use `contextMenu` option to change label like below:

```
const grid = new tui.Grid({
  el: document.getElementById("grid"),
  data: gridData,
  scrollX: false,
  scrollY: false,
  rowHeaders: ["checkbox"],
  columns: [
    { header: "Name", name: "name" },
    { header: "Artist", name: "artist" },
    { header: "Type", name: "type" },
    { header: "Release", name: "release" },
    { header: "Genre", name: "genre" },
  ],
  contextMenu: ({ rowKey, columnName }) => (
    [
      [
        {
          name: 'export',
          label: '내보내기',
          action: () => {
            // 옵션을 전달하지 않으면 초기 설정 옵션으로 내보내기가 수행된다.
            grid.export('csv');
          }
        }
      ]
    ]
  )
});
```

- https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/export.md
- https://nhn.github.io/tui.grid/latest/Grid

**Comment by sbyun1** [comment]
> You can use `contextMenu` option to change label like below:
> 
> ```
> const grid = new tui.Grid({
>   el: document.getElementById("grid"),
>   data: gridData,
>   scrollX: false,
>   scrollY: false,
>   rowHeaders: ["checkbox"],
>   columns: [
>     { header: "Name", name: "name" },
>     { header: "Artist", name: "artist" },
>     { header: "Type", name: "type" },
>     { header: "Release", name: "release" },
>     { header: "Genre", name: "genre" },
>   ],
>   contextMenu: ({ rowKey, columnName }) => (
>     [
>       [
>         {
>           name: 'export',
>           label: '내보내기',
>           action: () => {
>             grid.export('csv');
>           }
>         }
>       ]
>     ]
>   )
> });
> ```
> 
> * https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/export.md
> * https://nhn.github.io/tui.grid/latest/Grid

Thanks. Also can I ask one more question?
I'm trying to append rows by using appendRows but it doesn't work.

my code is below

HTML
![image](https://user-images.githubusercontent.com/86010657/173965862-23dde106-5875-4bb1-8ef0-11a69a9e54a9.png)

```
$(document).ready(function() {

const dataSource = {
 contentType: 'application/json',
  api: {
    readData: {
        url: 'getDeviceList',
        method: 'POST'
    },
    updateData: {
        url: 'updateDeviceList',
        method: 'POST'
    }
  }
}

const columnData = [

  {header: 'Code', name: 'deviceCode'},
  {header: 'Name',name: 'deviceName',editor: 'text'},
  {header: 'Type',name: 'connectType'},
  {header: 'IP',name: 'ipAddr',editor: 'text'}

];


const grid = new tui.Grid({
  el: document.getElementById('grid'),
  columns: columnData,
  data: dataSource,
  pageOptions: {
            useClient: true,
            perPage: 24
        }

});

})

function addrow(){
const rowData = [
  {
    deviceCode: 'test',
    deviceName: 'k11',
    connectType: 'content11',
    ipAddr: '111111'
  },
  {
    deviceCode: 'test22',
    deviceName: 'k22',
    connectType: 'content22',
    ipAddr: '222222'
  }
];

grid.appendRows(rowData)

}

```

**Comment by sbyun1** [comment]
Thanks...
this also works. making entire grid in Korean
```javascript
grid.setLanguage('ko'); 
```
