### ISSUE TITLE
How to insert text in grid cell with relations

### ISSUE THREAD

**Issue by parkeng** [nhn/tui.grid#1707]
**Summary**

I set a specific cell in the grid to the select type.
I want the value of the target column of relations to change to a preset value each time that cell is selected.
However, the example requires you to select the value set for twoDepthData.

**Screenshots**

![image](https://user-images.githubusercontent.com/107672050/174248252-cce08806-37a3-46ab-a558-a34ecbb1c965.png)

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by jajugoguma** [comment]
@parkeng 
How about using `afterChange` event?

```js
grid.on('afterChange', ({changes}) => {
  if (changes[0].columnName === `${baseColumnName}`) {
    switch(changes[0].value) {
      /* Value case */
      case `${valueCase}`:
        grid.setValue(changes[0].rowKey, `${targetColumnName}`, `${valueToSet}`);
        break;
      // ...
    }
  }
});
```

**Comment by parkeng** [comment]
Thank you for your support. I can input text with afterChange  envent!!
