### ISSUE TITLE
How to customize for excel export.

### ISSUE THREAD

**Issue by parkeng** [nhn/tui.grid#1712]
**Summary**
I am using for Excel Export as below.

function saveExcel(){
        const options = {
            includeHiddenColumns: true,
            onlySelected: true,
            fileName: 'TEST_<?php echo date("YmdHis"); ?>',
        };
        grid.export('xlsx',options);
    }

By default, Excel will generated like layout of the grid. But I want to move or hide, or add Excel columns when Excel will exported unlike grid layout. Is it possible?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by jajugoguma** [comment]
@parkeng 
You can do it by modifying the data to be exported in the `before Export` event.

**Comment by parkeng** [comment]
Thank you for reply.
Could you please provide simple example?
Thank

2022년 6월 29일 (수) 오전 10:43, 김대연 ***@***.***>님이 작성:

**Comment by parkeng** [comment]
@jajugoguma Could you please provide simple example? I had saw 'before Export', but I can't find way how to utilize.
