### ISSUE TITLE
disable functoin also disables checkbox ??

### ISSUE THREAD

**Issue by sbyun1** [nhn/tui.grid#1716]
when I initially load grid with disable function it doesn't disable the checkbox column
but when I change back to disable after enable, it does.

is this intended or some sort of bug?

```javascript
const grid = tui.Grid;
const instance = new grid({
  el: document.getElementById('grid'),
  columns: columnData,
  data: dataSource,
  selectionUnit: 'row',
  pageOptions: {
                    useClient: true,
                    perPage: 24
                },
  rowHeaders: [
                {type: 'checkbox'},
                {type: 'rowNum'}
              ]
})
instance.disable()

instance.on('check', ev => {
    instance.enable()
})

instance.on('uncheck', ev => {
         instance.disable() // this disables the checkboxes as well???
    }
})



```

**Comment by jajugoguma** [comment]
@sbyun1 
I can't reproduce the problem. When I tested, `disable` works normally in initial loading. Can you give me an example through codesandbox etc for reproducing?

**Comment by sbyun1** [comment]
@jajugoguma 
seems like there's problem with disabling checkboxes on initial load when using dataSource options.
I put data manually and it looks like its working properly and disables checkboxes. 

but when I use same code but put data using dataSource options, it still doesn't disable checkboxes on initial load
and looked like this.

please refer to below for my grid application code. 
https://codesandbox.io/s/affectionate-agnesi-0sjppj?file=/index.html


initial load : doesn't disable checkboxes
![image](https://user-images.githubusercontent.com/86010657/175235621-4c383a30-8dec-46e5-a586-be9ae3658e08.png)

when I manually make a disable/enable button and bind the event, it works as intended. (checkbox disables too )
attached short video FYI

https://user-images.githubusercontent.com/86010657/176354167-e83368d6-cc41-4316-b7d8-6bd9bcd409fd.mp4
