### ISSUE TITLE
How to enable/disable for editor by users

### ISSUE THREAD

**Issue by parkeng** [nhn/tui.grid#1722]
**Summary**
I want to that certain user only can edit gird. Before grid is rendering, are there why how to control for editor on grid?

For example, 
if A user log-in, he can edit grid. 
If B user log-in, he can't edit grid and only view grid. 

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by jajugoguma** [comment]
@parkeng 
How about creating a grid with different column options according to user privileges?

**Comment by parkeng** [comment]
You mean, new grid is created as below. Right? But gird which is added isn't rendered.

//AA user
const grid = new tui.Grid({
    el: document.getElementById('grid'),
    data: {...

//BB user
const grid2 = new tui.Grid({
    el: document.getElementById('grid2'),
    data: {...
