### ISSUE TITLE
How to create URL link in grid

### ISSUE THREAD

**Issue by parkeng** [nhn/tui.grid#1723]
**Summary**
I want to create URL link for value in Grid. I think URL link wiil be "http://www.sample.com/" + column value.
Are there way how to implement ?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by sbyun1** [comment]
@parkeng 
You can use custom renderer 
https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-renderer.md

I wanted to implement the same thing and I found out that custom renderer

FYI
https://jsfiddle.net/no0rh6g4/49/

**Comment by sbyun1** [comment]
@parkeng
I wanted to implement the same thing and I found out that custom renderer
Documentation can be found [here](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-renderer.md).





FYI: this is my test code
https://jsfiddle.net/no0rh6g4/49/

hope it helps!

**Comment by parkeng** [comment]
@sbyun1 Thank you for support.
