### ISSUE TITLE
How can I put a string type in the row header? How to include the row header in the lsider area

### ISSUE THREAD

**Issue by rlozib** [nhn/tui.grid#1734]
**Summary**
A clear and concise description of what the question is.

Can't there be a string in the row header other than the numbers and check boxes?
If you look at the main example attribute on the Toast Grid homepage, the row header and lside area are included together, and I want to make it like that. If I make it, the row header is located on the l-side and the columns are located on the r-side.
The sample example is that there's no sauce

Working on the second image using tui. As the contents of the right row increase, the area of the Rowheaders does not increase, which breaks the style. Rowheaders are in a parent named tui-grid-lside-area, and the right tui-grid-cell-content is in a parent named tui-grid-rside-area, so is there a solution? Is there a reason?

**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/87642220/177671192-8af3437f-cb8d-421b-a383-dfaa95f70f8d.png)
![image](https://user-images.githubusercontent.com/87642220/177700864-f1834a1d-1303-4905-b61a-5f99aeafaefb.png)

**Version**
Write the version of the grid you are currently using.
4.21.2
**Additional context**

**Comment by jajugoguma** [comment]
@rlozib 
It's a regular column, not a row header. This can be done by calling the `setFrozenColumnCount` API or by setting the value of the `frozenCount` property of `columnOptions`.
