### ISSUE TITLE
Enable editor with custom conditions

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1751]
**Summary**
Is possible to enable editor in grid only for some rows, for example only for the row that is selected in screenshot?

**Screenshots**
![1](https://user-images.githubusercontent.com/20266205/180728661-fac77e04-4fc2-49f6-b211-ef7a4d8c2c77.png)

**Version**
4.21.2

**Comment by denaldhushi** [comment]
Is anyone here?

**Comment by jajugoguma** [comment]
@denaldhushi 

Sorry for late replying.
There is no options or API to enable editing on specific rows, but you can block editing the cell or row what you want to do like below. 

```js
grid.on('editingStart', (ev) => {
  const { instance, rowKey, columnName } = ev;

  if ( /* Condtion what you want to disable edit */ ) {
    ev.stop();
  }
});
```
