### ISSUE TITLE
Can I dynamically create a listItems?

### ISSUE THREAD

**Issue by pianlinForGitHub** [nhn/tui.grid#1752]
**Summary**
Can I dynamically create a listItems of the check box, select box, radio buttons in the grid?

**Screenshots**
None

**Version**
4.21.3

**Additional context**
None

**Comment by jajugoguma** [comment]
@pianlinForGitHub 

Unfortunately, it is not supported. How about use [relation column](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/relation-between-columns.md)?
