### ISSUE TITLE
Disable right click

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1754]
**Summary**
How can I disable the menu when I click in row with right click?

**Screenshots**
![Image Pasted at 2022-7-26 12-17](https://user-images.githubusercontent.com/20266205/180983512-741a0b68-422f-403e-a4a1-cc2f2e09eef6.png)

**Version**
4.21.2

**Comment by kimvs** [comment]
[reference URL](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/contextMenu.md)
const grid = Grid({
  // ...
  contextMenu:null  // ---> **If the contextMenu option is null, the context menu is disabled and the browser's default context menu is activated.**

**Comment by denaldhushi** [comment]
Thank you @kimvs
