### ISSUE TITLE
select filter can incorrectly return no results

### ISSUE THREAD

**Issue by iainteractive-iain** [nhn/tui.grid#1757]
Thank you for this great grid control.

**Describe the bug**
The 'select' column filter can incorrectly return no rows of data. The grid behaves correctly if "Select All" is checked, or if only one value is checked (or if no values are checked). However, the grid incorrectly returns no results, if two or more (but not all) values are checked.

This bug doesn't appear in [Example 24](https://nhn.github.io/tui.grid/latest/tutorial-example24-filter) because in that example, 'filter' is passed as a string, not an object.

**To Reproduce**
1. Save the following HTML page
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tui-grid@4.21.3/dist/tui-grid.min.css" integrity="sha256-9RPaN0NUVW/MqctDkGoG33ZNIhuKLeXUc2NRWkkjXhQ=" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/tui-grid@4.21.3/dist/tui-grid.min.js" integrity="sha256-Ya5Prb+wTPYt3FarlecnYAqn4Q6M446v4LuXxMvFKMs=" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="grid" style="width: 800px"></div>

        <script>
            let data = [
                {name: "Alex"},
                {name: "Dana"},
                {name: "Ash"},
            ]

            const grid = new tui.Grid({
                el: document.getElementById('grid'),
                data: data,
                columns: [
                    {
                        header: 'Name',
                        name: 'name',

                        filter: {
                            type: 'select'
                        },
                    },
                ]
            })
        </script>
    </body>
</html>
```
2. Open the HTML page in a browser
3. Click on the filter icon in the header.
4. Uncheck any one of the data values (for example, uncheck "Ash").
5. No data is shown in the grid.

![filter error](https://user-images.githubusercontent.com/47395551/181540452-89393555-76cc-41d9-895c-47a45f3e8369.jpg)

**Expected behavior**
The checked rows should be shown in the grid (for example, "Alex" and "Dana").

![filter working](https://user-images.githubusercontent.com/47395551/181540172-7a8da23b-941f-4144-ac0f-46af616527b2.jpg)

**Desktop**
- Windows, Chrome v103

**Additional context**

Note, if the filter configuration is changed to
```javascript
filter: 'select'
```

then the grid behaves as expected. That is, the error occurs when 'filter' is configured as an object, but not when 'filter' is a string.

**Comment by jajugoguma** [comment]
@iainteractive-iain 
Sorry for late reply.

It is not a bug as it is intended behavior. if set a filter to object, not a text, it means you don't use interal filter with default options(e.g. operator and so on). So, it may not work what you intended.

In this case, you need to set 'operator: 'OR'` to use the selection filter you set as like an object as the default behavior.

**Comment by iainteractive-iain** [comment]
Ah! Thank you for this explanation.

**Comment by iainteractive-iain** [comment]
Actually, this doesn't work either:

```javascript
filter: {
    type: 'select',
    operator: 'OR',
},
```

I think the problem is this line:

https://github.com/nhn/tui.grid/blob/cb95461cd843f0eea2d868e528a7866a74404156/packages/toast-ui.grid/src/store/column.ts#L190

which omits `'operator'` from the returned filter options object.

**Comment by iainteractive-iain** [comment]
I think this is still an issue, and I think it's an actual bug (not a question). https://github.com/nhn/tui.grid/issues/1757#issuecomment-1216445704
