### ISSUE TITLE
To refresh a custom renderer outside the grid

### ISSUE THREAD

**Issue by yewon97** [nhn/tui.grid#1760]
````
class RowNumberRenderer {
	constructor(props) {
		const el = document.createElement('span');

		this.el = el;
		this.el.innerHTML = this.getRowNum(props);
	 }
	
	getRowNum(props) {
		const perPage = props.grid.getPagination()._options.itemsPerPage;
		let currentPage = props.grid.getPagination()._currentPage;
		return Number(props.formattedValue) + (currentPage - 1) * perPage;
	 }
	
	 getElement() {
		return this.el;
	 }
	
	 render(props) {
		this.el.innerHTML = this.getRowNum(props);
	 }
}
````

I am using the class written above.
There is a problem with that class.
![스크린샷 2022-08-03 오후 7 37 17](https://user-images.githubusercontent.com/87147898/182588426-16852449-1b59-4034-9490-aab8c10b9dd7.jpg)
`grid.readData(1,{perPage:perPageNum}, true);`
I implemented a 10-to-5 line change function, and there was a problem here.
I didn't find the reason, but if I change from 10 to 5 lines on the last page, the rowHeader number looks like an image.
![Kapture 2022-08-03 at 19 46 19](https://user-images.githubusercontent.com/87147898/182590287-63717e01-90e9-47bb-a217-02df33f31c6f.gif)
Is there an API that can be applied to rowHeader except for custom render in the grid column?
I already knew that it will be solved by calling again Ajax with `reloadData()`.
But I don't want to use the Ajax call twice. (readData, reloadData)

**Comment by jajugoguma** [comment]
@yewon97 

Sorry for late replying.

The solution to what you want requires a little more checks.
However, How use [`rowHeaders`](https://nhn.github.io/tui.grid/latest/tutorial-example11-row-headers) with [`setPerPage`](https://nhn.github.io/tui.grid/latest/Grid#setPerPage) API?
If use it, I guess it works properly like what you want.

```js
const grid = new Grid({
  rowHeaders: [{ type: 'rowNum' }),
  // ...
});

const onSelectChange = () => {
  const selectedValue = /* The value of select(perPage) */;
 
  grid.setPerPage(selectedValue);
};
```
