### ISSUE TITLE
API setColumns

### ISSUE THREAD

**Issue by yangyeongwon** [nhn/tui.grid#1768]
**Summary**

API/Example: https://nhn.github.io/tui.grid/latest/Grid#setColumns

How to solve the problem that the existing width value is not applied when initializing the setColumns column list?

**Screenshots**

**Version**
4.21.4

**Additional context**

**Comment by rumen-scholar** [comment]
저도 같은 문제를 겪고 있네요....
동적 컬럼 때문에  setColums 를 사용했는데 width 가 적용 안되서 문제를 겪고 있습니다.
혹시 해결하셨나요?

관련 이슈 올리신 것이 여기밖에 없네요.
