### ISSUE TITLE
커스텀에디터(Custom Editor)에서 텍스트 변경 시 바로 DB 데이터 변경 문의

### ISSUE THREAD

**Issue by with-geun** [nhn/tui.grid#1769]
**Summary**
A clear and concise description of what the question is.
커스텀에디터(Custom Editor)에서 텍스트 변경 시 바로 DB 데이터 변경하려면 어떻게 해야 하나요?
그 라인만 바로 바로 저장시키고 싶습니다. (마치 구글 스프레드시트처럼)
Mouseoutevent,  focusout이나 enter 이벤트로 넣을 수 있을 것 같은데 혹시 예제 코드 있을까요?

**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/99859768/185982891-162c5d98-a4a1-4d48-8d46-2e6716a8515c.png)

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by jajugoguma** [comment]
@with-geun 

Sorry for late replying.
When data is changed, write like following [document](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md#%EB%B3%80%EA%B2%BD-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5) and call `request` API, can do what you want.

```js
grid.on('afterChange', () => {
  grid.request('updateData');
});
```

If you want update DB on every changes in editor, you should create custom editor for it and add change event handler which is doing send data to DB on editor element(in this case, `input` element).
