### ISSUE TITLE
Filter type Select uses AND logical operator when multiple values are selected

### ISSUE THREAD

**Issue by gestoenergy-dev7** [nhn/tui.grid#1897]
When a column header has a "select" type filter, it works fine when all rows or only one row of the choices is selected but it doesn´t show anything when multiple rows are selected.

To reproduce the bug, create a table with at least one column  (can be numeric or text data) with a "select" type filter associated to it. Click the filter option and select more than one row and less than all the options available. When this is done none of the results are shown in the data table. I suppose the logical operation that is being used is an AND instead of an OR.

**Comment by rumen-scholar** [comment]
I'm experiencing the same phenomenon.
