### ISSUE TITLE
TUI Grid & Pagination

### ISSUE THREAD

**Issue by mbohdziul** [nhn/tui.grid#198]
## Version
3.0.0

## Development Environment
Chrome 69.0.3497.81

## Current Behavior
When am loading data to tui grid, it can be filtered - for example by date, or user id. parameters are taken from the form on my page.
The first page is ok (am populating it with readData()), the problem arrives when I switch page (with tui pagination) - new page is loaded without any filtering.

Grid init:
```js
var grid = new tui
    .Grid({
        el: $('#data-table'),
        scrollX: false,
        scrollY: false,
        minBodyHeight: 200,
        pagination: true,
        enableAjaxHistory: true,
        columns: [
            {title: 'province', name: 'province', whiteSpace: 'normal'},
            {title: 'user', name: 'user_name', whiteSpace: 'normal'}
        ]
    })
    .use('Net', {
        perPage: rowsPerPage,
        readDataMethod: 'POST',
        api: {
            readData: '/get-data'
        }
    })
    ```

When I use readData() method I can pass data with it to the server. 

```js
    var grid_net = grid.getAddOn('Net');

    grid_net
            .readData({
                page: 1,
                data: { 
                    query: 'D2',
                    params: 12,
                    nextp : 10
                },
                resetData: true
            });
```

## Expected Behavior
How can I pass data to the server when am changing pages with tui pagination?

**Comment by seonim-ryu** [comment]
@mbohdziul 
Sorry for the delay.
I need to check the value of the server data that is given when calling the `get-data` API.
Is the grid not updated even though the server is filtering out the data?
I want you to check it out and let me know.
