### ISSUE TITLE
Supporting button type for editOptions

### ISSUE THREAD

**Issue by Foretcs** [nhn/tui.grid#268]
안녕하세요.
TOAST UI 현재 잘 쓰고있습니다.

한가지 궁금한게 있는데요, 
GRID row에 editOptions으로 'text', 'password', 'select', 'radio', 'checkbox'.가 제공되고 있는데,
버튼을 추가하실 계획은 없으신가요?

---

이슈 관리 정책상 제목과 본문이 영어로 번역됩니다. 양해 부탁드립니다.

## English
Do you have any plan to support `button` type for `editOptions` in addition to `text`, `password`, `select`, `radio`, `checkbox`?

**Comment by dongwoo-kim** [comment]
I think the `button` element is not an essential input for inserting/updating data. You can implement this by using `formatter` options and assigning custom event handler. We are planning to offer an official way to make custom cell-editors after the major update for 4.0.0.
