### ISSUE TITLE
enable the checkbox of disabled row

### ISSUE THREAD

**Issue by yoonee25** [nhn/tui.grid#278]
안녕하세요. tui grid를 잘 사용하고 있습니다.
disableRow(rowKey) 하여 비활성할 수 있는 것을 알고있습니다.
다만 특정 행을 삭제하기 위해서는 rowHeaders를 체크하여 remove 시키는데
disableRow한 행은 체크박스가 활성화되지않아 체크할 수 없습니다.
enableCheck(rowKey) 하면 체크박스를 포함한 행의 전체 필드가 활성화됩니다.
특정 행의 모든 필드를 비활성화하되 rowHeaders의 체크박스를 활성화하는 방법은 없을까요?

---
이슈 관리 정책상 제목과 본문이 영어로 번역됩니다. 양해 부탁드립니다.

### Translated (English)
It seems that there is no way to enable the checkbox of disabled row.
`enableCheck(rowKey)` enables the entire fields including the checkbox.
Is there any way to enable only the checkbox and keep other fields to be disabled?

**Comment by dongwoo-kim** [comment]
안녕하세요. 
원래 `disableCheck()`와 `diableRow()`를 구분한 이유는 체크박스만 비활성화 시키려는 상황 때문인데, 반대의 경우는 고려하지 못한 것 같습니다. 현재는 `_extraData.rowState`가 `DISABLED`, `DISABLED_CHECK`, `CHECKED` 세 가지의 상태만 가질 수 있습니다. 여기에 `DISABLE_WITHOUT_CHECK`와 같은 상태를 추가할 수도 있겠지만, 그보다 행이 비활성화 상태와 체크박스의 비활성화 상태를 별도의 필드로 관리하는 게 좋을 것 같습니다. 다만 이 경우 API 변경이 이루어져야 하기 때문에, 메이저 업데이트인 4.0때 반영할 수 있을 것 같습니다. 

---
### Translated (English)

The initial purpose of separating `disbleCheck()` and `disableRow()` was for the case of disabling the only checkboxes of rows. Currently, `_extraData.rowState` can be the one of three states - `DISABLED`, `DISABLED_CHECK`, `CHECKED`. It might be possible to add an additional state like `DISABLE_WITHOUT_CHECK` but I think It would be better to manage disabled state of the checkbox and the other fields in separate variable. As this is breaking change, we can release this change in v4.0.0

**Comment by js87zz** [comment]
@yoonee25 
reference API(`enableRowCheck`, 'disableRowCheck') in v4.0.0
