### ISSUE TITLE
rowSpan된 항목의 onAfterChange 이벤트 중복 현상는 어떻게 처리하나요

### ISSUE THREAD

**Issue by hahuyun1** [nhn/tui.grid#281]
## Version 
tui.grid 3.3.0

## Development Environment
chrome

## Current Behavior
데이터를 주입할대 
_extraData를 활용하여 일부 컬럼에 rowSpan을 적용시킨 후
해당 항목에 onAfterChange 이벤트를 발생시키면
rowSpan된 갯수만큼 이벤트가 중복 처리되는데 이 현상에 대한 해결법이 있나요?

## Expected Behavior
.

**Comment by dongwoo-kim** [comment]
이슈 템플릿에 맞게 작성 부탁드립니다. 
본문 수정했으니, 버전 정보와 개발 환경 정보 기입 부탁드릴게요 :)

**Comment by dongwoo-kim** [comment]
rowSpan이 된 경우 셀의 데이터를 변경했을 때 영향을 받는 모든 행의 데이터를 조작해야 하는 경우도 있어서, 모든 행에서 이벤트를 발생시키고 있습니다. 만약 rowSpan된 첫번째 행에서만 이벤트 처리를 하고 싶다면, 다음과 같이 `getRowSpanData`를 활용하시면 될 것 같습니다.

```js
{
  name: "name",
  onAfterChange(ev) {
    const { isMainRow } = grid.getRowSpanData(ev.rowKey, "name");
    if (isMainRow) {
      // do something
    }
  }
}
```
