### ISSUE TITLE
grid 스크롤 사용

### ISSUE THREAD

**Issue by kkerel** [nhn/tui.grid#282]
## Version
3.3.1

## Development Environment
크롬 브라우저

## Current Behavior
```js
var noticeGrid = new tui.Grid({
  el: $('.notice__grid'),
  scrollX: false,
  scrollY: true,
  bodyHeight: 317,
  rowHeight: 44
});
```

scrollY: true 로 스크롤을 사용할 경우 class="tui-grid-scrollbar-right-top"가
생성 되어서 레이아웃이 추가 되는데 추가되지 않도록 설정기능이 따로 있는지 궁금합니다.

## Expected Behavior
스크롤 생성시 tui-grid-scrollbar-right-top가 사라지거나, 레이아웃에 영향이 없었으면 좋겠습니다.

**Comment by dongwoo-kim** [comment]
우측 상단 박스는 단지 디자인 요소를 위해 추가하고 있습니다만..  혹시 어떤 이슈가 있는지 알 수 있을까요?  
현재 이 박스만 제거하는 기능은 제공하지 않고 있습니다. 꼭 제거하고 싶다면 다음과 같이 외부 스타일에 별도로 정의하는 방법 밖에 없을 것 같습니다.

```css
.tui-grid-scrollbar-right-top {display: none}
```
