### ISSUE TITLE
net 이용할시 json 데이터 형식 문의

### ISSUE THREAD

**Issue by gyjeon** [nhn/tui.grid#285]
## Version
3.6.0

## Development Environment
윈도우즈

## Current Behavior
기본적인 질문일 수도 있으나 물어볼만한 곳이 없어 질문 드립니다.
/tui.grid-3.6.0/tui.grid-3.6.0/examples/example10-using-net.html 샘플로 테스트 중입니다.
아래와 같이 json 포맷을 만들어야 한다고 하는데요. 
이 상태로 조회를 하면 no data라고 표시됩니다.

```js
{
  "result": true,
  "data": {
    "contents": [],
    "pagination": {
      "page": 1,
      "totalCount": 1
    }
  }
}
```

그래서 아래와 같이 값을 넣어보면 에러가 납니다.
```js
{
  "result": true,
  "data": {
    "contents": [ 
      {
        id: 549731,
        name: 'B Lies'
      },
    ],
    "pagination": {
      "page": 1,
      "totalCount": 1
    }
  }
}
```

어떻게 값을 넣어야할지 모르겠습니다.
실 예제 데이터를 알려 주시면 좋겠습니다.

**Comment by dongwoo-kim** [comment]
위의 코드를 실행해도 정상저긍로 동작해야 합니다. 데이터 형식보다는 다른 쪽에 문제가 있는 것 같은데, 알려주신 정보만으로는 알기가 어렵네요. 에러 메시지나 다른 코드도 함께 알려주실 수 있나요?
