### ISSUE TITLE
Grid 헤더 동적 숨김, 보이기 기능 관련

### ISSUE THREAD

**Issue by raeganja** [nhn/tui.grid#288]
안녕하세요? Grid 기능관련 문의사항이 있습니다.

혹시 Grid 헤더를 동적으로 숨김하거나 보이기 하는 기능이 있는지 문의합니다.
그리드 컬럼 목록뷰 후 선택해서 숨김하거나 보이기 하는 기능

## Version
v3.6.0

## Development Environment
Chrome 버전 72.0.3626.121(공식 빌드) (64비트)

**Comment by dongwoo-kim** [comment]
안녕하세요. 현재 그리드의 헤더를 숨기는 기능은 제공하지 않습니다. 혹시 어떤 용도로 필요한 지 알 수 있을까요? 만약 범용적인 기능이라면 추가 개발을 고려해볼 수 있을 것 같습니다.

**Comment by raeganja** [comment]
안녕하세요? 답변주셔서 감사합니다.
현재 다른 UI Framework에서도 모두 그리드 헤더 숨기기 기능을 지원하고 있습니다.
마우스 우클릭시에 서브 메뉴로 헤더 숨기기를 지원하죠.
많은 사용자들이 자기가 원하는 데이터만 보고자하는 요구가 많이 있습니다.
해당 기능이 추가되면 프로그램에 유용할 것 같네요..

**Comment by dongwoo-kim** [comment]
답변 감사합니다. 제가 생각했던 기능과 다른 것 같은데.. 혹시 특정 컬럼을 숨기는 기능을 말씀하시는 건가요? 
원하는 데이터만 보고자 하는 요구라면, 특정 컬럼의 데이터를 모두 숨기려는 것 같은데.. 
그런 용도라면 [showColumn](http://nhn.github.io/tui.grid/latest/Grid#showColumn), [hideColumn](http://nhn.github.io/tui.grid/latest/Grid#hideColumn)을 활용하시면 됩니다.

**Comment by kkmjj** [comment]
header 숨김 여부는 haeder의 height 값을 0을 주면 되는거 같군요
