### ISSUE TITLE
excel 다운로드시 클라이언트에서 다운로드가 가능한가요?

### ISSUE THREAD

**Issue by bifungu** [nhn/tui.grid#292]
안녕하세요.
현재 grid 3.5.0 버전을 사용하여 개발하고 있습니다.

Net 기능 중에 excel download 기능을 사용하려 하는데
js 파일을 열어봐도 실제 클라이언트에서 엑셀로 내리는 기능은 없는 것 같은데요.
download function 을 호출하면 실제 서버에서 excel을 구현해야 하는 가요?

확인 요청드립니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
현재 Net에서 제공하는 엑셀 다운로드 기능은 특정 URL로 요청을 보내는 역할만 하고 있습니다. 
해당 URL에서 엑셀 파일을 내려주는 기능은 직접 구현해야만 합니다.
