### ISSUE TITLE
그리드 페이지시 컬럼 정렬 관련

### ISSUE THREAD

**Issue by raeganja** [nhn/tui.grid#301]
## Version
v3.7.0

## Development Environment
Chrome 73.0.xx, Windows10

## Current Behavior

```js
columns: [
    {
        title: '<s:text name="label.user.id"/>',
        name: 'userId',
        width: 150,
        sortable: true
    },
    {
        title: '<s:text name="common.user.name"/>',
        name: 'name',
        ellipsis:true,
        hidden:true,
        width: 150,
        sortable: true
    },
    {
        title: '<s:text name="common.dept"/>',
        name: 'deptName',
        width: 200
    },
    {
        title: '<s:text name="common.menu.group.name"/>',
        name: 'menuGroupName',
        width: 200
    },
    {
        title: '<s:text name="common.use.yn"/>',
        name: 'useYn',
        width: 200
    }
]
```

## Expected Behavior

Grid Hader Column에 Sort 기능을 사용할 때 문의사항이 있습니다.
Grid에 페이지 기능을 함께 사용할 때 컬럼 정렬을 하게되면 현재 보여지는 페이지에만 정렬이 되는데 전체 데이터 정렬은 안되는건가요? 다른 설정이 필요한 건가요?

**Comment by jung-han** [comment]
@raeganja
안녕하세요. 소팅 버튼을 누를 때 전체 데이터가 같이 소팅 되고 싶으시다면 서버에서 소팅이 같이 이뤄져 그 데이터를 가져와 보여주는 방법이 있을 것 같습니다. `useClientSort` 옵션을 false 로 하신다면 그리드에서 소팅 시 서버에서 소팅이 이뤄지도록 설정을 할 수 있습니다.

[링크](https://github.com/nhnent/tui.grid/blob/production/docs/binding-to-remote-data.md#protocol-of-readdata)는 remote data와 함께 사용할 때의 튜토리얼입니다. 감사합니다.
