### ISSUE TITLE
row.set 시 해당 데이터의 formatter 적용 방법 문의

### ISSUE THREAD

**Issue by EventHot** [nhn/tui.grid#302]
아래와 같이

```js
var row = this.get(rowKey);
if (row) {
  row.set(rowData, {
    silent: silent
  });
}
```

데이터를 변경 할때 
해당 하는 컬럼의 formatter 조건에 맞게 변경을 시키는 방법을 알고 싶습니다.
아래는 formatter에 적용한 구문 입니다.

```js
if(rowObject.PROGRESS_STATUS == 3 ){
  return 'alert("1");';
} else {
  return 'alert("2");';
}
```

로우의 PROGRESS_STATUS 데이터를 3으로 변경했지만
formatter의 조건 문이 동작하지 않아 확인해 보니
formatter가 처음 그리드 생성시에만 한번 적용되는것 같은데요.

위에 처럼 중간에 데이터를 변경 할 경우 해당 로우만
화면 갱신 없이 formatter를 재적용 하는 명령문이나 방법이 있을까요.ㅠ
이 기능이 꼭 필요 해서....부탁드립니다.

급한대로...

```js
  setRowData: function (rowKey, rowData, silent) {
	        var row = this.get(rowKey);

	        if (row) {
	            row.set(rowData, {
	                silent: silent
	            });

	            row.changed = _.pick(rowData, _.pluck(_.reject(row.columnModel.attributes.dataColumns, function (obj) { return obj.formatter == undefined; }), 'name'));
	            
	            row.trigger('change', row);
	        }
	    },
	    setCell: function(columnName, param) {
	        var isValueChanged = false;
	        var changed = [];
	        var rowIndex, rowKey, data;

	        if (!this.has(columnName)) {
	            return;
	        }

	        rowKey = this.get('rowKey');
	        data = _.clone(this.get(columnName));

	        _.each(param, function (changeValue, name) {
	          
	                isValueChanged = (name === 'value') ? true : isValueChanged;
	                data[name] = changeValue;
	                changed.push(name);
	      
	        }, this);

	        data.changed = changed;

	        this.set(columnName, data, {
	            silent: false
	        });

	        rowIndex = this.dataModel.indexOfRowKey(rowKey);
	        this.trigger('valueChange', rowIndex);
	    },
```

두곳을 수정하여 사용하고 있습니다...

**Comment by dongwoo-kim** [comment]
`formatter`는 데이터가 변경될 때마다 실행되는 게 기본 동작입니다. PROGRESS_STATUS 데이터를 어떤 식으로 변경하셨는지는 모르겠지만, `setValue` 등의 함수를 사용해서 값을 변경했다면 변경이 감지되서 formatter 가 실행되게 됩니다. 혹시 사용 코드를 좀 더 알려주실 수 있나요? 알려주신 정보만으로는 파악이 어렵네요.

**Comment by EventHot** [comment]
아래와 같은 함수를 만들어 사용을 하고 있습니다.

컬럼중 셀렉트 박스로 되어 있는 진행률 표시  PROGRESS_STATUS 컬럼의 데이터가 
변경이 될때 디비에서 계산 로직이 수행되고 결과 값이 리턴이 되면 

아래 함수로 수정된 로우의 데이터를 다시 바인딩 시킵니다. 

 setRowData: function (rowKey, rowData, silent) {
	        var row = this.get(rowKey);

	        if (row) {
	            row.set(rowData, {
	                silent: silent
	            });	            
	        }
	    },

위와 같이 바인딩을 시켯을 경우 
PROGRESS_STATUS의 컬럼은 변경이 되는 컬럼이기에 formatter가 작동이 되는데
setRowData로 처리된 다른 컬럼들도 formatter 가 작동이 되었으면 합니다.
