### ISSUE TITLE
그리드에서 현재 선택되어진 row 데이터 혹은 row id, row index를 가져오는 방법 문의

### ISSUE THREAD

**Issue by minsu0806** [nhn/tui.grid#303]
안녕하세요. 기능관련 문의를 드리고자 글을 남깁니다.

제가 원하는 기능은 그리드에서 현재 선택되어진 row들의 데이터를 가져오는 기능인데요..
예컨데.

```
tuiGrid.getSelectedRowData();                                      // 또는
tuiGrid.getRows( tuiGrid.getSelectedRowIndexes() );    
```
위와 같이 작성할 경우 아래처럼 json형태의 데이터를 가져오는 기능입니다.

`return data > [ { rowidx:0, col1:'데이터', col2:'입니다' }];`

제가  document를 읽어봤을 때 getRow, getRows, selection 과 같은 메소드는 찾을 수 있었는데
getSelection과 같이 현재 선택된 row에 대한 정보를 가져오는 api를 찾지 못하여 문의 드립니다.

읽어주셔서 감사합니다.

**Comment by EventHot** [comment]
공식 답변 달리기 전 급하시면(아시겟지만)
Grid.getRow( Grid.$el.find('.tui-grid-cell-current-row:first').parents('tr').data('rowKey') , false);
로 하시면 어떨까요.

**Comment by minsu0806** [comment]
EvenHot님 답변 감사합니다.. 현재는 이렇게 쓰고 있습니다 
내부요소에 접근해서 처리하니까 좀 불안하네요 ^^;;;
`
tui.Grid.prototype.getSelectedRows = function(){
	var inputRange = grid.modelManager.selectionModel.inputRange;
	var currentRow = this.$el.find('.tui-grid-cell-current-row:first').parents('tr').data('rowKey');
	
	if(inputRange){
		var selectedRows = [];
		for(var i = inputRange.row[0]; i <= inputRange.row[inputRange.row.length-1] ; i++)
			selectedRows.push(this.getRowAt(i,false));
		
		return selectedRows;
	}
	else if(currentRow){
		return [this.getRowAt( grid.$el.find('.tui-grid-cell-current-row:first').parents('tr').data('rowKey') , false)];
	}
	
	return null;
};
`

**Comment by minsu0806** [comment]
제가 만든 기능은 혹여 grid 클릭시 ctrl키를 누른 상태에서 서로 떨어져 있는 행을 멀티로 선택하는 기능이 있을 경우 버그가 발생할 가능성이 있습니다 ㅠ

**Comment by bifungu** [comment]
getFocusedCell 이라는 함수가 있습니다. 저 함수를 쓰시면 rowKey를 가져오실 수 있습니다.

**Comment by dongwoo-kim** [comment]
그러고 보니 Selection 정보를 반환하는 API가 없는 것 같네요. 포커스의 경우는 `getFocusedCell`이 있는데 말이죠.

Selection은 행 단위의 선택 보다는 Range Selection 용도로 사용하고 있어서, `getSelectedRows`와 같이 행 단위의 API를 제공하기는 좀 어려울 것 같습니다. 아마 `getSelectionRange` 라는 이름으로 start 셀 정보와 end 셀 정보를 반환하는 형태가 될 것 같습니다.

@minsu0806 : 현재는 구현하신 코드로 사용해도 크게 문제는 없을 것 같습니다만, 나중에 `getSelectionRange` API가 정식 제공된다면 `modelManager.selectionModel` 를 직접 접근하는 부분을 대체할 수 있을 것 같습니다. 포커스된 로우를 가져오는 부분은@bifungu 님 말씀처럼 `getFocusedCell`을 사용하는 게 나을 것 같아요.

**Comment by minsu0806** [comment]
@dongwoo-kim 네 감사합니다. 참고하겠습니다!!!

**Comment by jerryokwork** [comment]
@minsu0806 올려주신 getSelectedRows 함수 유용하게 쓰겠습니다. 
@dongwoo-kim 질문이 있어서 글 남깁니다.  modelManager.selectionModel.inputRange array start/end 값이 rowKey 와 일치하는지 여부가 궁금합니다. seleted rowData 와 별개로 selected rowKey를 알고 싶을때 위 값을 이용해도 상관없을까요? 혹시 inputRange 값이 그리드 row index 만을 의미한다면 해당 rowKey를 구하는 다른 방법이 있을까요?

**Comment by dongwoo-kim** [comment]
@jerryokwork 안녕하세요. 이 이슈와는 다른 내용인 것 같은데, 별도의 이슈로 등록해주실 수 있을까요? 관리를 위해 한 이슈에서는 한가지 내용만 논의하고 있습니다.
