### ISSUE TITLE
첫 호출 시 pagination 의 원하는 page 이동

### ISSUE THREAD

**Issue by Eden-Kim** [nhn/tui.grid#304]
## Version
tui.grid-3.6.0
tui-pagination-3.3.2

안녕하세요.
토스트 그리드를 사용하다 안되는 부분이 있어 질문 드립니다.

현재 구현하려는 의도는 검색 조건 유지를 위한 상황입니다.

Net 을 사용해서 그리드를 호출하여 사용하고 있습니다.
use 함수를 사용하는 옵션 중에는 그리드가 그려지고 나서 보여지는 페이지 설정 부분이 없는 것으로 보이는데 어떻게 해서 원하는 페이지로 보여지는지 궁금합니다.

검색 완료 후 항상 1 page 로만 호출이 됩니다.
이 때 pagination 에서 다른 페이지 이동은 잘 됩니다만...

검색 완료 후 2page 로 보여지고 싶은데 첫페이지 설정 옵션이 없다 보니
api 파라미터를 '?page=2'를 추가해서 넘기니 pagination 에서 다른 페이지 이동이 전혀 되지 않네요.

## Current Behavior
```js
grid.use('Net', {
  perPage: 10,
  readDataMethod: 'GET',
  api: { readData: apiUrl }
});
```
항상 1page 로 고정됨.

## Expected Behavior
grid.use 첫 호출 시 옵션 등의 값을 주어 1page가 아닌 원하는 page 가 나오길 원함

**Comment by dongwoo-kim** [comment]
안녕하세요. 페이지나 파라미터를 동적으로 변경하기 위해서는 Net 객체의 [readData](http://nhn.github.io/tui.grid/latest/addon_net#readData) 메소드를 사용해야 합니다. 아래 코드처럼 `grid.getAddOn`을 사용해서 Net 객체를 가져오신 다음에 호출하면 됩니다.

```js
const net = grid.getAddOn('Net');
const params = {
  param1: 'xx',
  param2: 'xx'
};
net.readData(2, params, true);
```

**Comment by Eden-Kim** [comment]
답변 감사합니다.
올려주신 예제대로 하니 파라미터에 의한 검색 및 페이지 설정은 잘 됩니다.
아래 코드처럼 이벤트 발생 시 적용하니 잘 적용되는 것을 확인 하였습니다.

```js
$('#btnSearch').click(function() {
    const net = grid.getAddOn('Net');
    net.readData(2, readDataParams, true);
});
```

하지만 검색조건 유지에 대한 상황이라 조건이 좀 맞이 않는 부분들이 있네요.
2번 페이지에서 그리드 클릭 후 상세 페이지로 갔다가 다시 목록 화면을 불러 올때 다시 2번 페이지 유지가 되어야 하는데 현재 상황은 1페이지로 가게 됩니다.
코드는 아래 처럼 구성을 했습니다.

```js
grid.use('Net', {
    perPage: perPage,
    readDataMethod: 'GET',
    api: {
        readData: apiUrl
    }
}).on('successResponse', function(data) {
     // 완료 후
    const net = grid.getAddOn('Net');
    net.readData(page, params, true);  // page 이전 화면에서 넘겨 받은 기존 page 유지
});
```

grid 객체 자체를 상세페이지 등으로 가지고 다녀야 할까요?
다른 좋은 방법 있으면 의견 주시면 감사하겠습니다.

**Comment by dongwoo-kim** [comment]
페이지를 어떤 방식으로 이동하는지는 모르겠습니다만(SPA인지, 페이지 변경인지), 검색 조건을 유지하고 싶다면 상세 페이지로 갈 때 파라미터를 전달한 다음, 목록으로 돌아올 때 동일한 파라미터를 전달해 주어야 할 것 같습니다. 사실 이 부분은 그리드의 기능 범위를 벗어나는 부분이라 딱히 가이드를 드리기가 어렵네요.
만약 SPA가 아니고, 목록 페이지를 불러올 때마다 그리드를 새로 생성한다면, `successResponse`를 사용하는 것이 아니라 `initialRequest`를 `false`로 지정한 다음에 직접 `readData`를 호출하는 것이 좋을 것 같습니다.
```js
grid.use('Net', {
  perPage: perPage,
  readDataMethod: 'GET',
  initialRequest: false,
  api: {
    readData: apiUrl
  }
});
const net = grid.getAddOn('Net');
const page = /* from URL or Router */;
const query = /* from URL or Router */;
net.readData(page, query, true);
```

**Comment by Eden-Kim** [comment]
답변 감사합니다.

제가 원하는게 맞네요. 저 initialRequest 옵션 부분을 제가 모르고 지나쳤나 봅니다.
항상 호출되서 1페이지로 가는 부분이 계속 걸림돌이 되었네요.

덕분에 잘 해결 했습니다. 
다시 한번 감사드립니다.

**Comment by dongwoo-kim** [comment]
해결됐다니 다행이네요 :) 
아무래도 Net 관련 튜토리얼이 부족해서 관련 옵션을 찾아보기가 어려운 것 같습니다. 
추후에 문서를 좀 더 보완할 수 있도록 하겠습니다.
