### ISSUE TITLE
grid tab 기능이 있나요?

### ISSUE THREAD

**Issue by bifungu** [nhn/tui.grid#308]
안녕하세요.
Toast UI Grid를 이용해서 기존 시스템을 변경 중에 있습니다.
다른 컴포넌트도 찾아봤는데 못 찾는 것인가 해서 문의 드립니다.

Toast UI에 혹시 Tab 관련 기능이 있는지요?
Layout 쪽도 찾아보니 보이질 않아서요.

답변 기다리겠습니다.

감사합니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
Toast UI에 Tab 기능을 제공하는 컴포넌트는 없습니다. 별개의 컴포넌트로 관리하기에는 기능이 제한적이라.. 제공이 힘들 것 같아요.
