### ISSUE TITLE
컬럼 옮기는 옵션에 대해 문의드립니다.

### ISSUE THREAD

**Issue by HwangYurim** [nhn/tui.grid#309]
## Version

3.4.0
## Development Environment

Windows 10
Chrome 73.0.3683.103
IE 8 이상
## Current Behavior

```js
// Write example code
```

## Expected Behavior

안녕하세요.
그리드를 원하는대로 생성하였는데, 사용자가 그리드 내에서 컬럼을 옮길 수 있는 옵션을 붙이고 싶습니다.
예시를 알 수 있을까요?
api 문서나  example 페이지에서 찾지못하여 글을 남깁니다.
감사합니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 현재 개별 컬럼의 위치를 옮기는 API는 따로 제공되지 않습니다. 다만 `setColumn` 메소드를 이용해서 전체 컬럼 정보를 재설정할 수는 있습니다. 예를 들어 기존 2번째와 3번째 컬럼의 위치를 서로 바꾸려면 다음과 같이 사용할 수 있습니다.

```js
const columns = [
  { /* ... */ },
  { /* ... */ },
  { /* ... */ }
];
 
const grid = new tui.Grid({
  el: $('#grid'),
  data: gridData,
  columns: columns
});

const columnsReordered = [columns[0], columns[2], columns[1]];

grid.setColumns(columnsReordered);
```
