### ISSUE TITLE
net 을 사용하여 서버측에 선택된 데이터 전달 관련 문의드립니다.

### ISSUE THREAD

**Issue by simson14** [nhn/tui.grid#312]
안녕하세요!
toast grid net을 이용하여 서버와 통신하여 DB의 데이터를 삭제하는 작업을 진행중에
잘 안되는 부분이 있어 문의 드립니다.

grid에서 복수개의 데이터를 선택(checked)후 아래와 같이 서버측에 삭제요청을 보내려고 합니다.

var deviceGridAddOn = deviceGrid.getAddOn('Net');

$("#deleteDevice").click(function () {
            var options = {
                url: '/device/delete.ajax',
                type: "post",
                hasDataParam: true,
                checkedOnly: true,
                modifiedOnly: false,
                showConfirm: true,
                updateOriginal : true,
                withCredentials: false
            };
            deviceGridAddOn.request("deleteData", options);
        }); 

서버측에 요청은 정상적으로 가고 있으나 grid에서 선택된 데이터를 서버측에 특정 이름의 json타입으로 보낼 수 있는 방법이 있는지 문의 드립니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
그리드 Net에서 제공하는 `request('deleteData')` 기능은 이미 클라이언트에서 삭제된 데이터에 대해 서버쪽에 동기화 요청을 보내는 용도로 사용됩니다. 설명해주신 것처럼 체크된 로우의 데이터를 서버쪽으로 전송하려면 [getCheckedRows](http://nhn.github.io/tui.grid/latest/Grid#getCheckedRows)나 [getCheckedRowKeys](http://nhn.github.io/tui.grid/latest/Grid#getCheckedRowKeys) 등을 활용해서 직접 Ajax 요청을 보내야 할 것 같습니다.
