### ISSUE TITLE
컨트롤 휠 키를 이용하여 확대시

### ISSUE THREAD

**Issue by EventHot** [nhn/tui.grid#315]
안녕하세요. 또 질문을 드립니다;;;

컴퓨터 해상도가 낮을 경우 
디스플레이 확대율이 110퍼 로 확대된 컴퓨터나

컨트롤 마우스키 휠 버튼을 이용하여 페이지 확대시에.
FocusLayer 의 위치가 어긋 나는 현상이 있습니다. 

어떻게 해결을 해야 할 까요

컴럼이 많아 지면 뒤로 갈수록 점점 fucus-selection 박스가 위치가 깨집니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
이 이슈는 브라우저가 확대된 상황에서 반환하는 DOM 위치 정보가 실제 그려지는 내용과 달라서 발생하는 것으로 알고 있습니다. 좀 더 자세히 들여봐야겠지만, 현재 상황에서는 해결하기가 어렵고 특정 환경에서만 발생하기 때문에 노운 이슈로 관리하고 있습니다.

**Comment by EventHot** [comment]
위의 예에서는 휠로 예를 들었는데요..

노트북의 경우 대다수의 display 글꼴 설정이 125% 권장설정이 되어 있어서 노트북은 거의 FocusLayer가 깨진다고 봐야 될 것 같습니다.

다시 한번 경중을 검토 해주시기 바랍니다.

**Comment by seonim-ryu** [comment]
@EventHot 
여러 상황을 테스트 해보았는데요.
해당 이슈는 크롬 브라우저에서 확대 비율에 따라 계산된 엘리먼트의 높이 값이 정수가 아닌 경우에 발생하는 것을 확인하였습니다. (브라우저 내부에서 계산 로직에 의한 버그로 확인됩니다)

그리드의 기본 행 높이 값을 사용할 때 위와 같은 상황이 발생하고 있고, 옵션으로 행 높이를 조정하면 문제를 해결할 수 
어 가이드 합니다.

아래와 같이 `rowHeight` 옵션 값을 설정하면 확대 시에도 포커스 위치를 보장할 수 있습니다.
그리드의 기본 행 높이는 `rowHeight` 내부 기본 값(`40px`)과  보더 값(`1px`)이 더해져 `41px`이 되며 확대 상황에서 행 높이가 소수 값을 가지게 됩니다.
이 로직에 따라 `rowHeight: 39`로 지정하면 행 높이가 `40px`이 되고 125% 확대 비율에서도 정수 값을 유지하여 정상 동작합니다.
추가로 `minRowHeight`의 값도 함께 설정을 해주셔야 행 높이가 변경됩니다.

```js
var grid = new tui.Grid({
  el: $('#grid'),
  ...
  rowHeight: 39,
  minRowHeight: 20, // 설정하지 않을 경우 기본 값이 40으로 설정되어 행 높이가 변경되지 않음
  ...
});
```
그리드에서 포커스 상태일 때 값을 보정하는 방법도 검토를 해보았으나 렌더링을 할 때마다 행 높이를 재설정 하게되는 부담이 있습니다. 

행 높이를 조정하는 방법 검토해주시면 감사하겠습니다. :)
