### ISSUE TITLE
RowHeight가 작동하지 않는것 같습니다.

### ISSUE THREAD

**Issue by jon890** [nhn/tui.grid#316]
## Version
3.7.0

## Development Environment
Spring, JSP

## Current Behavior

JSP에서 toast grid를 사용중에 있습니다.
virtuaScrolling을 사용하고, rowheight속성을 주는데
max-height:40?이라는 속성이 무조건 들어가고 height가 변경되지 않는것 같은데 확인부탁드립니다..
그리고 혹시 한가지 더 font-size 변경옵션은 없나요?

```js
// Write example code
```

**Comment by dongwoo-kim** [comment]
알려주신 내용만으로는 파악이 어렵습니다. `rowHeight`와 `virtualScrolling`을 같이 사용해도 큰 문제가 없는 것으로 알고 있습니다. 좀 더 자세한 옵션 사항을 알려주실 수 있을까요? 
폰트 사이즈는 별도의 옵션이 없어서, 만약 변경을 원하시면 CSS를 사용해야 할 것 같습니다.
