### ISSUE TITLE
Selection 관련 문의 드립니다.

### ISSUE THREAD

**Issue by jyspirit0208** [nhn/tui.grid#317]
selection메소드 사용시, 한 row 또는 연결되는 rows만 사용이 가능한가요?

독립된 row를 다중선택 하고싶은데 어떻게 하나요?
예를들어 0번째 row 와 4번째 row를 동시에 선택 하게 하고 싶습니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 현재 다중 범위 셀렉션은 지원하지 않고 있습니다. 연결되지 않은 행을 여러개 선택하고 싶다면 `rowHeader`옵션의 `checkbox`와 [getCheckedRows](http://nhn.github.io/tui.grid/latest/Grid#getCheckedRows) 메소드를 이용하는 방법 밖에 없을 것 같습니다.
