### ISSUE TITLE
onAfterChange 이벤트 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by josephkang619** [nhn/tui.grid#318]
안녕하세요. 수고가 많으십니다. 
사용중에 문의사항이 있어서 이렇게 글을 올립니다.

editOptions 이 select 인 컬럼에 대해 OnAfterChange 이벤트 발생 시,
변경된 값을 데이터베이스에 저장하고, SELECT 하여 setValue 를 통해 반영하고,
refreshLayout 으로 레이아웃을 다시 그려주는 작업을 진행하였습니다.

이 때 쿼리 에러등의 문제가 발생하여, 위의 로직이 제대로 동작하지 않아,
에러를 반환되는 경우, 변경되기 이전 값으로 돌려놓기위해 다음 코드를 작성하였습니다.
setValue 를 통해 이전 값으로 돌려놓으면서 OnAfterChange 동작 시 다시 
updateConsultInfoInline 함수를 거치게 되어 무한반복되게 됩니다.
이때 에러시엔 이벤트가 동작하지 않을 것 같아 ev.stop() 추가했는데 같았습니다.
혹시 이벤트 동작없이 값만 변경 또는 제가 설명드린 로직을 구현하기 위한 
방법이 있다면 조언 부탁드립니다.

감사합니다.

    // inline edit 구현. OnAfterChange 시 동작.
    function updateConsultInfoInline(ev, prevValue) {

        var updateColumn = ev.columnName;
        var updateValue = ev.value;
        var consultIdx = ev.instance.getValue(ev.rowKey, 'consultIdx');

        var formData = new FormData();

        formData.append('csrf_token', '<?= $csrf_token ?>');
        formData.append('updateColumn', updateColumn);
        formData.append('updateValue', updateValue);
        formData.append('consultIdx', consultIdx);

        $.ajax({
            url: '<?php echo base_url() ?>consult/updateConsultInfoInline',
            processData: false,
            contentType: false,
            data: formData,
            type: 'POST',
            success: function (result) {
                var msg = JSON.parse(result);

                if (msg.statusCode === 'ERROR') {

                    ev.stop();
                    ev.instance.setValue(ev.rowKey, updateColumn, prevValue);
                    alert(msg.statusValue);

                } else {

                    ev.instance.setValue(ev.rowKey, updateColumn, msg.jsonValue[0].UpdateValue);

                }
                ev.instance.refreshLayout();
            }
        });
    }

**Comment by dongwoo-kim** [comment]
안녕하세요. 코드까지 상세하게 적어주셔서 어떤 상황인지는 정확히 알 것 같습니다. 하지만 결국 `setValue`를 하면서 `onAfterChange`를 발생시키지 않는 방법이 필요한건데, 현재 그리드에서는 해당 기능을 제공하지 않고 있습니다. #296 에서도 비슷한 요구사항이 있어서 기능 추가를 고려하고 있긴 한데, 당장은 구현이 어렵고, 4.0 이후에나 가능할 것 같습니다.
현재  상태에서 해결하려면 Ajax 요청을 보낼 때 `rowKey`와 `columnName`을 별도로 저장하고 있다가, 요청 완료 후 성공적으로 `setValue`를 호출하기 전까지는 저장된 `rowKey`와 `columnName`에 대한 모든 이벤트 핸들러 동작을 막는 방식으로 구현해야 할 것 같습니다.

**Comment by josephkang619** [comment]
답변 감사드립니다.
