### ISSUE TITLE
그리드 내 데이터별로 폰트색상을 적용하고싶습니다.

### ISSUE THREAD

**Issue by ldk-hub** [nhn/tui.grid#319]
그리드 안에서 특정 폰트에 색상및 굵기 옵션을 넣고싶은데 혹시 가능할까요?

**Comment by dongwoo-kim** [comment]
현재 폰트 관련 옵션은 따로 제공하지 않고 있습니다. 로우나 셀 단위로 클래스명을 지정해서 CSS를 직접 작성하는 방식으로는 구현이 가능할 것 같습니다.
그리고, 이슈 등록 시에는 추후 관리를 위해서 버전 정보가 중요하기 때문에 작성 시에 제공되는 이슈 템플릿을 지우지 말고 활용해주시기 바랍니다.
