### ISSUE TITLE
그리드 생성하는 스크립트에서 listItems 동적 적용

### ISSUE THREAD

**Issue by TREX99** [nhn/tui.grid#320]
## Version

3.5.0

## Development Environment

Chrome, IE

## Current Behavior

```js
// Write example code
 columns: [
        {
            title: 'Category1',
            name: 'category1',
            editOptions: {
                type: 'select',
                listItems: [
                    { text: 'Select', value: '' },
                    { text: 'Domestic', value: '01' },
                    { text: 'Overseas', value: '02' },
                    { text: 'Etc', value: '03' }
                ],
                useViewMode: false
            }
```

## Expected Behavior

위 Category1 에 해당하는 컬럼의 listitems 를 위와 같이 static 하게 코딩하지 않고
Json 데이타 객체를 바인딩하고 싶습니다.

var objCategory1 = [{text:'대학교', value:'B02'}, {text:'고등학교', value:'B03'}];
위의 objCategory1 객체를 listItems 에 적용하는 방법이 있을까요 ?

**Comment by dongwoo-kim** [comment]
만약 그리드 생성하는 시점에 이미 데이터를 갖고 있다면 해당 데이터를 그대로 넘겨도 됩니다. 
```js
columns: [
  {
    title: 'Category1',
    name: 'category1',
    editOptions: {
      type: 'select',
      listItems: objCategory1,
      useViewMdoe: false
    }
  }
]
```
하지만 동적으로 `listItems`를 변경하는 API는 현재 제공되지 않기 때문에, 동적으로 변경하기 위해서는 [setColumns](http://nhn.github.io/tui.grid/latest/Grid#setColumns) 메소드를 사용해서 전체 컬럼 정보를 갱신해주어야 합니다.
