### ISSUE TITLE
컬럼 데이터의 format 적용 가능한지 문의드립니다.

### ISSUE THREAD

**Issue by bifungu** [nhn/tui.grid#323]
안녕하세요.
grid 내부에서 format 을 적용해서 number 타입의 경우 천 단위에서 콤마를 추가한다던지
날짜타입의 형태를 지정하는 식의 Format 적용이 가능한가요?

아니면  formatter에서 따로 구현을 해야 하나요?

**Comment by dongwoo-kim** [comment]
안녕하세요. 현재는 formatter 함수 외에 별도의 포맷팅 옵션을 제공하지 않기 때문에, 직접 formatter 함수를 사용해서 구현을 해야 합니다.

그리고, 이슈 등록 시에는 추후 관리를 위해서 버전 정보가 중요하기 때문에 작성 시에 제공되는 이슈 템플릿을 지우지 말고 활용해주시기 바랍니다.
