### ISSUE TITLE
다른컬럼의 값을 가져올수 있나요

### ISSUE THREAD

**Issue by oracle77** [nhn/tui.grid#330]
columns: [
          {
              title: '시군구',
              name: 'SI',
              align: 'left'
          },
          {
              title: '읍면동',
              name: 'DONG,				  
              align: 'left'
              ,formatter: function(value) {
				  
				 

	           return value + 'SI'
              }
          }

아래에서 읍면동 출력시 신군구 + 읍면동을 컬럼에 보여주고 싶습니다.
DB에서 가져오거나 다른 방법말고
아래 읍면동 컬럼에서 다른컬럼을 참조하여 표현하고자 합니다.

**Comment by hahuyun1** [comment]
읍면동 컬럼에서 formatter시에 value말고 두번째 인자가 들어갑니다.
formatter:function(value, ev){
  var temp = grid.getValue(grid.getRow(ev.rowKey), '가져올 컬럼명');  
  return value+temp;
}
위와같이 하면 다른 필드의 값을 가져올수 있습니다^^ 
저도 이거 찾느라 애 좀 태워서 관리자는 아니지만.. 답글 남겨드립니다~
