### ISSUE TITLE
_extraData로 rowSpan 옵션 추가 후 높이 지정 문의

### ISSUE THREAD

**Issue by hahuyun1** [nhn/tui.grid#332]
## Version

3.3.0
## Development Environment

Spring, JSP
## Current Behavior

```js
// Write example code
```

## Expected Behavior

수고많으십니다.
grid를 잘 활용하고 있는데, 한가지 문의사항이 있어 글 남깁니다.

grid 생성 후 필요에 따라 유동적인 rowSpan을 적용하고,
rowSpan된 td에 여러줄의 text를 삽입하려고 합니다.

여기서 발생하는 문제점은
rowSpan된 td에 text를 여러줄 삽입하면 
해당 tr의 자식 td들의 높이가 자동으로 rowSpan된 td에 맞춰
text줄만큼 높아지는 현상입니다.

그래서 grid생성시 rowHeight 옵션으로 행 높이값을 강제로 고정하면
rowSpan된 td 밑의 div태그( class="tui-grid-cell-content")에 
max-height 속성이 직접 부여되어 입력된 text가 짤리는 현상이 발생합니다.

정리하자면...
grid생성시 rowHeight 지정시 : 
div태그( class="tui-grid-cell-content")에 max-height속성이 부여되어 내부 text가 짤리는현상

grid생성시 rowHeight 미지정시:
div태그( class="tui-grid-cell-content")에 max-height속성이 부여되지 않아 text는 정상적으로 출력되지만. 해당 td높이값을 같은 tr내의 td들이 모두 동일하게 가져가면서 rowSpan되지 않은 td들도
불필요하게 높이가 높아지는 현상

위와같은 현상을 해결하는 옵션을 grid내에서 지원하는지 문의드립니다.
혹은 div태그( class="tui-grid-cell-content")에 max-height속성을 제거하거나 접근하는 
방법이 있는지 문의드립니다.

※추가로 rowSpan기능처럼 colSpan기능도 제공되는지 문의드립니다 :)

**Comment by hahuyun1** [comment]
grid 생성 후 js로 rowSpan된 td찾아서 max-height 속성값을 강제로 제거해서 해결은 했는데..

**Comment by dongwoo-kim** [comment]
안녕하세요. 정리를 잘 해 주셔서 문제 사항은 파악했습니다. 확인해보니, 컨텐츠의 높이에 따라 행 높이를 변경할 때 RowSpan에 대한 예외처리가 빠져 있어서 발생하는 버그인 것 같습니다. 약간 복잡한 이슈라서 4.0 구현시에 같이 수정될 예정입니다. 아마 3 버전에도 수정된 코드가 같이 반영될 수 있을 것 같습니다.

※ 아직 ColSpan 기능은 제공하지 않고 있습니니다만, 4.0 이후 계획에 포함되어 있습니다. 다음달 쯤에 향후 계획을 정리해서 공유할 예정입니다.
