### ISSUE TITLE
jquery tab을 활용하여 multi로 grid표현할경우 문제

### ISSUE THREAD

**Issue by hoeyun77** [nhn/tui.grid#337]
version: 3.5.0

Development Environment
Spring, JSP

안녕하세요.
좋은 그리드를 개발해 주셔서 잘 활용중에 있습니다.
작업중 issue가 발생하여 문의드립니다.
jquery tab을 활용하여 각각의 tab에서 grid표현중 입니다.
그런데 page resize 발생후 현재 focus되어있는 grid는 정상적으로 보이지만,
다른 tab의 grid는 해당 tab에 focus한 후 resize를 발생시켜야만 정상적으로 화면에 그려집니다.
이렇게 되면 다른 나머지 tab은 보이지 않게 됩니다.
해결방법이 있을까요?

**Comment by dongwoo-kim** [comment]
안녕하세요. 이 문제는 그리드가 숨겨진 상태에서 렌더링 될 경우 실제 DOM의 사이즈를 가져올 수 없어서 발생하는 문제로, #107 이나 #286 과 동일한 이슈인 것 같습니다. 탭이 활성화 된 다음에 `refreshLayout()` 메소드를 호출해주면 해결될 것 같습니다.

**Comment by hoeyun77** [comment]
감사합니다. 
tab의 activate 처리후 해당 grid에 refreshLayout() 처리 진행하니 정상작동하네요.
그럼 수고하세요.
