### ISSUE TITLE
setColumnTitles() method - how to pass parameter

### ISSUE THREAD

**Issue by huypvse02280** [nhn/tui.grid#340]
Hi!
In version 3.7.0 method setColumnTitles() is Added, but I don't understand how **columnsMap** parameter is passed, could you give an example to pass **columnsMap**

thanks!!

**Comment by dongwoo-kim** [comment]
Sorry for the lack of documentation. `setColumnTitles()` method gets the Key-Value object in which the key represents the name of the column name and the value represents the title of the column. For example, if you want to change the title of column "col1" to "address" and "col2" to "country", you can use the method like this: 
```js
var grid = new tui.Grid({
    el: $('#grid'),
    ...
});

grid.setColumnTitles({
  col1: 'address',
  col2: 'country'
});
```
