### ISSUE TITLE
one click edit 방법문의

### ISSUE THREAD

**Issue by Hunhuicho** [nhn/tui.grid#341]
## Version

3.7.0

## Development Environment

Window10, Chrome

아래 홈페이지 메인에 있는 그리드 처럼 원클릭 edit를 사용하려면 어떻게 해야 하나요?
https://ui.toast.com/tui-grid/

아래 useViewMode를 false로 하면 되지만, true로 했어도 더블클릭하지 않고 바로 에디트 할 수 있는 방법을 모르겠네요.
,editOptions: {
	                  type: 'text',
	                  useViewMode: true
	            }

**Comment by dongwoo-kim** [comment]
그리드 생성시에 `editingEvent` 옵션을 지정할 수 있습니다. 아래와 같이 기본값인 `dblclick` 대신 `click`을 지정하시면 됩니다.
```js
const grid = new tui.Grid({
  // ...
  editingEvent: 'click'
});
```
