### ISSUE TITLE
grid를 둘러싼 div를 처음에는 보이지 않다가 보이게 했을 때 grid의 데이터가 보이지 않습니다.

### ISSUE THREAD

**Issue by dongsilove** [nhn/tui.grid#352]
## Current Behavior

<style>
.result_list_detail{ display:none; position: absolute; top: 20px; left: 319px; right: 20px; box-sizing: border-box; background: #fff;z-index: 1101}
.result_list_detail.on {display: block}
</style>
<script>
function btnclick() {
	$('.result_list_detail').addClass('on');
}
</script>
</head>
<body>
<button onclick="btnclick();">grid 보기</button>
<div class="result_list_detail color1" data-search-result="list-detail">
	<div class="cheader">
        <h3>자세히 보기</h3>
        <button type="button" class="btn_close" onclick="gridListClose()">닫기</button>
    </div>
	<form id="data_form">
		제목 : <input type="text" name="title" id="title" /> 내용 : <input type="text" name="boardTp" name="boardTp" /> <input type="button" value="검색" id="btnSearch" onclick="search();" />
	</form>
	<div id='grid' style="margin-top: 10px;"></div>
</div>
	<script type="text/javascript">
		$("input:text").keyup(function(event) {
			if (event.keyCode == "13") {
				search();
			}
		});

		var grid = new tui.Grid({
			el : $('#grid'),
			bodyHeight : 600,
			scrollX : true,
			rowHeaders : [ 'rowNum' ],
			pagination : true,
			columns : [ {
				title : '게시물번호',
				name : 'boardSeq'
			}, {
				title : '제목',
				name : 'title'
			}, {
				title : '내용',
				name : 'boardTp'
			}, {
				title : '리뷰',
				name : 'reviewTxt'
			}, {
				title : '작성일',
				name : 'regDttm'
			}, {
				title : '수정일',
				name : 'modDttm'
			} ]
		});

		grid.on('beforeRequest', function(data) {
			// For all requests
		}).on('response', function(data) {
			// For all response (regardless of success or failure)
			grid.clear();
		}).on('successResponse', function(data) {
			// Only if response.result is true
		}).on('failResponse', function(data) {
			// Only if response.result is false
		}).on('errorResponse', function(data) {
			// For error response
		});

		grid.use('Net', {
			el : $('#data_form'),
			initialRequest : true,
			readDataMethod : 'GET',
			perPage : 20,
			enableAjaxHistory : true,
			api : {
				readData : 'http://localhost/api/boards'
			}
		});

		var net = grid.getAddOn('Net');

		function search() {
			console.log('search');
			var data = $("#data_form").serializeObject();
			net.readData(1, data, true);
		}
	</script>

</body>
</html>

**Comment by jintae-kim** [comment]
grid를 display 할때 grid.refreshLayout(); 을 추가해 보세요. 저는 이렇게 해결했습니다.
