### ISSUE TITLE
pagination 관련 문의

### ISSUE THREAD

**Issue by raeganja** [nhn/tui.grid#354]
안녕하세요?

그리드에서 pagination 사용시 처음에 기본값으로 10개씩 본 후 다시 조회조건을 변경하여 20개씩 보고자 할 때 그리드를 Refresh해야 하나요?

**Comment by dongwoo-kim** [comment]
안녕하세요. Net API 중에 `setPerPage()` 메소드가 있습니다. 다음과 같이 호출하시면 됩니다.
```js
const net = grid.getAddOn('Net');
net.setPerPage(20);
```
