### ISSUE TITLE
grid에 check박스 선택시 rowKey 초기화

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#363]
grid 페이지에서 체크박스를 선택시 페이지가 넘어가도 rowKey가 0부터 시작됩니다.

페이지가 넘어가면 rowKey가 0으로 초기화가 아닌 다음 rowKey로 보고 싶은데 방법이 있을까요?

ex) 1페이지에 데이터가 5개이면 rowKey는 0~4
      2페이지에 데이터가 5개이면 rowKey는 5~9 부터

**Comment by dongwoo-kim** [comment]
현재는 해당 기능을 제공하고 있지 않습니다. 페이지네이션 사용 중이라면 서버와 연동된 데이터를 사용한다는 의미라서, 이 경우 클라이언트가 별도로 페이지별 rowKey를 계산할 필요가 없다고 생각했습니다만.. 아마도 rowKey가 고유한 값을 갖길 원하시는 것 같네요. 이 기능은 클라이언트 페이지네이션 구현 시에 고려해보도록 하겠습니다.

지금도 `keyColumnName`을 지정해서 서버 데이터의 고유 ID를 rowKey를 사용한다면 비슷한 효과를 낼 수 있을 것 같습니다.
