### ISSUE TITLE
grid의 rowHeight 조정할 때

### ISSUE THREAD

**Issue by dongsilove** [nhn/tui.grid#375]
var grid = new tui.Grid({
      el: $('#grid'),
      scrollX: false,
      scrollY: false,
      **rowHeight : 20,**
      minRowHeight : 10,
      ....
});
위와 같이 조정하였습니다.  그러나 데이터가 row 안에서 height 중앙정렬되지 않고 잘려 보입니다.  row안에서 여백이 있으니 자동으로 중앙으로 정렬되어 보이면 좋겠는데요. 어떻게 하면 될까요?

**Comment by dongwoo-kim** [comment]
그리드는 기본적으로 데이터를 세로 중앙 정렬해서 표시하고 있습니다. 아마 설정 옵션보다는 데이터가 더 중요할 것 같은데, 어떤 데이터를 썼는지 알 수 있을까요? 
그리고, 이슈 등록 버전 정보와 사용 브라우저 환경을 명시해 주시면 원인을 파악하기가 좀 더 수월할 것 같습니다.
