### ISSUE TITLE
체크된 row의 input 값을 변경하여 넣으려고 하는데요.

### ISSUE THREAD

**Issue by rabbit8318** [nhn/tui.grid#376]
grid.on('check', function(ev) {
  var result = 123;
    grid.setValue(2, 'aaa', result );
 });

이렇게 하니 체크 이벤트를 무한으로 반복하는 문제가 생겼습니다.
어떻게 처리하면 되는건지 알려주시면 감사하겠습니다.
그리고 sort시킨 컬럼에 sort 눌렀을때 발생시킬수 있는 이벤트가 있는지도 궁금합니다.

**Comment by js87zz** [comment]
@rabbit8318  현재 소스만 봐서는 딱히 문제가 없어보이고, 무한 반복 이벤트 발생이 왜 일어나는지 알 수 없을 것 같습니다. 좀 더 자세한 소스 코드나 설명을 추가해주시면 감사하겠습니다! 
그리고 현재 정렬 시에는 별도의 이벤트는 열려 있지 않습니다. 이 부분은 현재 v4.0배포를 앞두고 있어서 이후에 논의 가능할 듯합니다.
