### ISSUE TITLE
tui calendar 팝업 css 위치값 질문입니다

### ISSUE THREAD

**Issue by dayemond11** [nhn/tui.grid#390]
![캡처](https://user-images.githubusercontent.com/51309681/58776411-81abf700-8605-11e9-9016-5c829f9d0a3e.PNG)

캘린더 위치가 선택한 셀에따라 위로 생길 경우와 아래로 생길 경우가 있는데,
위로 생길 경우 메뉴에 가려지게 됩니다.
팝업이 잘리지 않게 아래로 팝업이 뜨게 하고 싶은데 어떻게 해야할까요?

**Comment by jung-han** [comment]
@dayemond11 해당 문의는 tui-calendar 이슈를 이용해주시면 감사하겠습니다.
https://github.com/nhn/tui.calendar/issues
