### ISSUE TITLE
jquery is required in onClick event code

### ISSUE THREAD

**Issue by Owen-igaw** [nhn/tui.grid#394]
안녕하세요 tui-grid 팀 여러분, 훌륭한 라이브러리 제공에 감사드립니다. toast-ui.vue-grid를 통해 코드 작성 중 에러로 보이는 부분이 있어 전달드립니다.

상황부터 설명드리자면, Tree Data 형식을 이용하고자, 다음과 같이 설정한 후,
```js
//////////// template part /////////////
...
<Grid class="table"
            ref="table"
            theme="striped"
            :options="gridOptions"
            :columnData="columns"
            :rowData="batchData"
/>
...
/////////////////////////////////////
///////////// options //////////////
gridOptions: {
        bodyHeight: 'fitToParent',
        rowHeight: 30,
        virtualScrolling: true,
        treeColumnOptions: {
            name: 'app',
            useCascadingCheckbox: false,
        },
        summary: {
            position: 'bottom',
            height: 40,
            columnContent: {
               ......
            }
        },
}
```
collapse된 row를 열고자 클릭할 시, _onClick 핸들러와 관련하여 에러가 발생하고 있습니다.

## Version
tui-grid: v 3.8.0, @toast-ui/vue-grid: v 1.0.5

## Development Environment
@vue/cli: v 3.7.0, typescript: v 3.4.3

## Current Behavior
collapse 표시 (검은 삼각형)를 클릭할 시 다음과 같은 에러가 발생합니다.
```js
tui-grid.js?800b:17714 Uncaught ReferenceError: $ is not defined
    at init._onClick (tui-grid.js?800b:17714)
    at executeBound (underscore.js?3e81:762)
    at HTMLButtonElement.eval (underscore.js?3e81:775)
    at HTMLButtonElement.eval (underscore.js?3e81:122)
    at HTMLDivElement.dispatch (jquery.js?a881:5226)
    at HTMLDivElement.elemData.handle (jquery.js?a881:4878)
_onClick @ tui-grid.js?800b:17714
executeBound @ underscore.js?3e81:762
(anonymous) @ underscore.js?3e81:775
(anonymous) @ underscore.js?3e81:122
dispatch @ jquery.js?a881:5226
elemData.handle @ jquery.js?a881:4878
```

tui-grid.js 파일을 확인해보니
```js
/***/ }),
/* 65 */
/***/ (function(module, exports, __webpack_require__) {

	/**
	 * @fileoverview Tree cell painter
	 * @author NHN. FE Development Lab <dl_javascript@nhn.com>
	 */

	'use strict';

	var _ = __webpack_require__(2);
	var snippet = __webpack_require__(3);

	var Painter = __webpack_require__(63);
	var util = __webpack_require__(17);
	var attrNameConst = __webpack_require__(10).attrName;
	var dimensionConst = __webpack_require__(10).dimension;
	var classNameConst = __webpack_require__(19);

/*     17623 ~ 17641 부분입니다. */
```
위처럼 해당 부분에 $ 가 require되지 않고 있음을 확인했습니다.

## Expected Behavior
```js
/***/ }),
/* 65 */
/***/ (function(module, exports, __webpack_require__) {

	/**
	 * @fileoverview Tree cell painter
	 * @author NHN. FE Development Lab <dl_javascript@nhn.com>
	 */

	'use strict';
        var $ = __webpack_require__(7);
	var _ = __webpack_require__(2);
	var snippet = __webpack_require__(3);

	var Painter = __webpack_require__(63);
	var util = __webpack_require__(17);
	var attrNameConst = __webpack_require__(10).attrName;
	var dimensionConst = __webpack_require__(10).dimension;
	var classNameConst = __webpack_require__(19);

/*     17623 ~ 17642 부분입니다. */
```
위처럼 임시방편적으로 처리하여 사용하고 있는 중이긴 하다만, dist 파일이다보니 근본적인 처리가 필요할 듯하여, 이슈로 전달드립니다.

감사합니다 좋은 하루 되시기 바랍니다.

**Comment by seonim-ryu** [comment]
@Owen-igaw 
확인해보니 해당 모듈에서 jquery를 가져오는 코드가 누락되었네요 ^^;;
3.8.1에 픽스하여 배포될 예정입니다. 제보 감사합니다. :)

**Comment by js87zz** [comment]
@Owen-igaw 
## bug
Cannot require jquery module.
## fixed
fixed in v3.9.0

**Comment by kimyongyeon** [comment]
C:\Users\SKTelecom\project\my-svelte-test\node_modules\tui-grid\dist\tui-grid.js:16
})(window, function(__WEBPACK_EXTERNAL_MODULE__35__, __WEBPACK_EXTERNAL_MODULE__104__) {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\SKTelecom\project\my-svelte-test\node_modules\tui-grid\dist\tui-grid.js:16:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\SKTelecom\project\my-svelte-test\__sapper__\dev\server\server.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
스벨트에서 사용할려고 하니 다음과 같은 에러가 발생중 입니다.
혹시 확인 가능할까요?
