### ISSUE TITLE
invoke를 통한 expandAll과 collapseAll이 정상동작하지 않습니다.

### ISSUE THREAD

**Issue by Owen-igaw** [nhn/tui.grid#396]
Vue 환경에서 invoke 를 통해 expandAll, collapseAll 이 정상동작하지 않습니다.

## Version

tui-grid: v 3.8.0, @toast/vue-grid: v 1.0.2

## Development Environment

@vue/cli: 3.7.0, typescript: 3.4.3, Windows 10

## Current Behavior
다음처럼 코드를 작성한 후, button에 @click 이벤트로 지정했을때, collapseAll 시에는 검은색 삼각형 화살표와 폴더 아이콘만 접은 표시로 변경되고, expandAll 시에는 그와 반대로 화살표와 폴더 아이콘만 편 상태의 표시로 변경되며, 그 외 동작이 일어나지 않습니다.

자식데이터가 있을 때도 역시, 화살표 표시만 바뀔 뿐 어떠한 동작도 일어나지 않습니다. Grid의 @expand 트리거 조차도 동작하지 않습니다.

```js
    private toggleAll() {
        const table = this.$refs.table as Grid;
        if (this.IsAllExpanded) {
            table.invoke('collapseAll');
        } else {
            table.invoke('expandAll');
        }
        this.IsAllExpanded = !this.IsAllExpanded;
    }
```

## Expected Behavior
expandAll 과 collapseAll 시에 클릭으로 일일이 expand, collapse 시킬 때처럼 올바른 동작을 해야합니다. (자식데이터 보여지기, 숨기기 / 화살표 변경 /  폴더 아이콘 변경 / expand 이벤트 트리거 등)

**Comment by seonim-ryu** [comment]
@Owen-igaw 
해당 이슈는 그리드 트리 기능의 버그로 확인되었습니다.
`vue-grid`에서 정상적으로 사용하기 위해서는 그리드 버그 픽스가 이후에 사용이 가능합니다.
현재 그리드 v4 배포를 앞두고 있는데요. 배포 이후에 버그 픽스를 진행할 수 있을 것 같습니다.
참고 부탁드립니다. :)

**Comment by js87zz** [comment]
@Owen-igaw 
## bug
Wrong tree expanded, collapsed event
## fixed
fixed in v3.9.0
