### ISSUE TITLE
동일 컬럼 Name 이 있을 때, 키보드 방향키로 이동 시 기능 이상

### ISSUE THREAD

**Issue by gwantaek** [nhn/tui.grid#398]
컬럼 속성의 name 이 같은 컬럼이 있을 때, 방향키로 왼쪽 오른쪽 이동을 하다 보면
동일한 컬럼 name 이 selection 된 후 아직 오른쪽에 컬럼들이 남아 있음에도 불구하고 다음 row로 이동하는 현상이 발생 합니다.

가령 컬럼이 아래와 같다면 title (name)
화살표 오른쪽키로 [ID] 부터 시작해서 [주소]까지 이동 시킨다고 했을 때
[별명]까지 selection이 이동했다 [주소]까지 가지 못하고 다시 [ID]로 이동하는군요.

ID(user_id)    이름(user_name)    부서(dept)    별명(user_name)    주소(address)

버그 인가요?

## Current Behavior

```js
// Write example code
```

**Comment by nameofSEOKWONHONG** [comment]
버그라고 보기는 어려울 것 같은데요,
동일 컬럼명 사용시 다른 그리드 컨트롤에서는 허용 안하는 것도 있으니까요.
가장 빠른 해경법은 별명(user_nickname) 으로 변경하시는 것도 방법일 것 같습니다.

**Comment by jung-han** [comment]
@gwantaek 안녕하세요. @nameofSEOKWONHONG 님이 말씀해 주신것처럼 버그라 보기에는 조금 무리가 있을 것 같습니다. 동일 name일 경우 focus, selection 뿐만 아니라 다른 부분에서도 사용하시는데 문제가 있을 수 있습니다. name을 다른 이름으로 변경하시는 것이 가장 좋은 해결책 같습니다.
