### ISSUE TITLE
Scroll sticking

### ISSUE THREAD

**Issue by Alexby8** [nhn/tui.grid#401]
## Version
3.8.0

## Development Environment
Windows 10, Chrome

## Current Behavior
Sometimes scroll stick and I can't scroll the table. Often it was when I select column. The table tries to return to top.
Example on video:
https://youtu.be/K9gxpUBTAF0

**Comment by Alexby8** [comment]
Example in your site:
https://youtu.be/l3tl4ATZvtA

**Comment by js87zz** [comment]
@Alexby8 
we have generated new issue(#478 ) and will fix it.
So that, close this issue.
