### ISSUE TITLE
컬럼 사이즈를 마우스로 조절

### ISSUE THREAD

**Issue by youngwonseo** [nhn/tui.grid#410]
## Version

3.8
## Current Behavior

```js
// Write example code
```

## Expected Behavior

2.9 버전의 tui-grid.js를 쓰면 컬럼의 width를 마우스로 조정이 가능안데 3.8을 사용하면 조절이 안되네요. 이유가 있나요?

**Comment by jung-han** [comment]
#353 과 동일한 이슈로 한 이슈로 관리하겠습니다.
