### ISSUE TITLE
How to drag cell content, instead of cell selection.

### ISSUE THREAD

**Issue by BillionaireDY** [nhn/tui.grid#440]
## Version

v3.7.0
## Development Environment

Chrome latest, macOS Mojave v10.14 
## Current Behavior
셀 안의 텍스트중 일부를 드레그하고 싶은데 cell selection 으로 인해 드래그를 할 수 없습니다.

If users want to drag cell contents (ex, drag part of text) using mouse, but the Gird blocks dragging. 

## Expected Behavior
cell selection을 해제하고 드레그를 할 수 있도록 할 수 있는 옵션이 있을까요?

I want to drag content inside of each cell. Not to select Cell.
Is there any way can drag content?

**Comment by jung-han** [comment]
안녕하세요. 현재 selection을 해제할 수 있는 옵션은 제공하고 있지 않습니다. 
해당 기능이 추가되려면 좀 더 기능을 구체화 시킨 후에 이뤄져야 할 것 같은데요.

우선적으로 editOptions에 'text'를 사용해서 셀을 활성화 시킨 후에 내용을 드래그 하는 방식으로 적용하실 수 있을 것 같습니다.

```js
var grid = new Grid({
// ...options
columns: [
  {
    title: 'Name',
    name: 'name',
    editOptions: {
      type: 'text',
      useViewMode: true
    }
  }
]
```

* example: https://nhn.github.io/tui.grid/3.8.0/tutorial-example04-input-types
