### ISSUE TITLE
grid cell 데이터의 rowspan 기능

### ISSUE THREAD

**Issue by bifungu** [nhn/tui.grid#448]
**Is your feature request related to a problem? Please describe.**
cell 데이터 중 동일한 값을 가진 데이터들의 row span을 하고 싶습니다.
예를 들어

번호    코드     코드명
1         001       123 (123과 234를 하나의 셀로 표시)
                        234
2         002       456

확인 부탁 드립니다.
감사합니다.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jung-han** [comment]
안녕하세요.
![image](https://user-images.githubusercontent.com/35371660/59809751-f3da4680-933c-11e9-816a-f8522d1540d2.png)
제가 이해한 바로는 다음처럼 작성하고 싶다는 것으로 이해했는데 맞을까요?

**Comment by bifungu** [comment]
네 표현해주신 GRID 방식이 맞습니다.

**Comment by jung-han** [comment]
@bifungu 
해당 example 참고해주시면 될 것 같습니다.
https://nhn.github.io/tui.grid/latest/tutorial-example06-attributes

**Comment by bifungu** [comment]
현재 저희가 사용하는 버전은 3.8입니다. 3.8에서는 기능이 없는건가요?

**Comment by js87zz** [comment]
@bifungu 
아래 3.8.0 example 링크 참고하시면 됩니다.
https://nhn.github.io/tui.grid/3.8.0/tutorial-example06-using-extradata

**Comment by bifungu** [comment]
아! 있었네요. 제가 못 찾았었습니다.
감사합니다. ^^
