### ISSUE TITLE
그리드 특정 셀 클릭시 팝업 띄우기

### ISSUE THREAD

**Issue by ldk-hub** [nhn/tui.grid#457]
## Version
자바기반  
스프링 웹 시스템
부트스트랩
tui-grid version: 3.5.0

## Development Environment
OS : 윈도우7
browser : 크롬 기반

## Current Behavior
1. 지정된 컬럼의 셀을  클릭 또는 더블클릭시 팝업 또는 모달이 나오게 하는 목적

## Expected Behavior
특정 셀을 클릭하여 팝업을 띄우는 액션 호출 기능이 있는지 궁금합니다.
필요한 의도는 해당 셀의  미리보기 이미지를 확대하여 볼수 있도록하는 활용하는 목적으로 
사용하려합니다.

**Comment by jung-han** [comment]
안녕하세요. 
셀을 클릭할 때 팝업을 띄워주는 기능을 제공하고 있지는 않지만 제공되고 있는 `focusChange`이벤트를 이용해서 해당 rowKey와 columnName을 가져와서 팝업을 띄워주도록 하는 방식으로 개발이 될 수 있을 것 같습니다.

* API: https://nhn.github.io/tui.grid/3.5.0/Grid#event-focusChange

```js
grid.on('focusChange', (ev) => {
  const { columnName, rowKey } = ev;
  // ...정보를 가져와서 팝업을 띄워주는 코드
});
```

감사합니다.

**Comment by ldk-hub** [comment]
오우오우오오웇오우오우오우오우...

이렇게빨리답변주실줄 몰랐습니다.

감사합니다!!!!

**Comment by ldk-hub** [comment]
> 안녕하세요.
> 셀을 클릭할 때 팝업을 띄워주는 기능을 제공하고 있지는 않지만 제공되고 있는 `focusChange`이벤트를 이용해서 해당 rowKey와 columnName을 가져와서 팝업을 띄워주도록 하는 방식으로 개발이 될 수 있을 것 같습니다.
> 
> * API: https://nhn.github.io/tui.grid/3.5.0/Grid#event-focusChange
> 
> ```js
> grid.on('focusChange', (ev) => {
>   const { columnName, rowKey } = ev;
>   // ...정보를 가져와서 팝업을 띄워주는 코드
> });
> ```
> 
> 감사합니다.

**Comment by ldk-hub** [comment]
오우오우오우오우오우오ㅜ..

이렇ㄱ 빨리답변주실줄 몰랐습니다.

감사합니다!!!!
