### ISSUE TITLE
toast-ui.vue-grid 버전도 항상 최신 tui-grid버전을 랩핑 되어있는건가요?

### ISSUE THREAD

**Issue by hiphopddori** [nhn/tui.grid#460]
toast-ui.vue-grid 버전 제공해주시는데
혹시 그버전이  tui-grid 최신 버전(4.0.0) 을 랩핑한 버전인가여?

그리고 현재 최신 버전인 tui-grid 에서 셀을 제공해주는 기능말고 
커스텀하게 셀을 원하는 방식으로 제어할수 있는게 제공이 되나여?
예를들면 select box인데 저희가 원하는 스타일의 ul li 형식의 태그를 사용하여 
만들수있다든지 제가 태그를 직접 사용해서 적용을 할수있는지 예제를 한번 쭉 보긴했는데 커스텀하게 제어할수있는 방법이 안보여서여

**Comment by js87zz** [comment]
현재 제공되는 React, Vue wrapper는 tui-grid 3.8.0버전 기준으로 작성되어있으나, 4.0.0기준으로 랩핑한 2.0.0 버전도 조만간 배포 계획에 있으니 참고해주세요. 그리고 문의주신 커스텀 에디터는 아래 튜토리얼과 예제를 참고하시면 도움될 듯 합니다.
https://github.com/nhn/tui.grid/blob/master/docs/custom-editor.md
https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor

**Comment by jung-han** [comment]
@hiphopddori 
https://github.com/nhn/toast-ui.vue-grid/releases
wrapper 2.0을 사용해주시면 될 것 같습니다. 감사합니다.
