### ISSUE TITLE
gridAjax POST call content-type 오타 수정해주세요

### ISSUE THREAD

**Issue by lucasjo** [nhn/tui.grid#461]
**Describe the bug**
gridAjax.ts 에서 POST call 일때
content-type 오타 수정 요청 드립니다. 

open function 에서
xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoder');
-> xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');

이거때문에 하루를 지체 했네요

혹시 그리고 content-type을 option 에서 변경하려면 어떻게 하면 될까요?

**Comment by js87zz** [comment]
@lucasjo 
제보해주신 이슈는 조치하여 차주 중 버그 픽스 배포예정입니다.
말씀해주신 것처럼 content-type을 변경, 추가 하는 것은 현재는 옵션으로 열려 있지 않습니다만,
json type 또는 별도의 header를 받을 수 있도록 하는 작업이 향후 feature 목록으로 잡혀있습니다.
만약 content-type이나 커스텀 헤더를 요청 시에 꼭 변경, 추가해야 하는 상황이시라면 datasource를 통해서 통신하지 않고 직접 ajax요청을 하셔도 될 듯합니다.
그리고 앞으로 이슈는 템플릿에 맞춰 작성해주시면 감사하겠습니다!

**Comment by js87zz** [comment]
@lucasjo 
bugfixed in 4.0.2(#471)
