### ISSUE TITLE
grid 에디트 진입 상태시 휠 스크롤 사용

### ISSUE THREAD

**Issue by eastwook80** [nhn/tui.grid#462]
훌륭한 그리드를 공개해 주셔서 감사히 잘 쓰고 있습니다.
사용중 발견된 버그가 있어 제보드립니다.

에디트 모드 진입 후 마우스 휠을 사용하여 스크롤 사용시
에디트 컬럼이 그리드 영역 바깥으로 나가는 현상이 있습니다.

아래 링크에서 마우스 휠을 위아래로 움직여 확인할 수 있습니다.
https://codepen.io/eastwook/pen/gNgyLK

감사합니다.

**Comment by js87zz** [comment]
@eastwook80 
The bug has been fixed in `v4.9.0`(#853)
Thank you!
