### ISSUE TITLE
columns > renderer 기능의 대한 답변 부탁드립니다.

### ISSUE THREAD

**Issue by ksshim86** [nhn/tui.grid#464]
조건에 따라 row의 color를 변경하고자 했습니다.
공식 문서를 참고하였을 때, Attributes 를 사용하여 처리하면 되는것으로 보였습니다.

그렇다는 것은 data를 가져오기전에 data 속성에 공식문서에 나와있는대로 attributes 속성을 추가해야합니다. 

api를 통해 가져오는 data는 실 데이터 조회에만 집중하고 싶고, front에 무언가 보여주기 위해 관여를 하고 싶지 않았고, renderer 기능을 사용해서 처리해야겠다고 고민했습니다.

renderer 기능은 하나의 cell에 대해 자식 element를 추가하여 커스터마이징하는 기능이라고 볼 수 있고, default일 때 "div" element가 자식으로 append 됩니다.

그래서 똑같이 CustomSliderRenderer 에서 "div" element를 자식으로 return 하게 해주었고, props만 조작하여 row의 스타일을 변경할 수 있었습니다.

하지만 해당 기능 메커니즘을 무시하고 커스터마이징한 느낌입니다.

renderer와 유사하게 자식 element를 추가하지않고, renderer와 같은 기능이 있다면 더욱 활용범위가 넓어질꺼 같다고 느꼈습니다. 

- 요약

1. row 스타일변경 등에 대해서는 data에 attributes 속성을 추가하여 하도록 구현된 이유가 궁금합니다. 
2. 이 궁금증은 row의 스타일변경 같은 작업은 renderer와 같은 방식으로 처리할 수 있으면 더욱 좋다고 개인적으로 느꼈기 때문입니다. 
그래서 조건에 따라 row의 color를 변경하고 싶으면 Attributes 속성을 data에 추가하는게 최선의 방법입니까? 

저는 tui grid팀의 생각을 공유받고 싶어 글을 남깁니다.

감사합니다.

**Comment by js87zz** [comment]
@ksshim86 
문의주신 사항에 답변드립니다.
1. _attributes(checked, disabled, className, height...) 옵션들은 html attribute에 해당하는 항목의 수정을 원하는 경우 열어놓은 옵션(몇 가지 예외 속성들도 존재합니다.)입니다. 말씀하신 것처럼 단순하게 color나 height를 설정하는 경우는 이 옵션을 사용하시는 것을 권장합니다.
2. row의 간단한 스타일 변경을 위해 렌더러를 사용하여 커스터마이징하는 것은 저희의 의도와는 맞지 않는 것 같습니다. 커스텀 렌더러는 기존의 렌더러로는 데이터를 효율적으로 표현할 수 없는 경우, 즉 사용자 니즈에 맞게 데이터를 보여주기 위해 만들어진 스펙입니다. 데이터의 가시성에 더 초점을 맞췄다고 생각하시면 됩니다. 그렇기 때문에 그리드에서 제공하는 속성들을 props로 전달해주는 것이구요. 단순한 스타일 변경에는 _attributes 속성을 이용하는 것이 적합하다고 봅니다.

**Comment by ksshim86** [comment]
@js87zz 
답변 감사합니다.

그렇다면, 조건에 따른 간단한 스타일 변경을 위해서 backend에서는 어떻게보면 원하지않는 추가 작업을하게되는데, 그리드가 렌더링되기전 data을 수정할 수 있는 event가 있나요?

**Comment by js87zz** [comment]
@ksshim86 
백앤드에서 데이터를 가져온 후, 해당 데이터에 _attrubute을 자바스크립트로 넣어주고 그리드 옵션으로 넘기면 될 것 같습니다. 그리드가 렌더링되기 전 별도의 이벤트 콜백을 호출할 필요는 없어보이네요

**Comment by ksshim86** [comment]
@js87zz 
답변 감사합니다.
