### ISSUE TITLE
조회결과 json데이터 안에 또 다른 json데이터가 있는 경우 

### ISSUE THREAD

**Issue by dongsilove** [nhn/tui.grid#465]
[조회결과 데이터]가 다음과 같을 때 ftrCode.cdeNam을 그리드에 보이도록 하고 싶습니다.  column정의를 어떻게 해야 할까요? 다음과 같이 해 보았는데.. 안나오네요.
 {
    "ftrIds": "247",
    "ftrIdn": "179540326",
    "ftrCde": "SB001",
    "ftrCode": {
      "grpCde": "FTR_CDE",
      "cde": "SB001",
      "cdeNam": "하수관로",
      "useYn": "Y",
      "rsrv01": null,
      "rsrv02": null,
      "rsrv03": null,
      "remark": null,
      "ordr": 436,
      "regId": "SYSTEM",
      "regDt": "2019-05-07",
      "modId": "SYSTEM",
      "modDt": "2019-05-07"
    },
    "pipNm": null,
    "pipIdn": null
}

columns : [ 
		 {name : 'ftrIdn', title : '관리번호', width : 80         }
		,{name : 'ftrCde', title : '시설구분', width : 80       }
                ,{name : 'ftrCode.cdeNam', title : '시설구분명' , width : 80         }
                ,{name : 'pipNm', title : '관로명' , width : 80         }
		,{name : 'pipIdn', title : '관로번호' , width : 80         }
       ]

**Comment by js87zz** [comment]
@dongsilove 
그리드의 컬럼 옵션은 1 depth 기준으로 작성해주셔야 합니다. 
말씀하신 사항에 대해서는 현재 지원하고 있지 않습니다.
