### ISSUE TITLE
inputBox font color issue

### ISSUE THREAD

**Issue by sunjiyen** [nhn/tui.grid#467]
그리드 inputBox에 컬럼에 disabled: function(value,ev) 를 사용하였습니다. 

리스트에서 첫 조회시  수정이 들어가지 않은 상태에서 
어떤 행은 연한 회색으로 글자가 나옵니다. 
![그리드회색글자캡처](https://user-images.githubusercontent.com/52095089/59960059-e79ce780-94fc-11e9-96b1-fc503bce53ee.png)

같은 열 전체가 회색이 아니라 부분적으로 나오는 곳이 있는데 어떤 문제로 그런지 

문의 드립니다.

**Comment by js87zz** [comment]
@sunjiyen 
현재 문의주신 내용으로는 어떤 현상과 원인인지 파악하기가 어렵습니다.
관련된 소스와 정확한 현상을 첨부해주세요. 
그리고 앞으로는 이슈 템플릿에 맞춰 작성해주시면 감사하겠습니다!
