### ISSUE TITLE
그리드 resetData 이후 elemet 에 대한 변경요소 사용에 대한 이슈

### ISSUE THREAD

**Issue by jooyh** [nhn/tui.grid#482]
## Version

tui-grid 4.0

## Development Environment

window
chrome

## Current Behavior

```js

grid.resetData(resultList);
grid.getSummaryValues("cnt");

```

## Expected Behavior

이러한 방법으로 그리드의 정보를 갱신후 해당 그리드의 변경요소에대한 이벤트 또는 추가적인 로직이 들어 갈 경우 해당 그리드에 반영 새로운 데이터 반영이 되지 않은 상태에서 하위 함수가 동작이 되어 변경요소에 대한 제어가 되지 않습니다.

데이터는 이미 json 형식으로 정리가 되어있고 해당 데이터를 그리드에 반영하는 형식입니다.

**Comment by js87zz** [comment]
@jooyh 
## bug
The summary data cannot react to the row data's update.
## fixed
fixed in 4.0.3(#496)
