### ISSUE TITLE
일전에 클로즈 된 내역 확인 부탁드리겠습니다 ㅠ

### ISSUE THREAD

**Issue by ldk-hub** [nhn/tui.grid#488]
-----------------------------이전문의내역 -----------------------------------------------
Version
자바기반
스프링 웹 시스템
부트스트랩
tui-grid version: 3.5.0

Development Environment
OS : 윈도우7
browser : 크롬 기반

Current Behavior
지정된 컬럼의 셀을 클릭 또는 더블클릭시 팝업 또는 모달이 나오게 하는 목적
Expected Behavior
특정 셀을 클릭하여 팝업을 띄우는 액션 호출 기능이 있는지 궁금합니다.
필요한 의도는 해당 셀의 미리보기 이미지를 확대하여 볼수 있도록하는 활용하는 목적으로
사용하려합니다.

------------------------------------- 이전문의내역------

![1](https://user-images.githubusercontent.com/12209348/60224425-45468080-98bd-11e9-86f5-a79b1decbfc8.PNG)

해당알려주신 답변처럼 자바스크립트 내 소스를 입력시 실제로 작동은 잘됩니다.
하지만 위와같은 이미지처럼 오류표시가 나와서 신경쓰여..재문의드립니다.,.

- 그리고 추가적으로 궁금한게 한가지 더있습니다.
특정 컬럼만 선택시 해당 팝업을 호출해올수 있는지 궁금합니다.

현재 답변주신 코드를 활용해보니 전체 셀에대해서 반응이되어 가능한지 ...궁금합니다...

무더운 여름날 고생이많으십니다.

감사합니다.

**Comment by js87zz** [comment]
@ldk-hub 
린트 설정 문제로 발생하는 에러로 보이는대요. 이러한 오류문의는 저희의 영역이 아니라고 생각됩니다.
앞으로 이러한 질문은 지양해주시면 감사하겠습니다. 
추가적으로 문의주신 사항은 컬럼별로 열려있는 이벤트는 현재 제공하고 있지않습니다. `focusChange`에서 특정 컬럼일때만 modal창을 활성화하도록 조건문으로 처리하면 될 듯 합니다.

**Comment by ldk-hub** [comment]
유의하겠습니다. 감사합니다!.
