### ISSUE TITLE
Customizing Row headers 적용 시 복사 컬럼이 밀립니다.

### ISSUE THREAD

**Issue by jihyun416** [nhn/tui.grid#489]
안녕하세요

https://nhn.github.io/tui.grid/latest/tutorial-example11-row-headers

위 예제를 따라 row header를 적용하고 나면, 

클립보드 복사 시 추가한 컬럼 수 만큼 컬럼이 밀리는 현상이 있습니다.

![1](https://user-images.githubusercontent.com/52266870/60230664-a8daa900-98d1-11e9-955b-08ab0d8e9f81.PNG)
![2](https://user-images.githubusercontent.com/52266870/60230666-a9733f80-98d1-11e9-8023-cf7769857871.PNG)

row header를 n개 추가하고 나면
A열부터 B열까지 복사하면
A-n열부터 B-n열의 데이터가 복사됩니다.

첨부 이미지 확인 부탁드립니다.

감사합니다.

**Comment by js87zz** [comment]
@jihyun416 
## bug
Changing wrong selection, focus and clipboard area with row headers.
## fixed
fixed in v4.1.0
