### ISSUE TITLE
 How can I control header sorting events?

### ISSUE THREAD

**Issue by yongseokleecom** [nhn/tui.grid#495]
##  Version
3.8, 4.0

## Development Environment
VueJS

## 문의사항
Net (DataSource) 방식이 아닌 Data 객체를 주입해서 사용하려합니다.
별도 API 호출해서 데이터 가공하여 주입하는데,
정렬버튼을 눌렀을때 이벤트를 캡쳐해서 API를 재 요청하고 싶습니다.

정렬 이벤트 제어하는 방식을 찾을 수 없어 문의합니다.

**Comment by js87zz** [comment]
@yongseokleecom 
현재 정렬시 별도의 이벤트는 제공하고 있지 않습니다. 데이터를 이미 주입한 상태라면, 정렬 시에 특별히 API 요청이 필요할 것 같지는 않은대요. 정확히 어떤 용도로 필요하신 사항인지 구체적으로 설명해주시면 답변에 좀 더 도움이 될 것 같습니다.

**Comment by yongseokleecom** [comment]
@js87zz 
정렬버튼을 누르면 정렬 값을 포함하여 API 를 다시 호출하려합니다.

그리드에서 제공하는 DataSource 규격을 사용하는 상황이 아니다보니..
정렬 버튼클릭시 이벤트를 받아 API에 정렬값을 추가하여 
다시 호출하는 로직을 작성하려합니다.

addEventListener('clickSort', function(sortColumn, Ascending) {
// API 호출 후 데이터 갱신 
}

**Comment by js87zz** [comment]
@yongseokleecom 
말씀해주신 이벤트와 같은 그리드 이벤트 제공하고 있지 않는 상태입니다. 백엔드 API와 포맷이 맞지 않아서 별도로 사용하시는 것 같은대요..우선은 DataSource 규격에 맞춰 사용하는 게 현재로서는 최선인 것 같고, 해당 커스텀 이벤트 추가에 대해 논의해보겠습니다!

**Comment by yongseokleecom** [comment]
@js87zz 
감사합니다.
논의 후 좋은결과 생기면 회신부탁드립니다 !!

**Comment by js87zz** [comment]
@yongseokleecom 
관련 이벤트 추가 건은 feature 이슈(#515 )로 등록하였습니다. 
정확한 배포 일정은 픽스되지 않았고, 확정된다면 마일스톤에 추가될 예정이니 참고해주세요. 감사합니다.

**Comment by yongseokleecom** [comment]
@js87zz 
의견 반영해주셔서 감사합니다 (__)
좋은 하루 보내세요!

**Comment by js87zz** [comment]
@yongseokleecom 
## Feature
The new grid event that sorting event is added for those who need to subscribe the event after sorting the data in 4.2.0(#536)
