### ISSUE TITLE
rowHeight is not working under 25px

### ISSUE THREAD

**Issue by jayhyub7** [nhn/tui.grid#497]
```js
function initGrid() {
  var gridMaster = new tui.Grid({
    el: document.getElementById('grid'),
    rowHeight: 22,
    header: {
      height: 26
    },
    columns: [
      {
        header: 'COL1',
        name: 'COL1',
        editor: 'text'
      },
      {
        header: 'COL2',
        name: 'COL2'
      },
      {
        header: 'COL3',
        name: 'COL3'
      },
      {
        header: 'COL3',
        name: 'COL3'
      },
      {
        header: 'COL4',
        name: 'COL4'
      }
    ]
  });

  getGridMaster = function() {
    return gridMaster;
  };
  getCommonCodeList();
}
function getCommonCodeList() {
  var list = [];
  list.push({ COL1: '한글임', COL2: 555223, COL3: 'TEST TEST', COL4: '하하 TEST' });
  list.push({ COL1: '홍길동', COL2: 555223, COL3: 'TEST TEST', COL4: '하하 TEST546' });
  list.push({ COL1: '김길동', COL2: 5556565656556, COL3: 'TEST TEST', COL4: '하하 TEST' });
  list.push({ COL1: '한글임', COL2: 45654654546546, COL3: 'TEST TEST', COL4: '하하 TE5465464ST' });
  var gridMaster = getGridMaster();
  gridMaster.resetData(list);
}
```

-----------------------------------------------------
위의 소스코드로 html 만들고 크롬에서 실행을 하면 
tr(.tui-grid-row-odd, tui-grid-row-even)의 높이가 40px로 되어버립니다. 
크롬 개발자 도구로 tr의 높이를 25로 바꾸면 정상적으로 적용이 됩니다.

**Comment by jayhyub7** [comment]
맨 위에 
<link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />  이부분도 넣었는데 자꾸 안보이네요 ㅜ.ㅜ;

**Comment by jayhyub7** [comment]
css도 분명 넣었는데 자꾸 숨김처리가 되네요; 
[[https://uicdn.toast.com/tui-grid/latest/tui-grid.css]]

**Comment by jung-han** [comment]
@jayhyub7 안녕하세요. 해당 문제는 버그로 판단되서 다음 버전에 배포될 예정입니다. 감사합니다.

**Comment by jung-han** [comment]
#501 
현재 cell content의 padding, font-size가 고정값으로 rowHeight가 25px 미만으로 떨어질 경우 처리가 애매한 상태입니다. 임시 방편으로 수정할 수 있으나 불필요한 조치라 판단됩니다. 이후 마이너 버전 업데이트를 통해 cell content의 css를 수정할 수 있도록 옵션을 열어줄 예정입니다. 

우선적으로 4.0.3 버전 배포 이후 `minRowHeight`값을 같이 지정해 주신뒤 `25px` 이상으로 사용할 것을 권장드립니다.

**Comment by jayhyub7** [comment]
넵 답변 감사합니다.

**Comment by jung-han** [comment]
안녕하세요. 

rowHeight를 25px 미만으로 작성할 경우 그리드의 셀이 망가져 나타나는 부분이 있어 
현재는 rowHeight에 25미만의 값을 입력할 경우 기본 값으로 대체 되어 낮은 값은 지정이 안되게 됩니다.

25px 미만으로 셀을 지정해야 하는 경우가 꼭 필요하다면 몇가지 방법을 제안해 드릴 수 있을 것 같습니다.
* 밑 방법을 적용한는 경우에도 `rowHeight`값과 `minRowHeight`값은 지정해주셔야 합니다!

### CSS 수정

현재 증상이 발생하는 이유는 디폴트 렌더러에 padding 값이 들어가 적용이 불가능한 부분이기 때문에 수정이 필요한 row 에 `_attributes.className.row[]`에 임의의 클래스를 지정해 주신 뒤 `.test .tui-grid-cell-content` 의 css를 작성해 기존 css를 오버라이딩 해주시면 해당 row의 렌더러 스타일을 조정할 수 있습니다.

```js
const data  = [
  {
    name: 'john',
    _attributes: {
        className: {
          row: ['test']
        }
    }
  }
]
```

* 참고: https://nhn.github.io/tui.grid/latest/tutorial-example06-attributes

### Custom Cell Renderer

임의의 셀 렌더러를 만들어 사용하는 방법입니다. 사용자가 해당 셀의 렌더링 방식을 지정할 수 있습니다.
간단한 커스텀 렌더러 예시 코드입니다.

```js
class CustomRenderer implements CellRenderer {
  private el: HTMLDivElement;

  public constructor(renderData: CellRendererProps) {
    const el = document.createElement('div');
    el.style.fontSize = '10px';
    el.style.padding = '0';

    this.el = el;
    this.render(renderData);
  }

  public getElement() {
    return this.el;
  }

  public render(props: CellRendererProps) {
    this.el.innerHTML = String(props.value);
  }
}

const columns = [
  { name: 'name', renderer: { type: CustomRenderer } },
  // ...columns
];
```

위 코드대로 작성하면 아래 형태로 정상적으로 작동하는 그리드를 사용할 수 있습니다.

![image](https://user-images.githubusercontent.com/35371660/61344389-08522600-a88c-11e9-9e5d-69e90c27917a.png)

이후에 폰트 사이즈나 패딩을 쉽게 적용하는 부분은 좀 더 논의후 결정될 예정입니다. 감사합니다.

**Comment by js7309** [comment]
똑같은 형상 같은데
height 40으로 안하고 작게 하면 
 columns 항목에 컬럼 속성을  editor: 'text' 해서 더블클릭하면 엄한 곳에 에디터 인풋박스가 열리네요
