### ISSUE TITLE
gridInstance error after 4.0 upgrade when using vue wrapper

### ISSUE THREAD

**Issue by dayemond11** [nhn/tui.grid#498]
**Describe the bug**
tui grid 업그레이드 후 grid instance를 찾지 못하는 에러가 발생했습니다.

**To Reproduce**
1. tui grid 3.8.0 -> 4.0.2 버전으로 업그레이드 
2. tui grid 에러 발생
TypeError: this.gridInstance[methodName] is not a function

**Screenshots**
![image](https://user-images.githubusercontent.com/51309681/60476542-f7fc5180-9cb6-11e9-809f-80630f2d1459.png)
![image](https://user-images.githubusercontent.com/51309681/60476731-98527600-9cb7-11e9-83ac-ec235567a438.png)

**Desktop (please complete the following information):**
 - OS: window
 - Browser : chrome
 - Version

**Comment by js87zz** [comment]
@dayemond11 
현재 vue wrapper를 사용하고 계신걸로 보이는대요. wrapper는 현재 그리드 3.8 기준으로 작성되어 있어서 업데이트 시 위처럼 문제가 생길 것 같습니다. 우선 현재 상황에서는 기존 3.8로 사용하셔야 될 것 같구요. 그리드 4.x를 적용한 vue wrapper는 `7/11`일에 배포 예정이니 이후에는 업데이트하여 사용 가능하실 것 같습니다.

**Comment by dayemond11** [comment]
@js87zz 감사합니다. 그때 다시 확인해보겠습니다.

**Comment by jung-han** [comment]
@dayemond11 
https://github.com/nhn/toast-ui.vue-grid/releases
2.0 버전 래퍼를 사용하시면 될 것 같습니다. 감사합니다.
