### ISSUE TITLE
check event not trigger when select all checkboxes

### ISSUE THREAD

**Issue by preejer1** [nhn/tui.grid#499]
사용버전 4.2

체크박스 전체 선택 시 
grid.on('check', function(ev) {

})

해당 기능에 동작을 안하네요.
전체선택이 아닌 개별 선택의 경우 동작하고 있습니다.

**Comment by jung-han** [comment]
@preejer1 
버그로 보기는 힘들 것 같습니다. 현재 `check`이벤트는 선택된 row의 rowKey를 반환하는 형태로 작성되어 있습니다.
만약 전체 선택일 경우 check가 발생하려면 체크가 여러개가 될 경우 선택된 row의 정보가 아닌 rowKey가 배열 형태로 넘어가야 할 것으로 보입니다. 이럴 경우 기존 API와 다른 작동을 하게 되어 좀 더 논의가 되어야 할 것으로 보입니다.
수정이 이뤄질 방향은 이후에 댓글로 알려드리도록 하겠습니다.

이후에는 이슈 템플릿을 지우지 마시고 양식에 맞춰 작성해 주시면 감사하겠습니다.
