### ISSUE TITLE
Bug when using focusAt after expand

### ISSUE THREAD

**Issue by ksshim86** [nhn/tui.grid#500]
**Describe the bug**
- focusAt 할 노드의 상위노드가 닫혀있을 때, expand 해주고 focusAt 하면 스크롤이 덜 이동하게 됨.
- 상위노드가 모두 열려있을 때는 문제없이 focusAt이 잘 됨

-  노드는 다 접혀져있는 상태이며, tbody의 height는 300px 라고 가정(스크롤은 생긴상태)
-  검색할 노드가 아래의 순서대로 검색되어 focusAt 되었을 때, tbody의 height가 300px 보다 더 아래에 위치에 있는 경우 스크롤이 정상적으로 포커싱 되지 않음.

- 간략히 정리하자면 focusAt하기전 expand 함수를 통해 그리드의 height가 늘어나고,
늘어난 위치에 있는 focusAt를 하면 정상적으로 되지않음.

**To Reproduce**
1. 검색할 key값으로 getAncestorRows 함수를 이용하여 상위 key를 구합니다.
2. expand 함수를 이용하여 검색할 key의 상위 key를 모두 expand 합니다.
3. 검색할 key 값을 focusAt 함수를 이용하여 그리드 스크롤이 이동합니다.
4. focusAt 한 노드의 위치보다 스크롤이 위에서 멈춥니다.

`const parentRowsIndex = this.grid.getAncestorRows(clickedIndex)`

`parentRowsIndex.forEach(element => {
this.grid.expand(element.rowKey, false)
})`

`this.grid.focusAt(clickedIndex , 0 , true)`

**Expected behavior**
검색한 노드의 상위노드가 expand 된 후, 검색한 노드의 위치로 scroll이 정상적으로 됨

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser: chrome
 - Version: 75.0.3770.100(공식 빌드) (64비트)

**Additional context**

**Comment by js87zz** [comment]
@ksshim86 
v4.2.0에서 재현 결과 expand를 먼저 하고 `focusAt`을 호출하는 경우는 정상적으로 동작합니다. 반대의 경우(`focusAt`을 먼저 호출한 후 expand 하는 경우)에 말씀하신 것처럼 위에서 멈추는 현상이 발생하는대요. 이 부분은 focusing되는 cell이 expand하기 전이라 닫혀있는 상태이기 때문에 그 위의 셀까지만 이동하는 것이 스펙상 맞는 부분이라 생각됩니다.

**Comment by ksshim86** [comment]
@js87zz 
제 설명이 부족했는지 모르겠지만, expand하여 닫혀있는 하위 노드들을 다 열어주고, 그로인해 스크롤이 생기고 focusing 해야 할 노드가 스크롤로 내려야 하는 위치에 있다면, focusAt 했을 때, 스크롤이 덜 이동하는 버그를 말한겁니다.

**Comment by js87zz** [comment]
@ksshim86 
현상 재현 확인했습니다. 버그픽스하여 v4.3.0 반영 예정입니다. 제보 감사합니다 :)
