### ISSUE TITLE
The row data of createdRows and updatedRows are duplicated as the result of calling getModifiedRows().

### ISSUE THREAD

**Issue by jayhyub7** [nhn/tui.grid#502]
Version
4.2

Development Environment
윈도우10 크롬 최신버전

Current Behavior

그리드에 appendRow 또는 prependRow를 실행하여 row 1개를 추가 한 후에 
getModifiedRows()  함수를 호출했습니다.
createdRows와, updatedRows 에 중복되어 나타납니다.

image
![image](https://user-images.githubusercontent.com/52368975/60495134-2562f280-9ceb-11e9-9acb-25b4f038e5dd.png)

**Comment by js87zz** [comment]
@jayhyub7 
## bug
The data of createdRows and updatedRows are duplicated as the result of calling getModifiedRows method
## fixed
fixed in 4.2.0(#540)
