### ISSUE TITLE
appendRow 함수 사용 시 특정 컬럼 입력이 불가능합니다.

### ISSUE THREAD

**Issue by dayemond11** [nhn/tui.grid#503]
## Version
tui grid 3.8.0

## Development Environment
windows
Chrome

## Current Behavior
![image](https://user-images.githubusercontent.com/51309681/60557877-111e0480-9d82-11e9-92d9-755d936a6f46.png)

```js
{
          title: '사용자그룹 ID',
          name: 'usergroup_id',
          align: 'center',
          minWidth: 100
        },

this.$refs.userGroupGrid.invoke('appendRow')
```

## Expected Behavior
사용자 그룹 컬럼이 useViewMode: false로 편집이 불가능한 컬럼입니다. appendRow함수를 사용하면 사용자그룹명, 사용자그룹 상세는  useViewMode: true로 row 생성시 입력가능합니다. 하지만 사용자그룹ID 컬럼은 row의 컬럼이 수정이 안됩니다.
1. 추가 버튼 클릭
2. 6번째 row 생성
3. 6번째 줄에 사용자 그룹ID 컬럼은 입력이 불가능한 상태입니다.

편집이 불가능한 컬럼도 row 추가시 입력가능하게 하려면 어떻게해야 하나요?

**Comment by js87zz** [comment]
@dayemond11 
에디팅 옵션 기준은 컬럼단위로 되어 있기 때문에 특정 로우의 컬럼의 에디팅 옵션을 변경하는 것은 현재 제공하고 있지 않습니다. 감사합니다.
