### ISSUE TITLE
tree-grid 총 몇 건의 데이터를 소화할 수 있나요?

### ISSUE THREAD

**Issue by ksshim86** [nhn/tui.grid#505]
## Version

latest
## Development Environment
- win 10 64bit
- i5-7200u 2.71Gh
- 16G ram
- chrome( latest ver )

## Current Behavior

https://jsfiddle.net/7b9u1k0o/1/

## Expected Behavior

1000건 이상의 데이터는 브라우저가 버티기 힘들어하는 것 같습니다.
데이터가 119건 일때와 1205건의 경우만 테스트 했습니다.

어쩔수없는 부분인지? 개선 계획이 있으신건지? 제 구현방법이 잘 못된건지 궁금합니다.

**Comment by js87zz** [comment]
@ksshim86 
현재 4.x관련 성능개선 feature가 잡혀있으나 정확한 배포 일정은 확정되지 않았습니다.
정확한 마일스톤과 일정이 픽스되면 공유드리도록 하겠습니다!

**Comment by js87zz** [comment]
@ksshim86 
## Enhancement
Slowing down with tree data when scrolling has improved(#545)
