### ISSUE TITLE
tui-grid.js:5952 Uncaught TypeError: Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by sigpankyo** [nhn/tui.grid#508]
**Describe the bug**
샘플 예제대로 간단하게 html 파일을 만들어 테스트 해보았고,
spring boot 에서 파일을 만들어 톰켓으로도 돌려 보았습니다만 같은 에러가 계속 발생되어 
문의 드립니다.
`Uncaught TypeError: Cannot read property 'clientWidth' of null
    at Object.createStore (tui-grid.js:5952)
    at new Grid (tui-grid.js:4950)
    at (index):31` 

어디선가 width 값을 지정 해줘야 하는 것인지가 궁금합니다.
깃허브 이슈을 뒤져 봐도 해당 내용이 없어 문의 드려요.

현제 사용 하고 있는 tui-grid.js 의 버전은

>  /*!
>  * TOAST UI Grid
>  * @version 4.0.3 | Wed Jul 03 2019
>  * @author NHN. FE Development Lab
>  * @license MIT
입니다.
>  */

**To Reproduce**
1. 사용하고 계신 html 에디터 오픈
2.하단에 html 소스코드 복사 후 xxx.html 로 파일저장
3.크롬에서 해당 파일 오픈 개발자도구을 에러 확인

**Expected behavior**
베이직 그리드 정상표출

**Screenshots**
없음

**Desktop (please complete the following information):**
 - OS: MAC IOS CATALINA
 - Browser chrome
 - Version 75.0.3770.100 (64bit)

**Smartphone (please complete the following information):**
 - not useing

**Additional context**
사용했던 소스 코드 첨부합니다.
첨부파일을 html 확장자로 변경 해서 보시면 될것 같습니다.

[test.txt](https://github.com/nhn/tui.grid/files/3360771/test.txt)

**Comment by ksshim86** [comment]
그리드를 그려줄 div 요소가 없어서 나는 에러같은데요? grid 생성시 document.getElementById('grid') 구문은 해당 요소에다가 그리드를 그리겠다고 설정을 하는건데요. html에 그 요소가 없어서 그럴껍니다.

**Comment by js87zz** [comment]
@sigpankyo 
그리드와는 상관없는 현상으로 보이네요.
올려주신 코드를 보니 html이 파싱되기 전에 그리드 생성 스크립트를 호출하여 발생하는 에러이니 해당 부분을 수정하시면 될 것 같습니다..
