### ISSUE TITLE
Cannot find destroy method in v4.0.3

### ISSUE THREAD

**Issue by socketbear** [nhn/tui.grid#510]
**Describe the bug**
3.8 버전에서 사용하던 destroy 함수가 사라짐

**To Reproduce**
1. 기존 tui.grid 3.8 버전 사용 간, destroy 함수를 통해 instance 제거를 하였음
2. 4.0.3 버전으로 업그레이드 한 후, 변경 점 수정
3. 화면 전환으로 destroy 함수 실행 간 에러

**Expected behavior**
destroy 함수가 사라지고 다른 대체제가 생겼다면 댓글로 답변 부탁 드립니다.

**Screenshots**
* tui.grid 3.8 버전 프로토 타입 부분
![image](https://user-images.githubusercontent.com/3022713/60691590-cfb96080-9f0b-11e9-8e04-a2101eb18655.png)

* tui.grid 4.0.3 버전 프로토 타입 부분
![image](https://user-images.githubusercontent.com/3022713/60691597-de077c80-9f0b-11e9-851b-4c43777b146b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 75.0.3770.100(공식 빌드) (64비트)

**Comment by js87zz** [comment]
@socketbear 
4.x 메이저 업데이트 하면서 누락된 것으로 보이네요..4.1.1 업데이트 시 반영하도록 하겠습니다. 감사합니다.

**Comment by js87zz** [comment]
@socketbear 
destroy 메소드는 v4.5.0 배포에 적용될 예정입니다. 우선 순위 항목들이 있어서 그동안 미뤄진 점 양해 부탁드리겠습니다!

**Comment by js87zz** [comment]
@socketbear 
## bug
`destroy` API has been missed
## fixed
fixed in v4.4.1(#626)
