### ISSUE TITLE
4.0.x 업그레이드 가이드

### ISSUE THREAD

**Issue by socketbear** [nhn/tui.grid#511]
## Version
3.8.0에서 **4.0.3**으로 업그레이드 하여 사용

## Development Environment
Windows 10, Chrome 75.x

## Current Behavior
기존 column 정의 시, title이 header로 변경된 점 등, 예상치 못한 변경점이 많은 듯 보입니다.
함수가 사라지것도 있고...

## Expected Behavior
3.8에서 4.0.x로 업그레이드 되면서 조치를 할 만한 사항이 적힌 문서가 있으면 좋겠습니다.

**Comment by jung-han** [comment]
@socketbear 
불편 드려 죄송합니다. 리드미에 노출이 되는 방향으로 수정하도록 하겠습니다.
현재 마이그레이션 가이드는 docs에 한글과 영문버전으로 포함되어있습니다. 링크 첨부드립니다.
https://github.com/nhn/tui.grid/blob/master/docs/v4.0-migration-guide-kor.md

**Comment by socketbear** [comment]
@jung-han 
가이드가 있었군요! 정독하겠습니다~
