### ISSUE TITLE
pagination 오류

### ISSUE THREAD

**Issue by 1wind1** [nhn/tui.grid#513]
---------------------------------------------------------------------------------------------
IE 11에서 개체는 이 기능을 지원하지 않습니다. 오류 발생합니다.
tui-grid.js
PaginationComp.prototype.createPagination { ...
error-->   this.tuiPagination = new tui_pagination_1.default(this.el, options);
}

데이터를 정상적으로 읽어서 화면에 출력하지만
javascript 부분에
pageOptions: {
			        perPage: 10
			    },
코드를 작성하면 오류가 발생하고, 페이징 구현이 되지 않습니다.
확인 결과 totalCount, page 데이터가 제대로 연동되지 않고 있습니다.
---------------------------------------------------------------------------------------------
※ tui grid version : 4.0.2
※ Json Data
{"result":true,
  "data":{"pagination":{"page":1,"totalCount":124},
              "contents":[{"tableContent":"3","tableName":"2","tbCode":"1"},
                                   ... 생략
                                 {"tableContent":"5","tableName":"4","tbCode":"3"}, 
                                 {"tableContent":"ㄴ","tableName":"ㄱ","tbCode":"4"}]}
}

※ JavaScript Source
 const dataSource = {
			   api: {
				    readData: { url: '/test/testGrid.json', method: 'GET' }
				  }
				};
const grid = new tui.Grid({
			    el: document.getElementById('testGrid'),
			    data:dataSource,
			    pageOptions: {
			        perPage: 10
			    },
			    scrollX: false,
			    scrollY: false,
			    minBodyHeight: 30,
			    rowHeaders: ['rowNum'],
			    columns: [
			      {
			        header: 'TB_CODE',
			        name: 'tbCode'
			      },
			      {
			        header: 'TABLE_NAME',
			        name: 'tableName'
			      },
			      {
			        header: 'TABLE_CONTENT',
			        name: 'tableContent'
			      }
			    ]
			  });

**Comment by js87zz** [comment]
@1wind1 
`tui-pagination` dependency가 import 되어 있는 상태인가요?
의존성을 모두 제거하였기때문에 `tui-pagination`이나 `tui-datepicker` 사용시 import를 해주셔야합니다.
그리고 앞으로는 이슈 템플릿에 맞게 작성해주시면 감사하겠습니다!

**Comment by 1wind1** [comment]
감사합니다 오류가 해결됐습니다
tui-grid.css, tui-grid.js만 import 해서 발생한 문제였군요.
