### ISSUE TITLE
manymany columns일때...

### ISSUE THREAD

**Issue by saeparan** [nhn/tui.grid#516]
https://github.com/nhn/tui.grid/issues/225

해당이슈와 비슷한 질의지만...
columns의 width를 각기 다른 값으로 지정하고
scrollX: true일때..

마우스 스크롤시 
rowHeader와 columns간의 틀이 깨져버립니다.

이 부분만 보완되면 저희는 완벽하게 쓸수 잇는데 ㅠㅠ
뭔가 방법이 없을까요?

E.g,
`const gridData = [];
	(function() {
		for(let i = 0; i < 120; i += 1) {
			gridData.push({
				c1: 'User' + (i + 1),
				c2: ((i + 5) % 8) * 100 + i,
				c3: ((i + 3) % 7) * 60,
                c4: ((i + 3) % 7) * 60,
                c5: "awefopjawepojpawfepjafwoeoawefjoawfeowfejpowfepoj",
                c6: ((i + 3) % 7) * 60,
                c7: ((i + 3) % 7) * 60,
                c8: ((i + 3) % 7) * 60,
                c9: ((i + 3) % 7) * 60,
                c10: ((i + 3) % 7) * 60,
                c11: ((i + 3) % 7) * 60,
                c12: ((i + 3) % 7) * 60,
                c13: "awefopjawepojpawfepjafwoeoawefjoawfeowfejpowfepoj"
			});
		}
	})();

	const grid = new tui.Grid({
		el: document.getElementById('grid'),
		data: gridData,
		scrollX: true,
        scrollY: true,
		bodyHeight: 400,
		rowHeaders: ['rowNum'],
		columns: [
			{
				header: 'User ID',
				name: 'c1',
				align: 'center',
				editor: 'text',minWidth: 200,
			},
			{
				header: 'Score',
				name: 'c2',
				className: 'clickable',
				editor: 'text',minWidth: 500,
			},
			{
				header: 'Item Count',
				name: 'c4',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c5',
				editor: 'text',
                minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c6',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c7',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c8',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c9',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c10',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c11',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c12',
				editor: 'text',minWidth: 500,
			},
            {
				header: 'Item Count',
				name: 'c13',
				editor: 'text',
                minWidth: 500,
			}
		],
	});

    var Grid = tui.Grid;
    Grid.applyTheme()`

**Comment by js87zz** [comment]
@saeparan 
현재 컬럼 스크롤링 시 컬럼 사이즈 싱크가 맞지 않는 버그가 존재하고 있는데, 이 부분과 연관이 있을 것 같네요. `7/11일` v4.1.0 배포에 해당 버그 수정도 포함되니 이후에 한 번 더 확인해보시면 될 것 같습니다.

**Comment by saeparan** [comment]
@js87zz  감사합니다. ㅠㅠ 기다려지네요

**Comment by js87zz** [comment]
@saeparan 
v4.1.0 배포 되었으니 현상 다시 확인해보시면 될 것 같습니다.

**Comment by saeparan** [comment]
@js87zz 

아주 잘되네요. 이틀간 기다림 보람이 있네요. 감사합니다.
