### ISSUE TITLE
How can I simply change table data?

### ISSUE THREAD

**Issue by Alexby8** [nhn/tui.grid#537]
Hi. I have a question.
When I create table I put data object in data property using "new Grid".
For example I have a new data and I want to change original data. How can I do it? 
And the same question for summary.columnContent. Can I update it?
I have "getRows" method and I need something like "setRows", which just change old data to new.

Little more question: where can I find api docs for 3 version? Could't find here:
https://github.com/nhn/tui.grid/releases

**Comment by js87zz** [comment]
@Alexby8 
You can change the grid data through calling `setData(data, callback)` method. And summay column content can be changed by calling `setSummaryColumnContent(columnName, content)` method.
You can see the API and Example [here](https://nhn.github.io/tui.grid/3.9.0/) and find [the tutorial](https://github.com/nhn/tui.grid/tree/3.8/docs) in 3.8 branch. 
we would add the `3.9 API` link in README file soon :)

**Comment by Alexby8** [comment]
Thank you
