### ISSUE TITLE
tui-grid/index.d.ts에서의 에러가 발생합니다.

### ISSUE THREAD

**Issue by Owen-igaw** [nhn/tui.grid#553]
**Describe the bug**
v3.8.0에서 전달드린 버그리포트 (https://github.com/nhn/tui.grid/issues/391#issue-451363605) 처럼 `index.d.ts`의 아래와 같은 부분에서 에러가 발생합니다.
```js
interface IRow {
        [propName: string]: ColumnValueType;
        _extraData?: {
          ^
            rowState?: RowStateType;
        };
    }

    interface ITreeRow {
        [propName: string]: ColumnValueType;
           _extraData?: {
          ^
            rowState?: RowStateType;
            treeState?: TreeStateType;
        };
        _children: ITreeRow[];
    }
```

**To Reproduce**
1. yarn add @toast-ui/vue-grid@1.0.5
2. run vue
3. `error`

**Expected behavior**
IRow와 ITreeRow에 대해서 에러 없이 실행되길 바랍니다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser:  chrome
 - Version:  v75.0.3770.142(공식 빌드) (64비트)

**Additional context**

`[propName: string]: ColumnValueType` 이 
`_extraData ?: {~}` 에서의 `undefined` 일 경우를 처리하지 못해 발생하는 에러로 보입니다.
해당 부분에서 완전한 처리는 4.0.0 에서 이뤄진 것으로 보이나, `4.0.0`에서는 `index.d.ts`의 각 type과 interface가 export 되어있지 않아 기존 코드에서 활용하기가 곤란하여 `3.*.*`의 수정을 부탁드립니다. ( 기존 issue에서는 3.8.1버전(현재의 3.9.0 인 듯 합니다)에서 해결 후 배포될 것이라 전달받았으나, 3.9.0의 마일스톤에는 해당 부분이 포함되어 있지 않은 것을 확인했습니다. )

그리고 이번 사항과 더불어 `4.*.*` 버전에서 `index.d.ts` 내의 type과 interface의 export 또한 요청드리고자 합니다. 혹시 현재 상태에서 이용가능한 방법이 있다면 그 방법을 여쭙고 싶습니다.
   
   
   
바쁘신 와중에 감사합니다!

**Comment by js87zz** [comment]
@Owen-igaw 
확인해보니 3.9.0 에서 말씀하신 `index.d.ts` 수정이 되지 않은 상태라 `v3.9.1` 에 수정 반영하겠습니다. 현재 `v4.x`에서 개발진행 중인 사항들이 있어서 정확한 배포일정은 말씀드릴 수 없는 상황이지만 픽스되는 대로 공유드리겠습니다. 
그리고 `v4.x` 의 타입정의(index.d.ts) 파일 같은 경우는 `v3.9.0` 의 타입과는 다른 부분이 많아 이 타입을 적용하기는 힘드실 것 같습니다.
감사합니다 :)

**Comment by Owen-igaw** [comment]
@js87zz 
네 확인했습니다 ㅎㅎ 바쁘신 와중에도 대응해주시니 감사합니다!

**Comment by js87zz** [comment]
@Owen-igaw 
## bug
wrong type definition(#604)
## fixed
fixed in v3.9.1
