### ISSUE TITLE
expandAll이 정상적으로 동작하지 않습니다.

### ISSUE THREAD

**Issue by Owen-igaw** [nhn/tui.grid#554]
**Describe the bug**
v3.9.0에서 expandAll을 실행했을 때, treeData의 최상위 row들은 expanded event가 발생하지만, 최상위가 아닌 row들은 expanded event는 발생하지 않고 화살표 아이콘만 변경됩니다.

**To Reproduce**
1. expandAll 한 차례 실행
2. 최상위 row가 expand되며 expanded event handler를 통해 children 추가
3. expandAll 한차례 더 실행
4. 최상위 row의 expanded event 만 발생하며, chidren들은 화살표 아이콘만 변경됨.

**Expected behavior**
현재 보여지는 row 중 아직 펼쳐지지 않은 모든 row들이 expanded 되었으면 합니다.

**Screenshots**
1.  expand 한차례 실행
![image](https://user-images.githubusercontent.com/48425240/61506711-f30d0100-aa1d-11e9-8556-f680c936c488.png)
2. expand 한차례 더 실행
![image](https://user-images.githubusercontent.com/48425240/61506719-fd2eff80-aa1d-11e9-9af8-5ba6c09ba910.png)

---- 정상 동작 시의 모습 ---- ( 모든 row를 거치며 각 row를 모두 expand 시켰습니다. )
![image](https://user-images.githubusercontent.com/48425240/61506759-2d769e00-aa1e-11e9-9e14-c656fc38c8be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142(공식 빌드) (64비트)

**Additional context**
바쁘신 중에 감사합니다!

**Comment by seonim-ryu** [comment]
@Owen-igaw
이슈 확인 중에 궁금한 사항이 있습니다.
스텝 설명하신 부분에서는 `expandAll`을 호출하였으나 이미지상에서는`expand`로 되어있어서.. 어떤 것이 맞는지요?
그리고 간단하게 메서드, 이벤트 호출 로직을 코드로 전달해주시면 재현에 도움이 될 것 같습니다.
(제가 이해한대로 구현했을 때는 현상이 발생하지 않네요.. 😅)

**Comment by Owen-igaw** [comment]
> @Owen-igaw
> 이슈 확인 중에 궁금한 사항이 있습니다.
> 스텝 설명하신 부분에서는 `expandAll`을 호출하였으나 이미지상에서는`expand`로 되어있어서.. 어떤 것이 맞는지요?
> 그리고 간단하게 메서드, 이벤트 호출 로직을 코드로 전달해주시면 재현에 도움이 될 것 같습니다.
> (제가 이해한대로 구현했을 때는 현상이 발생하지 않네요.. 😅)

@seonim-ryu 
앗 죄송합니다..! 설명 중 오타가 있었네요. 그리고 늦은 답변 또한 죄송합니다...
말씀 주신 것처럼 `expandAll`을 호출했을 때 에러가 발생합니다.

해당 코드는 다음처럼 작성되어 있습니다.
```
private toggleAllHandler() {
        this.allExpandToggleConfirmVisible = false;
        const table = this.$refs.table as Grid;
        const rows = table.invoke('getRows') as RowType[];
        this.loading = true;
        setTimeout(() => {
            if (this.isAllExpanded === 2) {
                // rows.forEach((item: any) => {
                //     const row = item as tuiGrid.IRow & (IAppReport | IPlacementReportWrap) & { rowKey: tuiGrid.RowKeyType };
                //     if (row._children !== undefined) {
                //         table.invoke('collapse', row.rowKey, true);
                //     }
                // })
                // this.isAllExpanded = 0;
                table.invoke('collapseAll'); // 정상 동작안하는 메서드
            } else {
                this.isAllExpanded = 1;
                // rows.forEach((item: any) => {
                //     const row = item as tuiGrid.IRow & (IAppReport | IPlacementReportWrap) & { rowKey: tuiGrid.RowKeyType };
                //     if (row._children !== undefined && row._children !== false) {
                //         table.invoke('expand', row.rowKey, true);
                //     }
                //     if (row.dateRange) {
                //         this.isAllExpanded = 2;
                //     } 
                // })
                table.invoke('expandAll'); // 정상 동작안하는 메서드
            }
            this.loading = false;
        });
    }
```

주석처리된 부분은 expandAll 메서드 동작에 대한 대응책으로써 활용 중인 부분입니다. 현상은 위의 글에 설명드린 것과 같이 발생합니다.

현재 Vue.js에서 @toast-ui/vue-grid를 통해 코드 작성 중이며, 다음과 같이 이벤트를 전달받습니다.
```
<Grid
                ref="table"
                theme="striped"
                :options="gridOptions"
                :columnData="gridOptions.columns"
                :rowData="tableData"
                @expanded="expandedHandler"
            />
```

감사합니다!

**Comment by js87zz** [comment]
@Owen-igaw 
## bug
expanded event is not occurred properly on calling expandAll method(#605)
## fixed
fixed in v3.9.1
