### ISSUE TITLE
whiteSpace: 'normal' 옵션을 준 행의 높이인식에 버그가 있습니다.

### ISSUE THREAD

**Issue by jeung-ryu** [nhn/tui.grid#557]
**Describe the bug**
whiteSpace: 'normal'
rowHeight: 'auto'
옵션을 주고 그리드를 생성했는데 데이터의 길이가 길때 높이가 깨집니다.
셀을 더블클릭을해도 수정옵션으로 넘어가지 않습니다. 특정부분을 더블클릭해야 수정화면으로 넘어갑니다.

**To Reproduce**
1. 예시 소스 example10-data-source.html 코드 수정
2. 그리드 옵션 rowHeight: 'auto' 추가
    컬럼 옵션에 whiteSpace: 'normal', editor: 'text'
3. 예시 소스 ./data/basic-dummy.js 코드 수정
4. 컬럼의 데이터 길이를 크게 수정

**Expected behavior**
셀 안에 들어갈 데이터의 길이가 길 때
1. row의 크기가 깨지지 않는다.
2. 셀을 더블클릭시 수정화면으로 넘어간다.
3. 데이터 길이가 길 경우 input tag 수정화면이 아니라  textarea 수정화면이었으면 (not bug)

**Screenshots**

![tui버그](https://user-images.githubusercontent.com/46561470/61507953-d1fadf00-aa22-11e9-9c9c-83f70ba2670c.PNG)

**Desktop (please complete the following information):**
 - OS: window10
 - Browser: chrome
 - Version: tui-grid-4.1.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeung-ryu** [comment]
v3 -> v4로 마이그레이션 어드민 운영환경에 적용중인데
버그픽스 부탁합니다.

**Comment by seonim-ryu** [comment]
@jeung-ryu 
#541 이 이슈와 동일한 것으로 보이네요. 제보 감사합니다. :)

**Comment by js87zz** [comment]
@jeung-ryu 
## bug
row height is set to the default row height, when the cell content height is larger than the default value
## fixed
fixed in v4.4.0(#599)
