### ISSUE TITLE
한 column 내 여러가지 이벤트

### ISSUE THREAD

**Issue by deadlockk** [nhn/tui.grid#559]
![image](https://user-images.githubusercontent.com/22904763/61512422-d16b4400-aa34-11e9-9418-f09048644b61.png)

그림과 같이 edit과 delete 두 개의 이벤트를 한 컬럼에 넣고 싶습니다.
Toast gird에서 한 컬럼에 두가지 또는 그 이상의 이벤트를 받을 수 있는 방법이 있을까요?

**Comment by js87zz** [comment]
@deadlockk 
v4.x 를 사용하고 계시면 커스텀 렌더러를 구현하여 원하는 이벤트를 구현하실 수 있을 것 같습니다.
https://github.com/nhn/tui.grid/blob/master/docs/ko/custom-renderer.md
