### ISSUE TITLE
Renderer bug of reloaded or reseted grid

### ISSUE THREAD

**Issue by kimboha** [nhn/tui.grid#566]
**Describe the bug**
특정 상황에서 셀 값의 수정사항이 반영되지 않습니다. (보이는것만 변하지 않고, 실제 내부 데이터는 변합니다.)

**To Reproduce**
1. editable한 그리드를 준비합니다.
2. 그리드의 최초 데이터 셋팅이 끝난 뒤, (datasource로 하거나 resetData로 하거나 무관)
3. datasource를 통해 데이터를 reload하거나, resetData를 통해 데이터를 reset합니다.
4. 셀의 값을 수정하고, edit-mode를 마칩니다. 

**Expected behavior**
셀의 값을 수정하여도 수정 사항이 반영되지 않습니다.
단, getData를 통한 데이터 상으론 수정되어 있습니다. 해당 셀을 다시 edit-mode로 바꾸어도 수정사항이 반영되어 있습니다.
최초 load혹은 reset시, grid를 clear한 후에 reset할 경우는 위의 버그가 발생하지 않습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/12408609/61696036-88d2c400-ad6f-11e9-9834-09bbf5431f10.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: chrome
 - Version: 4.1.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by js87zz** [comment]
@kimboha 
## bug
The data has not been refreshed after calling `resetData` API
## fixed
fixed in 4.2.0(#576)
