### ISSUE TITLE
How can I dynamically add that data?

### ISSUE THREAD

**Issue by weleek** [nhn/tui.grid#571]
## Version
3.9.0

## Development Environment
Windows 10

## Current Behavior

https://nhn.github.io/tui.grid/3.9.0/tutorial-example06-using-extradata

```js
var GridTable = new tui.Grid({
            el: $('#grid_area'), 
            bodyHeight: 500,
            scrollX: true,
            scrollY: true,
            rowHeaders: ['rowNum'],
            display: { noData: 'No Data' },
            columns: [
{ title: '상태', name: 'STATUS', whiteSpace: 'normal', width:60, sortable: true,
                    formatter: function(value, rowData, columnInfo){
                         // 실패인 경우 로우를 붉은 색으로 표시해야 한다.
                        return value == '1' ? '성공':'실패';
                    }
                }
           ]
});
// 서버에서 보내온 더미 데이터 형식
GridTable .setData([{'STATUS':'1'},{'STATUS':'0'},{'STATUS':'1'}]);
```

## Expected Behavior
안녕하세요 질문이 있어서 올립니다.
해당 버전의 _extraData 라는 속성 데이터를 서버에서 받아온 뒤 해당 row데이터 특정 속성값에 따라  동적으로 추가하고 싶습니다.

예를 들어 서버에서 보내준 rowDataList의 status 라는 값에 따라 하나의 셀이 아닌 한 로우의 색상을 빨간색으로 변하게 한다던가 하는 효과를 주고 싶어서 예제 링크를 보았으나 해당 예제에서는
서버에서 받아온 rowDataList에 이미 _extraData라는 속성값이 추가 되어 나오는군요.

이러한 동작을 컬럼 정의 할 시 formatter 속성의 함수에서 처리 할수 있습니까?

**Comment by js87zz** [comment]
@weleek 
특정 셀의 데이터에 따라 로우의 배경색을 변경하고 싶다면 아래처럼 로우 데이터에 _extraData를 옵션을 추가해주시면 될 것 같습니다.
```js
// grid instance 생성 이후

const dummyData = [{'STATUS':'1'},{'STATUS':'0'},{'STATUS':'1'}];

// STATUS 컬럼의 값이 0 인 경우에 로우의 className을 변경하고 싶은 경우
dummyData.forEach((data) => {
   if (data.STATUS === '0') {
      data._extraData = {
         className: { // Add class name on a row
            row: ['red']
         }
      }
   }
);

grid.setData(dummyData);
```

**Comment by weleek** [comment]
이렇게 처리하면 서버에서 가지고 온 데이터를 한번더 가공하게 되니 성능에 좋을것 같지 않아서
화면에 데이터를 처리할 때 같이 처리할 수 있는 방법이 있을거 같아서 여쭤봅니다.

혹시 formatter 함수가 실행 되는 시점에서 처리 할 수 있는 방법이 있을까요?

**Comment by js87zz** [comment]
@weleek 
아래처럼 formatter 함수를 사용해서 원하시는 동작 구현은 가능 할 것 같습니다만, formatter 는 셀의 값을 어떻게 효과적으로 보여줄지 위해 만든 스펙이기 때문에 원래 저희의 의도와는 맞지 않는 것 같습니다. 로우의 스타일 지정을 위한 거라면 위의 방법을 권장 드립니다. 데이터가 수 천, 수 만건이 아니라면 성능에 큰 영향은 없을 것 같습니다.
```
formatter: function(value, rowData) {
   if (rowData.STATUS === '0') {
      grid.addRowClassName(rowData.rowKey, 'red')
   }
   return value;
}
```

**Comment by weleek** [comment]
빠른 답변 감사드립니다.
최초 개발의도와 다른 의도라니 할말이 없군요 ㅜㅠ...
화면에 테이블을 정의 하는 부분과 데이터에 대한 유효성 검사나 별도 로직을 추가하지 않고 부분적으로 함수를 나누려다 보니 이렇게 된거 같습니다.

알려주신 방법 잘 적용하여 사용해보겠습니다.
감사합니다.

**Comment by jhjung3797** [comment]
1
