### ISSUE TITLE
afterimage of tui grid when pop up a modal

### ISSUE THREAD

**Issue by deadlockk** [nhn/tui.grid#572]
## Version

4.1.0
## Current Behavior

![image](https://user-images.githubusercontent.com/22904763/61840781-46bf9480-aecd-11e9-8707-b9f869e1756a.png)

모달 창이 뜰 때 그리드의 잔상이 남아있어서 그리드의 테두리가 잠시동안 보입니다. 심지어 데이터가 없을 때에는 no data 부분이 잠시동안 모달창과 겹쳐 보이는 현상이 있습니다. 어떻게 해결해야 할까요

**Comment by MCJoo** [comment]
저도 잔상이 남는 비슷한 오류가 있네요

**Comment by js87zz** [comment]
@deadlockk 
모달 창의 z-index css 속성을 20이상으로 조정하시면 될 것 같습니다.
