### ISSUE TITLE
appendRow로 Row추가시 추가된 Row edit속성 변경

### ISSUE THREAD

**Issue by scs9310** [nhn/tui.grid#588]
기존 Row에는 edit이 불가능하고 appendRow로 새로운 row를 추가했을 때 새로 추가된 row에만 edit이 가능하게 하고싶습니다. 해당되는 기능이 존재하나요?

**Comment by jung-han** [comment]
@scs9310 안녕하세요. 현재 해당기능은 제공하고 있지 않습니다.
