### ISSUE TITLE
toast Grid readData 및 tab키 사용 컬럼이동

### ISSUE THREAD

**Issue by sungjae94** [nhn/tui.grid#589]
toast ui Grid 가 오픈소스라는 소리를 듣고 공부를 하는중입니다. 데이터베이스에서 테이블을 불러와서 조회 및 생성 수정 삭제 등을 해보려고 하고있는데 예제를 보니 data source 라 적힌 부분이 DB에서 정보를 조회해서 뿌려오는거 같은데 예제에는 일부분만 코딩 되어 있는거 같아서 맞춰서 해보는데 아무리 해보고 찾아봐도 조회가 되지않아서 문의를 드립니다. 실례가 안된다면 어떻게 작성해야 문제가없는지 답변해 주실수 있으신가요? 그 후 생성 수정 삭제 관련 소스도 피드백좀 주시면 감사합니다.  또한 그 toast ui grid에 tab키 사용으로 포커스가 이동을 하던데 그것도 설정을 해줘야되는건가요?

**Comment by jung-han** [comment]
@sungjae94 
안녕하세요. 우선 어떻게 사용하는지 정보가 부족해 튜토리얼 링크 제공해 드리겠습니다.

* dataSoruce: https://github.com/nhn/tui.grid/blob/master/docs/ko/data-source.md
* Keymap: https://github.com/nhn/tui.grid/blob/master/docs/ko/keymap.md

만약 이후에 이슈를 올리실 때는 템플릿 양식에 맞춰 작성해 주시면 감사하겠습니다.
