### ISSUE TITLE
error occurred when i try removing row which  editor is open

### ISSUE THREAD

**Issue by moonchanyong** [nhn/tui.grid#590]
**Describe the bug**

like title, i'm testing issue #547 but error occurred 

may be it's own issue by my machine

**To Reproduce**

1. [open example in private chrome](https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor)
2. dbclick any cells in first row 
3. in console, change contexts to example iframe, do `grid.removeRow(0)`
4. see log

**Expected behavior**

close text editor and remove the row

**Screenshots**
![low-gi](https://user-images.githubusercontent.com/17975472/62419075-1e951a00-b6b3-11e9-892e-46b66faaa371.gif)

**Desktop (please complete the following information):**

- "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
- version 4.2.0 

**Additional context**

this issue occur in tree example when i modify column to be editable by overriding document of chrome source tab

**Comment by jung-han** [comment]
Hi, @moonchanyong. 

I think It's not your machine issue. As you said, It seems to be an issue similar to #547.
It seems to be a bug that occurs when trying to delete the row being edited.
It will be fixed soon. Thanks.

**Comment by moonchanyong** [comment]
can I take up this issue?

**Comment by jung-han** [comment]
@moonchanyong No problem 🙂.

**Comment by moonchanyong** [comment]
solved at d93776a0073eae8883723212008097bda14e57bd.
