### ISSUE TITLE
Row 컬럼 버튼생성 문의

### ISSUE THREAD

**Issue by sungjae94** [nhn/tui.grid#591]
Row추가나 edit시 일부 컬럼에 버튼을 줄 수있는 옵션이 있을까요?

**Comment by jung-han** [comment]
@sungjae94 
커스텀 에디터 옵션 확인 부탁드립니다.
* https://github.com/nhn/tui.grid/blob/master/docs/ko/custom-editor.md

이후 이슈 템플릿 양식을 지켜주시지 않을 경우 답변 없이 close하도록 하겠습니다. 양해 부탁드립니다.

**Comment by sungjae94** [comment]
@jung-han 
이번이 처음써보는거라 양식을 몰라서요...;;
