### ISSUE TITLE
grid column 이 editor일때 해당column내에 button 넣는법좀 알려주세요

### ISSUE THREAD

**Issue by sungjae94** [nhn/tui.grid#597]
## Current Behavior

grid column 이 editor상태가 되면 input type=text와 button을 같이 만들고 싶은데 원하는 정보가 있지도 않을뿐더러 옵션 설명해놓은 사이트를 봐도 찾지못하였습니다 formatter를 사용하여 버튼을 만들어봣는데  나오는데 해당column이 기본상태일때는 나오나 editor상태가되면 나오지 않습니다  grid column이 editor 상태가 되었을때 해당 column에 button을 넣을 수 있는방법좀 알려주시면 감사하겠습니다.
```js
// Write example code
```

**Comment by jung-han** [comment]
@sungjae94 버전과 개발 환경, 문제가 되는 내용 또는 질문 사항, 작성한 코드 혹은 에러, 개선사항등을 양식에 맞춰 자세히 명시해주시면 감사하겠습니다.
