### ISSUE TITLE
grid column 이 editor일때 해당column내에 button 넣는법좀 알려주세요

### ISSUE THREAD

**Issue by sungjae94** [nhn/tui.grid#600]
**Summary**
스크린샷에 나온것 처럼 Editor 상태일때 input type=text 옆에 button을 추가할 수 있는 법좀 알려주세요 옵션등등 사용해봐두 나타나지않습니다..

**Screenshots**
![1](https://user-images.githubusercontent.com/43875733/62594561-0c66e600-b916-11e9-8cfd-e96ffbfdcea6.PNG)

**Version**
4.1 Version

**Additional context**

**Comment by js87zz** [comment]
@sungjae94 
아래 링크를 참조하셔서 원하시는 포맷의 editor class를 만든 후 옵션에 설정해서 사용하시면 됩니다.
https://github.com/nhn/tui.grid/blob/master/docs/ko/custom-editor.md

**Comment by sungjae94** [comment]
@js87zz 
사이트를 참조하여서 버튼을 만들기는 했습니다만 한컬럼안에 editor가 두개가 안먹는거 같아서요 두개를 같이사용하려면
const grid = new Grid({
  // ... another options
  columns: [
    {
      header: 'Custom',
      name: 'custom',
      editor: {
        type: CustomTextEditor,
        options: {
          customTextEditorOptions: {
            // ...
          }
        }
      }        
    }
    // ...
  ]
});
이 예제처처럼 customTextEditorOptions에 두개를 적용시켜야되는것인가요?

**Comment by js87zz** [comment]
@sungjae94 
CustomTextEditor class 안에서 text와 button을 동시에 생성하고 원하는 이벤트 핸들러를 등록하시면 될 것 같습니다. 이 이상 세부적인 구현은 직접하셔야 될 것 같습니다. 스펙 이외에 구현까지 저희가 가이드하진 않으니 양해 부탁드립니다.
