### ISSUE TITLE
pageOption 사용시 문제

### ISSUE THREAD

**Issue by nanna0** [nhn/tui.grid#606]
grid v4 에서는 pagination.js를 따로 임포트하여 사용하지 않고 자체적으로 해결할 수 있다고 해서 적용하고 있습니다. 
![image](https://user-images.githubusercontent.com/46311402/62703394-15de7400-ba24-11e9-8384-86d5a1c60e99.png)
위와 같은 에러가 뜨고 넘어가질 않네요.. 혹시나해서 pagination.js도 임포트해봤는데 require(tui-code-snippet) 을 찾을 수 없다고 하여 또 tui-code-snippet역시 임포트 해봤지만 계속 defined뜹니다 
이게 문제가 아닌거같은데 어떻게 해결해야하나요? 
데이터 불러오는것은 별도의 함수로 ajax호출하고있습니다.
```
function makeGrid(data){
const grid = new tui.Grid({
		el: document.getElementById('gridDiv'),	
		data:data,
		scrollX: false,
		scrollY: false,
		minBodyHeight: 30,
	    pageOptions: {
			perPage : 5,
		}, 
	    columns: [		
            ...생략
   	{

```

예제로 도저히 모르겠어서 헤매고있습니다. 어떻게 해결해야하나요?

**Comment by js87zz** [comment]
@nanna0 
import하는 부분을 정확하게 올려주셔야 답변을 드릴 수 있을 것 같습니다. 의존성이 분리되었기 때문에 별도로 tui-code-snippet.js, tui-pagination.js, tui-pagination.css 파일을 import해서 사용하시면 정상적으로 동작합니다. (datapicker의 경우도 마찬가지입니다.)
그리고 앞으로는 이슈 템플릿을 지우지말고 양식에 맞춰서 작성해주시면 감사하겠습니다.

**Comment by nanna0** [comment]
![image](https://user-images.githubusercontent.com/46311402/62757908-bcc02000-bab7-11e9-95a2-2fd3bd05e4f9.png)
![image](https://user-images.githubusercontent.com/46311402/62757914-c34e9780-bab7-11e9-86da-458b8feeb694.png)

의존성문제라고 하시면 순서가 문제인가요? 아니면 경로가 문제인가요? 현재 모두 같은 경로입니다.

**Comment by js87zz** [comment]
@nanna0 
script 정의 순서 문제네요. script는 순서대로 파싱되고 실행되기 때문에 tui-grid.js 파일의 import 위치가 pagination이나 code snippet 보다 아래에 위치해야 정상동작합니다. (마찬가지 이유로 pagination은 code snippet보다 아래에 위치해야하구요)
