### ISSUE TITLE
focusChange API 사용시 cell을 클릭하였을때 row 전체가 선탠되게하는 방법

### ISSUE THREAD

**Issue by haruharmony** [nhn/tui.grid#612]
> ## Version
> 4.3
> 
> ## Development Environment
> 크롬 버전 75.0.3770.142(공식 빌드) (64비트)
> 
> ## Current Behavior
> ```js
>grid.on('focusChange', (ev) => {
>  grid.setSelectionRange({
>    start: [ev.rowKey, 0],
>    end: [ev.rowKey, grid.getColumns().length]
>  });
>});
>
> grid.on('click', function (ev) {
>    console.log("hi");
>  });
>
> grid.on('dblclick', function (ev) {
>   console.log("hi");
>});
> ```
> 그리드의 셀을 선택할경우 전체 로우를 선택하고자 다음과 같은 API를 사용했습니다.
> 근데 이 API를 사용할경우 같은 셀을 더블릭할때 포커스 체인지 이벤트가 안일어나는데도
> 셀 선택 색이 사라집니다.
>
> 그리고 셀의 클릭 시 포커스 체인지와 클릭이벤트는 동시에 발생하나
> 더블클릭 이벤트는 동시에 발생하지 않아서, 3번 클릭해야 합니다.
>
> ## Expected Behavior
>포커스체인지 이벤트가 발생하지 않을때(같은 셀 선택하였을때) 셀 선택 색깔이 유지되었으면 합니다.
>그리고 포커스 체인지 이벤트와 더블크릭 이벤트가 같이 발생하면 좋겠습니다..
> 감사합니다.
>

**Comment by js87zz** [comment]
@haruharmony 
`grid 내에 셀 영역을 클릭하면 셀렉션 영역이 해제된다`라는 것이 스펙이기 때문에 현재로서는 올바른 동작으로 보입니다. 해당 사항에 관련된 니즈가 조금 더 많아지면, 추가적인 이벤트를 제공하거나 다른 방법으로 풀 수 있는지 팀원들과 논의해보겠습니다! 그리고 더블클릭 이벤트는 더블클릭시에 발생하는 것이기 때문에 포커스 체인지와 함께 발생하는 것은 맞지않는 듯 합니다.

**Comment by haruharmony** [comment]
@js87zz 
grid 내에 셀 영역을 클릭하면 셀렉션 영역이 해제된다. 
에서 셀이 다른 셀일경우에는 셀렉션 영역이 해제되어야 하지만, 같은 셀을 선택 하였는데 유지하지 못하고, 해제되는것은 조금 이상한거 같습니다. 번거로우시겠지만 다시 한번 확인해주실 수 있을까요?

그리고 focusChange와 dblclick 이벤트를 같이 등록 시 dblclick 이벤트가 잘 동작하지 않습니다.
처음에 셀을 더블클릭하여도 dblclick 이벤트가 발생하지 않습니다. 여러번 클릭 한 뒤에 동작합니다.

**Comment by jung-han** [comment]
@haruharmony 
내부적으로 좀 더 검토 되어야 하지만 셀렉션 영역을 다시 클릭하여 선택 했을때 셀렉션이 해제되고 선택된 셀에 focus가 지정이 되는 것은 외부 그리드나 엑셀, 스프레드 시트 등에서 사용되고 있는 사용성이라 생각됩니다. 

다음으로, 현재 `focusChange`와 `dblclick` 이벤트를 추가해준 결과 제대로 작동되는 것으로 보여집니다. 버그로 판단되는 내용은 새로운 이슈로 템플릿 양식에 맞춰 작성해주시면 감사하겠습니다.

**Comment by haruharmony** [comment]
@jung-han 
버그 이슈는 아닌거 같아. 질문 내용을 다시 정리하여 질문으로 올렸습니다.. https://github.com/nhn/tui.grid/issues/628#issue-482662232

이 페이지는 클로즈 하겠습니다.
