### ISSUE TITLE
Where can I find the old version guide?

### ISSUE THREAD

**Issue by rhrh82** [nhn/tui.grid#617]
안녕하세요.

그리드 3.5~3.8 버전대의 가이드를 찾을 수 없어 문의 드립니다.

이전 버전에 대한 가이드는 어디서 볼수 있는지 링크 부탁드립니다.

감사합니다!

**Comment by jung-han** [comment]
안녕하세요, 이전 버전 API 문서입니다.
* 3.5.0: https://nhn.github.io/tui.grid/3.5.0/
* 3.7.0: https://nhn.github.io/tui.grid/3.7.0/
* 3.8.0: https://nhn.github.io/tui.grid/3.8.0/

이후에 이슈를 올려주실 경우에는 템플릿 양식을 지우지 말고 양식에 맞춰 올려주시면 감사하겠습니다.
