### ISSUE TITLE
tui-pagination CDN 관련 문의 드립니다.

### ISSUE THREAD

**Issue by ebhan-ui** [nhn/tui.grid#622]
이미지를 첨부하고 싶은데 도저히 못찾겠네요 ;;ㅠㅠ

이번에 tui 이용해서 그리드를 이용해 볼려고 하는데요. 

이렇게 현재 추가 되어진 상황입니다.
------------------------------------------------------------------------------------------------
<script src="https://uicdn.toast.com/tui.pagination/latest/tui-pagination.js"></script>
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
------------------------------------------------------------------------------------------------

개발자도구에서 보면 tui-pagination 해당 js 파일에서 오류가 나네요.
따로 다른 무언가를 해줘야 하나요?
------------------------------------------------------------------------------------------------
tui-pagination.js:492 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (tui-pagination.js:492)
    at __webpack_require__ (tui-pagination.js:36)
    at Object.<anonymous> (tui-pagination.js:93)
    at __webpack_require__ (tui-pagination.js:36)
    at Object.<anonymous> (tui-pagination.js:72)
    at __webpack_require__ (tui-pagination.js:36)
    at tui-pagination.js:56
    at tui-pagination.js:59
    at webpackUniversalModuleDefinition (tui-pagination.js:15)
    at tui-pagination.js:16

**Comment by jung-han** [comment]
@ebhan-ui 
`tui-pagination`에 현재 `tui-code-snippet`의존이 존재하여 CDN으로 사용시 tui.pagination 상단에 code snippet 의존을 추가해주시면 됩니다. 

```js
<script type="text/javascript" src="https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.pagination/v3.3.0/tui-pagination.js"></script>
```
