### ISSUE TITLE
데이터를 두줄로 표현 하는 방법이 있을까요?

### ISSUE THREAD

**Issue by kwonv2** [nhn/tui.grid#624]
하나의 데이터를 두줄 혹은 그 이상의 row로 표현해서 좌우 스크롤 없이 표현이 가능 할까요???

**Comment by jung-han** [comment]
@kwonv2 구체적인 설명이 부족하여 답변이 어려울 것 같습니다. 
이슈 템플릿에 맞춰 사용버전과 환경을 명시해 다시 작성해주시면 감사하겠습니다.
