### ISSUE TITLE
그리드의 cell 선택시 row 전체가 선택되도록 하는 기능

### ISSUE THREAD

**Issue by haruharmony** [nhn/tui.grid#628]
**Summary**
cell 선택시 row 전체가 선택되도록 하는 기능

**Screenshots**
![1](https://user-images.githubusercontent.com/39803281/63324257-a55c1f00-c362-11e9-9465-e15187a3b68a.PNG)
![2](https://user-images.githubusercontent.com/39803281/63324264-a7be7900-c362-11e9-8930-e7d15a855e77.PNG)

```
  grid.on('focusChange', (ev) => {
    console.log("focusChange");
    grid.setSelectionRange({
      start: [ev.rowKey, 0],
      end: [ev.rowKey, grid.getColumns().length-1]
    });
  });

  grid.on('click', function (ev) {
    console.log("click");
  });

  grid.on('dblclick', function (ev) {
    console.log("dblclick");
  });
```

**Version**
4.4

**Additional context**
focusChange에 setSelectionRange을 적용할 경우 위 스크린샷 1번 처럼 처음에 셀렉트 영역이 지정도지만 같은 셀 영역을 다시 클릭 시 2번 처럼 셀렉트 영역이 사라집니다. 혹시 셀렉트 영역을 유지할 방법이 있을까요?
또한 focusChange에 setSelectionRange을 적용할 경우 dblclick이 정상적으로 동작하지 않습니다.
지난 질문에서 https://github.com/nhn/tui.grid/issues/567#issuecomment-516741553
focusChange에 setSelectionRange 사용방법을 알려주셨었는데 이렇게 사용하는게 아닌가요?

**Comment by js87zz** [comment]
@haruharmony 
이전 이슈에서 말씀드렸듯이 `그리드 내에 영역을 클릭하면 셀렉션 영역이 해제된다`가 현재의 스펙이고, 이 스펙은 포커스 셀의 변경과는 무관합니다. 이러한 기준이 없다면 셀렉션을 해제할 방법이 API를 통해 해제하는 방법밖에 없기때문에 이러한 기준을 만들었고, 이는 다른 상용 그리드에서도 보편적으로 적용되고 있습니다. 
우선 셀이 포커스된 경우 셀렉션이 되어야만 하는 이유가 정확이 무엇인지 알 수 있을까요?

**Comment by haruharmony** [comment]
@js87zz

셀이 포커스된 경우 셀렉션이 되어야만 하는 이유.
현재 셀을 클릭했을 경우 하나의 셀만 셀렉션됩니다. 저는 셀을 클릭했을 때 로우를 전체를
셀렉션영역으로 잡아서 해당 로우가 선택되었다고 사용자에게 알려주기 위해 이 기능이 필요합니다.
해당 관련 질문을 하였고 https://github.com/nhn/tui.grid/issues/567#issue-471575909 에서 포커스를 통한 셀렉션을 추천받았기에 이 방법에 관련하여 문의드리고 있습니다.

'그리드 내에 영역을 클릭하면 셀렉션 영역이 해제된다' 의 경우는 그리드 내의 다른 셀을 클릭 했을
경우에는 셀렉션이 해제되지만 같은 셀을 클릭하였을 땐 유지됩니다.
때문에 현재 올린 이슈에서도 같은 셀을 클릭했을 경우에 선택된 로우 영역이 유지되었으면 합니다.

**Comment by js87zz** [comment]
@haruharmony 
해당 로우가 선택된 것을 알려주고 싶은 경우, 셀렉션을 이용하여 하이라이팅을 하는 것은 기능의 의도와는 맞지 않는 것 같습니다. 셀렉션은 필요한 영역을 선택하여 셀의 내용을 복사하거나 붙여넣기 하는 의도로 만들어진 기능이라, 하이라이팅을 위함이라면, CSS로 풀어내는 것이 맞을 것 같습니다. 이 두 가지 동작을 분리하는 것이 사용성에 있어서도 충돌없이 좋을 것 같구요. 
아래 예제처럼 className을 추가하는 API를 이용하여 하이라이팅을 추가하시면 될 것 같습니다. 문의주신 내용의 목적과 정확한 의도를 몰랐기 때문에 기존 가이드 사항이 오히려 혼란을 드린 것 같네요. 감사합니다! :)

```js
let selectedRowKey = null;
grid.on('focusChange', ev => {
  if (selectedRowKey) {
    grid.removeRowClassName(selectedRowKey, 'someClassName');
  }
  selectedRowKey = ev.rowKey;
  grid.addRowClassName(selectedRowKey, 'someClassName');
});
```

**Comment by haruharmony** [comment]
감사합니다 해결했습니다!
