### ISSUE TITLE
grid.getModifiedRows() 시 createdRows 결과값 활용법

### ISSUE THREAD

**Issue by hwasalko** [nhn/tui.grid#634]
**Summary**

appendRow()를 통해 행추가 후
데이터를 입력하고 'grid.getModifiedRows()' 를 호출해보면 아래 3가지 엘레멘트가 반환됩니다.

- createdRows
- deletedRows
- updatedRows

세가지 중 deletedRows, updatedRows 는 값이 잘 반환되지만, createdRows의 경우 입력한 데이터 값은 넘어오지 않는 것으로 추정됩니다.(아래 첨부이미지 참조)

위와같이 rowKey, rowSpanMap, sortKey, uniqueKey 가 반환되는것이 맞는지? 
아니면 다른 function을 호출해야 하는지 문의 드립니다.
(입력한 값을 서버로 전송하여 DB에 저장하려 합니다.)

**Screenshots**
![캡처](https://user-images.githubusercontent.com/16667071/63818396-d1d3f480-c97b-11e9-9078-927fd6fcf1c7.JPG)

**Version**
4.4.0

**Comment by hwasalko** [comment]
참고로, 아래와 같이 첫번째 파라미터(data)를 넘겨주니 createdRows 엘레멘트에 값이 잘 담겨오네요.
(반드시 이렇게 호출해야 한다면, 약간의? 불편함이 있긴 하네요)

`
grid.appendRow(
  {  
     id : "",  
     city : "",  
     ... 
  } 
)
`

**Comment by js87zz** [comment]
@hwasalko 
테스트 결과 빈 행을 추가하여도 `createdRows`에 잘 담겨오네요. 소스를 첨부해주셔야 정확한 답변이 가능할 것 같습니다.

**Comment by js87zz** [comment]
@hwasalko 
`createdRows`에 데이터는 담기는데 컬럼 필드 값들은 넘어오지 않는 점을 질문 주신 것 같은대요. 현재로서는 내부적으로 구현이 안되어 있는 상태라 댓글로 남겨주신 사항처럼 사용하셔야될 것 같습니다. 사용성을 위해 추가하여 추후 배포되면 공지하도록 하겠습니다. 감사합니다 :)

**Comment by hwasalko** [comment]
@js87zz
말씀과 같이 '컬럼필드값들이 넘어오지 않는 점' 이 맞습니다. 우선은 위와같이 우회하여 사용토록 하겠습니다.
덕분에 좋은 S/W 잘 사용하고 있습니다. 감사합니다^^

**Comment by js87zz** [comment]
@hwasalko 
## bug
the value is not inserted for each column when appends the empty row
## fixed
fixed in v4.6.0(#707)
