### ISSUE TITLE
4.4.1 useViewmode 사용가능여부

### ISSUE THREAD

**Issue by yealbae** [nhn/tui.grid#638]
아래와 같은 코드로 작성하여 적용하였는데.
useViewMode : false 로 설정시 input 영역이 바로 보이지 않습니다.
혹시 4.4.1 버전에서는 없어진 기능인지요??

혹 대체 가능 기능이 있는지요?

```js
{
  header:'계약상태',
  name:'cdCntrSttsNm',
  width:'180',
  sortable:true,
  editor :{
    type: CustomTextEditor,
    editOptions: {
      type: CustomTextEditor,
      useViewMode: false
    }
  }
}
```

**Comment by jung-han** [comment]
안녕하세요.
`useViewMode`는 4.0 버전에서 제거되었으며 커스텀 렌더러로 동일한 동작을 구현할 수 있습니다.
하단 링크에서 마이그레이션 가이드를 참고해주시면 감사하겠습니다.

* https://github.com/nhn/tui.grid/blob/production/docs/v4.0-migration-guide-kor.md#columnseditoptions-%EC%98%B5%EC%85%98

**Comment by yealbae** [comment]
useViewMode 모드가 클릭없이 input을 활성화 시키는 것으로 알고 있는데요.
알려주신 마이그레이션 가이드 부분에는 커스텀 렌더러 로 가능하다.
만 나와 있고 적당한 가이드는 없는것 같네요.

가이드는 없을까요?

**Comment by KihwaLee** [comment]
> useViewMode 모드가 클릭없이 input을 활성화 시키는 것으로 알고 있는데요.
> 알려주신 마이그레이션 가이드 부분에는 커스텀 렌더러 로 가능하다.
> 만 나와 있고 적당한 가이드는 없는것 같네요.
> 가이드는 없을까요?

혹시 해당 건 해결하셨을까요?  저도 찾고 있는데 가이드가 부족해서 난감하네요..

**Comment by flyskyne** [comment]
@yealbae 
저도 검토 중에 해당 기능이 필요하여 대강 만들어보았습니다.
https://jsfiddle.net/2bpygz9f/1/

@jung-han 
마이그레이션 안내에 원래 제공되던 기능에 대한 대체 구현 쯤은 참고 코드로 넣어주셔도 좋았을 것 같네요...
