### ISSUE TITLE
그리드 내 date-picker 사용 시 아이콘 노출 여부

### ISSUE THREAD

**Issue by unique-jj** [nhn/tui.grid#641]
## Version
version 4.4.1

## Development Environment
OS

## Current Behavior

```js
var grid = new tui.Grid({
  el: document.getElementById('grid'),
  scrollX: false,
  showDummyRows: false,
  bodyHeight: 340,
  rowHeight: 40,
  heightResizable: false,
  virtualScrolling: true,
  selectionUnit: 'row',
  data: gridData,
  columns: [
    {
      title: 'birth',
      name: '생년월일',
      editor: {
        type: 'datePicker',
        options: {
          selectableRanges: [[new Date(2014, 3, 10), new Date(2014, 5, 20)]]
        }
      }
    }
  ]
});
```

## Expected Behavior

안녕하세요.
그리드 내 데이터피커 사용 관련해 문의 드립니다.

//현재작업요약 
그리드 row에 데이터피커 적용 시 인풋박스와 캘린더 노출 지원되지만 아이콘 지원이 안되고 있습니다.
https://nhn.github.io/tui.date-picker/4.0.0/tutorial-example01-basic 참고하여
formatter로 html을 강제로 적용했을시 디자인형태는 나오지만 기능이 작동하지 않습니다. 

//원하는결과 : 아이콘 노출
https://nhn.github.io/tui.date-picker/4.0.0/tutorial-example01-basic 에서
html "<span class="tui-ico-date"  /span>" 처럼
![image](https://user-images.githubusercontent.com/49803637/63935724-0be6e880-ca99-11e9-968c-cc8a23b37729.png)
이런 형식으로 span 아이콘이 노출되길 원하는데 가능한지 가능하다면 어떤방식인지 문의드립니다.

이와 같은 맥락으로 콤보박스도 궁금합니다.
![image](https://user-images.githubusercontent.com/49803637/63936315-7e0bfd00-ca9a-11e9-9962-d54b622b5416.png)

**Comment by jung-han** [comment]
@unique-jj 안녕하세요.
현재 데이트피커 아이콘은 옵션을 통해 보여주는 방식으로 개발 될 예정입니다.(v4.6.0 이후에 포함 될 예정입니다.) 

콤보 박스의 경우 디폴트로 내장 되어있는 'select'를 사용하는 것은 어떠신가요?
* 내장 에디터 튜토리얼: https://github.com/nhn/tui.grid/blob/production/docs/ko/custom-editor.md#%EB%82%B4%EC%9E%A5-%EC%97%90%EB%94%94%ED%84%B0
* 만약 스타일을 입히기 위한 목적으로 사용하신다면 [`custom editor`](https://github.com/nhn/tui.grid/blob/master/docs/ko/custom-editor.md)를 이용해서 개발하셔야 할 것 같습니다.

**Comment by jung-han** [comment]
@unique-jj 해당 내용은 4.6.0에 포함되어 배포될 예정입니다!
