### ISSUE TITLE
grid creation error 문의

### ISSUE THREAD

**Issue by aimhigh123** [nhn/tui.grid#642]
3.x 버전 사용하다가 4.5.0으로 업그레이드 작업중인데
다음과 같은 grid creation error가 발생하네요.

**Uncaught TypeError: parent.appendChild is not a function
    at diff (tui-grid.js:965)
    at Module.render (tui-grid.js:1458)
    at new Grid (tui-grid.js:5759)**

소스코드는 다음과 같습니다.

	var grid = new tui.Grid({
		el: gridPanel,
		columns: [{
			header: 'DUMMY',
			name: 'dummy',
			editor: 'text'
		}],
		scrollX: false,
		scrollY: false,
		minBodyHeight: 40,
		rowHeaders: [{
			type: 'rowNum',
			header: 'No.'
		}],
		usageStatistics: false
	});

그리고,
실행 중 동적으로 컬럼을 생성할 필요가 있어
일단 grid 생성 후 setColumns 를 이용하여 컬럼을 설정하려고 하는데
grid 생성시 위 코드와 같이 columns 옵션에는 임의의 컬럼(dummy)을 설정하고
이후 setColumns 로 원하는 컬럼들을 생성하면 되는지요?
(이전 버전과 달리 4.x에서는 columns 옵션이 필수가 된 거 같아서요..)

**Version**
4.5.0

**Comment by js87zz** [comment]
@aimhigh123 
말씀해주신 사항만으로는 에러 재현이 안되네요. 더 구체적인 소스를 첨부해주셔야 확인이 될 것 같습니다.
`columns` options 같은 경우는 v4.x 부터는 필수 옵션으로 변경되었습니다. 컬럼 정보가 가변적인 상황이라면 말씀하신 것처럼 빈 배열이나 dummy column을 설정하신 후, `setColumns`로 컬럼을 설정하시면 됩니다.

**Comment by aimhigh123** [comment]
@js87zz 
다시 살펴보니, el 값을 function parameter로 전달받는 과정에서 문제가 있었네요.
해결되었습니다. 감사합니다.
