### ISSUE TITLE
toast-ui.react-grid column 각각 width 조정

### ISSUE THREAD

**Issue by athilog** [nhn/tui.grid#643]
editOptions: { type: "text", width: 100 }
현재 이렇게 옵션을 주고
grid.current.getInstance().refreshLayout(); 을 해봤지만 사이즈 조절이 되지 않습니다.

어떻게 하면 사이즈 조절을 할 수 있을 까요?

**Comment by jung-han** [comment]
@athilog 
현재 사용중이신 react-wrapper의 버전을 명시해 주셔야 답변이 가능할 것 같습니다.
이후에는 이슈 템플릿을 지우지 말고 작성해주시면 감사하겠습니다.

**Comment by athilog** [comment]
버젼은 ^1.0.0 입니다.
