### ISSUE TITLE
특정 컬럼의 텍스트 색상변경 

### ISSUE THREAD

**Issue by yealbae** [nhn/tui.grid#646]
**Summary**
특정컬럼의 글짜색을 변경하고 싶습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/16408961/64094879-1e626a00-cd98-11e9-97a3-169eb461d3e4.png)

**Version**
4.4.1

**Additional context**
안녕하세요

특정컬럼의 텍스트 색상을 변경 할 수 있는 방법이 있을까요?
addCellClassName 이라는 펑션을 이용해서 바꿀수 있다는것 같은데..
정확히 어떻게 조치하면 되는지 잘 모르겠네요.

도움 부탁드립니다.

**Comment by js87zz** [comment]
@yealbae 
아래 2가지 방법으로 설정이 가능합니다. 감사합니다 :)

1. data option 정의 시 설정
```js
const gridData = [
    {
      name: 'Lee',
      age: 30,
      _attributes: {
        className: {
          column: { name: ['someClassName'] }
        }
      }
    },
    {
      name: 'Park',
      age: 20,
      _attributes: {
        className: {
          column: { name: ['someClassName'] }
        }
      }
    }
    // ...
];

const new Grid({
  data: gridData, 
  // ...
});
```
2. addCellClassName API
```js
grid.getData().forEach(row => {
  grid.addCellClassName(row.rowKey, 'name', 'someClassName');
});
```
