### ISSUE TITLE
리로드 시 체크박스의 체크 값들을 그대로 유지할 수 있나요 ?

### ISSUE THREAD

**Issue by dyWe2216** [nhn/tui.grid#649]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

차트에 보면 체크박스가 있는데, 리로드 시 체크박스의 체크 유무 값들을 유지할 수 있는 방법이 없을까요 ? 현재 미구현된건지 궁금합니다.

그리고 가로축의 데이터가 길 경우 .. 줄여서 보여주는 그런 옵션은 따로 없을까요 ?

**Comment by js87zz** [comment]
@dyWe2216 
차트 관련된 문의는 차트 이슈에 문의해주세요.(https://github.com/nhn/tui.chart/issues)
해당 이슈는 클로즈 하겠습니다~
