### ISSUE TITLE
CustomEditor input focus 사용 관련 질문 드립니다.

### ISSUE THREAD

**Issue by zzdd1558** [nhn/tui.grid#654]
현재 cell내부를 customEditor를 사용하여 
input el에 focus가 맞춰지면 button을 show 하게 하는 div를 구성하고있습니다.
현재 tui.grid 최신버전을 사용하고 있습니다.

click 등등은 먹는데 focus를 주니 이벤트가 처리되지 않습니다 .

어떻게 해결해야할지 힌트 얻어볼수 있을까요 
다른 getElement , getValue등등 메서드들은 제외 하였습니다 . 

class CustomTextEditor {
    constructor(props) {

      let div = document.createElement(`div`);
      let input = document.createElement(`input`);

      div.addEventListener('focus' , ()=> {
        console.log('div focus')
      } , true)

      input.type="text";
      input.value = String(props.value);
      input.addEventListener(`focus` , function(){
        console.log("input focus")
      });

      let button = document.createElement(`button`);
      button.addEventListener(`click` , function(){
        alert("button")
      });
      div.appendChild(input);
      div.appendChild(button);

      this.el = div;
    }
    ...
}

**Comment by js87zz** [comment]
@zzdd1558 
올려주신 소스상에서 `div` 블록 엘리먼트에 캡처링 이벤트 리스너를 추가한 부분은 불필요해보이고, 이외에는 `focus` 이벤트를 걸어도 정상 동작할 것 같고 이상이 없어보이네요. 정확한 현상에 관련된 스크린 샷이나 관련된 소스가 없다면 답변 드리기 어려울 것 같습니다.
해당 질문은 답변드리겠지만, 내부적인 커스터마이징 소스 가이드까지는 저희가 하고 있지 않습니다. 앞으로 이 부분 양해 부탁드리겠습니다.

**Comment by zzdd1558** [comment]
@js87zz  
넵 답변 감사합니다!
