### ISSUE TITLE
Column header renderer 기능 요청

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#657]
## Version
4.5.1

## Development Environment
무관

## Current Behavior
Column header 에 단순 String 말고도 Customizing 이 필요합니다.
따라서 기존에 editor 옵션이나 renderer 옵션처럼
renderer 가 있으면 좋을 것 같습니다.

## Expected Behavior

**Comment by js87zz** [comment]
@ryum91 
Column header 관련하여 몇몇 옵션 추가는 고려하고 있으나, renderer나 editor 처럼 커스터마이징 가능하도록 확장할 계획은 없습니다. 이미 넓이, 높이, 배경색, 텍스트 정렬과 같은 부분은 옵션 설정으로 커스터마이징 가능하구요. 이외에 다른 부분이 커스터마이징이 필요하다면 정확히 어떤 용도로 무엇을 위해 필요한지 설명 부탁드리겠습니다.

**Comment by ryum91** [comment]
Header 부분에 별도 DOM 을 추가해서 추가적으로 표현하고자 했던 부분이 존재합니다.
(ex. header에 대한 설명이나 Custom Filtering 등..)

당장 꼭 필요한 기능은 아니지만
이 외에도 다양하게 활용할 수 있지 않을까 싶어서 의견 드렸습니다!
감사합니다.

**Comment by js87zz** [comment]
@ryum91 
필터링 관련 기능은 별도로 개발 진행 중으로 따로 제공될 예정입니다. 이외에 다른 커스터 마이징이 필요한 옵션추가에 대해서는 검토해보겠습니다. 감사합니다 :)

**Comment by js87zz** [comment]
@ryum91 
해당 이슈는 feature 이슈로 확정되었으니 클로즈하겠습니다. 관련 내용을 #759 를 참조해주세요 :)
