### ISSUE TITLE
datasource를 사용하여 그리드에 데이터 로딩 문의드려요

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#666]
최신버전 toast grid를 쓰려고 합니다
검색 조건 데이터를 가지고 request해서 서버에서 데이터를 불러와서 그리드에 로딩하고 싶은데
datasource  예제나 api를 아무리 봐도
서버로 data를 보내는 부분이 없더라구요
그리드내의 데이터말고 다른 영역의 searchform 같은 form안의 데이터를 검색조건으로 넘겨서 그 조건에 맞는 데이터를 가져와서 뿌릴 방법은 없나요?

**Comment by jung-han** [comment]
@higamza 안녕하세요. 말씀해주신 필터링 기능은 개발 예정중인 기능으로 현재는 제공되지 않고 있습니다.
대신 검색시 가져온 데이터를 [resetData API](https://nhn.github.io/tui.grid/latest/Grid#resetData) 로 데이터를 다시 할당해주는 방식으로 구현해 보시는건 어떤가요?

**Comment by higamza** [comment]
> @higamza 안녕하세요. 말씀해주신 필터링 기능은 개발 예정중인 기능으로 현재는 제공되지 않고 있습니다.
> 대신 검색시 가져온 데이터를 [resetData API](https://nhn.github.io/tui.grid/latest/Grid#resetData) 로 데이터를 다시 할당해주는 방식으로 구현해 보시는건 어떤가요?

알려주신 function으로 해결 했습니다. 도움 감사합니다 ^^
