### ISSUE TITLE
(vue) setPerPage 호출 시  페이지네비게이션 구성 버그

### ISSUE THREAD

**Issue by lng0415** [nhn/tui.grid#667]
**Describe the bug**
setPerPage 호출 시 버그
```
<template>
  <div>
    <div @click="perPage">클릭클릭</div>
    <grid ref="tuiGrid"
      :data="gridProps.data"
      :columns="gridProps.columns"
      :options="gridProps.options"
      @successResponse="successResponse"
    />
  </div>
</template>

<script>
import 'tui-grid/dist/tui-grid.css'
import 'tui-pagination/dist/tui-pagination.css';
import { Grid } from '@toast-ui/vue-grid'

export default {
  components: {
    'grid': Grid
  },
  data() {
    return {
      instance: null,
      gridProps: null
    }
  },
  created() {
    this.gridProps = {
      data: {
        api: {
          readData: { url: '/api/brand', method: 'GET' },
        }
      },
      options: {
        pageOptions: {
          perPage: 1
        }
      },
      columns: [
        { name: "no", header: "No", align: "center" },
        { name: "nm", header: "이름", align: "center" }
      ]
    }
  },
  methods: {
    perPage: function() {
      this.$refs.tuiGrid.invoke("setPerPage", 5);
      //  this.instance.setPerPage(5);
    },
    successResponse: function(event) {
      if (this.instance == null) {
        this.instance = event.instance;
      }
    }
  }
}
</script>
```

**To Reproduce**
1페이지에서 setPerPage로 페이지당 개수 변경 시 페이지네비게이션이 재구성 되지 않아요.

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/50689646/64929979-37265180-d867-11e9-926b-cd49ffeac87c.png)
현재 페이지당 1개, 총 12건이 존재, 12페이지로 구성되어 있습니다.

![2](https://user-images.githubusercontent.com/50689646/64929990-4e653f00-d867-11e9-8d91-04717d810636.png)
페이지 당 5건으로 setPerPage 호출 시 페이지 당 5개로 구성되었으나
페이징은 3페이지로 변경되지 않습니다.
이 때 다른 페이지로 이동하게 되면 3페이지로 재구성 됩니다.

(단, 1페이지 이외의 페이지로 이동 후 setPerPage를 호출하면 위 문제는 발생하지 않습니다)

그리드 버전: [tui for vue 2.0.1](https://github.com/nhn/toast-ui.vue-grid)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Whale
 - Version: 1.6.81.16 (64-bit)

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser -
 - Version -

**Additional context**
Vue에서는(위 코드) noData를 어떻게 변경할 수 있나요?
검색 수행 시 데이터가 없을 경우 변경코자 합니다.
```
setLanguage("ko", { display: { noData: "검색 결과가 없습니다." } });
```

**Comment by js87zz** [comment]
@lng0415 
제보 감사합니다. `setPerPage()` API 관련 버그는 수정하여 다음 배포에 반영될 예정입니다.
다국어는 아래처럼 변경하시면 될 것 같습니다.

`this.$refs.tuiGrid.setLanguage('ko',{ display: { noData: "검색 결과가 없습니다." } });`

감사합니다.

**Comment by lng0415** [comment]
@js87zz 
해당 코드로 했을 때 안되어서 문의드렸습니다. ^^;
```
search: function(param) {
  // 검색 시 안내 문구 변경
  //this.$refs.tuiGrid.invoke("setLanguage", "ko", { display: { noData: noSearchStr } });
  this.$refs.tuiGrid.setLanguage("ko", { display: { noData: noSearchStr } });
  // 데이터 검색
  this.instance.readData(1, param, true); // no data
}
```
위와 같이 했을 때 noSearchStr의 값이 아닌 초기 설정된 값이 노출됩니다.

```
      options: {
          ......
      }, 
      language: {
        name: "ko",
        value: {
          display: {
            noData: "데이터가 없습니다."
          }
        }
      },
      ....
'''

**Comment by js87zz** [comment]
@lng0415 
다시 확인해보니 vue wrapper의 `setLanguage`는 `language` props를 바라보고 변경이되네요. 아래처럼 그리드 props로 language 객체를 넘겨야 제대로 동작할 것 같고 `setLanguage` API는 호출할 필요가 없을 것 같습니다. `setLanguage` API는 인자를 받아 동작하게끔 개선이 필요해보이네요. 감사합니다!
```js
language: {
  name: 'ko',
  value: { display: { noData: noSearchStr } }
}
```

**Comment by lng0415** [comment]
@js87zz 
```
this.$refs.tuiGrid.language.value.display.noData = noSearchStr;
this.$refs.tuiGrid.setLanguage();
```
답변 중 props를 바라본다는 것을 보고 먼저 props를 고치고 setLanguage를 호출하니 반영이 되네요~!
추후 api 개선을 해 주시면 더할나위 없을 것 같습니다!

좋은 그리드 제공 해 주셔서 감사합니다 :D

**Comment by js87zz** [comment]
@lng0415 
`setPerPage` API 관련 버그는 `v4.6.0`에서 수정 배포되었습니다. 그리고 문의주셨던 `setLanguage` API 같은 경우는 기존 vue-wrapper 에서의 사용성이 문제가 있어 추후 `deprecated`될 예정입니다. `setLanguage` 자체가 grid 내에서 `static` method 이기 때문에 직접 접근하여 사용하는 것으로 변경하여 가이드하고 있습니다. 아래 링크를 참조해주세요 :)
https://github.com/nhn/toast-ui.vue-grid#static-methods
