### ISSUE TITLE
그리드 전체에 edit mode를 설정할 수 있나요?

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#675]
그리드 전체에 edit mode를 설정하고 싶어요
appendRow 했을때 셀을 클릭하지 않아도 edit mode로 보이게 하려고 하는데 editingEvent 옵션은 봤는데
클릭없이 바로 edit 모드로 보이는 옵션은 못찾아서 문의드립니다

**Comment by js87zz** [comment]
@higamza 
개인 게시판이 아니기때문에 질문은 정리해서 한 가지 이슈로 올려주시면 감사하겠습니다. 그리고 이슈 템플릿을 지우지 말고 양식에 맞게 작성해주셔야 정확한 답변이 가능하니 꼭 준수해주세요~! 올려주신 이슈들은 우선 모두 클로즈할테니 다시 작성 부탁드리겠습니다.
