### ISSUE TITLE
그리드의 keyColumnName 속성이 잘 적용되지 않아요

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#678]
**Summary**
현재 ajax로 서버로 부터 가져온 데이터를 grid.resetData 함수를 이용해서
grid에 데이터를 rendering 하는 구조입니다.

keyColumnName : 'mainId' 이런식으로 그리드 옵션을 줬더니 
rowKey가 'NaN'으로 표시됩니다.

**Screenshots**

**Version**
toast-ui-grid 4.5.2

**Additional context**
1. 그리드의 셀에 버튼을 넣으려면 커스텀 렌더 예제를 참조해서 구현해야 하는지 궁금합니다.

2.  그리드 속성중 keyColumnName 을, keyColumnName : 'mainId' 이런식으로 설정하면
rowKey가 해당 컬럼의 값으로 지정된다고 다른 문의글에서 봤는데요
rowKey가 해당 컬럼의 값으로 지정되지 않고 'NaN'으로 표시됩니다.
keyColumnName 을 지정하는 방법이 다른건가요?

3. 그리드의 옵션중 editingEvent 를 'click'로 지정해서 single click으로 그리드의 셀이 edit로 변경은 되는데
그리드 전체 옵션을 edit mode로 해서 클릭없이도 모든 셀이 edit mode로 될 수 있는 방법이 혹시 있을까요?

**Comment by js87zz** [comment]
@higamza 
아래에 질문사항에 대한 답변 남깁니다.

1. 말씀하신 것처럼 커스텀 렌더러 예제를 참조하여 버튼을 렌더링하도록 하시면 됩니다.
 
2. 현재 그리드는 rowKey는 숫자 또는 숫자로 변환이 가능한 값이라 가정하고 동작하고 있습니다. (이 부분에 대해서는 그리드 가이드 설명이 조금 부족하기도 하고 개선이 필요해보이네요) keyColumnName도 숫자 또는 숫자값을 가진 컬럼으로 지정해주시는게 좋을 것 같습니다. (지정하지 않는 경우는 index와 동일하게 rowKey가 생성됩니다)

3. 클릭 없이 모든 셀이 기본적으로 에디팅 모드로 활성화되는 기능은 제공하고 있지 않습니다. 구현을 위해서 커스텀 렌더러로 자체 구현하셔야될 것 같습니다.

감사합니다 :)

**Comment by higamza** [comment]
답변 감사합니다 ^^
