### ISSUE TITLE
grid 컬럼의 값을 수정나서 getValue에서 값을 가져오지 못하는 문제 문의

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#682]
**Summary**
grid 컬럼의 값을 수정하고나서 수정한 컬럼의 edit mode가 해제되기 전에는 
getValue 함수에서 값을 가져오지 못하고 있어요

**Screenshots**

**Version**
toast ui grid 4.5.2

**Additional context**
1. grid 컬럼의 값을 수정하고나서 저장 버튼 클릭시 
마우스가 다른 버튼을 클릭했는데도
grid의 컬럼은 계속 edit mode 상태로 있다보니
저장 버튼 click 함수에서 getValue 로 수정한 컬럼의 값을 가져오려해도 빈값만 가져옵니다.
강제로 컬럼의 edit mode를 해제할 방법이 있을까요?

2. 컬럼값에 따라 radio, checkbox 를 선택하게 하고 싶은데 그리드안에 조건문을 사용해서 속성들을 선택할 수 있을까요?
예를 들면 
editor : { type: atype == 'R' ? 'radio' : 'checkbox'
이렇게요

그리고 컬럼필드 지정때도 아래처럼 할 수 있을까요?
예를 들면 name : aid == '1' ? 'bname' : 'cname' 이런 식으로요.

**Comment by jung-han** [comment]
@higamza 
1. 버튼을 눌러 에디팅 결과가 반영되어야 한다는 의미로 해석됩니다. 그렇다면 [finishEditing](https://nhn.github.io/tui.grid/latest/Grid#finishEditing) API를 참고해주시면 감사하겠습니다.

2. 컬럼 값에 따라 다르게 한다는 말씀은 셀 내용에 따라 달라진다는 말씀이신가요? 해당 내용으로는 어떤 이슈인지 파악하기 어려운 것 같습니다.

**Comment by higamza** [comment]
넵 셀 내용에 따라 셀에 컬럼을 지정할 수 있나해서요
ex) {header : 'test', name : sortType == 'A' ? aList : outerList}

만약 sortType이 A이면 서버에서 가져온 데이터들 중 aList 에 담긴 값들을 표시하고
그렇지 않으면 otherList 에 담긴 값을 표시하고 싶어서요

3. 그리고 혹시 셀에 tooltip 기능도 custom render로 가능할까요? 
<td title='aaa'></td> td의 title 속성이 제공 하는 것과 같은 기능이요

**Comment by js87zz** [comment]
@higamza 
1. 우선 그리드 외의 셀을 클릭하는 경우에는 편집 중인 셀이 비활성화되지 않습니다. 이 부분은 그리드 사용성을 위한 스펙이구요. 이런 이유 때문에 그리드 외의 버튼을 클릭했을 때 편집상태가 유지되는 것은 정상 동작입니다.
원하는 동작은 버튼을 눌렀을 경우, `편집이 완료되고, 값을 가져온 후 포커싱을 제거한다.` 같은대요. 이런 경우는 아래처럼 사용하시면 될 것 같습니다. 다만 현재 `finishEditing` API가의 value 인자가 필수값이기 때문에 value값이 없는 경우도 사용가능하도록 개선이 필요할 것 같네요. 이 부분은 다음 버전에 반영되면 정상 동작할 것 같네요
```js
btn.addEventListener('click', () => {
  grid.finishEditing(0, 'columnName', 'value');
  console.log(grid.getValue());
  grid.blur();
});
```
2. 처음 한 번만 조건문에 의해 값이 들어가고 동적으로 변하진 않습니다. 해당 부분은 직접 핸들링하셔야 될 것 같네요.
3. 툴팁 구현은 커스텀 렌더러를 통해 구현하시면 될 것 같습니다.

**Comment by js87zz** [comment]
@higamza 
## bug
the previous editing cell should be destroyed in case of calling finishEditing, startEditing API in a row.
## fixed
fixed in v4.6.0(#702)
