### ISSUE TITLE
startEditing 함수 사용시 이전 셀의 값이 복사되는 오류

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#686]
**Describe the bug**
그리드에 appendRow 함수로 row를 추가하고 startEditing 함수로 새로 추가된 row의 특정 셀에 editing을 설정하면 이전 row의 수정한 셀의 값이
새로 추가된 row의 셀에 복사되어 표시되는 문제

**To Reproduce**
1. 추가 버튼을 생성하고 추가 버튼 클릭시 대상 그리드에 행이 추가되게 한다
추가버튼 클릭시에 아래의 코드를 실행한다
var row = {mainId: '', mainTitle: ''}
grid.appendRow(row);
var gridCnt = grid.getRowCount();
grid.startEditing(gridCnt-1, 'mainId', true);

2. 위의 코드 수행시 새로 추가된 row의 mainId 컬럼에 이전 row의 mainId 값이 복사되어 들어가는 에러 발생

**Expected behavior**
행이 추가되고 추가된 행의 지정한 셀이 edit 상태로 활성화된다

**Screenshots**
![image](https://user-images.githubusercontent.com/4151146/65388958-c82b8a00-dd8b-11e9-8683-37d5b206a99c.png)

**Desktop (please complete the following information):**
 - OS: window 7
 - Browser : chrome
 - Version : 65.0....

**Additional context**

**Comment by js87zz** [comment]
@higamza 
말씀하신 것처럼 모두 빈 값으로 새로운 로우를 추가하고 eiditing했을 때 재현해보면, 정상 동작하는대요.
혹시 mainId를 keyColumnName으로 사용하고 계시나요?

**Comment by higamza** [comment]
음 아닙니다. mainId를 keyColumnName으로 사용하고 있지 않습니다.
mainId 셀에 값을 입력하고 바로 Add 버튼을 클릭하면(mainId를 수정하고 다른 셀의 편집없이 바로 Add 버튼 클릭으로 row를 추가하고 startEditing 할 경우)
이전 row의 mainId 셀의 값이 새로 추가된 row에 복사되어 표시됩니다

**Comment by higamza** [comment]
mainId를 keyColumnName으로 사용하고 있지 않습니다.
전체소스를 올려봅니다.
테스트 절차입니다.
1. 아래 소스를 크롬에서 열어주세요
2. ADD 버튼을 클릭해서 새로 추가된 row의 첫번째 컬럼에 'aa'를 입력해 주세요
=> 다른 셀로 이동해서 값을 입력한다거나 하는 action 없이 첫번째 셀에 값을 입력하고나서 바로
바로 ADD 버튼을 클릭해주세요
(첫번째 셀에 값을 입력한 후에 focus 이동없이 바로 ADD 버튼을 클릭하셔야 합니다)
3. 바로 ADD 버튼을 클릭해주세요
================
위의 절차대로 수행하면, add 버튼을 클릭해서 추가된 새로운 row의 첫번째 컬럼에 이전 컬럼의 값이 복사되어 있는 것을 확인하실 수 있습니다.
심지어 이전 컬럼이 select (combobox)일 경우 그 형태까지 복사되는 현상도 있습니다.

전체소스는 아래와 같습니다.

<!doctype html>
<html lang="en">
 <head>
 <meta charset="UTF-8">
<link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
 <title>Document</title>
 <script>
 function fnTest(){
	 alert('button test');
}
 function addRow(){
	 var row ={
      c1: '',
      c2: '',
      c3: 1
    }
	grid.appendRow(row);
	var gn =  grid.getRowCount();
	grid.startEditing(gn-1, 'c1', true);
 }
 </script>
</head>

<body>

 <p>grid test</p>
 <button id="addBtn" onclick="addRow();">ADD</button>
  <div id="grid"></div>
<script>
  var Grid = tui.Grid;
  class CustomButtonRenderer {
		constructor(props) {
			const el = document.createElement('input');
			const { value, onclick } = props.columnInfo.renderer.options;

			el.type = 'button';
			el.value = String(value);
			el.addEventListener('click', (ev) => {
			  fnTest();
			});

			this.el = el;
			this.render(props);
		}

		getElement() {
			return this.el;
		}

		render(props) {
			//this.el.value = value;
			//this.el.onclick = fnTest();
		}
	}
	const gridData = [
    {
      c1: '100013',
      c2: 'Mustafa Cosme',
      c3: 291232
    },
    {
      c1: '201212',
      c2: 'Gunnar Fausto',
      c3: 32123
    }
  ];

  const grid = new tui.Grid({
    el: document.getElementById('grid'),
    scrollX: false,
    scrollY: false,
    rowHeight: 35,
	data: gridData,
    rowHeaders: ['rowNum'],
    header: {
      height: 40
    },
    columns: [
      {
        header: 'ID',
        name: 'c1',
		editor : 'text'
      },
      {
        header: 'Name',
        defaultValue: 2,
        name: 'c2',
		editor : 'text'
      },
      {
        header: 'Score',
        name: 'c3',
		renderer: {
					type: CustomButtonRenderer,
					options: {
						value: 'link',
						onclick: 'fnTest()'
					}
				}
      }
    ]
  });

 </script>
</body>
</html>

**Comment by js87zz** [comment]
@higamza 
어떤 현상인지 확인했습니다. 제보 감사합니다 :)

**Comment by js87zz** [comment]
@higamza 
## bug
the previous editing cell should be destroyed in case of calling finishEditing, startEditing API in a row.
## fixed
fixed in v4.6.0(#702)
