### ISSUE TITLE
그리드 숫자로만 이루어져있는 컬럼 정렬시 오류

### ISSUE THREAD

**Issue by kuckjwi0928** [nhn/tui.grid#687]
**Describe the bug**
그리드 정렬 시 데이터가 숫자로만 이루어져있을 경우 정상적으로 정렬이 되지 않음

**To Reproduce**
1. 숫자로만 구성된 컬럼 및 데이터 셋팅
2. 정렬 기능 활성화
3. 정렬

**Expected behavior**
숫자순으로 정렬이 되야하지만, 문자열로 인식하여 201 11 형식으로 정렬이 되는현상

**Screenshots**
![2019-09-22 15-20-39 2019-09-22 15_22_38](https://user-images.githubusercontent.com/20429567/65383215-d6a68100-dd4c-11e9-9fd2-59b460f3bebf.gif)

**Desktop (please complete the following information):**
 - OS: `Mac`
 - Browser `chrome`
 - Version `77.0.3865.90`

**Additional context**
No

**Comment by kuckjwi0928** [comment]
https://github.com/kuckjwi0928/tui.grid/commit/fdfddf02c8004d835355b28ba5a51509b9f23e56

PR 제출해도될까요?

**Comment by jung-han** [comment]
@kuckjwi0928 넵

**Comment by jung-han** [comment]
@kuckjwi0928 이 내용은 v4.6.0에 포함되어 배포될 예정입니다.

**Comment by kuckjwi0928** [comment]
@jung-han 
해당이슈는 close 해도 될까요?

**Comment by jung-han** [comment]
@kuckjwi0928 넵~
