### ISSUE TITLE
Event type and validation option query that occur when moving rows of grid

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#688]
**Summary**
1. grid의 row이동시 이벤트를 이용해서 이전 row의 셀 데이타의 validation 체크를 하려고 하는데
focusChange, editingStart, editingFinish 이벤트가 두번씩 발생합니다.
row change시에 사용할 만한 이벤트가 없을까요?

2. validation 옵션을 걸어도 테마가 stripe일 경우에는 배경의 색상이 변경되지 않아서 문의드립니다.
**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
grid 4.5.2

**Additional context**
grid 4.5.2를 사용하고 있습니다
 editingFinish 이벤트를 사용하여 특정 셀 편집이 끝나고서 해당 셀의 값의 validation 체크를 하려고 했는데 focus 이동시에 editingFinish 이벤트가 두번 발생합니다
그리드의 row 이동시에 발생하는 이벤트로(마우스가 다른 row를 클릭할때의 이벤트) 활용할 수 있는 이벤트가 있을까요?
focusChange나 editingFinish 이벤트들은 제가 잘못한 건지 몰라도 오작동이 발생하거나 기대한대로 작동하지 않더군요(다른 셀 클릭시 해당 이벤트가 두번 발생합니다)
row change 시에 이전 row 의 셀값들의 validation을 체크하고 싶은데 활용할 이벤트가 마땅치가 않네요
그리드에 있는 validation option은 셀의 색은 변경되는데 별다른 강제성이 없어서요
validation { dataType: 'number'} 하면 숫자만 입력되게 강제하는 줄 알았는데 그냥 셀의 배경색만 달라지구요
validation에 따른 색 변경도 그리드에 stripe테마를 입히니까 적용이 안됩니다.

**Comment by js87zz** [comment]
@higamza 
1. 이벤트들이 중복 발생하는 현상 확인하였고, 이 부분은 버그 픽스 릴리즈에 반영될 예정입니다.(정확한 일정은 아직 정해지지 않았습니다.)
2. row 이동시에는 별도의 이벤트는 제공되지 않습니다. 현재로서는 focusChange 로 처리하셔야될 것 같습니다. 추가적인 이벤트 제공에 대해서는 논의해보겠습니다. 
3. 말씀하신대로 그리드의 validation은 조건에 따라 시각적으로 잘못된 값인지 확인만 가능합니다. 이외에 값을 강제하는 기능 확장에 대해서는 논의해보겠습니다. `stripe`와 관련된 부분은 버그이니 버그 픽스 릴리즈에 반영될 예정입니다.

감사합니다 :)
