### ISSUE TITLE
grid column의 onAfterChange 사용시 ie11에서 grid가 표시되지 않는 오류

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#690]
**Describe the bug**
grid column 옵션에 onAfterChange, onBeforeChange function 을 사용하면 ie11에서 콘솔에 오류 로그가 찍히고 grid가 표시도 안되고 정상작동하지 않습니다

**To Reproduce**
1. grid column 에 onAfterChange function을 선언하고 코드를 입력한다.
2. ie11에서 해당 url을 호출하여 grid가 표시되는지 화면을 확인한다.

**Expected behavior**
ie11에서 그리드가 정상적으로 표시되고 작동한다

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window 7
 - Browser internet explorer
 - Version 11.950.17134.0

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by js87zz** [comment]
@higamza 
모두 정상동작하는 부분인대요.`onAfterChange`, `onBeforeChange` 옵션설정하는 소스를 올려주셔야 파악이 가능할 것 같습니다.

**Comment by higamza** [comment]
onAfterChange 옵션설정하는 전체 소스입니다
<!doctype html>
<html lang="en">
 <head>
 <meta charset="UTF-8">
<link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
 <title>Document</title>
 <script>
 function fnTest(){
	 alert('button test');
}
 function addRow(){
	 var row ={
      c1: '',
      c2: '',
      c3: 1
    }
	grid.appendRow(row);
	var gn =  grid.getRowCount();
	grid.startEditing(gn-1, 'c1', true);
 }
 </script>
</head>

<body>

 <p>grid test</p>
 <button id="addBtn" onclick="addRow();">ADD</button>
  <div id="grid"></div>
<script>
  var Grid = tui.Grid;
  class CustomButtonRenderer {
		constructor(props) {
			const el = document.createElement('input');
			const { value, onclick } = props.columnInfo.renderer.options;

			el.type = 'button';
			el.value = String(value);
			el.addEventListener('click', (ev) => {
			  fnTest();
			});

			this.el = el;
			this.render(props);
		}

		getElement() {
			return this.el;
		}

		render(props) {
			//this.el.value = value;
			//this.el.onclick = fnTest();
		}
	}
	const gridData = [
    {
      c1: '100013',
      c2: 'Mustafa Cosme',
      c3: 291232
    },
    {
      c1: '201212',
      c2: 'Gunnar Fausto',
      c3: 32123
    }
  ];

  const grid = new tui.Grid({
    el: document.getElementById('grid'),
    scrollX: false,
    scrollY: false,
    rowHeight: 35,
	data: gridData,
    rowHeaders: ['rowNum'],
    header: {
      height: 40
    },
    columns: [
      {
        header: 'ID',
        name: 'c1',
		editor : 'text',
		onAfterChange(ev){
			alert('1');
		}
      },
      {
        header: 'Name',
        defaultValue: 2,
        name: 'c2',
		editor : 'text'
      },
      {
        header: 'Score',
        name: 'c3',
		renderer: {
					type: CustomButtonRenderer,
					options: {
						value: 'link',
						onclick: 'fnTest()'
					}
				}
      }
    ]
  });

 </script>
</body>
</html>

**Comment by js87zz** [comment]
@higamza 
`class` 문법이나 객체내에서 함수를 줄여서 사용하는 문법은 IE11에서 지원하지 않기때문에 제대로 동작하지 않습니다. 해당 부분은 `es5`로 작성해주셔야 정상 동작합니다. 그리드와는 별개의 이슈네요~

**Comment by higamza** [comment]
아래 소스를 다시 봐주시기 바랍니다.
보시면 튜토리얼에 있는대로 작성한 기본 그리드에 onAfterChange 함수만 넣었어요
이렇게 해도 ie11에서 grid가 rendering되지 않습니다.
확인 _부탁드립니다._
__
<!doctype html>
<html lang="en">
 <head>
 <meta charset="UTF-8">
 <link rel="stylesheet" href="https://uicdn.toast.com/tui-grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/tui-grid/latest/tui-grid.js"></script>
 <title>Document</title>
 <script>

 </script>
</head>

<body>

 <p>grid test</p>

  <div id="grid"></div>
<script>
  var Grid = tui.Grid;
  
 const gridData = [
    {
      c1: '100013',
      c2: 'Mustafa Cosme',
      c3: 291232
    },
    {
      c1: '201212',
      c2: 'Gunnar Fausto',
      c3: 32123
    }
  ];

  const grid = new tui.Grid({
    el: document.getElementById('grid'),
    scrollX: false,
    scrollY: false,
    rowHeight: 35,
 data: gridData,
    rowHeaders: ['rowNum'],
    header: {
      height: 40
    },
    columns: [
      {
        header: 'ID',
        name: 'c1',
  editor : 'text',
onAfterChange(ev){
alert('1');
}
      },
      {
        header: 'Name',
        defaultValue: 2,
        name: 'c2',
  editor : 'text'
      },
      {
        header: 'Score',
        name: 'c3'
      }
    ]
  });

 </script>
</body>
</html>

**Comment by js87zz** [comment]
@higamza 
튜토리얼에 있는 예제는 es6 기준으로 작성되었습니다. IE11에서는 지원 안하는 문법이 있으니 아래처럼 es5로 작성하셔야됩니다.
```js
// es6
onAfterChange(ev){
  alert('1');
}
//es5
onAfterChange: function(ev) {
  alert('1');
}
```

**Comment by jung-han** [comment]
@higamza 
* zip 파일링크는 삭제하도록 하겠습니다. 
* 예제 파일 작성은 jsfiddle, jsbin, codepen 같은 사이트에 작성하여 링크를 공유해주시면 감사하겠습니다.
