### ISSUE TITLE
startEditing function error after removeRow

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#694]
**Describe the bug**
startEditing function error after removeRow
>removeRow 수행후 startEditing 함수 실행시 오류발생

**To Reproduce**
1. Create rows 1, 2, and 3 with the appendRow function (total 3 rows)
2. Remove the second row with the removeRow function in the click event of the delete button.
2. In the click event of the other button, startEditing function of the second row (because I deleted the second row, the first third row is now the second row)
Set first cell to edit

>1. appendRow 함수로 1, 2, 3 행을 생성(총 3개의 행 생성)
>2. 삭제버튼의 click 이벤트에 removeRow 함수로 2번째 행 삭제
>3. 다른 버튼의 click 이벤트에 startEditing 함수로 2번째 행의 (2번째 행을 삭제했으므로 처음의 3번째행이 이제 2번째 행이 되었음, )
첫번째 셀을 edit 상태로 설정

**Expected behavior**

The first cell in the second row is in the edit state
>2번째 행의 첫번째 셀이 edit 상태가 된다

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window 7
 - Browser chrome
 - Version 65...

**Smartphone (please complete the following information):**

**Additional context**
error

**Comment by js87zz** [comment]
@higamza 
혹시 `startEditing`은 rowKey 기준인대 index를 그대로 넣은 것은 아닌가요? 
(2번째행이 삭제되었어도 3번째 행의 rowKey는 변함없이 3 이므로 `startEditing(3, 'columnName')`이 되어야합니다.)
아니라면 소스랑 에러 내용도 캡쳐해서 같이 올려주셔야 현상 확인이 될 것 같습니다.
