### ISSUE TITLE
grid read 후 disableRow setRowState' of undefined 에러

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#695]
grid read 후 원하는 행에 disabled 처리를 하려고 합니다.

클릭 이벤트를 통해 grid.disableRow(rowKey); 를 하면 원하는 행에 disabled 처리가 됩니다.

하지만 readData를 하고난 후 grid.disableRow(rowKey); 를 사용하면 

setRowState' of undefined 에러가 납니다.

의심되는 부분은 readData를 하고나서 데이터를 완전히 읽어오지 않은 상태에서 disabled 처리를 하려고 하기 때문에 나는 에러인것 같습니다.

readData를 하고난 상태에서 disabled 를 하는 방법이 있는지 질문 드립니다.

**Comment by js87zz** [comment]
@gurgus0189 
이슈 템플릿에 맞춰서 작성해주시고 정확한 버전을 명시해주세요. 해당 이슈는 우선 클로즈 하겠습니다.
