### ISSUE TITLE
How to disableRow after grid read

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#696]
version : 3.6.0

1.Check the desired rows in A grid
2. Click the Add Row button
3. Use append to move data from grid A to grid B
    -A check in the A grid after moving disabled
4. Click 'Register' button and add data to the added row DB of B grid.

Operation sequence is as above.

In addition, we will compare each grid data PK and treat duplicate rows as Disabled.

The process executed in 3 when readData is initialized

DisableRow (rowKey) works fine when a click event occurs, but if you call it after readData
I am getting 'setRowState' of undefined error.

I think this error occurs when I try to disableRow (rowKey) without reading data in readData.

tell me your opinions.

>1. A 그리드에 원하는 행 체크
>2. 행 추가 버튼 클릭
>3. A 그리드에서 체크한 행 B 그리드로 데이터 이동 append 사용
>   - 이동 후 A 그리드에 체크한 행 disabled(선택 막기) 
>4. 등록버튼 클릭시 B 그리드의 추가한 행 DB에 데이터 추가 후 각각의 그리드 readData
>동작순서는 위와 같습니다.
>추가적으로 각각의 그리드 데이터 PK 를 비교하여 중복되는 행은 Disabled 처리 할 계획입니다.
>readData시 3번에서 실행한 과정은 초기화 

>클릭 이벤트 발생시 disableRow(rowKey)는 잘 동작되지만 readData 이후 호출을 하면  
'setRowState' of undefined 에러가 발생합니다.

> readData 시 데이터를 불러오지 않은 상태에서 disableRow(rowKey) 를 하려다보니 발생하는 에러라고 생각됩니다.

>의견 부탁드립니다.

![git_img](https://user-images.githubusercontent.com/45814209/65591452-871fb980-dfc7-11e9-9dce-5bda689048af.png)

**Comment by js87zz** [comment]
@gurgus0189 
readData 는 ajax 요청이기 때문에 비동기로 동작하니 setTimeout으로 disableRow 호출하는 부분을 감싸주면 될 것 같네요.

**Comment by js87zz** [comment]
@gurgus0189 
아래 링크의 이벤트 참고하시면 도움될 것 같네요.
https://nhn.github.io/tui.grid/3.9.0/Grid#event-successResponse
