### ISSUE TITLE
How to prevent certain areas from being clicked

### ISSUE THREAD

**Issue by daehan0522** [nhn/tui.grid#697]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

version : 3.9.0

Good morning. This time I created a data list using toast-grid.
However, as I worked, I made a button in a specific area of the grid.
The form will be clicked first.

> 안녕하세요. 제가 요번에 toast-grid를 사용해서 데이터리스트를 만들었습니다.
그런데 작업하다보니 그리드 특정 영역안에 버튼을 만들엇는데 버튼이 눌리지않고
해당 폼이 먼저 클릭이 됩니다. 

1. Clicking on a specific area of the grid and clicking again does not recognize it.
> 1. 그리드 특정 영역을 클릭 후 다시 클릭하면 인식이 안되는 문제.

![image](https://user-images.githubusercontent.com/42962279/65680397-d2060380-e091-11e9-9dc6-8a614c7bb649.png)

Click on Application 227 to view the data in a popup window, then click on the Application 227 again and nothing happens. Must press the other side in the same row

> (용도 227를 클릭해서 팝업창을통해서 데이터를 본다음 다시 용도227 부분을 클릭하면 아무 반응 안함. 같은 로우에 다른 쪽을 눌러야지 인)

2. When creating a specific area button, the form is pressed first without the button being pressed.
> 2. 특정영역 버튼 생성시 버튼이 눌리지않고 폼이 먼저눌림

![image](https://user-images.githubusercontent.com/42962279/65680363-c0bcf700-e091-11e9-9f03-abb43d6b4bdc.png)

(If you click the download button, the button is not executed and the popup window is executed.)
>(다운로드 버튼을 클릭시 버튼이 실행되지 않고 팝업창이 실행됨. 다시 다운로드 버튼을 누를 때는 1번의 문제 때문에 다운로드 버튼이 누를수 있게됨.)

**Comment by js87zz** [comment]
@daehan0522 
해당 케이스를 저희가 모두 재현해서 확인하기는 어려우니 정확한 현상을 codepen 이나 jsfiddle 같은 곳에 올려주세요. 그리고 이슈 타이틀은 완성된 문장으로 수정 부탁드리겠습니다.
