### ISSUE TITLE
특정 셀 객체를 가져올 수 있을까요?

### ISSUE THREAD

**Issue by higamza** [nhn/tui.grid#703]
**Summary**
특정 셀 객체를 가져와서 그 셀의 콤보 옵션 목록을 다르게 주고 싶습니다.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
grid 4.5.2

**Additional context**
특정 셀 객체를 가져와서 그 셀의 콤보 박스 목록을 다르게 설정하고 싶습니다
api를 아무리봐도 getColumns는 있는데
특정 행의 특정 셀의 객체를 가져오는건 없더라구요

예를들어 1번째 행의 1번째 셀의 콤보박스의 값을 '과일' 로 선택하면 
1번째 행의 2번째 셀의 콤보박스에는 사과, 오렌지, 수박 을 목록으로 넣고 싶고
2번째 행의 1번째 셀의 콤보박스의 값을 '채소'로 선택하면 2번째 행의 2번째 셀의 콤보박스에는 마늘, 당근, 오이
이런식으로 넣고 싶어요

근데 이걸 자바스크립트로 구현해야해서 자바스크립트에서 특정 셀을 가져오려고하니 method가 없네요 ㅜㅡㅜ

**Comment by js87zz** [comment]
@higamza 
아래 링크 참조하시면 도움 될 것 같네요.
튜토리얼: https://github.com/nhn/tui.grid/blob/master/docs/ko/relation-between-columns.md
예시: https://nhn.github.io/tui.grid/latest/tutorial-example05-relation-columns

**Comment by higamza** [comment]
정말 감사합니다. ^^
