### ISSUE TITLE
Process paging after data insertion

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#714]
version : 4.5.2

```js
data: {
     api: {
	       readData: { url: 'api주소', method: 'POST' }
            }
	 },
pageOptions: {
	perPage: 10
},
```

이와 같이 api호출후 컨트롤러에서 한 페이지당 10씩 보여주는 페이징을 구현 하였습니다.

위 방법같이 컨트롤러 단을 거치지 않고  스크립트 단에서 데이터 형식을 만들어주고 
페이징 하는 방법을 사용하고 싶습니다. 

1.
```
data: gridData, 
pageOptions: {
	 perPage: 10
},
```

Attempted the same way as No.1 but not paging, showing the entire gridData data on one page
> 1번과 같은 방법으로 시도했으나 페이징이 되지않고 한 페이지에 gridData 전체 데이터를 보여줌

2.
```
data : {
	contents: gridData,
	pagination: {
		page: 1,
		totalCount: gridData.length
	}
},
pageOptions: {
	 perPage: 10
},
```

I've written method 2 according to the paging format, but it doesn't work very well...
Is there a way to insert and paging data at the script?

>2번 방법은 페이징 형식에 맞춰서 작성했지만 잘 동작하지 않네요...
스크립트 단에서 데이터를 넣어주고 페이징 하는 방법이 있을까요?

**Comment by js87zz** [comment]
@gurgus0189 
클라이언트 페이지네이션을 원하시는 것 같은대요.
아래처럼 설정하시면 사용 가능합니다. 
```js
pageOptions: {
  useClient: true,
  perPage: 5
}
```
관련 튜토리얼 링크 아래에 남겼으니 참고해주세요~
https://github.com/nhn/tui.grid/blob/master/docs/ko/pagination.md
