### ISSUE TITLE
mouseover/mouseout 일 때 row에 배경색을 변경하고 싶습니다. 

### ISSUE THREAD

**Issue by ahacross** [nhn/tui.grid#717]
어떻게 하는게 가장 좋은 방법일 까요?

구현된 방법이 있다면 알려주세요... 

전 css의 class 하나 만들고 class를 넣었다 뺐다 하려고 하는데 더 좋은 방법이 있을까요?

**Comment by jung-han** [comment]
@ahacross
4.4.0 버전 이후로 row hover 테마 기능을 제공하고 있습니다.

```js
Grid.applyTheme('custom', { 
  row: { 
    hover: { 
      background: '#00eeff' 
    }
  }
});
```

**_이슈를 작성하실 때 템플릿을 지우지 마시고 내용을 모두 채워서 작성해주시면 감사하겠습니다. 해당 이슈는 close하겠습니다._**
