### ISSUE TITLE
Disable editing mode after shell modification

### ISSUE THREAD

**Issue by youngwonseo** [nhn/tui.grid#719]
**Summary**
Is there any API to disable editing mode? This means that the shell cannot be modified.

> editing 모드 해제하는 API는 없나요 ? 즉 수정활성화 되어있는 쉘을 수정이 안되게 닫는 기능을 뜻합니다.

**Version**
v4.2.0

**Additional context**

**Comment by js87zz** [comment]
`finishEditing` API가 있습니다. 
```js
grid.finishEditing(rowKey, columnName, value);
```
API 관련하여 아래 링크 참조해주세요.
https://nhn.github.io/tui.grid/latest/Grid#finishEditing
