### ISSUE TITLE
Dummy row 에 이벤트 trigger

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#722]
**Summary**
현재 `showDummyRows` 옵션을 켜두고
row 이벤트를 설정해두면
dummy row에도 해당 이벤트가 trigger 됩니다.

이 부분은 의도하신건가요?
이것 때문에 가끔가다가 에러가 나는 부분이 존재해서요.

만약 의도하신게 아니라면 수정 후 PR 하겠습니다 !

감사합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/18422353/66378043-a538e100-e9ed-11e9-855a-e811d9edc443.png)

**Version**
4.6.0

**Additional context**

**Comment by js87zz** [comment]
@ryum91 
의도한 바는 아닙니다.. PR 올려주시면 감사하겠습니다 :)
