### ISSUE TITLE
Is it possible to implement expandable rows?

### ISSUE THREAD

**Issue by vcardins** [nhn/tui.grid#734]
**Summary**
I'd like to be able to expand a row and load another grid or even a external component within it .

**Screenshots**
![image](https://user-images.githubusercontent.com/2383329/66679262-adc62d00-ec22-11e9-9645-a4e227da02a7.png)

**Comment by vcardins** [comment]
Hi, maybe this could work. I'd like for example, colspan an entire row and load a react component in it, having the parent row and the expander trigger. Not sure I made myself clear.

**Comment by js87zz** [comment]
@vcardins 
Unfortunately, `colspan` has not been provided yet and react component couldn't be the our custom renderer due to not support `JSX` as custom renderer format. We are planned to add `colspan` functionality, but there is no fixed date.
