### ISSUE TITLE
bootstrap 모달 안에서 tui.grid 사용시 출력문제

### ISSUE THREAD

**Issue by Leewangro** [nhn/tui.grid#735]
**Version**
tui.grid4.6

**Summary**
bootstrap 3.3.1 버전과 tui.grid 4.6버전을 사용중입니다.
bootstrap 모달 창 안에서 tui.grid를 이용하여 grid를 그려줄 때
개발자 도구나 페이지를 resize하지 않으면 grid가 출력되지 않습니다.

**Comment by jung-han** [comment]
@Leewangro 

코드와 스크린샷을 올려주시면 파악에 좀 더 도움이 될 것 같습니다.

**Comment by kim-seung** [comment]
> **Version**
> tui.grid4.6
> 
> **Summary**
> bootstrap 3.3.1 버전과 tui.grid 4.6버전을 사용중입니다.
> bootstrap 모달 창 안에서 tui.grid를 이용하여 grid를 그려줄 때
> 개발자 도구나 페이지를 resize하지 않으면 grid가 출력되지 않습니다.

안녕하세요 똑같은 문제를 겪고 있는데 혹시 해결하셨으면 해결 방안 좀 알 수 있을까요..?
