### ISSUE TITLE
Can I use html tags on the colums header?

### ISSUE THREAD

**Issue by eldestbro** [nhn/tui.grid#736]
columns: [
		{
			header: '작업일시',
			name: 'artist',
			align: 'center'
		},
		{
			header: '대상건수',
			name: 'type',
            align: 'center'
		},
		{
			header: '영상등록건수 <br />(대기/성공/실패)',
			name: 'release',
            align: 'center'
		}
	],

I'd like to make a line-up.

**Comment by js87zz** [comment]
@eldestbro 
현재 헤더 영역 관련 커스터마이징은 지원하지 않는 상태입니다. 추후 개발 항목으로는 잡혀있으나 정확한 일정은 확정되지 않았습니다.

**Comment by js87zz** [comment]
@eldestbro 
added in `v4.7.0`
The related document will be updated next week.
Thank you!
