### ISSUE TITLE
grid.appendRow() 사용시 버그

### ISSUE THREAD

**Issue by lhj0621** [nhn/tui.grid#740]
**Describe the bug**
grid.appendRow() 사용 시 버그입니니다.
한번 사용하면 아무것도 뜨지 않고 2번째 사용했을 때 2개가 보이는 현상입니다.

**Screenshots**
![](https://github.com/lhj0621/imagetemp/blob/master/ToastIssueImage.gif?raw=true)

**Desktop (please complete the following information):**
window 10 
chrome
toast 4.6

**Comment by jung-han** [comment]
It is similar with #732. I will manage it as one issue.
