### ISSUE TITLE
rowHeaders : ['checkbox'] 을 이용한 row 제어

### ISSUE THREAD

**Issue by lhj0621** [nhn/tui.grid#741]
**Summary**
rowHeaders : ['checkbox'] 를 이용하여 해당 row를 grid.disableRow(rowKey) 하려고 합니다.
어떤식으로 진행하면 될까요?

**Screenshots**

**Version**
toast 4.6

**Comment by js87zz** [comment]
@lhj0621 
질문의 의도가 어떤 의도인지 모르겠네요.
API 관련 질문이라면 아래 링크를 참조해주세요~
https://nhn.github.io/tui.grid/latest
