### ISSUE TITLE
Merge header column

### ISSUE THREAD

**Issue by js87zz** [nhn/tui.grid#742]
## Version
4.7.0
### Merge header column
* Users can merge specific **header** columns for displaying the column data as an one header column like as below.
<img width="391" alt="스크린샷 2019-08-09 오후 12 32 14" src="https://user-images.githubusercontent.com/37766175/62752275-c63e8d80-baa1-11e9-8d0f-8461da47c466.png">

* Since the merge the header column, it affects `range selection` and some API. 
  * As click the merged header column, the range of selection is extended by 
 spanning count.
  * if you show or hide one of the merged columns through API, all merged columns is affected.
  * The operation(`ex. selection, focus, editing`) in the grid cell is not changed for usability. because only the column of header is spanned.

### Setting option
```js
const grid = new Grid({
  data,
  column,
  header: {
    height: 100,
    complexColumns: [
      {
        header: 'name',
        name: 'nameHeader',
        childNames: ['id', 'name'],
        hideChildHeaders: true
       }
    ]
  }
});
```

**Comment by jung-han** [comment]
* [ ] selection
* [ ] focus
* [ ] 하위 cell 선택 시 header 선택 되는것
* [ ] `setHeader()`

* *colSpan이 있을 경우 sort, filter 불가.*

**Comment by ryum91** [comment]
colspan 적용 후 `resizable` 옵션에 대한 처리는 어떻게 진행되나요?

**Comment by js87zz** [comment]
@ryum91 
spanning을 지정한 컬럼의 `resizable` 옵션이 적용되게끔 할 예정입니다.
