### ISSUE TITLE
className not working

### ISSUE THREAD

**Issue by eldestbro** [nhn/tui.grid#749]
**Summary**
```js
columns: [{
	header: '작업일시',
	align: 'center',
	name: 'workday',
        className:'someclass'
}]
```
className을 해도 클래스가 추가가 안됩니다.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
4.6.1

**Additional context**

**Comment by jung-han** [comment]
@eldestbro 안녕하세요. 
옵션을 통한 컬럼의 className 지정이 누락된 것으로 보입니다. 현재 추가되어있는 `addCellClassName`을 우선적으로 이용해주시고 다음 배포버전인 `v4.7.0`에 해당 내용 배포하도록 하겠습니다. 감사합니다.

**Comment by js87zz** [comment]
@eldestbro 
added in `v4.7.0`
Thank you!
