### ISSUE TITLE
hover bug

### ISSUE THREAD

**Issue by eldestbro** [nhn/tui.grid#750]
**Describe the bug**

**To Reproduce**
4.6.0에서 4.6.1로 업데이트 된후 
마우스 아웃시 hover class가 사라지지 않습니다.

https://nhn.github.io/tui.grid/latest/tutorial-example07-themes

에서도 apply 하시면 현상을 보실수 있습니다

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  window
 - Browser chrome
 - Version 4.6.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jung-han** [comment]
#748 PR에서 수정되었습니다. 해당 내용은 v4.7.0에 포함되어 배포 될 예정입니다.

**Comment by js87zz** [comment]
@eldestbro 
fixed in `v4.7.0`
Thank you!
