### ISSUE TITLE
범위 지정한 영역의 cell 정보를 가져올 수 있나요?

### ISSUE THREAD

**Issue by kkhkykkk** [nhn/tui.grid#751]
getFocusedCell()을 이용하면 선택된 단 하나의 셀 정보만을 가져오더군요.
현업에서 그리드의 셀을 범위 지정 했을 경우, 엑셀 처럼 해당 지정된 범위의 계를 보여달라고해서..

범위지정해서 복사 하는 기능이 있는걸 보면 가능하지 않을까 싶어서 질문을 납깁니다.

**Comment by js87zz** [comment]
@kkhkykkk 
이슈 템플릿을 준수해서 다시 작성 부탁드리겠습니다. 현재 이슈는 클로즈하겠습니다.
