### ISSUE TITLE
Grid dataSource 연동 문제 문의드립니다. v4.0

### ISSUE THREAD

**Issue by sidohigar** [nhn/tui.grid#754]
dataSource 에 readData api 주소 설정하고 조회하여
grid에 정상적인 결과를 표시하였습니다.

그런데 수정을 하려고 cell에 더블 클릭 하면 아래 에러가 표시됩니다.

tui-grid.js:2615 Uncaught TypeError: Cannot read property '_attributes' of undefined
    at Object.createRawRow (tui-grid.js:2615)
    at makeObservable (tui-grid.js:3443)
    at Object.startEditing (tui-grid.js:3305)
    at dispatch (tui-grid.js:11188)
    at ContainerComp.startEditing (tui-grid.js:9027)
    at Object.ContainerComp._this.handleDblClick [as dblclick] (tui-grid.js:8999)
    at HTMLDivElement.eventProxy (tui-grid.js:947)
createRawRow @ tui-grid.js:2615
makeObservable @ tui-grid.js:3443
startEditing @ tui-grid.js:3305
dispatch @ tui-grid.js:11188
ContainerComp.startEditing @ tui-grid.js:9027
ContainerComp._this.handleDblClick @ tui-grid.js:8999
eventProxy @ tui-grid.js:947

응답받은 GridEvent {stopped: false, xhr: XMLHttpRequest, instance: Grid}의
response 의 contents  내용을
data에 담아 해당 grid에 설정하면 정상 동작 합니다.

ajax 호출 하여 grid.resetData(data) 형태로 사용하면 이상없이 되는데, dataSource 를 사용하면
grid cell 더블 클릭 시 스크립트 에러가 발생하고 있습니다.

tui-grid.js : 2615
function createRawRow(row, index, defaultValues, options) {
    ......
    if (row._attributes) {   <-- error (Cannot read property '_attributes' of undefined)
        rowSpan = row._attributes.rowSpan;
    }
    .......

답변 부탁드립니다.
감사합니다.

**Comment by js87zz** [comment]
@sidohigar 
이슈 템플릿에 맞춰 정확한 그리드 버전을 적어주세요. 그리고 codepen이나 jsfiddle 에 관련 소스를 올려주시면 현상 확인에 도움이 될 것 같습니다. 모든 케이스를 저희가 재현하기는 어려운 상황이니 양해 부탁드립니다~!
