### ISSUE TITLE
Can I get the cell information of the selection area?

### ISSUE THREAD

**Issue by kkhkykkk** [nhn/tui.grid#756]
**Summary**

Can I get the cell information of the specified area?
For example, ranged start_rowidx, start_colidx, end_rowidx, end_colidx.

>범위 지정한 영역의 셀정보를 가져올 수 잇나요?
예를 들자면 범위지정한 start_rowidx, start_colidx, end_rowidx, end_colidx
같은 것들이요.

**Screenshots**

**Version**
3.1.0

**Additional context**

Now getFocusedCell only gets the first cell information you specified.

The scoping part is considered possible to copy to the clipboard, so I ask if it's possible.

>현재 getFocusedCell 로는 처음 지정한 단 하나의 셀 정보만 가져오더군요..
범위지정한 부분을 클립보드로 복사가 가능한 것으로 보아, 혹시나 가능한지 여쭤봅니다.

**Comment by js87zz** [comment]
@kkhkykkk 
현재 셀렉션 범위를 가져오는 API 는 `3.x`, `4.x` 모두 존재하지 않습니다. 말씀하신 API는 feature 항목에 추가하겠습니다. 감사합니다.

**Comment by js87zz** [comment]
@kkhkykkk 
Sorry for late reply.
[getSelectionRange](https://nhn.github.io/tui.grid/latest/Grid#getSelectionRange) API has been added in `v4.8.0`.
