### ISSUE TITLE
grid tree ie 스택 오버플로우 문제

### ISSUE THREAD

**Issue by sidohigar** [nhn/tui.grid#761]
grid tree example ie 에서 스택 오버플로우 에러 발생합니다.

ie : v11.805.17763.0
tui-grid : v4.6.1

es5 문법으로 변경 후 실행

SCRIPT28 : 스택 공간 부족
tui-grid.js (336,5)

**Comment by js87zz** [comment]
@sidohigar 
이슈 템플릿 지우지 마시고 양식에 맞춰 다시 작성해주세요.
정확한 현상을 설명해주시고, 소스 코드나 가능하다면 스크린샷을 올려주세요. 
이 이슈는 클로즈하겠습니다.
