### ISSUE TITLE
grid editingStart Enter Key Not Working

### ISSUE THREAD

**Issue by zzdd1558** [nhn/tui.grid#766]
**Describe the bug**

**Expected behavior**
더블클릭하여 Editor모드로 들어갈때는 editingStart 이벤트가 발생하지만  Enter키를 쳐서 접속할때 editingStart이벤트가 발생하지 않습니다.

> Double-clicking to enter editor mode raises the editingStart event, but pressing Enter does not raise the editingStart event.

마우스가 보이지 않지만 

첫번째 row가 Enter 를 치고 editor모드로 들어갔을경우 
두번째 row가 마우스 더블클릭으로 editor모드로 들어갔을 경우 입니다.

editingStart를 주었으며 .
  grid.on('editingStart' , (e) => {
    console.log("editingStart");
    let {instance , columnName , rowKey , value} = e;
    instance.setValue(rowKey , columnName , "abc");
  })

해당 editor는 customEditor를 사용하였습니다.

**Screenshots**
![editingStartNotWorking](https://user-images.githubusercontent.com/13596225/67456239-04902580-f66b-11e9-9d58-361a2bcf37bf.gif)

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]

**Comment by js87zz** [comment]
@zzdd1558 
fixed in `v4.7.0`(#774)
Thank you!
