### ISSUE TITLE
4.7.0 배포 날짜

### ISSUE THREAD

**Issue by eldestbro** [nhn/tui.grid#768]
**Summary**
안녕하세요.
버그 관련해서 몇가지 이슈를 4.7.0에 배포가 되신다고 하셨는데
혹시 배포 시점을 알 수 있을까요?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@eldestbro 
We are planned to release `v4.7.0` on the second week of November. 
However, it could be changed.
Please fill out the issue **in English**. This is our policy to share our issue to other people.
