### ISSUE TITLE
editingFinish callback parameter columnName type String 

### ISSUE THREAD

**Issue by zzdd1558** [nhn/tui.grid#775]
**Describe the bug**
In the parameter of the editingFinish event callback function
The value of columnName is initially a string but from the second it appears as an array.

**Corresponding source code**

grid.on('editingStart' , (e) => {
    let {instance , columnName , rowKey , value} = e;
      if (columnName === 'G_CD_NM'){
           beforeCompareResult = e;
      }
});

grid.on('editingFinish', function (e) {
  let {instance , columnName , rowKey , value} = e;
  // console.log("----- this source Start -----");
  // console.log(value)
  // console.log(columnName)
  // console.log(CD)
  // console.log("----- this source End -----");
});

**Screenshots**
![Code](https://user-images.githubusercontent.com/13596225/67652656-41b92800-f989-11e9-8fea-38ecef548997.gif)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]

**Comment by js87zz** [comment]
@zzdd1558 
We need more detail information to solve this issue.
if it's possible, writing your code in codepen or jsfiddle would be more helpful. :)
