### ISSUE TITLE
How to apply  callback data to grid

### ISSUE THREAD

**Issue by sidohigar** [nhn/tui.grid#781]
**Summary**

Checkbox disabled according to callback data value.

step 1.  initialRequest - readData 

const dataSource = {
    initialRequest: true,  
    withCredentials: true,
    api: {
        readData: { url: '/xxx/xxxxx', method: 'GET' }
    }
};

const grid_options = {
    .....
    data: dataSource, 
    rowHeaders: ['checkbox'],  // checkbox option
    .....
}

step 2. Processing response result data

grid.on('successResponse', function (data) {
    var jsonResponse = JSON.parse(data.xhr.responseText);
    var $data= jsonResponse.data.contents.map(function (item) {
        if ( ... ) // condition check
                item._attributes = {
                    checkDisabled: true // A checkbox is disabled only
                };
        return item;
    });
    grid.resetData($data);  <=   set grid data ??
});

How do I apply the changed result values?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
tui-grid : 4.6.1

**Additional context**

**Comment by js87zz** [comment]
@sidohigar 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.

**Comment by js87zz** [comment]
@sidohigar 
Currently, there is no way to control the grid by using API in `successResponse` event callback.
I think another custom event needs to be provided. we will discuss it.

**Comment by js87zz** [comment]
@sidohigar 
This issue is old. So if you still have a problem with our latest version(`v4.14.0`), Please write new issue.
Thank you!
