### ISSUE TITLE
dataSource 관련 질문합니다.

### ISSUE THREAD

**Issue by tkarnr11** [nhn/tui.grid#783]
**Summary**
안녕하세요. dataSource  관련 질문 하나만 할려고 합니다.
dataSource 관련문서에서 "변경된 데이터 저장하기" 카테고리에서 request() 메서드 호출시 전송되는 데이터 문자열이 아래 스크린샷과 같다고하였는데 테스트 중에 확인해본 결과 전혀 다른식으로 넘어오는거 같은데 제가 잘못하고 있는건가요?
{createdRows[0][column]=aa,createdRows[0][title]=fff,createdRows[0][rowKey]=27,createdRows[1][column]=bb,createdRows[1][title]=ccc,createdRows[1][rowKey]=28} 이런식으로 넘어 오고있습니다..

**Screenshots**
![image](https://user-images.githubusercontent.com/36393057/67926476-76cbb180-fbf9-11e9-8c09-7c70e304a2ec.png)

**Version**
4.6.1

**Additional context**

**Comment by js87zz** [comment]
@tkarnr11 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.
