### ISSUE TITLE
Click event in a column

### ISSUE THREAD

**Issue by shreygeekyants** [nhn/tui.grid#786]
**Summary**
I have added two buttons in a column using the formatter. I am trying to bind a function to the click of that button, but it is not working

**Version**
    tui-grid: 3.7.0,

**Additional context**
This is the column definition
```
{
            title: "",
            name: "buttons",
            sortable: false,
            minWidth: 80,
            align: "center",
            formatter: function() {
              return `<button class="VEbutton" id="view" @click="handleClick">View</button> <button id="edit" class="VEbutton" >Edit</button>`;
            }
          }

```

**Comment by js87zz** [comment]
@shreygeekyants 
formatter supports only `html` template. It doesn't support the specific template used in other frameworks(ex. react, vue, angular..). 
How about using [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/complex-columns.md) with `v4.6.1`? This functionality helps you.
