### ISSUE TITLE
How to use tui gird?

### ISSUE THREAD

**Issue by 2Seok0** [nhn/tui.grid#790]
hello, i want to use tui grid. I did search how to use it.
 
I found there are two ways.
they says need to use npm or bower to download the source.
but I want to know other ways, except for npm, bower and cdn.

should I going to download github.com/nhn/tui.grid/releases/Source code(zip) ??

explain to me detail please. 
Thank you.

**Comment by jung-han** [comment]
@2Seok0 Please fill out the issue in `English`. This is our policy to share our issue to other people.

**Comment by 2Seok0** [comment]
hello, i want to use tui grid. I did search how to use it.
 
I found there are two ways.
they says need to use npm or bower to download the source.
but I want to know other ways, except for npm, bower and cdn.

should I going to download github.com/nhn/tui.grid/releases/Source code(zip) ??

explain to me detail please. 
Thank you.

**Comment by js87zz** [comment]
@2Seok0 
You can get the bundle files as below.
1. clone our git repository
2. execute `npm install` in command line
3. execute `npm run build` in command line
4. check the `./dist` folder
