### ISSUE TITLE
Datapicker Questions in Toast Grids

### ISSUE THREAD

**Issue by tjdgus3087** [nhn/tui.grid#793]
**Summary**
I followed the example and an error occurred, the error details are shown in the screenshot.
Please solve the problem.

example :https://nhn.github.io/tui.grid/latest/tutorial-example08-date-picker 

**Screenshots**
![image](https://user-images.githubusercontent.com/52440648/68634692-abb10000-0539-11ea-93a6-1a9a54b5782d.png)
++ lastest dom.js,snippet.js added

![image](https://user-images.githubusercontent.com/52440648/68634619-6d1b4580-0539-11ea-9413-120791f495d9.png)

**Version**
tui grid 4.x
windows 10 64x

**Additional context**

**Comment by jung-han** [comment]
Hi. @tjdgus3087.
Yesterday, CDN was an issue for https domestic service domain.
Can you try again?

**Comment by tjdgus3087** [comment]
HI, @jung-han 
Thank you for your reply
But still not solved.
Can I get an example that includes Script and CSS with cdn alone?
---------------------------translate----------------------------------
안녕하세요 답변 감사합니다 ㅜㅜ
다시 시도 해봤는데 여전히 똑같습니다 ..
datepicker 기능을 쓰려면 dom과snippet의 사용이 필수인가요 ??
혹시 다운받아 적용하지않고 cdn으로만 스크립트와 css를 적용하여 완성된 예제를 받아볼수있을까요

**Comment by tjdgus3087** [comment]
solved
