### ISSUE TITLE
IE11 row hover delay issue

### ISSUE THREAD

**Issue by taeyoung4808** [nhn/tui.grid#799]
**Describe the bug**
IE11 row hover delay

**To Reproduce**
i'm testing tui row hover theme on IE11 but hover is to slow. 

**Expected behavior**

**Screenshots**
Chrome:
![Chrome](https://user-images.githubusercontent.com/6241817/68822063-3e38d700-06d3-11ea-8ea0-a220932b3b6a.gif)

IE11: 
![IE11](https://user-images.githubusercontent.com/6241817/68822065-3e38d700-06d3-11ea-8aa0-5e01fb058d52.gif)

**Desktop (please complete the following information):**
 - OS: Window11
 - Browser [IE11]
 - Version [11.476.18362.0]

**Comment by js87zz** [comment]
@taeyoung4808 
Could you give up your configuring information(`data` and `column` options) for grid?
