### ISSUE TITLE
class override (vue)

### ISSUE THREAD

**Issue by lng0415** [nhn/tui.grid#802]
**Summary**
how to override these classes? i cant find options in applyTheme API.
.tui-grid-table
.tui-grid-border-line
.tui-grid-border-line-top

**Version**
2.1

**Comment by js87zz** [comment]
@lng0415 
You can apply the theme for `tui-grid-border-line-top`, `tui-grid-border-line-bottom` though `outline` option.(refer to http://nhn.github.io/tui.grid/latest/Grid#applyTheme) and we do not support the theme for `tui-grid-table` yet.

**Comment by lng0415** [comment]
@js87zz 
Can you tell me the code?
how to use static method in Vue?
```
import { Grid } from '@toast-ui/vue-grid';
...
...
***.applyTheme("default", {
    outline: {
        border: "#333"
    }
});
```

**Comment by js87zz** [comment]
@lng0415 
Use the static method as below.(refer to https://github.com/nhn/tui.grid/tree/master/packages/toast-ui.vue-grid#static-methods) :)
```js
import TuiGrid from 'tui-grid';
import { Grid } from '@toast-ui/vue-grid';
...
...
TuiGrid.applyTheme("default", {
    outline: {
        border: "#333"
    }
});
```

**Comment by lng0415** [comment]
@js87zz 
thank you. it works well.
