### ISSUE TITLE
how to disable loading progress bar text in Vue

### ISSUE THREAD

**Issue by lng0415** [nhn/tui.grid#805]
**Summary**
how to disable loading progress bar text?
i set to this null or "" , but text is seeing default characters (Loading Data).
how to disable text with text area?
(just loading progress bar)
```
language: {
    name: 'ko',
    value: {
        display: {
            noData: this.noDataStr,
            loadingData: null // "" // progress text
        }
    }
}
```

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
2.1.0

**Additional context**
[http://nhn.github.io/tui.grid/latest/Grid#setLanguage](http://nhn.github.io/tui.grid/latest/Grid#setLanguage) API has some options,(noData, loadingData, resizeHandleGuide....)
but Insufficient description of the API. 
only thing listed is 'localeCode' and 'data' option
Please write down additional options.

**Comment by js87zz** [comment]
@lng0415 
The option you inquired is not supporte yet. But we are planned to improve `datasource` functionality. Thank you!

**Comment by js87zz** [comment]
@lng0415 
`hideLoadingBar` option has been added in `v4.9.0`(#862)
```js
const dataSource = {
  // hide loading bar
  hideLoadingBar: true,
  api: {
    readData: { 
      url: '/readData', 
      method: 'get'
    }
  }
}
```
Thank you!
