### ISSUE TITLE
filter api is not working

### ISSUE THREAD

**Issue by Bombay** [nhn/tui.grid#806]
**Describe the bug**

**To Reproduce**
I'm using @toast-ui/vue-grid. I use filter api by invoke, but nothing happened.
```
this.$refs.table.invoke('filter', 'ordSeq', [{ code: 'eq', value: 1 }])
```

**Expected behavior**
thw row that has columnName = 'ordSeq' and value = 1 is displayed only.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version [e.g. 22] 78.0.3904.97
- tui-grid: 4.7.0
- @toast-ui/vue-grid: 2.1.0

Thank you for great grid!

**Comment by Bombay** [comment]
```
<grid
          ref="grid"
          :data="data"
          :columns="columns"
          :options="options"
/>
```
```
const defaultOptions = {
  minBodyHeight: 30,
  scrollX: false,
  scrollY: false,
  pageOptions: {
    useClient: true,
    perPage: 1
  },
  header: {
    height: 82
  }
}
```

제가 이런식으로 options 값을 주고 있는데, pageOptions 속성을 제거하면 정상 작동됩니다.

**Comment by js87zz** [comment]
@Bombay 
I have tested the bug you commented, but I couldn't confirm the bug. Regardless of configuring `pageOptions`, filter API has been operated well. 
So, Can you give us the more detail source code or data to solve your issue? if you upload your code on [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/), we'll be able to handle it faster.

**Comment by Bombay** [comment]
[codesandbox](https://codesandbox.io/embed/twilight-wildflower-orkzv?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)

filter is displayed. but It's not working.

In my project, It's not work when useClient option is true.
when I remove this option, It's work well.
maybe "useClient = true" occur the error.

this is my error message in console.
![image](https://user-images.githubusercontent.com/9034302/70204846-5bf2dc80-1765-11ea-91b7-652b974470c1.png)

**Comment by Bombay** [comment]
4.8 업그레이드 이후 넘나 잘 됩니다. 빠른 처리 정말 감사합니다.

After upgrade to 4.8, It works very well. Thank you :)
