### ISSUE TITLE
TUI GRID 몇 가지 질문드립니다.

### ISSUE THREAD

**Issue by dyhwangbo** [nhn/tui.grid#807]
현재 사용하고 있는 데이터 그리드에 몇몇 문제가 있어서 그리드 바꾸려고 합니다.

혹시 아래의 기능에 대해 지원 가능 또는 현재 가능한 상태인지 답변 부탁드리겠습니다.

1. 브라우져 창 크기를 사용자가 줄일 시 모든 컬럼의 WIDTH 값을 MIN-WIDTH 같은 형식으로 고정시킬 수 있는지 ?
- 기존 그리드는 하나의 컬럼은 항상 유동적이어야 하고 이와 관련해 창 크기를 사용자가 천천히 줄일 시 깨지는 현상이 있습니다.

2. 트리 그리드의 페이지네이션 가능 여부
- 이 부분은 이슈 부분 확인하다가 궁금해서 문의드립니다. 
  좀 더 말씀드리면 트리그리드 안의 자식 데이터는 상관없고 단순히 부모 데이터만 페이지네이션이 되는지에 대한 문의입니다.

**Comment by js87zz** [comment]
@dyhwangbo 
1. Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.
2. Please write your issue title and content more clearly, seperate the issue like as below
  * Is it possible to fix the all columns width?
  * Question about applying pagination functionality to tree grid
