### ISSUE TITLE
toast-ui.vue-grid  , 'complexColumns' didn't work 

### ISSUE THREAD

**Issue by JhonHoon-Han** [nhn/tui.grid#808]
**Summary**
I just want use 'complexColumns' option 
but that is didn't work well, 

header is crashed like image
It's support 'complexColumns' option?

**Screenshots**
![image](https://user-images.githubusercontent.com/43872626/69398144-4248a280-0d2c-11ea-8a4e-6a8da7aed1de.png)

**Version**
"@toast-ui/vue-grid": "^2.1.0",  

**Options**
`options : { 
         header:{
            complexColumns: [
              {
                header: 'TEST',
                name: 'ther',
                childNames: ['name', 'artist' ,'ggg','test']
              }
            ]
          }  ,
          columnOptions: {
            resizable: true
          }
      }`

**Comment by lng0415** [comment]
using height property.
```
options: {
    header: {
        height: 100, // header height
        complexColumns: [
.....
```

**Comment by js87zz** [comment]
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.

**Comment by js87zz** [comment]
@JhonHoon-Han 
It looks that `height` options has been missed. 
Try like below.
```js
// ...
height: 100, // set the height
header: { 
  complexColumns: [ { header: 'TEST', name: 'ther', childNames: ['name', 'artist' ,'ggg','test'] } ] 
},
// ...
```

**Comment by JhonHoon-Han** [comment]
@js87zz thank you :)
