### ISSUE TITLE
Filter UI is hidden when the Grid is on the far right

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#812]
**Describe the bug**
Filter UI is hidden when the Grid is on the far right

**To Reproduce**
1. Grid is on the far right of the browser
2. Filter open
3. Some UI is invisible

**Expected behavior**
In the rightmost case, the position should be changed to show the Filter UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/18422353/69596768-091f7380-1047-11ea-9596-26b5b1974c85.png)

**Comment by ryum91** [comment]
@js87zz 
See this commit.
I did not pull request because it was a temporary development.
https://github.com/ryum91/tui.grid/commit/6eae8e35dff83a8439e2ab057537813ba569f9de

**Comment by js87zz** [comment]
Duplicated issue with #1295.
