### ISSUE TITLE
Render the grid without using dataSource

### ISSUE THREAD

**Issue by hbjang** [nhn/tui.grid#814]
**Summary**
Grid Paging Data and Server Communication Parameters

**Version**
v3.3.0/tui-pagination
v1.5.0/tui-code-snippet
v4.7.0/tui-grid

**Additional context**
I entered the data through the resetData command in the form provided by the document, but the data is not visible in the grid. Please confirm.
grid.resetData(json)
var json = {
  "result": true,
  "data": {
    "contents": [{"file_01":"1, "file_02":"2"}],
    "pagination": {
      "page": 1,
      "totalCount": 1
    }
  }
};
In addition, please check how to put the parameter.
data: {
      api: { readData: { url: '/xxx/xxx/xxx', method: 'GET' }}
},

**Comment by js87zz** [comment]
@hbjang 
1. using `resetData`: Can you provide us more detail source code to [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)?
2. API: The parameter cannot be added on defining datasource api. we know this is annoying, so have plan to improve this problem in next release :)

**Comment by js87zz** [comment]
@hbjang 
DataSource has been improved in `v4.9.0`(#862)
1. You can pass `initParams` to get data
```js
// ...
data: {
  api: {
    // ...
    readData: { 
      url: '/api/oper/user', 
      method: 'GET', 

      // define the parameters to pass on communicating with server to get data initially
      initParams: { params: 'params' }
    },
  }
}
```
2. ajax option is extended
```js
const dataSource = {
  hideLoadingBar: true,
  api: {
    readData: { 
      url: '/readData', 
      method: 'get'
    },
    createData: {
      url: '/createData`, 
      method: 'post',

      // define content type for `json`
      contentType: 'application/json',

      // define headers what you want
      headers: { 'x-custom-header': 'x-custom-header' }
    },

    // define custom serializer if you need
    serializer(params) {
      return Qs.stringify(params);
    },

    // You can also define the option in common
    contentType: 'application/json',
    headers: { 'x-custom-header': 'x-custom-header' }
  }
}
```


Thank you!
