### ISSUE TITLE
Formatter settings on columns do not apply to select filter

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#816]
**Describe the bug**
Formatter settings on columns do not apply to select filter

**To Reproduce**
1. column `formatter` options setting
```js
    {
      name: 'type',
      filter: 'select',
      formatter(val) {
        return `formatted-${val.value}`;
      }
    }
```
2. The row data is changed and output.
![image](https://user-images.githubusercontent.com/18422353/69838598-8ccf9f00-1297-11ea-84bb-f7077dc19869.png)
(real data : 1000, 1001, 1002, 1003 ...)
3. Select filter open
4. Do not change
![image](https://user-images.githubusercontent.com/18422353/69838623-9f49d880-1297-11ea-80c6-67fe6da8f0c9.png)

**Comment by js87zz** [comment]
@ryum91 
The bug has been fixed in `v4.8.1`(#849)
Thank you!
