### ISSUE TITLE
Bug when using filter and sortable together

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#834]
**Describe the bug**
Bug when using filter and sortable together

**To Reproduce**
1. set filter and sortable to the column option
2. filter applied
3. Error during initialization after sort (sort 3 clicks)
4. Grid is freezing and error log

**Screenshots**
**Release**
![image](https://user-images.githubusercontent.com/18422353/70594739-c0f67880-1c24-11ea-9fd6-8facdd94d7d0.png)

**Master head**
![image](https://user-images.githubusercontent.com/18422353/70594772-d8cdfc80-1c24-11ea-8f4a-270c15504cc3.png)

**Additional context**
https://codepen.io/ryum/pen/NWPNXEZ

**Comment by js87zz** [comment]
@ryum91 
The bug has been fixed in `v4.8.1`(#841)
Thank you!
