### ISSUE TITLE
IE Browser Grid Cell No copy&paste

### ISSUE THREAD

**Issue by kjc6120** [nhn/tui.grid#835]
**Summary**
In Chrome and Edge, copying and pasting grid cells is good, but not in IE

**Screenshots**

**Version**
tuigrid : 4.5.2
IE : 11

**Additional context**
I am not good at English, so I wrote it through a translator.

**Comment by js87zz** [comment]
@kjc6120 
The bug has been fixed in `v4.8.1`(#835)
Thank you!
