### ISSUE TITLE
getRow is null

### ISSUE THREAD

**Issue by withmoon** [nhn/tui.grid#836]
tui-grid

## Version
4.7.0

## Development Environment
Window10, eclipse, java, springboot

## Current Behavior
 
```js
//grid.refreshLayout(); // == 1
				
console.log(rkey); // == 2
console.log(grid.getData()); // == 3
			
var originData = grid.getRow(rkey); // == 4
console.log(originData); //== 5

originData.en='changeValue'; // == 6

//grid.setValue(rkey, 'columnName',changeValue);	// = 8
grid.setRow(rkey, originData); // == 7
```

## Expected Behavior
[ First issue ]
 if column event.target-> 'cell' click binding event to Aajx function throw grid.on('click',function()) for Give event.rowKey to data changer function,
After generate Event action grid.setRow(rowKey,data); also I was use grid.setValue(rowKey,'columnName',data) but it's work once not more then once in Ajax success function.

[ Second issue ]
 Another issue is appendRow( ) After scroll event, not work setRow and set Value both.

[ Third issue ]
 GetRow(rowKey) is return  null After setRow and binding changed present rowKey to event..

[ Fourth issue ]
 After appendRow not work both, too.

But It's work at console of browser..

I want to action setRow or setValue in Ajax success function..

Thank you for attention to this issue

![image](https://user-images.githubusercontent.com/46144788/70678860-aaa8f500-1cd6-11ea-9cbe-b8fb5dd136d3.png)

**Comment by js87zz** [comment]
@withmoon 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue. It's hard to understand your issue now.

**Comment by withmoon** [comment]
@js87zz  
All right! translation'll take 2day thank you for attention to this issue

**Comment by withmoon** [comment]
> 
> 
> @withmoon
> Please respect our policy that writing the form **in English** to share our issue to other people.
> Change the title and content in English.
> It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue. It's hard to understand your issue now.

Translation done now

**Comment by withmoon** [comment]
@js87zz 
Translation done now

**Comment by js87zz** [comment]
@withmoon 
Can you upload your source code to [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)? We need more detail source code to check this issue.
