### ISSUE TITLE
getCheckedRows() returns previous value in check, uncheck event handler.

### ISSUE THREAD

**Issue by flyskyne** [nhn/tui.grid#838]
**Describe the bug**
Example: https://jsfiddle.net/oka7m5zr/

```javascript
grid.on('check', function () {
	console.log(grid.getCheckedRows());
});

grid.on('uncheck', function () {
	console.log(grid.getCheckedRows());
});

grid.on('checkAll', function () {
	console.log(grid.getCheckedRows());
});

grid.on('uncheckAll', function () {
	console.log(grid.getCheckedRows());
});
```

If you want to get checked rows by calling a `getCheckedRows()` in `check`, `uncheck` event handler, you get previous checked rows.
In `checkAll`, `uncheckAll`, you get expected checked rows.

**To Reproduce**
1. Go to https://jsfiddle.net/oka7m5zr/
2. Open console.
2. Click checkbox on grid.
4. See console

**Expected behavior**
Gets exact results of checked.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 79.0.3945.79

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -
 - Version: -

**Additional context**
TUI Grid: 4.7.0

**Comment by js87zz** [comment]
@flyskyne 
The bug has been fixed in `v4.8.1`(#840)
Thank you!
