### ISSUE TITLE
Is there a way to pass parameters to readData?

### ISSUE THREAD

**Issue by bogni** [nhn/tui.grid#843]
### Development Environment
window10 / chrome 79 / eclipse / spring

First of all, thank you so much.
ㅇ Version: 4.7.0
ㅇ Inquiries

Reading data using readData works fine, but I can't find a way to pass parameters for a particular condition.

Is it unique to import and filter all data?

You can pass a querystring using the second argument of readData
But, It crashes due to the page value set by default.
For example, {domain}? A = 1 & b = 2? Page = 1

**Comment by js87zz** [comment]
@bogni 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue. It's hard to understand your issue now.

**Comment by js87zz** [comment]
@bogni 
* I think the first question is about defining the datasource API with any parameter what you want like as below.
  ```js
  const data = {
    api: {
      readData: { url: '/api/read', method: 'GET', params }, // you want to pass 'params' to API
      // ...
    }
  };
  ```
  we don't support that datasource structure yet. However, It will be improved and other customizing options will be added in planned release for usability.

* The second question is about problem of the query string. You need to provide more detail source code and option for configuring grid to solve issue.
Give us your example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/). If It's hard to upload the source code, provide the configuring option for creating grid instance at least.

**Comment by bogni** [comment]
> @bogni
> 
> * I think the first question is about defining the datasource API with any parameters what you want like as below.
>   ```js
>   const data = {
>     api: {
>       readData: { url: '/api/read', method: 'GET', params }, // you want to pass 'params' to API
>       // ...
>     }
>   };
>   ```
>   
>   
>   we don't support that datasource structure yet. However, It will be improved and other customizing options will be added in planned release for usability.
> * The second question is about problem of the query string. You need to provide more detail source code and option for configuring grid to solve issue.
>   Give us your example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/). If It's hard to upload the source code, provide the configuring option for creating grid instance at least.

Thank you for answer.
But what is the format of params?

**Comment by js87zz** [comment]
@bogni 
The format is not fixed completely but it may be plain object.
  ```js
  const params = { a: 1, b: 2 };
  const data = {
    api: {
      readData: { url: '/api/read', method: 'GET', params }, // you want to pass 'params' to API
      // ...
    }
  };
  ```

**Comment by js87zz** [comment]
@bogni 
DataSource has been improved in `v4.9.0`(#862)
1. You can pass `initParams` to get data
```js
// ...
data: {
  api: {
    // ...
    readData: { 
      url: '/api/oper/user', 
      method: 'GET', 

      // define the parameters to pass on communicating with server to get data initially
      initParams: { params: 'params' }
    },
  }
}
```
2. ajax option is extended
```js
const dataSource = {
  hideLoadingBar: true,
  api: {
    readData: { 
      url: '/readData', 
      method: 'get'
    },
    createData: {
      url: '/createData`, 
      method: 'post',

      // define content type for `json`
      contentType: 'application/json',

      // define headers what you want
      headers: { 'x-custom-header': 'x-custom-header' }
    },

    // define custom serializer if you need
    serializer(params) {
      return Qs.stringify(params);
    },

    // You can also define the option in common
    contentType: 'application/json',
    headers: { 'x-custom-header': 'x-custom-header' }
  }
}
```

Thank you!
