### ISSUE TITLE
Tree 에서의 edit

### ISSUE THREAD

**Issue by LEECHUNGRYEOL** [nhn/tui.grid#845]
안녕하세요
일반 Grid에서의 edit후 변경 된 값이 그리드에 유지가 되고 
onAfterChange:fuction을 사용하여 데이터를 변경해주고 있습니다.

그런데 
Tree에서 edit를 할 경우 변경된 값이 그리드에 유지가 되지 않습니다.
onAfterChange:fuction을 사용하여 데이터를 재 조회해 주어도
트리구조다 보니 방금 변경된 데이터의 위치까지 찾아 들어가는것도 불편한데
혹시 Tree에서 edit 하고 값을 유지하는 기능이 있나요?
혹시 제가 잘못 구현해서 유지를 못하는 걸까요?

**Comment by js87zz** [comment]
@LEECHUNGRYEOL 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.
