### ISSUE TITLE
Tree grid column data cannot be maintained after changed

### ISSUE THREAD

**Issue by jahwang91** [nhn/tui.grid#847]
There is a problem to return the original value when moving the focuse after changing the data of the TreeGrid column.
Is there a workaround for this issue?

**Comment by js87zz** [comment]
@jahwang91 
Please respect our issue template that writing the form.
You need to provide more detail information like **grid version**, **browser version** and **source code**.
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue.
