### ISSUE TITLE
how can I load Grid list?

### ISSUE THREAD

**Issue by egg2d** [nhn/tui.grid#855]
**Summary**
DataSource readData JSON String Like this 👍 

{"result":true,"data":{"pagination":{"page":1,"totalCount":10},"contents":[{"USER_ID":"egg33d","EMAIL":"egg10d@naver.com"},{"USER_ID":"egg3d","EMAIL":"efew"},{"USER_ID":"egg4d","EMAIL":"efew"},{"USER_ID":"egg35d","EMAIL":"efew"},{"USER_ID":"egg36d","EMAIL":"efew"},{"USER_ID":"egg37d","EMAIL":"efew"},{"USER_ID":"egg38d","EMAIL":"efew"},{"USER_ID":"egg39d","EMAIL":"efew"},{"USER_ID":"egg392d","EMAIL":"efew"},{"USER_ID":"egg312d","EMAIL":"efew"}]}}

but no error in Chrome 
-> 

My jsp code is like this  :
<div id="grid"></div>
<script> 
	var dataSource = {
			  withCredentials: false,  
			  initialRequest: true,
			  api: {
			      readData: { url: '/admin/ChangeLimit.do', method: 'GET' },
			      createData: { url: '/api/create', method: 'POST' },
			      updateData: { url: '/api/update', method: 'PUT' },
			      deleteData: { url: '/api/delete', method: 'DELETE' },
			      modifyData: { url: '/api/modify', method: 'POST' }
			  }
			}

	const grid = new tui.Grid({
	    el: document.getElementById('grid'),
	    data: {
	    	  api: {
			      readData: { url: '/admin/ChangeLimit.do', method: 'GET' }	 
	    	  } 
	    },
	    scrollX: false,
		scrollY: false,
	    pageOptions: { 
	    	 perPage: 10
	    },
	    	 
	    	 
	    columns: [
	    	{
	    	    header: 'id',
	    	    name: 'USER_ID'
	    	  },
	    	  {
	    	    header: 'email',
	    	    name: 'EMAIL'
	    	  //,  editor: 'text'
	    	  }
	    ],
	 
	    
	  });

 HOW COULD FIX my code....? 

**Screenshots**
If applicable, add screenshots to help explain your question.

![image](https://user-images.githubusercontent.com/12668158/71638165-de56b980-2c9b-11ea-93cd-8dd60c7e8651.png)

**Version**
Write the version of the grid you are currently using.
V.4.81
**Additional context**

**Comment by js87zz** [comment]
@egg2d 
It's weird, your configuration looks like no problem. 
Could you give us more detail response data in chrome network tab?
If you can upload your source code in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/), it will be best way to solve this issue.

**Comment by egg2d** [comment]
dddd

**Comment by js87zz** [comment]
@egg2d 
I find the cause of this problem, `XMLHttpRequest.DONE` is considered as `string` value in the specific browser type or version. So, we fixed the bug in this PR(#862).

Thank you for your contributing!
