### ISSUE TITLE
How to use checkbox and external handler in custom renderer on React 

### ISSUE THREAD

**Issue by fullipsori** [nhn/tui.grid#860]
**Summary**
I have tried toast-ui.react-grid examples on React. But i have following isses.
Please let me know how to solve it.

1. How to use external Grid handler in custom render (ref : https://nhn.github.io/tui.grid/latest/tutorial-example11-row-headers)

From ref, i have tried event handler from CustomRenderer to Grid. But i get that EventHandler is undefined.

```javascript
  
  const ToastGrid = React.createRef();
  class Test extends React.component {
      /* 1. Add EventHandler */
       componentDidMount() {
        ToastGrid.current.getInstance().on("click", ev => {
            console.log("Grid Event:", ev);
        });
    }
    render() {
      class CustomRenerer {
          this.el.addEventListener("click", () => {
                /* 2. i checked click handler,  but always print : click is undefined */
                console.log("Custom AddEventLister", "clicked", ToastGrid.current.getInstance().click);    
           });
      }
   }
```

2.  how to add checkbox in column on React.

i tried to add checkbox in random column from tast-ui examples but i cannot get checkbox displayed.  
The following is my buggy code for reproducing it.

```javascript
const headCells = [
    { header: "번호", name: "id", align: "center", editor: "text" },
    { header: "이름", name: "name", align: "center", editor: "text", width: "200" },
    {
        header: "Genre",
        name: "genreCode",
        onBeforeChange: function(ev) {
            console.log("Before change:" + ev);
        },
        onAfterChange: function(ev) {
            console.log("After change" + ev); // call api
        },
        editOptions: {
            type: "checkbox",
            useViewMode: false    <---- false/true 모두 않됨.
        }
    },
    { header: "마지막", name: "display", editor: "text" },
];

  render() {
        <Grid
            ref={ToastGrid}
            data={rows}
            columns={headCells}
            rowHeight={25}
            virtualScrolling={true}
            heightResizable={true}
            scrollX={false}
            scrollY={false}
            pageOptions={{
               useClient: true,
                perPage: rowsPerPage
            }}
         />
  }
```

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.
 - tru-grid : 4.8.1
 - @toast-ui/react-grid: 4.8.1

**Additional context**

**Comment by js87zz** [comment]
@fullipsori 
1. The `click` custom event is fired internally and not registered in grid instance. I wonder the purpose of the `click` event handler of `CustomRenerer` instance and `CustomRenerer` should be configured to grid column option not React `render` function. Refer this [link](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) and [example](https://nhn.github.io/tui.grid/latest/tutorial-example04-custom-renderer)
2. The `editOptions`, `useViewMode` are deprecated in `v4.x`. Refer this [link](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-editor.md) and [example](https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor)

**Comment by fullipsori** [comment]
@js87zz 
I commented the click handler for describing the purpose. i want to send parent handler to inner customRender class. But i think its impossable.
Thanks for it.
