### ISSUE TITLE
refreshLayout() issues

### ISSUE THREAD

**Issue by cwkang89** [nhn/tui.grid#861]
"@toast-ui/vue-grid": "^4.8.1" version in use.

After the screen rendering,

Aside when folded, the grid is cut as shown below.

If you force the browser window size to change, the grid width value is automatically set.

Is there a solution?

![스크린샷 2020-01-13 오후 4 51 44](https://user-images.githubusercontent.com/50858429/72239640-fc6dd380-3624-11ea-9c7c-bde3bce2c7fc.png)
![스크린샷 2020-01-13 오후 4 52 00](https://user-images.githubusercontent.com/50858429/72239651-05f73b80-3625-11ea-829c-fd6946d1d3dd.png)

**Comment by js87zz** [comment]
@cwkang89 
Can you give us more detail source code(grid configuring option, calling `refreshLayout` function)?
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue.

**Comment by js87zz** [comment]
@cwkang89 
If you call the method in Vue, method should be called through `invoke` as below.
```js
this.$refs.tuiGrid.invoke('refreshLayout')
```

**Comment by cwkang89** [comment]
I know.
But there was no change.
And I found the answer.
The problem was that the grid layout did not change because of the css transition.
it works well when i remove the transition
