### ISSUE TITLE
grid rowheaders를 checkbox설정 클릭 에러 

### ISSUE THREAD

**Issue by audtjddld** [nhn/tui.grid#870]
**Summary**
rowHeaders를 체크 박스 타입으로 변경 후 체크박스 클릭시 오류가 발생됩니다.
API 문서 찾아봤는데 클릭시 이벤트를 걸어주는 설명을 못찾겠습니다.

**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/6148003/72582672-e151db00-3926-11ea-9aea-807a4fea3254.png)

**Version**
최신버전

**Additional context**

**Comment by js87zz** [comment]
@audtjddld 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
You need provide us more detail source code. It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue.

**Comment by audtjddld** [comment]
I looked for a solution.

this issue closing.

https://nhn.github.io/tui.grid/latest/tutorial-example15-custom-event


checkbox event binding is

```
    grid.on('check', function() {
      alert('check!');
    });

    grid.on('uncheck', function() {
      alert('uncheck!');
    });
```
