### ISSUE TITLE
하나의 컬럼에 두가지의 데이터를 표현하는 방법은 없나요 ?

### ISSUE THREAD

**Issue by shinhu91** [nhn/tui.grid#879]
하나의 컬럼에 두가지의 데이터를 표현 하는 방법은 없나요 ?

예를들어 [{a:1, b:2}] 라는 데이터가 있고, 이걸 바인딩 하면 

a | b
1 | 2

이런식으로는 표현이 되는데 

a/b 
1/2

처럼 하나의 컬럼에 두가지의 데이터를 보여줄 순 없나요?

**Comment by js87zz** [comment]
@shinhu91 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue. It's hard to understand your issue now.
