### ISSUE TITLE
html Multiple Grid sorce opne error question

### ISSUE THREAD

**Issue by passcrow** [nhn/tui.grid#880]
안녕하세요. 제목과 같이 부모창과 bPopup을 이용한 자식창에 grid 가 각각 존재 하는 화면을
구현하려 합니다.

하지만 자식창 html 에서 예를 들어 아래와 같은 소스코드를 만들면
![image](https://user-images.githubusercontent.com/60086147/72701041-44df4100-3b91-11ea-8e01-7b36d6871165.png)
![image](https://user-images.githubusercontent.com/60086147/72701080-62140f80-3b91-11ea-8ef2-72d08a742a45.png)
위와 같은 스크립트 오류가 발생합니다.

각 그리드 생성 시 const 에 대한 상수명은 다르고, new tui.Grid 는 동일합니다.

**Comment by js87zz** [comment]
@passcrow 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue. It's hard to understand your issue now.
