### ISSUE TITLE
 Is there any way to represent two types of data in one column?

### ISSUE THREAD

**Issue by shinhu91** [nhn/tui.grid#881]
**Summary**
Is there any way to represent two types of data in one column?

For example, if you have data called [{a: 1, b: 2}] and you use this data,
The output is like this.
a | b
1 | 2

But I want
ab|...
12|...

Is it possible?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@shinhu91 
Sorry for late replying.
Using the [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md), you can display the data you want.
