### ISSUE TITLE
tree grid issue

### ISSUE THREAD

**Issue by cwkang89** [nhn/tui.grid#882]
**Describe the bug**
When creating a tree grid in vue.js

**To Reproduce**
created() {
    this.gridProps = {
      data: this.gridList,
      columns: this.gridHeader,
      options: {
        treeColumnOptions: {
          name: "name"
        },
      }
    };
  },

Error when referring to data: this.gridList data as shown above

**Screenshots**
<img width="615" alt="스크린샷 2020-01-21 오전 9 35 16" src="https://user-images.githubusercontent.com/50858429/72765870-ed44e200-3c31-11ea-902d-b338d985f034.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : chrome
 - Version @toast-ui/vue-grid": "^4.8.1

**Additional context**
After creating an empty tree grid, an error occurs even if you run the row array with appendRow or appendTreeRow.

I'm sorry to have so many questions.

**Comment by cwkang89** [comment]
@js87zz 
개발하다가 넘 답답해서 그런데 ..  개인적인 연락처 공유가 안되나요

**Comment by js87zz** [comment]
@cwkang89 
Can you upload the source code with the all issues about grid in the [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) and give it to us? It's more convenient than email.
