### ISSUE TITLE
have any way for displaying rowNum in rowHeaders on descending mode.

### ISSUE THREAD

**Issue by fullipsori** [nhn/tui.grid#884]
**Summary**
The table number in our project should be displayed on descending mode.  But rowNum is always displayed on ascending mode. is there any way to control sorting mode? If you have example, please let me know it.
 

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.

**Additional context**

**Comment by js87zz** [comment]
@fullipsori 
You can resolve the issue through defining your custom row headers.
```js
class RowNumRenderer {
  constructor(props) {
    const el = document.createElement('span');
    el.innerHTML = props.grid.getRowCount() - props.formattedValue + 1;
    this.el = el;
  }

  getElement() {
    return this.el;
  }

  render(props) {
    this.el.innerHTML = props.grid.getRowCount() - props.formattedValue + 1;
  }
}

const grid = new tui.Grid({
    el,
    data: gridData,
    rowHeaders: [
      {
        type: 'rowNum',
        renderer: {
          type: RowNumberRenderer
        }
      }
    ],
    columns
});
```
