### ISSUE TITLE
Cannot read property 'rowSpanMap' of undefined 란 오류가 출력됩니다.

### ISSUE THREAD

**Issue by ahacross** [nhn/tui.grid#890]
**Describe the bug**
grid 데이터를 resetData로 바꾸면서 테스트를 하는데 
스크롤을 한페이지 이상 내린 후 데이터를 변경하면 제목과 같은 에러가 나오고 데이터 영역이 하얗게 표시됩니다.(아무 데이터도 보이지 않습니다. 스크롤은 남아 있어서 왔다갔다 할 수 있어요.) 스크롤을 내리지 않고 데이터를 변경하면 잘 변경 됩니다. 

**To Reproduce**
1. 'grid를 그립니다.(50개쯤?)'
2. 스크롤을 내립니다. (에러가 잘 나도록 맨 아래로 내려줍니다.)
3. ajax로 10개쯤 되는 데이터를 가져와서 resetData()를 통해 data를 변경해 줍니다.

**Expected behavior**
그냥 데이터가 변경되어 새로운 데이터를 뿌려주길 바랄뿐입니다.

**Screenshots**
![스크롤내린거](https://user-images.githubusercontent.com/1546934/73376540-efc5cc80-4300-11ea-8ef2-726b88a26fd9.png)
위에 화면은 처음에 데이터를 뿌리고 스크롤을 아래로 내린화면이며 
아무런 에러도 없는 상태 입니다. (데이터를 변경해도 스크롤을 안 내리면 잘 변경됩니다.)
![에러난 화면](https://user-images.githubusercontent.com/1546934/73376553-f3f1ea00-4300-11ea-8afd-98d06bc3d5ea.png)
스크롤을 내리고 변경을 하면 이런 에러를 뿜으며 데이터 영역에 아무정보도 표시하지 않습니다.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome 79]
 - Version [4.8.1]

데이터를 바꿔줄 땐 별도의 ajax로 data를 받아와서 resetData함수를 통해 수정합니다.

**Comment by js87zz** [comment]
@ahacross 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
We need more detail information to solve your issue. Please give us your source code or grid configuration. It's helpful to give us detail example source in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) for solving the issue.

**Comment by js87zz** [comment]
@ahacross 
The bug has been fixed in `v4.9.0`(#892)
