### ISSUE TITLE
_attributes 항목의 className 적용 문의

### ISSUE THREAD

**Issue by nimbas** [nhn/tui.grid#902]
**Summary**
_attributes에 배경색을 입힐때, cell에 데이터가 존재 하지 않으면 해당 색상이 적용이 안되는 현상이 있습니다. 

코드는 아래와 같습니다.
`
gird data내의 속성값
_attributes: {
  className: {
   row: ['test']
  }
}

grid css 파일
.test .tui-grid-cell-content {
  padding: 12px 12px 11px;
  overflow: hidden;
  box-sizing: border-box;
  word-break: break-all;
  background-color: #0088d9;
}
`

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the grid you are currently using.
4.8.0

**Additional context**

**Comment by js87zz** [comment]
@nimbas 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English.
