### ISSUE TITLE
How do I change several columns to editor?

### ISSUE THREAD

**Issue by cwkang89** [nhn/tui.grid#903]
**Summary**
I know that one column is changed to editor using startEditing.
But When I click a specific button outside the grid, I want to change several columns to editor, but I don't know what to do.

**Version**
"@toast-ui/vue-grid": "^4.8.1"

**Comment by js87zz** [comment]
@cwkang89 
What is your point?
You want to finish the editing by clicking outside button?

**Comment by cwkang89** [comment]
@js87zz 
I want to change several columns to edit mode.

**Comment by js87zz** [comment]
@cwkang89 
We don't support concurrent editing mode on several cells. 
The editing mode is only activated on a cell.
Could you give us your detail scenario?
