### ISSUE TITLE
How to merge cell?

### ISSUE THREAD

**Issue by gwonsuji** [nhn/tui.grid#904]
**Summary**
I'd like to merge the cells. In api, however, there are no examples or detailed methods of that method. Can you give me an example?

**Screenshots**
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/60372704/73921279-5dc65100-490a-11ea-8650-882c629273f7.png)
(example)

**Version**
CDN using

**Additional context**

**Comment by js87zz** [comment]
@gwonsuji 
Check this [tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/row-span.md) and [example](https://nhn.github.io/tui.grid/latest/tutorial-example06-attributes)
Thank you~!
