### ISSUE TITLE
Tui grid datasource 와 tui pagination 연동

### ISSUE THREAD

**Issue by kimsiwon** [nhn/tui.grid#916]
안녕하세요.. 제공해주시는 tui grid로 컨버전 작업중 막히는 부분이 있습니다..
vue.js로 개발 하였습니다. 버전은 tui grid- 4.9 , tui pagination - 3.5 입니다.
spa로 개발중이고 @/api/manager/menu 라는 경로에 export function getEtcORG() {} 형태의 resful api가 있습니다. 해당 resful api는 url, method, params, header meta데이터등을 저희가 사전에 만들어둔 유틸 컴포넌트로 태워 해당 url로 rest요청을 합니다..

tui grid 생성을할때 data 영역에 api: { readData: { url: '@/api/manager/menu', method: 'GET' } } 이라고 넣으면 되는게 아닌가요? status code는 200ok가 떨어졌는데 응답전문에서는 'we're sorry but preset doesn't work properly without javascript enalbled' 라는 에러가나네요
콘솔창에서 는 unexpected token in json at position 0 라는 에러가 뜹니다
저희가 백단에서 데이터를 가져올때 json형태로 클라이언트로 보내는데 문제가 되나요?

그리고 올려주신 이전 글들을 참고하며 mounted() 영역에 this.$refs.tuiGrid.invoke('setPerPage', 1)도 작성하였는데 동작하지않습니다..

그리드 옵션에는 pageOptions: { perPage: 5 } 라는 옵션을 주었습니다..

구글링을 하루종일해도 자료가 부족함이 많이 느껴집니다. 오픈소스를 제공해주셔서 감사하기는 하나 nhn.github.io 사이트의 api와 예제들도 어떤 옵션들과 메서드들이 있는지 알수 있지만 실제로 개발할때 도움이 되지 않습니다..

vue.js로 datasource와 pagination 구현되어있는 예제가 있으시면 도와주세요..
전체 패키지를 주시면 더 감사합니다.. 구성이 이해가 잘 안되서요..
backend에 perPage등의 변수를 받아서 처리하여 반환해주는것인지 backend에서 데이터를 전체 다 받아와서 perpage등의 옵션으로 분기하여 페이징처리하는것인지 알고싶습니다

도와주세요 상당히 곤혹을 치르고있습니다 부탁드립니다 살려주세요

**Comment by jung-han** [comment]
@kimsiwon 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
