### ISSUE TITLE
javascript 와 tui pagination  연동 방법이 궁급합니다.

### ISSUE THREAD

**Issue by ParkKiyoung** [nhn/tui.grid#917]
안녕하세요.
tui grid로 새로운 시도를 하고 있는데 JSON 데이터를 불러와 GRID로 표출하는 것 까지는
큰 무리 없이 진행을 했는데 페이징을 어떻게 하면 좋을지 아무리 찾아봐도 적절한 예제가 없는것 같아
글을 남기게 되었습니다.
현재 스프링 프레임워크로 자바와 자바스크립트를 통해 grid를 표시하고있습니다.

grid를 접했을때 json 형태로 전체 자료를 가지고 오면 스스로
한번에 표출하는 로우데이터 수 조절과
거기에 맞춘 페이징 기능이 있다고 보고 다른 분들의 예제와 API를 검색해서 보았지만,
어떻게 표출해야할지 중간에 막혀서 질문드립니다.
혹시 자바와 자바스크립트를 통한 페이지 API 예제 같은걸 참고 할수 있을까요?

현재 아래와 같이 되어있는데
페이징 visivlePage에 따라 분리되어 적절하게 나뉘고 있는데
문제는 불러온 데이터가 페이징 분리 없이 한페이지에 전부 표출되고
다음 페이지 버튼을 눌러도 응답이 없는 것이 현재 상황입니다.

도움 부탁드립니다 ㅠㅠ

```js	
const options = { 	//pagination 옵션
			  totalItems: data.length, //그리드로 불러온 데이터 길이
			  itemsPerPage: 10, // 페이지당 표시할 갯수
			  visiblePages: 10, // 페이징 버튼에 보일 링크버튼 갯수
			  page: 1, // 기본적으로 페이징 하고 난 다음에 나오는 페이지
			  centerAlign: true, //페이지 선택시 버튼을 중앙에 놓을건지 아닌지
			  firstItemClassName: 'tui-first-child',
			  lastItemClassName: 'tui-last-child',
			  template: {
			    page: '<a href="#">{{page}}</a>',
			    currentPage: '<a href="#" class="active">{{page}}</a>',
			    moveButton:
			      '<a href="#" class="pb {{type}}"></a>',
			    disabledMoveButton:
	    		  '<a href="#" class="pb {{type}}"></a>'
			  }
			};

	const pagination = new tui.Pagination('pagination', options);
	pagination.on('afterMove', (function(x){
		var pageNumber = x.page
		var data = getJsonData(pageNumber,10);
		grid.resetData(data);
	}));
	pagination.getCurrentPage();//페이지 현재 페이지 불러옴
```

**Comment by jung-han** [comment]
@ParkKiyoung 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.

**Comment by js87zz** [comment]
@ParkKiyoung 

This [tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md) will be helpful to you
