### ISSUE TITLE
Is there any part where handles the virtualScrolling prop?

### ISSUE THREAD

**Issue by jeiea** [nhn/tui.grid#920]
Just for my curiosity, where is handling`virtualScolling` prop?

I searched by `git log -SvirtualScrolling --oneline | grep -P '^\w+' -o | xargs git show | less`, but couldn't find anything like a implementation.

**Comment by js87zz** [comment]
@jeiea 
You use the `v4.x`? `virtualScolling` prop has been removed in `v4.x`.

**Comment by jeiea** [comment]
Yes, I'm using latest version. I'm still curious why history search brought no results but I understand this prop has no importance anyway.

Maybe react version readme need to be modified.
