### ISSUE TITLE
When I select a lot of data and press Control + C, get error.

### ISSUE THREAD

**Issue by kkhkykkk** [nhn/tui.grid#934]
**Describe the bug**
 When I select a lot of data and press Control + C,  get error.

**To Reproduce**
1. set focus to many cell
2. press Control + a (select all)
3. press Control + c (copy)
4. result console : Cannot read property...(reference to screenshot)

**Expected behavior**
copy to clipboard

**Screenshots**
![image](https://user-images.githubusercontent.com/17283453/75251632-549c1600-581e-11ea-8813-2d923a24d0b1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jung-han** [comment]
@kkhkykkk 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.

**Comment by js87zz** [comment]
@kkhkykkk 
This bug has been fixed in `v4.17.0`. Thanks.
