### ISSUE TITLE
Can I print a grid header in multiple lines?

### ISSUE THREAD

**Issue by TEXT85** [nhn/tui.grid#941]
Hello

I am using toast grid ui. I want to display text in grid headers in multiple lines, but I want to ask how.

![image](https://user-images.githubusercontent.com/59544163/75781594-d81ab180-5da0-11ea-9fed-b12d0e657a23.png)

**Comment by jung-han** [comment]
@TEXT85 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.

**Comment by js87zz** [comment]
@TEXT85 
Sorry for late reply~!
We provide the [custom column header](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-column-header.md). Using this functionality, you can define what you want.
Thank you!
