### ISSUE TITLE
Test process complains about absent 'prettier' module

### ISSUE THREAD

**Issue by Luke1982** [nhn/tui.grid#944]
On Ubuntu 18.04, recently updated, I try to follow the steps [here](https://github.com/nhn/tui.grid#setup) but the test fails since I run into a missing 'prettier' module. Running `npm install --save-dev prettier` solved the issue and added it to the package.json file.

**Comment by js87zz** [comment]
@Luke1982 
Sorry for late reply.
There is missed step for mono-repo. we will fix it
Follow the below step~! Thank you!
```sh
$ git clone https://github.com/{your-personal-repo}/tui.grid.git
$ npm install  <-- missed step
$ cd packages/toast-ui.grid
$ npm install
$ npm run test
```

**Comment by Luke1982** [comment]
Hi,

Are you sure that'll fix it? Since `npm install` installs the package,json file and I don't see the prettier dependency in there I think.

**Comment by jung-han** [comment]
@Luke1982 
https://github.com/nhn/tui.grid/blob/master/package.json

Sorry. It exists in the root directory package file.

**Comment by Luke1982** [comment]
I was just about the say that. I just noticed the `npm install` was twice.
