### ISSUE TITLE
Wrong capitalization breaks build

### ISSUE THREAD

**Issue by Luke1982** [nhn/tui.grid#945]
When trying to run an `npm run build` you run into
```nodejs
error TS2307: Cannot find module '../store/Selection'.
```
Changing [this line](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/types/event/index.d.ts#L3) to
```
import { SelectionRange } from '../store/selection';
```
fixes that. The same goes for [this line](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/types/store/index.d.ts#L5)

**Comment by js87zz** [comment]
@Luke1982 
Thank you! We will fix it.

**Comment by Luke1982** [comment]
Great!

**Comment by js87zz** [comment]
@Luke1982 
It has been fixed!

**Comment by Luke1982** [comment]
Nice, thanks!
