### ISSUE TITLE
setValue does not work in vue

### ISSUE THREAD

**Issue by WoohyunBae** [nhn/tui.grid#948]
**Describe the bug**
setValue does not work in vue

**Expected behavior**
`this.$refs.tuiGrid.invoke('setValue', 2, 'artist', 'testArtist')`

**Error message**
![주석 2020-03-10 111345](https://user-images.githubusercontent.com/28975892/76273285-d5e4b580-62c0-11ea-82fa-031303f769d8.png)
![주석 2020-03-10 111408](https://user-images.githubusercontent.com/28975892/76273245-c36a7c00-62c0-11ea-8a7e-608102912082.png)
`Cannot set property name of #<Object> which has only a getter`

setWidth 나 getValue  는 정상 작동 되는데 setValue 적용 시 해당 문제가 발생합니다.

**Comment by jung-han** [comment]
@WoohyunBae 
It's hard to answer because I don't know what column and what data you used.
If you use codesandbox like me in an error environment, it will be much easier to answer.

Check this example.
* https://codesandbox.io/s/romantic-brown-6lse2?fontsize=14&hidenavigation=1&theme=dark

**Comment by WoohyunBae** [comment]
@jung-han 
sorry about forgetting to notify more information.
first, I am using Nuxt.js,  I have to tui-grid through plugin( in Nuxt ).
I am not sure, but I think that's same reason why tui-grid doesn't support SSR mode.
so, when I don't define `onBeforeChange` in columns, occur below error.

`Cannot set property name of #<Object> which has only a getter`

So the solution I found, just define `onBeforeChange`  as `onBeforeChange= ev => { ev.stop() }` in column, and using invoke method in script.

like your example 
`this.$refs.tuiGrid.invoke("setValue", 1, "artist", "100");`

It is well operated except setValue, include getValue, setRow, etc.

there is part of my code below.

```javascript
<tempate>
  <TuiGrid
      :data="results" 
      :column="column"
      @editingFinish="(ev) => onchange(ev, $refs.tuiGrid)"
      ref="tuiGrid"
  />
...
</tempate>
...
<script>
export default {
  data() {
    return {
      results: [
        { name: 'foo', address: 'seoul' }
      ],
      column: [
        { 
           header: 'Name',
           name: 'name',
           onBeforeChange= ev => { ev.stop() }
         },
        { 
           header: 'Address',
           name: 'address',
           onBeforeChange= ev => { ev.stop() }
         } 
       ]
    }   
  },
  methods: {
    onchange: function() {
      // Do Work
      this.$refs.tuiGrid.invoke("getValue", 2, "name");
      this.$refs.tuiGrid.invoke("setRow", 1, { name: 'setRow', address: 'busan' });

     // Does not work
      this.$refs.tuiGrid.invoke("setValue", 1, "artist", "100");
    }
  }
}
</script>
```

** 추가적으로 오역이 있을 것 같아서 한국어로도 작성합니다.
1. Nuxt 사용중이며, SSR로 인해
`import "tui-grid/dist/tui-grid.css";   
import { Grid } from "@toast-ui/vue-grid"; ` 를 사용할 수 없어, Plugin  으로 작성하여 전역 컴포넌트로 사용 중입니다.
2. Column 안에 `onBeforeChange` 를 정의하지 않으면 `Cannot set property name of #<Object> which has only a getter` 라는 에러가 발생하여 Column에 `onBeforeChange= ev => { ev.stop() }` 를 정의하였습니다.
3. `this.$refs.tuiGrid.invoke("setValue", 1, "artist", "name");` 는 정상적으로 작동하지 않으며 
그 외 `this.$refs.tuiGrid.invoke("getValue", 1, "name");`, `this.$refs.tuiGrid.invoke("setRow", 1, "artist", "100");`` 는 정상 작동 됩니다

**Comment by js87zz** [comment]
@WoohyunBae 
I think that Vue reactivity system prevent our internal reactivity system. To prevent this, we are guiding the definition of general object, not `data` of Vue instance. 
Can you try like as below?
```js
<tempate>
   <client-only>
     <TuiGrid
         :data="gridProps.results" 
         :column="gridProps.column"
         @editingFinish="(ev) => onchange(ev, $refs.tuiGrid)"
         ref="tuiGrid"
     />
   <client-only>
...
</tempate>

export default {
  created() {
    // should define the general object as below
    this.gridProps = {
      results: [
        { name: 'foo', address: 'seoul' }
      ],
      column: [
        { 
           header: 'Name',
           name: 'name',
           onBeforeChange: ev => { ev.stop() }
         },
        { 
           header: 'Address',
           name: 'address',
           onBeforeChange: ev => { ev.stop() }
         } 
       ]
    }
  },
  data() {
    // Vue reactive data prevent our reactivity system and cause side effect.
    // should avoid to define grid config in `data`
    /**
    return {
      results: [
        { name: 'foo', address: 'seoul' }
      ],
      column: [
        { 
           header: 'Name',
           name: 'name',
           onBeforeChange: ev => { ev.stop() }
         },
        { 
           header: 'Address',
           name: 'address',
           onBeforeChange: ev => { ev.stop() }
         } 
       ]
    }   
    */
  }
  methods: {
    onchange: function() {
      // Do Work
      this.$refs.tuiGrid.invoke("getValue", 2, "name");
      this.$refs.tuiGrid.invoke("setRow", 1, { name: 'setRow', address: 'busan' });

     // Does not work
      this.$refs.tuiGrid.invoke("setValue", 1, "artist", "100");
    }
  }
}
```

**Comment by WoohyunBae** [comment]
@js87zz 
Thanks for your help, but there is not working yet.

as your help, I did define in `created()`, but didn't work.
and got inspired by your words, did define  out of `export default {}` but didn't work.

you said " Vue reactivity system prevent our internal reactivity system",
but if it did, is that right `setRow` neither do?
let me know diffrence both of `setRow`  and `setValue`, I will try more.

thanks.


**  korean
빠른 답변에 감사드립니다.
말씀해주신 것처럼 data 인스턴스가 아닌  created() 내에 정의도 해보았고, export default() 밖에 정의를 하여 시도 해보았지만 작동하지 않았습니다.

말씀해주신 것 처럼 뷰 자체의 데이터 인스턴스 문제라면, 제 소견으로는 @jung-han 님의 sandbox 예시 또한 작동하지 않거나, setRow 또한 작동을 하지 않을 것으로 예상됩니다.

하여 setRow와 setValue 매커니즘이 달라서 생기는 문제라고 생각이 되는데,  관련하여 다른 조언 또는 시도해볼만한 방법이 있으시다면 도움 부탁드립니다.

감사합니다.

```javascript
<tempate>
   <client-only>
     <TuiGrid
         :data="gridProps.results" 
         :column="gridProps.column"
         @editingFinish="(ev) => onchange(ev, $refs.tuiGrid)"
         ref="tuiGrid"
     />
   <client-only>
...
</tempate>

<script>
<tempate>
   <client-only>
     <TuiGrid
         :data="gridProps.results" 
         :column="gridProps.column"
         @editingFinish="(ev) => onchange(ev, $refs.tuiGrid)"
         ref="tuiGrid"
     />
   <client-only>
...
</tempate>

<script>

// my second try

const gridProps = {
  results: [
    { name: 'foo', address: 'seoul' }
  ],
  column: [
    { 
      header: 'Name',
      name: 'name',
      onBeforeChange: ev => { ev.stop() }
    },
    { 
      header: 'Address',
      name: 'address',
      onBeforeChange: ev => { ev.stop() }
    } 
  ]
}
export default {
...

// my first try
created() {
    // should define the general object as below
    this.gridProps = {
      results: [
        { name: 'foo', address: 'seoul' }
      ],
      column: [
        { 
           header: 'Name',
           name: 'name',
           onBeforeChange: ev => { ev.stop() }
         },
        { 
           header: 'Address',
           name: 'address',
           onBeforeChange: ev => { ev.stop() }
         } 
       ]
    }
  },
```

**Comment by js87zz** [comment]
@WoohyunBae 
Sorry! I didn't tell you one thing about your column config. If you call `ev.stop()` in `onBeforeChange`, it will prevent to set value. 
```js
  created() {
    // should define the general object as below
    this.gridProps = {
      results: [
        { name: 'foo', address: 'seoul' }
      ],
      column: [
        { 
           header: 'Name',
           name: 'name',
           // should be removed
           // onBeforeChange: ev => { ev.stop() }
         },
        { 
           header: 'Address',
           name: 'address',
           // should be removed
           // onBeforeChange: ev => { ev.stop() }
         } 
       ]
    }
  },
```

**Comment by WoohyunBae** [comment]
Thanks. It is resolved
