### ISSUE TITLE
not effect on updatedRows in using keyboard input "delete" 

### ISSUE THREAD

**Issue by jayceepark** [nhn/tui.grid#949]
hello. Im using toas grid on my project.

i think it is so useful than other professinal grid tool.

anyway, i found a little bug to report.

i think there are some differences process when using keyboard input "delete" key or editing cell in edit mode.

let me describe.

this is data to edit.
![image](https://user-images.githubusercontent.com/35021788/76286928-a0eb5980-62e6-11ea-9826-baf7deb99308.png)

let me use keyboard "delete" (second row, fourth column - red rectangular)
![image](https://user-images.githubusercontent.com/35021788/76289190-e65e5580-62eb-11ea-8b60-73377a96f245.png)

and then try to request this data. but it is not possible to put. because toast grid can't recognize situation that changes happened.
![image](https://user-images.githubusercontent.com/35021788/76288518-3cca9480-62ea-11ea-8d05-e6f40f476a27.png)

but in other case, edit on cell edit mode. i can request data.

this is picture of returned object after using keyboard "delete"
![image](https://user-images.githubusercontent.com/35021788/76287177-28d16380-62e7-11ea-862c-bb2460a9ce04.png)

this is returned object after editing in cell edit mode
![image](https://user-images.githubusercontent.com/35021788/76287180-2bcc5400-62e7-11ea-8c00-2bfc746ccfb6.png)

i think two actions must work same.

 my OS is win10 and browser is chrome 80.

-----------------
혹시 영어로 오역한 부분도 있을지 몰라 한글 문의도 첨부드립니다.

안녕하세요. 토스트 그리드를 이용해 간단한 프로젝트를 하고 있습니다.

웬만한 상용 그리드보다도 체계적이어서 유용하게 사용하고있습니다.

다름이 아니라 버그를 발견한 듯하여 이슈 리포트를 합니다.

셀편집 모드를 들어가지 않고 키보드의 딜리트키를 이용하여 셀을 삭제했을 때와, 편집하려는 셀을 더블클릭하거나 엔터를 입력하여 셀 편집모드로 내용을 지웠을 때의 상태값 처리가 다른 것 같습니다.

설명을 드리면..

편집하려는 초기 데이터입니다.
![image](https://user-images.githubusercontent.com/35021788/76286928-a0eb5980-62e6-11ea-9826-baf7deb99308.png)

"코드 설명" 컬럼의 두번째 로우를 키보드 Delete키를 이용해 지우고 myGrid.request('modifyData') 를 할경우 처리할 데이터가 없다고 나옵니다. 즉 편집된 데이터가 없다고 인식되어 저장을 할 수가 없습니다.
![image](https://user-images.githubusercontent.com/35021788/76289201-ececcd00-62eb-11ea-872a-46854ba1ef29.png)

![image](https://user-images.githubusercontent.com/35021788/76287129-0c352b80-62e7-11ea-9d4a-fe23fc587fff.png)

데이터 저장 요청을 할 수가 없습니다. 토스트 그리드가 변경된 사항에 대해 인식을 못하는 것 같습니다.
![image](https://user-images.githubusercontent.com/35021788/76288518-3cca9480-62ea-11ea-8d05-e6f40f476a27.png)

반대로 수정하려는 셀을 편집모드에서 내용을 지우고 저장하게 되면  정상적으로 updatedRow로 처리가 되구요.

키보드 delete로 삭제 후 myGrid.getModifiedRows() 했을때 리턴되는 오브젝트입니다.
![image](https://user-images.githubusercontent.com/35021788/76287177-28d16380-62e7-11ea-862c-bb2460a9ce04.png)

셀편집 모드에서 내용을 삭제한 후에 myGrid.getModifiedRows() 했을때 리턴되는 오브젝트입니다.
![image](https://user-images.githubusercontent.com/35021788/76287180-2bcc5400-62e7-11ea-8c00-2bfc746ccfb6.png)

두 액션이 동일하게 상태처리가 되어야 하지 않은지 문의드립니다.

저의 개발 및 사용 환경은 윈도우 10 & 크롬 80  버젼입니다.

**Comment by jung-han** [comment]
#859 It is considered the same issue.

**Comment by js87zz** [comment]
@jayceepark 
We will fix it this bug in next release~!
Thank you for providing detail information :)

**Comment by js87zz** [comment]
The bug has been fixed in `v4.10.1`(#957).
