### ISSUE TITLE
Why isn't it possible to select the text present in the grid?

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#958]
#### The data as well as the header content text cannot be selected and highlighted.

I cannot copy paste the values from the grid because of this issue. 
Am I missing a prop that I need to pass or is this actually a bug in the grid?

**Comment by js87zz** [comment]
@SanjaySankar 
Currently, we use the `mousemove` event for making our selection area and it prevents to make general selection range for text content. To solve this, we need to consider any `off option` about selection functionality.
Header content can't be copied but cell content can be copied and pasted using selection.
Refer this [link](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/clipboard.md).

**Comment by SanjaySankar** [comment]
oh okay! thanks!
