### ISSUE TITLE
Editor does not work when using DataSource.

### ISSUE THREAD

**Issue by LeeSeungyeon** [nhn/tui.grid#959]
**Issue**
We are using tui-grid, but we have changed the DataSource from the previous data processing method to Ajax. Since then, the editor for that grid has not been active. Don't you support editor when using DataSource?

**Version**
tui-grid 4.10.0

**Comment by js87zz** [comment]
@LeeSeungyeon 
Currently, editor is well performed with dataSource.
It's hard to answer because I don't know your grid configuration like `column`, `dataSource` options you used.
If you use codesandbox like me in an error environment, it will be much easier to answer.

Check this example.
* https://codesandbox.io/s/romantic-brown-6lse2?fontsize=14&hidenavigation=1&theme=dark

**Comment by LeeSeungyeon** [comment]
I wrote the code by referring to the tui-grid api as follows.
tui-grid that created by DataSource in the object type in the 'data' option of grid is redering serverside data source. By any chance, toast-ui.vue-grid is not support DataSource?

**- DataSource**
http://nhn.github.io/tui.grid/latest/tutorial-example10-data-source
```
dataSource: {
	initialRequest: false,
	api: {
	  readData: {
		url: '/test/list.ajax',
		method: 'POST'
	  }
	},
	contentType: 'application/json;charset=UTF-8'
}
```
**- Custom editor**
http://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor
```
columns: [{
	  header: 'column',
	  name: 'column',
	  editor: {
            type: 'select',
            options: {
              listItems: [
                { text: '1', value: '1' },
                { text: '2', value: '2' },
                { text: '3', value: '3' }
              ]
            }
          }
	}]
```
**- Screen when DataSource is not used**
![image](https://user-images.githubusercontent.com/10701880/76593466-b906e700-6539-11ea-9493-21fc564779fd.png)

**Comment by js87zz** [comment]
@LeeSeungyeon 
Sorry for late reply. 
You can use the dataSource in vue wrapper.
Can you give us your full configuration code in jsfiddle or code sandbox?
It's hard to know the problem using your source code.
