### ISSUE TITLE
readData 데이터 조회 문의

### ISSUE THREAD

**Issue by soreyeon** [nhn/tui.grid#962]
CDN 최신버전
스프링4
mybatis
JQuery

![image](https://user-images.githubusercontent.com/53546101/76942684-7bdb9400-6941-11ea-8ac8-89933e4015c9.png)

![image](https://user-images.githubusercontent.com/53546101/76942699-8007b180-6941-11ea-970f-33d53a628760.png)

![image](https://user-images.githubusercontent.com/53546101/76942707-839b3880-6941-11ea-9890-1620dd44b9dc.png)

![image](https://user-images.githubusercontent.com/53546101/76942712-85fd9280-6941-11ea-914a-294ed24594ee.png)

JSON형식으로 데이터를 보내줬는데 그리드에 뿌리질 못합니다.

뿌릴 데이터만 보내주면 readData가 자동으로 응답데이터 형식을 만들어 주는거 아닌가요?

{
  "result": true,
  "data": {
    "contents": [],
    "pagination": {
      "page": 1,
      "totalCount": 100
    }
  }
}

위 형식을 직접 만들어야하는건가요?

ResponseBody 어노테이션으로 데이터만 보내주면 안되는건가요?

**Comment by js87zz** [comment]
@soreyeon 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
