### ISSUE TITLE
Merging two cells in two rows

### ISSUE THREAD

**Issue by JithinKS97** [nhn/tui.grid#963]
Is it possible to merge two cells in two rows? I want to merge two rows
Similar to the name field as shown in this question
https://stackoverflow.com/questions/32088676/how-to-add-rowspan-in-jquery-datatables

**Comment by js87zz** [comment]
@JithinKS97 
[This tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/row-span.md) will be helpful to you.

**Comment by JithinKS97** [comment]
Perfect thanks
