### ISSUE TITLE
Is it possible to sort Dates in different formats?

### ISSUE THREAD

**Issue by SanjaySankar** [nhn/tui.grid#965]
#### I have a column showing `last updated` time. I'm using momentJs to format the dates.

- If the date in my incoming data is the current date, I'm using `h:mm:ss A [(${relativeTime})]` which is like `3:40:00 PM (2 hours ago)`

- If it is not, I'm using `h:mm A · MMM DD, YYYY` which is like `3:40 PM · Feb 19, 2020`

#### But the sorting functionality breaks when I use different formats for the same `Last Updated` column.
Is there a solution ?

**Comment by js87zz** [comment]
@SanjaySankar 
I think you want to sort the data of specific column with your custom date format(using momentjs). **Custom sort comparator** option will be helpful to you. 
But we are not providing it at the moment. Add this functionality to planned feature in grid.
Thank you!

**Comment by SanjaySankar** [comment]
@js87zz 
Oh okay. Thanks. Waiting for the release!

**Comment by js87zz** [comment]
@SanjaySankar 
The Custom Comparator options has been added in `4.14.0`(#1096). 
You can sort the data with your comparator through this feature.([tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/sort.md#custom-comparator))
Thank you!
