### ISSUE TITLE
'tuiGrid' namespace not found

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#967]
**Summary**
Is the 'tuiGrid' namespace removed?
I'm asking because it's not in the Release Note.

**Screenshots**
![image](https://user-images.githubusercontent.com/18422353/77286510-be70e800-6d16-11ea-823a-72152bb818da.png)

![image](https://user-images.githubusercontent.com/18422353/77286555-d5afd580-6d16-11ea-82bd-2261a8f0a573.png)

**Version**
4.10.1

**Comment by js87zz** [comment]
@ryum91 
Sorry, It's missed in release note. Our type definition is totally changed to prevent duplicated definition.
namespace is changed and `types` folder is included in `v4.10.1`.
```js
import TuiGrid,{ GridOptions, Row } from 'tui-grid';
import { OptColumn as Column } from 'tui-grid/types/options';
import { CellRendererProps } from 'tui-grid/types/renderer';
import { TuiGridEvent } from 'tui-grid/types/event';
```

**Comment by ryum91** [comment]
@js87zz 

Thank you.

Please write in the release notes!
And personally, I think this is a major update, not a minor update.

**Comment by js87zz** [comment]
@ryum91 
Added the changes in release note as breaking changes.
Actually, It was not our intention to use the type of namespace that is **not exported**. But the problem is that there was no guide about it and we should have prevented it in advance in our definition file.
