### ISSUE TITLE
example of readdata method 

### ISSUE THREAD

**Issue by kbkim-qw** [nhn/tui.grid#969]
Hello,

Version : eclipse 2019-09 R (4.13.0)
              Apache Tomcat 8.0
             tui-grid/latest/tui-grid.css
             tui.time-picker/v1.5.0
             tui.date-picker/v3.2.1
             jquery-3.3.1.min.js

1 ) There are 2 grid instant.

2 ) First one is Master table 
    download data from backend server (jsp)

3) Second one is Sub table of 2)
   
When user click rows of Mastertable,
```js
grid.on('focusChange', function(ev) {
  rmId=grid.getRow(ev.rowKey,true)['id'];
  reloadGridDetail();
}); 
```

I used an eventhandler for draw 3) table.

   1) find key of selected row
   2) call reloadGridDetail() function

```js
function reloadGridDetail() {
  gridDetail.readData(333,{artist: 'Birdy',price: 10000},true);
}
```

... tried many times, on gooogling data.
but still I can't find send parameter to backend

I want call my backend like this method

```js
const dataSourceOfDetail = {
  initialRequest: true,
  api : {
    readData : {
      url : 'doit?command=ajaxGetSrmDetails&srmId=${srmId}',
      method : 'GET'
    },
    createData: { url: 'doit?command=ajaxCreateSrmDetail', method: 'POST' },
    updateData: { url: 'doit?command=ajaxUpdateSrmDetail', method: 'PUT' },
    modifyData: { url: 'doit?command=ajaxModifySrmDetail', method: 'PUT' },
    deleteData: { url: 'doit?command=ajaxDeleteSrmDetail', method: 'DELETE' }
  }
};
```
which ${srmId} value is clicked Master table's id value

Can you help me how to do it?
or Doc link?

Thanks.

**Comment by kbkim-qw** [comment]
doit?command=login:365 Uncaught TypeError: gridDetail.readData is not a function
    at reloadGridDetail (doit?command=login:365)
    at doit?command=login:528
    at tui-grid.js:2158
    at Array.forEach (<anonymous>)
    at Object.trigger (tui-grid.js:2157)
    at Object.changeFocus (tui-grid.js:3909)
    at Object.mouseDownBody (tui-grid.js:13813)
    at dispatch (tui-grid.js:13209)
    at Object.BodyAreaComp._this.handleMouseDown [as mousedown] (tui-grid.js:6438)
    at HTMLDivElement.eventProxy (tui-grid.js:945)
reloadGridDetail @ doit?command=login:365
(anonymous) @ doit?command=login:528
(anonymous) @ tui-grid.js:2158
trigger @ tui-grid.js:2157
changeFocus @ tui-grid.js:3909
mouseDownBody @ tui-grid.js:13813
dispatch @ tui-grid.js:13209
BodyAreaComp._this.handleMouseDown @ tui-grid.js:6438
eventProxy @ tui-grid.js:945

**Comment by kbkim-qw** [comment]
Parameter  to Backend is

command=ajaxGetSrmList2&perPage=&page=1
command=ajaxGetSrmDetails&srmId=&perPage=&page=1

srmId value is null..

that's problem

**Comment by kbkim-qw** [comment]
In Your API Guide 

"
Protocol Used in readData
Let's discuss the protocols used in readData. The following is the string parameter used when the Grid sends requests through the URL and method.

page=1&perPage=10
page {number}: The current page
perPage {number}: The number of rows represented per each page.
If you are using the sort feature, you have to explicitly mention the sorting option in the string parameter.

**page=1&perPage=10&sortColumn=XXX&sortAscending=true**
sortColumn {string}: The name of the column that determines the order of rows.
sortAscending {boolean}: If it is set to true, it will sort in the ascending order, and when set to false, it will sort in descending order.

"




I want example of " page=1&perPage=10&sortColumn=XXX&sortAscending=true " 
these parameters where I call grid.readdata() method on JAVASCRIPT environment.


I can't write english well....   
thanks.

**Comment by js87zz** [comment]
@kbkim-qw 
I think you want to pass the parameter using RESTFul URI. right?

1. The `url` option should be `function` for using RESTFul URI with dataSource.
```js
const dataSourceOfDetail = {
  initialRequest: true,
  api : {
    readData : {
      // change the url as function as below
      url : () => `doit?command=ajaxGetSrmDetails&srmId=${srmId}`,
      method : 'GET'
    },
    // ...
  }
};
```
2. `readData` method has 3 parameters. you can check the this [API](https://nhn.github.io/tui.grid/latest/Grid#readData) page

[This tutorial](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md) will be helpful to you.

**Comment by kbkim-qw** [comment]
Thanks. But still encounter error.


This is foucus Change Event Handler of Master Grid

`	  grid.on('focusChange', function(ev) {
  	  srmId=grid.getRow(ev.rowKey,true)['id'];
	  console.log('srmId value :' + srmId);
	  makeGridDetail();
	    }); `

when master Grid focus Changed :

console log marks correct srmId value 

doit?command=login:531 srmId value :243
doit?command=login:531 srmId value :261
doit?command=login:531 srmId value :243
doit?command=login:531 srmId value :221
doit?command=login:531 srmId value :243
doit?command=login:531 srmId value :1122


but,
I changed data source method which you guided.






`
var srmId=0;

const dataSourceOfDetail = {
		 initialRequest: false,
	api : {
		 readData : {
		      // change the url as function as below
		      url : () => `doit?command=ajaxGetSrmDetails&srmId=${srmId}`,
		      method : 'GET'
		    },
  createData: { url: 'doit?command=ajaxCreateSrmDetail', method: 'POST' },
  updateData: { url: 'doit?command=ajaxUpdateSrmDetail', method: 'PUT' },
  modifyData: { url: 'doit?command=ajaxModifySrmDetail', method: 'PUT' },
  deleteData: { url: 'doit?command=ajaxDeleteSrmDetail', method: 'DELETE' }
	}
};

`


and , Call this at Event Handler 

` grid.on('focusChange', function(ev) {
		  srmId=grid.getRow(ev.rowKey,true)['id'];
		  gridDetail.readData();
	    }); `




error occured on browser 

ncaught TypeError: gridDetail.readData is not a function
    at doit?command=login:533
    at tui-grid.js:2158
    at Array.forEach (<anonymous>)
    at Object.trigger (tui-grid.js:2157)
    at Object.changeFocus (tui-grid.js:3909)
    at Object.mouseDownBody (tui-grid.js:13813)
    at dispatch (tui-grid.js:13209)
    at Object.BodyAreaComp._this.handleMouseDown [as mousedown] (tui-grid.js:6438)
    at HTMLDivElement.eventProxy (tui-grid.js:945)


Help me please
Thank you

**Comment by kbkim-qw** [comment]
![11](https://user-images.githubusercontent.com/62542039/77378738-38a67880-6dba-11ea-81cb-4aa8922de174.png)

**Comment by kbkim-qw** [comment]
![22](https://user-images.githubusercontent.com/62542039/77378785-5ffd4580-6dba-11ea-8727-35c80116ae35.png)

**Comment by kbkim-qw** [comment]
When initial call of function )

**var srmId=0;**
const dataSourceOfDetail = {
		 **initialRequest: true,**
	api : {
		 readData : {
		      // change the url as function as below
		      url : () => `doit?command=ajaxGetSrmDetails&srmId=${srmId}`,
		      method : 'GET'
		    },
  createData: { url: 'doit?command=ajaxCreateSrmDetail', method: 'POST' },
  updateData: { url: 'doit?command=ajaxUpdateSrmDetail', method: 'PUT' },
  modifyData: { url: 'doit?command=ajaxModifySrmDetail', method: 'PUT' },
  deleteData: { url: 'doit?command=ajaxDeleteSrmDetail', method: 'DELETE' }
	}
};

I setted srmId value to 0.
and initialRequest parameter to true

and Backend received this parameter 


command=ajaxGetSrmDetails&**srmId=&perPage=&page=1**
3월 24, 2020 10:36:06 오전 org.apache.catalina.core.StandardWrapperValve invoke
심각: Servlet.service() for servlet [sales.ipiche.controller.doit] in context with path [/ipicheSales] threw exception
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at sales.ipiche.controller.action.ajaxGetSrmDetails.execute(ajaxGetSrmDetails.java:45)
	at sales.ipiche.controller.doit.doGet(doit.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)



null value of srmId sended
and I don't know whu perPage and Page parameter sended

Can I handling that parameter?


and

You suggested API guide Link of readdata

"

Name | Type | Description
-- | -- | --
page | Number | Page number
data | Object | Data(parameters) to send to the server
resetData | Boolean | If set to true, last requested data will be ignored.

"

I want example of "data" parameter which object type.
example  like this
var paramter = {"srmId" : 1 };


thank you

**Comment by kbkim-qw** [comment]
Yes! I want Dynamic parameter.

but  

problem is 

1) null value send to backend when initial call

2) readdata function call at eventhandler
meets error " TypeError: gridDetail.readData is not a function "

Thank you.

**Comment by js87zz** [comment]
@kbkim-qw 
I think `gridDetail` has not been created properly and it caused the `TypeError`. It's better to check the `gridDetail` variable not `readData`.
It's hard to know your exact cause about backend issue seeing your comment. 
Please put your code up neatly in codepen or jsfiddle.
