### ISSUE TITLE
The Selected Section does not match in header and column on Chrome Browser

### ISSUE THREAD

**Issue by eggplantiny** [nhn/tui.grid#972]
**Describe the bug**
I'm using tui.grid-vue 4.10 version and Chrome Browser. I made custom components with javascript and VueComponent for render grid component. and i insert them to Grid. by the way, header position and column position does not match on Chrome Browser. I also test this component on Firefox Browser however this bug was not occurred.

**To Reproduce**
1. Create custom renderer and insert to Grid.

**Expected behavior**
The selected Section does not match on header and column

**Screenshots**

![1](https://user-images.githubusercontent.com/57978095/77496020-61e40900-6e8d-11ea-8acd-89671f14e95e.png)
![2](https://user-images.githubusercontent.com/57978095/77496044-6d373480-6e8d-11ea-979a-699748e948ad.png)
![3](https://user-images.githubusercontent.com/57978095/77496061-74f6d900-6e8d-11ea-9727-f0848205d121.png)
![4](https://user-images.githubusercontent.com/57978095/77497327-66f68780-6e90-11ea-994c-e77a811fc158.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: chrome 80
"@toast-ui/vue-grid": "^4.10.0"

**Additional context**

**Comment by js87zz** [comment]
@eggplantiny 
Your issue is that the width of focus and selection area is not matched to column width. Right?
Can you upload your code in codePen or jsfiddle? To solve the issue, we should know your custom renderer and other config.

**Comment by eggplantiny** [comment]
@js87zz 
I made a example project. [here](https://github.com/eggplantiny/TUI.grid.vue-Example)
and i have a question.
I wanna pass parameter to component so using props option on my project.
But i catched handled original data on Grid component.
How can i prevent to affect original data effectively?

**Comment by eggplantiny** [comment]
I think this bug is expected to be occured on checkbox-header.
But I can't understand why Grid make a mistake because I almost bring Header Component from [Grid example](https://nhn.github.io/tui.grid/latest/tutorial-example11-row-headers) and add some of features (eg. change background color when checked).

**Comment by js87zz** [comment]
@eggplantiny 
Sorry for late replying.
I have checked the issue using your [example repository](https://github.com/eggplantiny/TUI.grid.vue-Example). However, the position of selection area had not problem as below image.
![스크린샷 2020-03-31 오전 8 39 37](https://user-images.githubusercontent.com/37766175/77972112-73b12a80-732b-11ea-876e-66bda9eb1c54.png) in chrome browser(latest version- 80.0.3987.149).

How about checking the problem whether the position or size of other components(navigation or right detail area) affect grid layout?

* How can i prevent to affect original data effectively?
  * If you want prevent to affect original data, data should be copied deeply and passed as grid props. However, we don't recommend it about large data for performance.

**Comment by eggplantiny** [comment]
@js87zz 
I checked again today and it's working normally on mine.
I think there was a problem with the Chrome Browser.
Thank you for your comment.
