### ISSUE TITLE
How do I disable the tab function?

### ISSUE THREAD

**Issue by prisml** [nhn/tui.grid#974]
**Summary**
I am using 'react'. Pressing the 'tab' key will 'rerender' it with another 'state' change, but 'editingStart' has already been executed and the next action looks like a bug.
I want to disable the 'tab' function.
How do I disable the tab function?

**Version**
v4.10.1

**Comment by js87zz** [comment]
@prisml 
You can change the operation of `tab` key as moving the **focused cell**. If you configure like as below, it will prevent to edit the cell using `tab` key.
```js
<Grid 
  // ...
  tabMode="move" 
>
```
Except above configuration, the options is not provided to prevent `tab` keyMap functionality currently.

**Comment by prisml** [comment]
It works fine. Thank you.
