### ISSUE TITLE
I want to draw grid layout order

### ISSUE THREAD

**Issue by Deku164** [nhn/tui.grid#978]
#한글
안녕하세요. 토스트 UI 그리드를 통해 그리드를 뿌려주고 있습니다.
다만 그릴떄 문제가 발생하는데요. 다른 페이지에서 쓰는 타이틀바를 여기서도 사용하는데,
타이틀바 같은 경우 fixed속성에 의해 항상 어느 UI를 만나건 위에 그려지게 되어있습니다.
그런데 분명 그리드가 얘보다 하위 컴포넌트임에도 불구하고 그리는 순서가 그리드가 무조건 위입니다.
그래서 모든걸 가려버리더라구요..

이것에대한 해결 방법이 있을까요?

#english
Hi, im using react with toast ui grid
but bug is  when i draw grid layout.
titlebar is always top -> have fixed attribute
but this grid is always on top..

**Comment by Deku164** [comment]
Hello, I'm spraying the grid through the toast UI grid.
But there's a problem with drawing. We use the title bar here that we use on other pages.
The title bar is always drawn on any UI by fixed property.
But even though the grid is a lower component than this one, the grid is definitely above the grid.
So he covered everything.

**Comment by js87zz** [comment]
@Deku164 
Did you change the [z-index](https://developer.mozilla.org/ko/docs/Web/CSS/z-index) css property of your title bar component?
