### ISSUE TITLE
Issue grid.request('createData'); , What is {0} group meaning?

### ISSUE THREAD

**Issue by kbkim-qw** [nhn/tui.grid#980]
**Summary**
When I use  grid.request('createData'); function.

Backend gets some data of created rows.

I want know {0} group mean, and how can I remove this. 

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
New Version

**Additional context**

Hello.

When I called request with createData parameters.

Backend  receives this message.

{
   "createdRows":[
      {
         **"0":{},**
         "id":"",
         "sequence":"",
         "Sales_man":"",
         "Business_type":"",
         "Site_name":"",
         "Site_type":"",
         "Project_name":"프로젝트1",
         "Partner_name":"Qd07aY",
         "Contract_date":"2018-09-27",
         "Est_accept_date":"2018-10-11",
         "Price":"",
         "rowKey":160,
         "rowSpanMap":{

         }
      },
      {
         "0":{
            "id":"",
            "sequence":"",
            "Sales_man":"",
            "Business_type":"",
            "Site_name":"",
            "Site_type":"",
            "Project_name":"",
            "Partner_name":"",
            "Contract_date":"",
            "Est_accept_date":"",
            "Price":""
         },

{0} group has column name and null value of datagrid.
What {0} group means and Can I remove it?

**Comment by js87zz** [comment]
@kbkim-qw 
Please write your issue clearly and neatly and give us more detail source code in codepen or code sandbox. 
Please understand that It is hard for us to make the scenario of all the issues ourselves.
