### ISSUE TITLE
toast grid first row trigger

### ISSUE THREAD

**Issue by ko-kyeong-sik** [nhn/tui.grid#985]
After GRID loads, I want to force the first ROW to use TRIGGER to give a click event. Please teach me the way.

**Comment by js87zz** [comment]
@ko-kyeong-sik 
You mean clicking the first cell? what is the purpose?
If you want to make first cell focused, [focusAt](https://nhn.github.io/tui.grid/latest/Grid#focusAt) API will be helpful.
