### ISSUE TITLE
edit cell not work in tree

### ISSUE THREAD

**Issue by sayaya1090** [nhn/tui.grid#986]
I have a question in the Toast Grid Tree feature.
In the tutorial(https://nhn.github.io/tui.grid/latest/tutorial-example14-tree),
I appended an edit option in a column.
Displayed well, but cell value does not change at all.
Is it work?
Should I use custom editor or renderer?
I tried but not work either.

The data('treeData' in bottom) seems be updated but edit event stuck before render cell with no error msg.

const grid = new tui.Grid({
      el: document.getElementById('grid'),
      data: treeData,
      rowHeaders: ['checkbox'],
      bodyHeight: 500,
      treeColumnOptions: {
        name: 'name',
        useCascadingCheckbox: true
      },
      columns: [{
          header: 'Name',
          name: 'name',
          width: 300
        }, {
          header: 'Artist',
          name: 'artist',
          **editor: 'text'**
        }, {
          header: 'Type',
          name: 'type'
        }, {
          header: 'Release',
          name: 'release'
        },{
          header: 'Genre',
          name: 'genre'
        }
      ]
    });

**Comment by js87zz** [comment]
@sayaya1090 
We checked this bug. It will be fixed in next release.
Thank you!

**Comment by js87zz** [comment]
The bug has been fixed in v4.11.0(#995).
