### ISSUE TITLE
How to move a row with drag and drop?

### ISSUE THREAD

**Issue by joebordes** [nhn/tui.grid#987]
**Summary**
I need to be able to select and drag a column to another position. I read and tried the moveRow API which works correctly but I couldn't find a way to select and drag a row to the destination position.

**Version**
4.10.1

**Additional context**
I tried with jQuery sortable and draggable

**Comment by js87zz** [comment]
@joebordes 
Currently, we don't support the API or custom event to drag and drop column or row.
We are planned to provide the functionality(DnD), but the exact schedule is not decided yet.

**Comment by joebordes** [comment]
Thanks

**Comment by shinsunho** [comment]
May I have a rough schedule? In a few months?
