### ISSUE TITLE
grid옵션의 bodyHeight을 'auto'로 줄 경우, 마우스 셀 선택 시 속도가 저하됩니다.

### ISSUE THREAD

**Issue by soonJ817** [nhn/tui.grid#988]
# Version

4.0

# Development Environment

Chrome, win10

# Current Behavior

column 20개, row 100개를 기준으로 bodyHeight옵션을 주지 않고(또는 'auto'로 설정하고) 실행할 경우 mouse click & drag 이벤트 시 속도 저하가 발생합니다.

혹시나 해서 examples의 Large Data Performance 코드를 기준으로 bodyHeight을 삭제하고 실행했더니 같은 현상이 발생합니다.

성능을 개선할 방법이 있을까요?

**Comment by js87zz** [comment]
@soonJ817 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.

If you want to improve the performance, try to set the fixed height to `bodyHeight` and `scrollY: true` as below.
```js
const gridOptions =  {
  // ...
  bodyHeight: 500,
  scrollY: true  // default value is true
}
```
If the options is set to `bodyHeight: auto'`, all grid cell will be rendered on DOM and the performance will be slowed.
