### ISSUE TITLE
why el is missing type error?

### ISSUE THREAD

**Issue by mwrote** [nhn/tui.grid#990]
**Summary**

In using '@toast-ui/react-grid' in TypeScript.
If not set `el` prop, TypeScript error occurred.
But it works.
Why `el` prop is required?
README.md examples does not set `el`.
I think it should be optional.

**Screenshots**
![image](https://user-images.githubusercontent.com/805577/78972264-4db83100-7b48-11ea-9bb2-7c57d28e4fe4.png)

![image](https://user-images.githubusercontent.com/805577/78972283-5d377a00-7b48-11ea-8b3d-46357944a4e0.png)

**Version**
@toast-ui/react-grid 4.10.1

**Comment by js87zz** [comment]
@mwrote 
The type definition of wrapper is wrong. We will fix it.
Thank you!

**Comment by js87zz** [comment]
The bug has been fixed in `v4.11.0`(#1007).
