### ISSUE TITLE
Grid values are not changing in tree grid

### ISSUE THREAD

**Issue by izzumi** [nhn/tui.grid#991]
In case of using "resetData", cell value does not change.
After finishing changing cell value in tree, displayed value doesn't change. but inner data value changed well.
worked well with using [data] option at initializing.

**Comment by js87zz** [comment]
@izzumi 
Please respect our policy that writing the form in English to share our issue to other people.
Change the title and content in English.
I think that this issue is same as the (#986)

**Comment by izzumi** [comment]
> @izzumi
> Please respect our policy that writing the form in English to share our issue to other people.
> Change the title and content in English.
> I think that this issue is same as the (#986)

And I have one more question.
In the tutorial(https://nhn.github.io/tui.grid/latest/tutorial-example03-custom-editor),
I found a similar bug.
In tutorial editing is not working. cell value not changed.
tutorial uses method "resetData".

Is not this related bug with issue that I mentioned upward?

**Comment by js87zz** [comment]
@izzumi 
The example can makes you confused. However, it is not the bug.
If you see the example source code, `ev.stop()` has been called and this code will prevent to change the value on `name` column. 
<img width="365" alt="스크린샷 2020-04-13 오후 7 46 45" src="https://user-images.githubusercontent.com/37766175/79114968-a0e7e900-7dbf-11ea-9493-bd3dd3b3168f.png">

I think it's better to fix the example for the people who get confused through it.
Thank you!

**Comment by izzumi** [comment]
@js87zz 
Aha I missed it. I got it.
Thanks!

**Comment by js87zz** [comment]
@izzumi 
The bug has been fixed in `v4.11.0`(#995).
